export const SCALE_REGISTRY: Record<string, number> = {
  // Spec Core
  module_val: 4,
  pitch_diameter: 3,
  face_width: 2,
  teeth_count: 0,
  torque_nm: 2,
  yield_strength_mpa: 1,
  safety_factor: 3,
  mass_g: 1,
  fp_tol: 8,

  // gearStrength.ts solver keys (Exact camelCase)
  teethPinion: 0,
  teethGear: 0,
  faceWidth: 2,
  pressureAngle: 3,
  helixAngle: 3,
  qualityGrade: 0,
  youngsModulus: 0,
  poissonRatio: 3,
  allowableBending: 1,
  allowableContact: 1,
  hardness: 0,
  power: 2,
  rpm: 1,
  applicationFactor: 2,
  dynamicFactor: 2,
  pitchDiameterPinion: 3,
  pitchDiameterGear: 3,
  centerDistance: 3,
  transmissionRatio: 4,
  transverseContactRatio: 3,
  tangentialForce: 1,
  radialForce: 1,
  axialForce: 1,
  contactStress: 1,
  bendingStressPinion: 1,
  bendingStressGear: 1,
  safetyContact: 3,
  safetyBendingPinion: 3,
  safetyBendingGear: 3,
  module: 4,

  // General Engineering Extensions
  power_kw: 2,
  speed_rpm: 1,
  ratio: 4,
  efficiency: 3,
  pressure_mpa: 2,
  stress_mpa: 2,
  bending_stress_mpa: 2,
  contact_stress_mpa: 2,
  deflection_mm: 3,
  thickness_mm: 2,
  length_mm: 2,
  width_mm: 2,
  height_mm: 2,
  diameter_mm: 2,
  inner_diameter_mm: 2,
  outer_diameter_mm: 2,
  force_n: 1,
  load_kn: 2,
  temperature_c: 1,
  cost_estimate: 2,
  weight_kg: 3,
  volume_cm3: 2,
  area_mm2: 2,
  moment_of_inertia_mm4: 1,
  section_modulus_mm3: 1,
  bolt_diameter_mm: 2,
  pitch_mm: 2,
  clamp_load_kn: 2,
  tightening_torque_nm: 2,
  friction_coeff: 3,
  hardness_hrc: 1,
  poissons_ratio: 3,
  youngs_modulus_gpa: 1,
  shear_modulus_gpa: 1,
  tensile_strength_mpa: 1,
  fatigue_limit_mpa: 1,
};

export const DEFAULT_FORBIDDEN = true;
