/** Workstation pages — layout, resultPanel, naval, failure, shafts */

const EN = {
  layout: {
    returnToCommandCenter: 'Return to Command Center', executeAnalysis: 'Execute Analysis',
    saveToWorkspace: 'Save to Workspace', status: 'Status', statusIdle: 'idle', statusStable: 'stable',
    statusError: 'error', moduleLoading: 'Loading...',
  },
  resultPanel: {
    processing: 'Processing Engine Request', awaiting: 'Awaiting Parameters', reportIssue: 'Report Issue',
    engineVerified: 'Engine Verified', hideLogs: 'Hide Logs', inspect: 'Inspect',
    calculatedStress: 'Calculated Stress Output', displacementTonnes: 'Displacement / Tonnes',
    executionMs: 'Execution', determinism: 'Determinism v1.0', executionTimeline: 'Execution Timeline',
    totalLogicStages: 'Total Logic Stages', steps: 'steps',
  },
  naval: {
    title: 'Naval Hydrostatics', hullDimensions: 'Hull Dimensions', length: 'Length (Lpp)', beam: 'Beam (B)',
    draft: 'Draft (T)', blockCoeff: 'Block Coeff (Cb)', loadingStability: 'Loading & Stability',
    centerOfGravity: 'Center of Gravity (KG)', waterDensity: 'Water Density', simulationFailed: 'Simulation Failed',
    marineAssessment: 'Marine Stability Assessment', stable: 'STABLE', unstable: 'UNSTABLE',
    stableDesc: 'The vessel possesses a positive metacentric height, ensuring a self-righting moment during heeling.',
    unstableDesc: 'WARNING: Negative GM detected. The vessel lacks initial stability and may capsize under external moments.',
    metacentricHeight: 'Metacentric Height (GM)', displacement: 'Displacement', buoyancyForce: 'Buoyancy Force',
    schematicCaption: 'Technical Schematic // Static Stability Curve', initiating: 'Initiating hydrostatic simulation...',
  },
  failure: {
    title: 'Failure Diagnosis', stressParameters: 'Stress Parameters', operatingStress: 'Operating Stress (\u03c3)',
    concentration: 'Kt (Concentration)', materialLimits: 'Material Limits', yieldStrength: 'Yield Strength (Sy)',
    enduranceLimit: 'Endurance Limit (Se)', diagnosticFailed: 'Diagnostic Failed',
    integrityDiagnosis: 'Structural Integrity Diagnosis', safe: 'SAFE', critical: 'CRITICAL',
    safeDesc: 'The component is within safe operating limits for the specified cycles and load conditions.',
    criticalDesc: 'WARNING: High probability of fatigue failure. The applied cyclic loads exceed the material endurance limit.',
    primaryFailureMode: 'Primary Failure Mode', staticSf: 'Static SF', fatigueSf: 'Fatigue SF',
    schematicCaption: 'Technical Schematic // S-N Fatigue Curve Analysis', waitingInput: 'Waiting for diagnostic input payload...',
  },
  shafts: {
    breadcrumb: 'Workstation', assembly: 'Assembly', title: 'Shaft Analysis',
    subtitle: 'Beam statics and reaction force resolution for bearings.',
    inputTitle: 'Shaft Statics & Loading', totalLength: 'Total Length (L)', forcePosition: 'Force Position (a)',
    assemblyConnector: 'Assembly Connector', refHint: 'Provide $ref to Gear Stress Output:',
    refPlaceholder: 'e.g. {calc_id}.stress', appliedForce: 'Applied Force (F)',
    reactionMatrix: 'Reaction Matrix',
    reactionDesc: 'Forces resolved at Support A and Support B for direct bearing load injection.',
    dataBusSync: 'Data-Bus Sync',
    dataBusDesc: 'Resolved values are tracked in the execution timeline for project-wide consistency.',
  },
};

const LOCALE = {
  de: {
    layout: { returnToCommandCenter: 'Zurück zur Kommandozentrale', executeAnalysis: 'Analyse ausführen', saveToWorkspace: 'In Workspace speichern', status: 'Status', statusIdle: 'leerlauf', statusStable: 'stabil', statusError: 'fehler', moduleLoading: 'Laden...' },
    resultPanel: { processing: 'Motoranfrage wird verarbeitet', awaiting: 'Parameter werden erwartet', reportIssue: 'Problem melden', engineVerified: 'Motor verifiziert', hideLogs: 'Logs ausblenden', inspect: 'Prüfen', calculatedStress: 'Berechnete Spannungsausgabe', displacementTonnes: 'Verdrängung / Tonnen', executionMs: 'Ausführung', determinism: 'Determinismus v1.0', executionTimeline: 'Ausführungszeitachse', totalLogicStages: 'Logikstufen gesamt', steps: 'Schritte' },
    naval: { title: 'Schiffshydrostatik', hullDimensions: 'Rumpfabmessungen', length: 'Länge (Lpp)', beam: 'Breite (B)', draft: 'Tiefgang (T)', blockCoeff: 'Blockkoeffizient (Cb)', loadingStability: 'Beladung & Stabilität', centerOfGravity: 'Schwerpunkt (KG)', waterDensity: 'Wasserdichte', simulationFailed: 'Simulation fehlgeschlagen', marineAssessment: 'Stabilitätsbewertung', stable: 'STABIL', unstable: 'INSTABIL', stableDesc: 'Das Schiff hat positive metazentrische Höhe und selbstrichtendes Moment bei Krängung.', unstableDesc: 'WARNUNG: Negatives GM erkannt. Das Schiff fehlt anfängliche Stabilität und kann kentern.', metacentricHeight: 'Metazentrische Höhe (GM)', displacement: 'Verdrängung', buoyancyForce: 'Auftriebskraft', schematicCaption: 'Technisches Schema // Statische Stabilitätskurve', initiating: 'Hydrostatische Simulation wird gestartet...' },
    failure: { title: 'Ausfalldiagnose', stressParameters: 'Spannungsparameter', operatingStress: 'Betriebsspannung (\u03c3)', concentration: 'Kt (Konzentration)', materialLimits: 'Materialgrenzen', yieldStrength: 'Streckgrenze (Sy)', enduranceLimit: 'Dauerfestigkeit (Se)', diagnosticFailed: 'Diagnose fehlgeschlagen', integrityDiagnosis: 'Strukturintegritätsdiagnose', safe: 'SICHER', critical: 'KRITISCH', safeDesc: 'Die Komponente liegt innerhalb sicherer Betriebsgrenzen für die angegebenen Zyklen und Lasten.', criticalDesc: 'WARNUNG: Hohe Ermüdungsbruchwahrscheinlichkeit. Die zyklischen Lasten überschreiten die Dauerfestigkeit.', primaryFailureMode: 'Primärer Ausfallmodus', staticSf: 'Stat. SF', fatigueSf: 'Ermüdungs-SF', schematicCaption: 'Technisches Schema // S-N-Ermüdungsanalyse', waitingInput: 'Warte auf Diagnose-Eingabedaten...' },
    shafts: { breadcrumb: 'Workstation', assembly: 'Baugruppe', title: 'Wellenanalyse', subtitle: 'Balkenstatik und Reaktionskräfte für Lager.', inputTitle: 'Wellenstatik & Belastung', totalLength: 'Gesamtlänge (L)', forcePosition: 'Kraftposition (a)', assemblyConnector: 'Baugruppenverbinder', refHint: '$ref zur Zahnrad-Spannungsausgabe angeben:', refPlaceholder: 'z. B. {calc_id}.stress', appliedForce: 'Angewandte Kraft (F)', reactionMatrix: 'Reaktionsmatrix', reactionDesc: 'Kräfte an Lager A und B für direkte Lagerlastinjektion aufgelöst.', dataBusSync: 'Datenbus-Sync', dataBusDesc: 'Aufgelöste Werte werden in der Zeitachse für projektweite Konsistenz verfolgt.' },
  },
  es: {
    layout: { returnToCommandCenter: 'Volver al centro de mando', executeAnalysis: 'Ejecutar análisis', saveToWorkspace: 'Guardar en workspace', status: 'Estado', statusIdle: 'inactivo', statusStable: 'estable', statusError: 'error', moduleLoading: 'Cargando...' },
    resultPanel: { processing: 'Procesando solicitud del motor', awaiting: 'Esperando parámetros', reportIssue: 'Informar problema', engineVerified: 'Motor verificado', hideLogs: 'Ocultar registros', inspect: 'Inspeccionar', calculatedStress: 'Salida de tensión calculada', displacementTonnes: 'Desplazamiento / Toneladas', executionMs: 'Ejecución', determinism: 'Determinismo v1.0', executionTimeline: 'Línea temporal de ejecución', totalLogicStages: 'Etapas lógicas totales', steps: 'pasos' },
    naval: { title: 'Hidrostática naval', hullDimensions: 'Dimensiones del casco', length: 'Eslora (Lpp)', beam: 'Manga (B)', draft: 'Calado (T)', blockCoeff: 'Coef. de bloque (Cb)', loadingStability: 'Carga y estabilidad', centerOfGravity: 'Centro de gravedad (KG)', waterDensity: 'Densidad del agua', simulationFailed: 'Simulación fallida', marineAssessment: 'Evaluación de estabilidad marina', stable: 'ESTABLE', unstable: 'INESTABLE', stableDesc: 'El buque tiene altura metacéntrica positiva, asegurando momento de enderezamiento al escorar.', unstableDesc: 'ADVERTENCIA: GM negativo detectado. El buque carece de estabilidad inicial y puede volcar.', metacentricHeight: 'Altura metacéntrica (GM)', displacement: 'Desplazamiento', buoyancyForce: 'Fuerza de flotación', schematicCaption: 'Esquema técnico // Curva de estabilidad estática', initiating: 'Iniciando simulación hidrostática...' },
    failure: { title: 'Diagnóstico de fallo', stressParameters: 'Parámetros de tensión', operatingStress: 'Tensión de operación (\u03c3)', concentration: 'Kt (concentración)', materialLimits: 'Límites del material', yieldStrength: 'Límite elástico (Sy)', enduranceLimit: 'Límite de fatiga (Se)', diagnosticFailed: 'Diagnóstico fallido', integrityDiagnosis: 'Diagnóstico de integridad estructural', safe: 'SEGURO', critical: 'CRÍTICO', safeDesc: 'El componente está dentro de límites seguros para los ciclos y cargas especificados.', criticalDesc: 'ADVERTENCIA: Alta probabilidad de fallo por fatiga. Las cargas cíclicas superan el límite de resistencia.', primaryFailureMode: 'Modo de fallo principal', staticSf: 'SF estático', fatigueSf: 'SF fatiga', schematicCaption: 'Esquema técnico // Análisis curva S-N', waitingInput: 'Esperando carga de entrada de diagnóstico...' },
    shafts: { breadcrumb: 'Estación de trabajo', assembly: 'Ensamblaje', title: 'Análisis de eje', subtitle: 'Estática de viga y resolución de reacciones para rodamientos.', inputTitle: 'Estática y carga del eje', totalLength: 'Longitud total (L)', forcePosition: 'Posición de fuerza (a)', assemblyConnector: 'Conector de ensamblaje', refHint: 'Proporcione $ref a la salida de tensión del engranaje:', refPlaceholder: 'p. ej. {calc_id}.stress', appliedForce: 'Fuerza aplicada (F)', reactionMatrix: 'Matriz de reacciones', reactionDesc: 'Fuerzas resueltas en soporte A y B para inyección directa de carga en rodamientos.', dataBusSync: 'Sincronización bus de datos', dataBusDesc: 'Los valores resueltos se rastrean en la línea temporal para consistencia del proyecto.' },
  },
  fr: {
    layout: { returnToCommandCenter: 'Retour au centre de commande', executeAnalysis: 'Exécuter l\u2019analyse', saveToWorkspace: 'Enregistrer dans l\u2019espace de travail', status: 'État', statusIdle: 'inactif', statusStable: 'stable', statusError: 'erreur', moduleLoading: 'Chargement...' },
    resultPanel: { processing: 'Traitement de la requête moteur', awaiting: 'En attente de paramètres', reportIssue: 'Signaler un problème', engineVerified: 'Moteur vérifié', hideLogs: 'Masquer les journaux', inspect: 'Inspecter', calculatedStress: 'Sortie de contrainte calculée', displacementTonnes: 'Déplacement / Tonnes', executionMs: 'Exécution', determinism: 'Déterminisme v1.0', executionTimeline: 'Chronologie d\u2019exécution', totalLogicStages: 'Étapes logiques totales', steps: 'étapes' },
    naval: { title: 'Hydrostatique navale', hullDimensions: 'Dimensions de coque', length: 'Longueur (Lpp)', beam: 'Largeur (B)', draft: 'Tirant d\u2019eau (T)', blockCoeff: 'Coeff. de bloc (Cb)', loadingStability: 'Chargement et stabilité', centerOfGravity: 'Centre de gravité (KG)', waterDensity: 'Densité de l\u2019eau', simulationFailed: 'Simulation échouée', marineAssessment: 'Évaluation de stabilité marine', stable: 'STABLE', unstable: 'INSTABLE', stableDesc: 'Le navire possède une hauteur métacentrique positive assurant un moment de redressement au roulis.', unstableDesc: 'AVERTISSEMENT : GM négatif détecté. Le navire manque de stabilité initiale et peut chavirer.', metacentricHeight: 'Hauteur métacentrique (GM)', displacement: 'Déplacement', buoyancyForce: 'Force de flottabilité', schematicCaption: 'Schéma technique // Courbe de stabilité statique', initiating: 'Lancement de la simulation hydrostatique...' },
    failure: { title: 'Diagnostic de défaillance', stressParameters: 'Paramètres de contrainte', operatingStress: 'Contrainte de fonctionnement (\u03c3)', concentration: 'Kt (concentration)', materialLimits: 'Limites du matériau', yieldStrength: 'Limite élastique (Sy)', enduranceLimit: 'Limite d\u2019endurance (Se)', diagnosticFailed: 'Diagnostic échoué', integrityDiagnosis: 'Diagnostic d\u2019intégrité structurelle', safe: 'SÛR', critical: 'CRITIQUE', safeDesc: 'Le composant est dans les limites de fonctionnement sûres pour les cycles et charges spécifiés.', criticalDesc: 'AVERTISSEMENT : Forte probabilité de rupture par fatigue. Les charges cycliques dépassent la limite d\u2019endurance.', primaryFailureMode: 'Mode de défaillance principal', staticSf: 'SF statique', fatigueSf: 'SF fatigue', schematicCaption: 'Schéma technique // Analyse courbe S-N', waitingInput: 'En attente de la charge d\u2019entrée de diagnostic...' },
    shafts: { breadcrumb: 'Poste de travail', assembly: 'Assemblage', title: 'Analyse d\u2019arbre', subtitle: 'Statique de poutre et résolution des réactions pour roulements.', inputTitle: 'Statique et chargement d\u2019arbre', totalLength: 'Longueur totale (L)', forcePosition: 'Position de force (a)', assemblyConnector: 'Connecteur d\u2019assemblage', refHint: 'Fournir $ref à la sortie contrainte engrenage :', refPlaceholder: 'p. ex. {calc_id}.stress', appliedForce: 'Force appliquée (F)', reactionMatrix: 'Matrice de réactions', reactionDesc: 'Forces résolues aux appuis A et B pour injection directe de charge roulement.', dataBusSync: 'Sync bus de données', dataBusDesc: 'Les valeurs résolues sont suivies dans la chronologie pour la cohérence du projet.' },
  },
  it: {
    layout: { returnToCommandCenter: 'Torna al centro di comando', executeAnalysis: 'Esegui analisi', saveToWorkspace: 'Salva nel workspace', status: 'Stato', statusIdle: 'inattivo', statusStable: 'stabile', statusError: 'errore', moduleLoading: 'Caricamento...' },
    resultPanel: { processing: 'Elaborazione richiesta motore', awaiting: 'In attesa di parametri', reportIssue: 'Segnala problema', engineVerified: 'Motore verificato', hideLogs: 'Nascondi log', inspect: 'Ispeziona', calculatedStress: 'Output tensione calcolata', displacementTonnes: 'Dislocamento / Tonnellate', executionMs: 'Esecuzione', determinism: 'Determinismo v1.0', executionTimeline: 'Timeline di esecuzione', totalLogicStages: 'Fasi logiche totali', steps: 'passi' },
    naval: { title: 'Idrostatica navale', hullDimensions: 'Dimensioni scafo', length: 'Lunghezza (Lpp)', beam: 'Larghezza (B)', draft: 'Pescaggio (T)', blockCoeff: 'Coeff. di blocco (Cb)', loadingStability: 'Carico e stabilità', centerOfGravity: 'Baricentro (KG)', waterDensity: 'Densità acqua', simulationFailed: 'Simulazione fallita', marineAssessment: 'Valutazione stabilità marina', stable: 'STABILE', unstable: 'INSTABILE', stableDesc: 'La nave ha altezza metacentrica positiva con momento di raddrizzamento al rollio.', unstableDesc: 'AVVISO: GM negativo rilevato. La nave manca di stabilità iniziale e può capovolgersi.', metacentricHeight: 'Altezza metacentrica (GM)', displacement: 'Dislocamento', buoyancyForce: 'Forza di galleggiamento', schematicCaption: 'Schema tecnico // Curva stabilità statica', initiating: 'Avvio simulazione idrostatica...' },
    failure: { title: 'Diagnosi guasto', stressParameters: 'Parametri di tensione', operatingStress: 'Tensione operativa (\u03c3)', concentration: 'Kt (concentrazione)', materialLimits: 'Limiti del materiale', yieldStrength: 'Tensione di snervamento (Sy)', enduranceLimit: 'Limite di fatica (Se)', diagnosticFailed: 'Diagnosi fallita', integrityDiagnosis: 'Diagnosi integrità strutturale', safe: 'SICURO', critical: 'CRITICO', safeDesc: 'Il componente è entro i limiti operativi sicuri per i cicli e carichi specificati.', criticalDesc: 'AVVISO: Alta probabilità di rottura a fatica. I carichi ciclici superano il limite di resistenza.', primaryFailureMode: 'Modalità di guasto primaria', staticSf: 'SF statico', fatigueSf: 'SF fatica', schematicCaption: 'Schema tecnico // Analisi curva S-N', waitingInput: 'In attesa del payload di input diagnostico...' },
    shafts: { breadcrumb: 'Workstation', assembly: 'Assemblaggio', title: 'Analisi albero', subtitle: 'Statica della trave e risoluzione reazioni per cuscinetti.', inputTitle: 'Statica e carico albero', totalLength: 'Lunghezza totale (L)', forcePosition: 'Posizione forza (a)', assemblyConnector: 'Connettore assemblaggio', refHint: 'Fornire $ref all\u2019output tensione ingranaggio:', refPlaceholder: 'es. {calc_id}.stress', appliedForce: 'Forza applicata (F)', reactionMatrix: 'Matrice reazioni', reactionDesc: 'Forze risolte ai supporti A e B per iniezione diretta carico cuscinetto.', dataBusSync: 'Sync data-bus', dataBusDesc: 'I valori risolti sono tracciati nella timeline per coerenza di progetto.' },
  },
  pt: {
    layout: { returnToCommandCenter: 'Voltar ao centro de comando', executeAnalysis: 'Executar análise', saveToWorkspace: 'Salvar no workspace', status: 'Estado', statusIdle: 'ocioso', statusStable: 'estável', statusError: 'erro', moduleLoading: 'Carregando...' },
    resultPanel: { processing: 'Processando solicitação do motor', awaiting: 'Aguardando parâmetros', reportIssue: 'Reportar problema', engineVerified: 'Motor verificado', hideLogs: 'Ocultar logs', inspect: 'Inspecionar', calculatedStress: 'Saída de tensão calculada', displacementTonnes: 'Deslocamento / Toneladas', executionMs: 'Execução', determinism: 'Determinismo v1.0', executionTimeline: 'Linha do tempo de execução', totalLogicStages: 'Etapas lógicas totais', steps: 'passos' },
    naval: { title: 'Hidrostática naval', hullDimensions: 'Dimensões do casco', length: 'Comprimento (Lpp)', beam: 'Boca (B)', draft: 'Calado (T)', blockCoeff: 'Coef. de bloco (Cb)', loadingStability: 'Carga e estabilidade', centerOfGravity: 'Centro de gravidade (KG)', waterDensity: 'Densidade da água', simulationFailed: 'Simulação falhou', marineAssessment: 'Avaliação de estabilidade marinha', stable: 'ESTÁVEL', unstable: 'INSTÁVEL', stableDesc: 'A embarcação possui altura metacêntrica positiva garantindo momento de endireitamento ao rolamento.', unstableDesc: 'AVISO: GM negativo detectado. A embarcação carece de estabilidade inicial e pode capotar.', metacentricHeight: 'Altura metacêntrica (GM)', displacement: 'Deslocamento', buoyancyForce: 'Força de flutuabilidade', schematicCaption: 'Esquema técnico // Curva de estabilidade estática', initiating: 'Iniciando simulação hidrostática...' },
    failure: { title: 'Diagnóstico de falha', stressParameters: 'Parâmetros de tensão', operatingStress: 'Tensão de operação (\u03c3)', concentration: 'Kt (concentração)', materialLimits: 'Limites do material', yieldStrength: 'Tensão de escoamento (Sy)', enduranceLimit: 'Limite de fadiga (Se)', diagnosticFailed: 'Diagnóstico falhou', integrityDiagnosis: 'Diagnóstico de integridade estrutural', safe: 'SEGURO', critical: 'CRÍTICO', safeDesc: 'O componente está dentro dos limites seguros para os ciclos e cargas especificados.', criticalDesc: 'AVISO: Alta probabilidade de falha por fadiga. As cargas cíclicas excedem o limite de resistência.', primaryFailureMode: 'Modo de falha primário', staticSf: 'SF estático', fatigueSf: 'SF fadiga', schematicCaption: 'Esquema técnico // Análise curva S-N', waitingInput: 'Aguardando payload de entrada de diagnóstico...' },
    shafts: { breadcrumb: 'Workstation', assembly: 'Montagem', title: 'Análise de eixo', subtitle: 'Estática de viga e resolução de reações para rolamentos.', inputTitle: 'Estática e carga do eixo', totalLength: 'Comprimento total (L)', forcePosition: 'Posição da força (a)', assemblyConnector: 'Conector de montagem', refHint: 'Forneça $ref à saída de tensão da engrenagem:', refPlaceholder: 'ex. {calc_id}.stress', appliedForce: 'Força aplicada (F)', reactionMatrix: 'Matriz de reações', reactionDesc: 'Forças resolvidas nos suportes A e B para injeção direta de carga no rolamento.', dataBusSync: 'Sync barramento de dados', dataBusDesc: 'Valores resolvidos são rastreados na linha do tempo para consistência do projeto.' },
  },
  ru: {
    layout: { returnToCommandCenter: 'Вернуться в командный центр', executeAnalysis: 'Выполнить анализ', saveToWorkspace: 'Сохранить в workspace', status: 'Статус', statusIdle: 'ожидание', statusStable: 'стабильно', statusError: 'ошибка', moduleLoading: 'Загрузка...' },
    resultPanel: { processing: 'Обработка запроса движка', awaiting: 'Ожидание параметров', reportIssue: 'Сообщить о проблеме', engineVerified: 'Движок проверен', hideLogs: 'Скрыть логи', inspect: 'Проверить', calculatedStress: 'Расчётное напряжение', displacementTonnes: 'Водоизмещение / Тонны', executionMs: 'Выполнение', determinism: 'Детерминизм v1.0', executionTimeline: 'Временная шкала выполнения', totalLogicStages: 'Всего логических этапов', steps: 'шагов' },
    naval: { title: 'Судовая гидростатика', hullDimensions: 'Размеры корпуса', length: 'Длина (Lpp)', beam: 'Ширина (B)', draft: 'Осадка (T)', blockCoeff: 'Коэф. блока (Cb)', loadingStability: 'Загрузка и остойчивость', centerOfGravity: 'Центр тяжести (KG)', waterDensity: 'Плотность воды', simulationFailed: 'Симуляция не удалась', marineAssessment: 'Оценка морской остойчивости', stable: 'УСТОЙЧИВО', unstable: 'НЕУСТОЙЧИВО', stableDesc: 'Судно имеет положительную метацентрическую высоту, обеспечивающую самовыравнивающий момент при крене.', unstableDesc: 'ПРЕДУПРЕЖДЕНИЕ: Обнаружен отрицательный GM. Судно не имеет начальной остойчивости и может опрокинуться.', metacentricHeight: 'Метацентрическая высота (GM)', displacement: 'Водоизмещение', buoyancyForce: 'Сила плавучести', schematicCaption: 'Техническая схема // Кривая статической остойчивости', initiating: 'Запуск гидростатической симуляции...' },
    failure: { title: 'Диагностика отказа', stressParameters: 'Параметры напряжения', operatingStress: 'Рабочее напряжение (\u03c3)', concentration: 'Kt (концентрация)', materialLimits: 'Пределы материала', yieldStrength: 'Предел текучести (Sy)', enduranceLimit: 'Предел выносливости (Se)', diagnosticFailed: 'Диагностика не удалась', integrityDiagnosis: 'Диагностика структурной целостности', safe: 'БЕЗОПАСНО', critical: 'КРИТИЧНО', safeDesc: 'Компонент в пределах безопасной эксплуатации для указанных циклов и нагрузок.', criticalDesc: 'ПРЕДУПРЕЖДЕНИЕ: Высокая вероятность усталостного разрушения. Циклические нагрузки превышают предел выносливости.', primaryFailureMode: 'Основной режим отказа', staticSf: 'Стат. SF', fatigueSf: 'Усталостный SF', schematicCaption: 'Техническая схема // Анализ кривой S-N', waitingInput: 'Ожидание входных данных диагностики...' },
    shafts: { breadcrumb: 'Рабочая станция', assembly: 'Сборка', title: 'Анализ вала', subtitle: 'Статика балки и определение реакций для подшипников.', inputTitle: 'Статика и нагрузка вала', totalLength: 'Общая длина (L)', forcePosition: 'Положение силы (a)', assemblyConnector: 'Соединитель сборки', refHint: 'Укажите $ref к выходу напряжения шестерни:', refPlaceholder: 'напр. {calc_id}.stress', appliedForce: 'Прикладная сила (F)', reactionMatrix: 'Матрица реакций', reactionDesc: 'Силы на опорах A и B для прямой подачи нагрузки на подшипники.', dataBusSync: 'Синхронизация шины данных', dataBusDesc: 'Решённые значения отслеживаются на временной шкале для согласованности проекта.' },
  },
  ja: {
    layout: { returnToCommandCenter: 'コマンドセンターに戻る', executeAnalysis: '解析を実行', saveToWorkspace: 'ワークスペースに保存', status: '状態', statusIdle: '待機', statusStable: '安定', statusError: 'エラー', moduleLoading: '読み込み中...' },
    resultPanel: { processing: 'エンジンリクエスト処理中', awaiting: 'パラメータ待機中', reportIssue: '問題を報告', engineVerified: 'エンジン検証済み', hideLogs: 'ログを非表示', inspect: '検査', calculatedStress: '計算応力出力', displacementTonnes: '排水量 / トン', executionMs: '実行', determinism: '決定論 v1.0', executionTimeline: '実行タイムライン', totalLogicStages: '論理ステージ合計', steps: 'ステップ' },
    naval: { title: '船舶静水力学', hullDimensions: '船体寸法', length: '長さ (Lpp)', beam: '幅 (B)', draft: '喫水 (T)', blockCoeff: 'ブロック係数 (Cb)', loadingStability: '積載と安定性', centerOfGravity: '重心 (KG)', waterDensity: '水の密度', simulationFailed: 'シミュレーション失敗', marineAssessment: '船舶安定性評価', stable: '安定', unstable: '不安定', stableDesc: '船舶は正のメタセントリック高さを持ち、傾斜時の復元モーメントを確保します。', unstableDesc: '警告: 負のGMを検出。初期安定性がなく転覆の可能性があります。', metacentricHeight: 'メタセントリック高さ (GM)', displacement: '排水量', buoyancyForce: '浮力', schematicCaption: '技術模式図 // 静安定曲線', initiating: '静水力学シミュレーションを開始中...' },
    failure: { title: '故障診断', stressParameters: '応力パラメータ', operatingStress: '作動応力 (\u03c3)', concentration: 'Kt (集中)', materialLimits: '材料限界', yieldStrength: '降伏強度 (Sy)', enduranceLimit: '耐久限界 (Se)', diagnosticFailed: '診断失敗', integrityDiagnosis: '構造整合性診断', safe: '安全', critical: '危険', safeDesc: '部品は指定サイクルと荷重条件の安全作動限界内です。', criticalDesc: '警告: 疲労破壊の可能性が高い。繰返し荷重が材料耐久限界を超えています。', primaryFailureMode: '主要故障モード', staticSf: '静的SF', fatigueSf: '疲労SF', schematicCaption: '技術模式図 // S-N疲労曲線分析', waitingInput: '診断入力ペイロードを待機中...' },
    shafts: { breadcrumb: 'ワークステーション', assembly: '組立', title: '軸解析', subtitle: 'ベアリング用の梁静力学と反力解析。', inputTitle: '軸静力学と荷重', totalLength: '全長 (L)', forcePosition: '力の位置 (a)', assemblyConnector: '組立コネクタ', refHint: 'ギア応力出力への $ref を指定:', refPlaceholder: '例: {calc_id}.stress', appliedForce: '加力 (F)', reactionMatrix: '反力マトリクス', reactionDesc: '支持点AとBの力をベアリング荷重注入用に解決。', dataBusSync: 'データバス同期', dataBusDesc: '解決値はプロジェクト全体の一貫性のため実行タイムラインで追跡されます。' },
  },
  zh: {
    layout: { returnToCommandCenter: '返回指挥中心', executeAnalysis: '执行分析', saveToWorkspace: '保存到工作区', status: '状态', statusIdle: '空闲', statusStable: '稳定', statusError: '错误', moduleLoading: '加载中...' },
    resultPanel: { processing: '正在处理引擎请求', awaiting: '等待参数', reportIssue: '报告问题', engineVerified: '引擎已验证', hideLogs: '隐藏日志', inspect: '检查', calculatedStress: '计算应力输出', displacementTonnes: '排水量 / 吨', executionMs: '执行', determinism: '确定性 v1.0', executionTimeline: '执行时间线', totalLogicStages: '逻辑阶段总数', steps: '步' },
    naval: { title: '船舶静水力学', hullDimensions: '船体尺寸', length: '船长 (Lpp)', beam: '船宽 (B)', draft: '吃水 (T)', blockCoeff: '方形系数 (Cb)', loadingStability: '装载与稳性', centerOfGravity: '重心 (KG)', waterDensity: '水密度', simulationFailed: '仿真失败', marineAssessment: '船舶稳性评估', stable: '稳定', unstable: '不稳定', stableDesc: '船舶具有正稳心高度，在横倾时具有自扶正力矩。', unstableDesc: '警告：检测到负GM。船舶缺乏初稳性，可能倾覆。', metacentricHeight: '稳心高度 (GM)', displacement: '排水量', buoyancyForce: '浮力', schematicCaption: '技术示意图 // 静稳性曲线', initiating: '正在启动静水力学仿真...' },
    failure: { title: '故障诊断', stressParameters: '应力参数', operatingStress: '工作应力 (\u03c3)', concentration: 'Kt (应力集中)', materialLimits: '材料极限', yieldStrength: '屈服强度 (Sy)', enduranceLimit: '疲劳极限 (Se)', diagnosticFailed: '诊断失败', integrityDiagnosis: '结构完整性诊断', safe: '安全', critical: '危险', safeDesc: '部件在指定循环和载荷条件下的安全工作范围内。', criticalDesc: '警告：疲劳失效概率高。施加的循环载荷超过材料疲劳极限。', primaryFailureMode: '主要失效模式', staticSf: '静态安全系数', fatigueSf: '疲劳安全系数', schematicCaption: '技术示意图 // S-N 疲劳曲线分析', waitingInput: '等待诊断输入载荷...' },
    shafts: { breadcrumb: '工作站', assembly: '装配', title: '轴分析', subtitle: '轴承用梁静力学与反力求解。', inputTitle: '轴静力学与载荷', totalLength: '总长度 (L)', forcePosition: '力作用位置 (a)', assemblyConnector: '装配连接器', refHint: '提供齿轮应力输出的 $ref：', refPlaceholder: '例如 {calc_id}.stress', appliedForce: '施加力 (F)', reactionMatrix: '反力矩阵', reactionDesc: '在支座 A 和 B 处求解力，用于直接轴承载荷注入。', dataBusSync: '数据总线同步', dataBusDesc: '求解值在执行时间线中跟踪，以确保项目范围一致性。' },
  },
  ko: {
    layout: { returnToCommandCenter: '명령 센터로 돌아가기', executeAnalysis: '분석 실행', saveToWorkspace: '워크스페이스에 저장', status: '상태', statusIdle: '대기', statusStable: '안정', statusError: '오류', moduleLoading: '로드 중...' },
    resultPanel: { processing: '엔진 요청 처리 중', awaiting: '매개변수 대기 중', reportIssue: '문제 보고', engineVerified: '엔진 검증됨', hideLogs: '로그 숨기기', inspect: '검사', calculatedStress: '계산 응력 출력', displacementTonnes: '배수량 / 톤', executionMs: '실행', determinism: '결정론 v1.0', executionTimeline: '실행 타임라인', totalLogicStages: '총 논리 단계', steps: '단계' },
    naval: { title: '선박 정수역학', hullDimensions: '선체 치수', length: '길이 (Lpp)', beam: '폭 (B)', draft: '흘수 (T)', blockCoeff: '블록 계수 (Cb)', loadingStability: '적재 및 안정성', centerOfGravity: '무게 중심 (KG)', waterDensity: '물 밀도', simulationFailed: '시뮬레이션 실패', marineAssessment: '해양 안정성 평가', stable: '안정', unstable: '불안정', stableDesc: '선박은 양의 메타센트릭 높이를 가져 경사 시 자복 모멘트를 보장합니다.', unstableDesc: '경고: 음의 GM 감지. 초기 안정성이 부족하여 전복될 수 있습니다.', metacentricHeight: '메타센트릭 높이 (GM)', displacement: '배수량', buoyancyForce: '부력', schematicCaption: '기술 개략도 // 정적 안정성 곡선', initiating: '정수역학 시뮬레이션 시작 중...' },
    failure: { title: '고장 진단', stressParameters: '응력 매개변수', operatingStress: '작동 응력 (\u03c3)', concentration: 'Kt (집중)', materialLimits: '재료 한계', yieldStrength: '항복 강도 (Sy)', enduranceLimit: '피로 한계 (Se)', diagnosticFailed: '진단 실패', integrityDiagnosis: '구조 무결성 진단', safe: '안전', critical: '위험', safeDesc: '부품이 지정된 사이클 및 하중 조건의 안전 작동 한계 내에 있습니다.', criticalDesc: '경고: 피로 파괴 가능성 높음. 적용된 반복 하중이 재료 피로 한계를 초과합니다.', primaryFailureMode: '주요 고장 모드', staticSf: '정적 SF', fatigueSf: '피로 SF', schematicCaption: '기술 개략도 // S-N 피로 곡선 분석', waitingInput: '진단 입력 페이로드 대기 중...' },
    shafts: { breadcrumb: '워크스테이션', assembly: '조립', title: '축 분석', subtitle: '베어링용 보 정역학 및 반력 해석.', inputTitle: '축 정역학 및 하중', totalLength: '전체 길이 (L)', forcePosition: '힘 위치 (a)', assemblyConnector: '조립 커넥터', refHint: '기어 응력 출력에 대한 $ref 제공:', refPlaceholder: '예: {calc_id}.stress', appliedForce: '가하 힘 (F)', reactionMatrix: '반력 행렬', reactionDesc: '지지점 A와 B에서 베어링 하중 주입용 힘을 해석합니다.', dataBusSync: '데이터 버스 동기화', dataBusDesc: '해석된 값은 프로젝트 전체 일관성을 위해 실행 타임라인에서 추적됩니다.' },
  },
  ar: {
    layout: { returnToCommandCenter: 'العودة إلى مركز القيادة', executeAnalysis: 'تنفيذ التحليل', saveToWorkspace: 'حفظ في مساحة العمل', status: 'الحالة', statusIdle: 'خامل', statusStable: 'مستقر', statusError: 'خطأ', moduleLoading: 'جارٍ التحميل...' },
    resultPanel: { processing: 'معالجة طلب المحرك', awaiting: 'في انتظار المعلمات', reportIssue: 'الإبلاغ عن مشكلة', engineVerified: 'تم التحقق من المحرك', hideLogs: 'إخفاء السجلات', inspect: 'فحص', calculatedStress: 'مخرجات الإجهاد المحسوب', displacementTonnes: 'الإزاحة / أطنان', executionMs: 'التنفيذ', determinism: 'الحتمية v1.0', executionTimeline: 'الجدول الزمني للتنفيذ', totalLogicStages: 'إجمالي مراحل المنطق', steps: 'خطوات' },
    naval: { title: 'الهيدروستاتيكا البحرية', hullDimensions: 'أبعاد الهيكل', length: 'الطول (Lpp)', beam: 'العرض (B)', draft: 'الغاطس (T)', blockCoeff: 'معامل الكتلة (Cb)', loadingStability: 'التحميل والاستقرار', centerOfGravity: 'مركز الثقل (KG)', waterDensity: 'كثافة الماء', simulationFailed: 'فشلت المحاكاة', marineAssessment: 'تقييم الاستقرار البحري', stable: 'مستقر', unstable: 'غير مستقر', stableDesc: 'تمتلك السفينة ارتفاعاً ميتاسنترياً موجباً يضمن عزم استرداد ذاتي عند الميل.', unstableDesc: 'تحذير: تم اكتشاف GM سالب. تفتقر السفينة إلى الاستقرار الأولي وقد تنقلب.', metacentricHeight: 'الارتفاع الميتاسنتري (GM)', displacement: 'الإزاحة', buoyancyForce: 'قوة الطفو', schematicCaption: 'مخطط تقني // منحنى الاستقرار الساكن', initiating: 'جارٍ بدء محاكاة الهيدروستاتيكا...' },
    failure: { title: 'تشخيص العطل', stressParameters: 'معاملات الإجهاد', operatingStress: 'إجهاد التشغيل (\u03c3)', concentration: 'Kt (تركيز)', materialLimits: 'حدود المادة', yieldStrength: 'مقاومة الخضوع (Sy)', enduranceLimit: 'حد التحمل (Se)', diagnosticFailed: 'فشل التشخيص', integrityDiagnosis: 'تشخيص السلامة الإنشائية', safe: 'آمن', critical: 'حرج', safeDesc: 'المكون ضمن حدود التشغيل الآمنة للدورات وظروف الحمل المحددة.', criticalDesc: 'تحذير: احتمال عالٍ لفشل الإجهاد. الأحمال الدورية تتجاوز حد تحمل المادة.', primaryFailureMode: 'نمط العطل الأساسي', staticSf: 'معامل السلامة الساكن', fatigueSf: 'معامل سلامة الإجهاد', schematicCaption: 'مخطط تقني // تحليل منحنى S-N', waitingInput: 'في انتظار حمولة إدخال التشخيص...' },
    shafts: { breadcrumb: 'محطة العمل', assembly: 'التجميع', title: 'تحليل العمود', subtitle: 'إحصاءات العتبة وحل قوى رد الفعل للمحامل.', inputTitle: 'إحصاءات العمود والحمل', totalLength: 'الطول الكلي (L)', forcePosition: 'موضع القوة (a)', assemblyConnector: 'موصل التجميع', refHint: 'قدّم $ref لمخرج إجهاد الترس:', refPlaceholder: 'مثال {calc_id}.stress', appliedForce: 'القوة المطبقة (F)', reactionMatrix: 'مصفوفة رد الفعل', reactionDesc: 'قوى محلولة عند الدعامتين A و B لحقن حمل المحمل مباشرة.', dataBusSync: 'مزامنة ناقل البيانات', dataBusDesc: 'تُتتبع القيم المحلولة في الجدول الزمني للتنفيذ لاتساق المشروع.' },
  },
};

function deepMerge(base, patch) {
  const out = structuredClone(base);
  for (const [k, v] of Object.entries(patch)) {
    if (v && typeof v === 'object' && !Array.isArray(v)) {
      out[k] = { ...out[k], ...v };
    } else {
      out[k] = v;
    }
  }
  return out;
}

export const WORKSTATION = Object.fromEntries(
  Object.keys(LOCALE).map((lang) => [lang, deepMerge(EN, LOCALE[lang])]),
);
