/** Global Module Routing Dictionary — covers every AluCalc OS module */
export interface ModuleRoute {
  keywords: string[];
  route: string;
  en: { label: string; desc: string };
  tr: { label: string; desc: string };
}

export const GLOBAL_MODULES: ModuleRoute[] = [
  { 
    keywords: ['gear','dişli','spur gear','helis dişli','helical','bevel','konik','module','modül','gear ratio','dişli oranı'], 
    route: '/gears/', 
    en: { 
      label: 'Open Gears Module', 
      desc: '**Gears & Power Transmission Engine**\n\nThis workstation provides high-fidelity parametric modeling for spur and helical gears according to ISO 6336 and AGMA 2001-D04 standards. Capabilities include:\n• Dynamic tooth profile generation (Involute geometry)\n• Contact stress (Hertzian) and bending stress (Lewis) analysis\n• Gear ratio optimization for multi-stage reduction\n• Real-time 3D CAD visualization with material-specific weight estimation.' 
    }, 
    tr: { 
      label: 'Dişli Modülünü Aç', 
      desc: '**Dişli & Güç İletimi Mühendislik Çekirdeği**\n\nBu çalışma istasyonu, ISO 6336 ve AGMA 2001-D04 standartlarına uygun olarak düz ve helis dişliler için yüksek sadakatli parametrik modelleme sağlar. Yetenekler şunları içerir:\n• Dinamik diş profili oluşturma (Evolvent geometri)\n• Temas gerilmesi (Hertz) ve eğilme gerilmesi (Lewis) analizi\n• Çok kademeli redüksiyon için dişli oranı optimizasyonu\n• Malzemeye özel ağırlık tahmini ile gerçek zamanlı 3D CAD görselleştirmesi.' 
    } 
  },
  { 
    keywords: ['cad','teknik çizim','technical drawing','draft','2d cad','çizim yap','drawing'], 
    route: '/cad-editor/', 
    en: { 
      label: 'Open CAD Editor', 
      desc: '**Advanced 2D CAD Environment**\n\nA full-featured vector-based drafting suite built for mechanical engineers. It supports:\n• Real-time parametric constraints and geometric relations\n• Professional-grade DXF export for CNC/Laser cutting workflows\n• Smart dimensioning (ISO/ANSI standard) with tolerance support\n• Complex polyline and spline manipulation for profile design.' 
    }, 
    tr: { 
      label: 'CAD Editörünü Aç', 
      desc: '**Gelişmiş 2D CAD Ortamı**\n\nMekanik mühendisleri için oluşturulmuş tam özellikli vektör tabanlı teknik çizim paketi. Şunları destekler:\n• Gerçek zamanlı parametrik kısıtlamalar ve geometrik ilişkiler\n• CNC/Lazer kesim iş akışları için profesyonel seviyede DXF dışa aktarma\n• Tolerans destekli akıllı ölçülendirme (ISO/ANSI standartları)\n• Profil tasarımı için karmaşık çoklu çizgi ve spline manipülasyonu.' 
    } 
  },
  { 
    keywords: ['beam','kiriş','simply supported','cantilever','konsol','sehim','deflection','atıl','moment'], 
    route: '/beam-deflection/', 
    en: { 
      label: 'Open Beam Deflection', 
      desc: '**Structural Beam Analysis Suite**\n\nPerform rigorous structural analysis on linear members under complex loading conditions. Features include:\n• Shear-Force and Bending-Moment diagrams (SFD/BMD)\n• Deflection curve integration using Macaulay’s method\n• Support for multiple point loads, distributed loads (UDL), and moments\n• Cross-section library (I-beams, C-channels, Hollow sections) with automated area moment of inertia calculation.' 
    }, 
    tr: { 
      label: 'Kiriş Sehim Analizini Aç', 
      desc: '**Yapısal Kiriş Analiz Paketi**\n\nKarmaşık yükleme koşulları altında doğrusal elemanlar üzerinde titiz yapısal analizler gerçekleştirin. Özellikler şunları içerir:\n• Kesme kuvveti ve eğilme momenti diyagramları (SFD/BMD)\n• Macaulay yöntemi kullanılarak sehim eğrisi entegrasyonu\n• Çoklu nokta yükleri, yayılı yükler (UDL) ve momentler için destek\n• Otomatik alan atalet momenti hesaplamalı kesit kütüphanesi (I-profil, C-kanal, kutu profil).' 
    } 
  },
  { keywords: ['fatigue','yorulma','s-n','endurance','dayanım','wöhler'], route: '/fatigue/', en: { label: 'Open Fatigue Analysis', desc: '**Fatigue Life Analysis**\n\nS-N curve based fatigue life estimation with stress concentration factors and mean stress corrections.' }, tr: { label: 'Yorulma Analizini Aç', desc: '**Yorulma Ömür Analizi**\n\nS-N eğrisi tabanlı yorulma ömrü tahmini, gerilme yığılma faktörleri ve ortalama gerilme düzeltmeleri.' } },
  { keywords: ['thermal','ısıl','genleşme','expansion','sıcaklık','temperature','heat','ısı'], route: '/thermal/', en: { label: 'Open Thermal Analysis', desc: '**Thermal Expansion Calculator**\n\nLinear and volumetric thermal expansion, heat transfer coefficients, and thermal stress analysis.' }, tr: { label: 'Isıl Analizi Aç', desc: '**Isıl Genleşme Hesaplayıcı**\n\nDoğrusal ve hacimsel ısıl genleşme, ısı transfer katsayıları ve termal gerilme analizi.' } },
  { keywords: ['fluid','akışkan','reynolds','bernoulli','pipe','boru','akış'], route: '/fluids/', en: { label: 'Open Fluid Dynamics', desc: '**Fluid Dynamics**\n\nReynolds number, Bernoulli equation, pipe friction losses (Darcy-Weisbach), and flow regime analysis.' }, tr: { label: 'Akışkanlar Modülünü Aç', desc: '**Akışkanlar Mekaniği**\n\nReynolds sayısı, Bernoulli denklemi, boru sürtünme kayıpları (Darcy-Weisbach) ve akış rejimi analizi.' } },
  { keywords: ['aerospace','havacılık','flight','uçuş','drag','lift','kaldırma','sürükleme'], route: '/aerospace/', en: { label: 'Open Aerospace Module', desc: '**Aerospace Dynamics**\n\nLift/drag coefficient analysis, thrust calculations, and basic flight performance envelope modeling.' }, tr: { label: 'Havacılık Modülünü Aç', desc: '**Havacılık Dinamiği**\n\nKaldırma/sürükleme katsayısı analizi, itki hesaplamaları ve temel uçuş performans zarfı modelleme.' } },
  { keywords: ['kinematic','hız','velocity','ivme','acceleration','hareket','motion','fizik hareket'], route: '/kinematics/', en: { label: 'Open Kinematics', desc: '**Physics Kinematics**\n\nProjectile motion, circular motion, and multi-body kinematic chain solvers.' }, tr: { label: 'Kinematik Modülünü Aç', desc: '**Fizik Kinematiği**\n\nMermi hareketi, dairesel hareket ve çok gövdeli kinematik zincir çözücüler.' } },
  { keywords: ['fea','finite element','sonlu eleman','simülasyon','simulation','mesh'], route: '/simulation-fea/', en: { label: 'Open FEA Simulation', desc: '**Finite Element Analysis**\n\nInteractive FEA mesh generation, boundary condition assignment, and stress/displacement result visualization.' }, tr: { label: 'FEA Simülasyonu Aç', desc: '**Sonlu Eleman Analizi**\n\nİnteraktif FEA ağ oluşturma, sınır koşulu atama ve gerilme/deplasman sonuç görselleştirmesi.' } },
  { keywords: ['topology','topoloji','generative','optimizasyon'], route: '/topology-optimization/', en: { label: 'Open Topology Optimization', desc: '**Topology Optimization**\n\nGenerative design with density-based topology optimization for lightweight structural components.' }, tr: { label: 'Topoloji Optimizasyonunu Aç', desc: '**Topoloji Optimizasyonu**\n\nHafif yapısal bileşenler için yoğunluk tabanlı topoloji optimizasyonu ile jeneratif tasarım.' } },
  { keywords: ['cutting','kesim','bar','stock','profil kesim','cut optim'], route: '/cutting-optimizer/', en: { label: 'Open Cutting Optimizer', desc: '**1D Cutting Optimizer**\n\nOptimal cutting patterns for bar/profile stock to minimize waste and maximize material yield.' }, tr: { label: 'Kesim Optimizasyonunu Aç', desc: '**1D Kesim Optimizasyonu**\n\nMinimum fire ve maksimum malzeme verimi için çubuk/profil stok kesim planı optimizasyonu.' } },
  { keywords: ['material database','malzeme veritabanı','material propert','malzeme özellik','materials-db'], route: '/materials-db/', en: { label: 'Open Materials Database', desc: '**Materials Database**\n\nSearchable database of engineering materials with mechanical, thermal, and physical properties.' }, tr: { label: 'Malzeme Veritabanını Aç', desc: '**Malzeme Veritabanı**\n\nMekanik, termal ve fiziksel özellikleriyle aranabilir mühendislik malzemeleri veritabanı.' } },
  { keywords: ['material explorer','malzeme keşf','ashby','compare material','malzeme karşılaştır'], route: '/materials-explorer/', en: { label: 'Open Materials Explorer', desc: '**Materials Explorer**\n\nAshby-style material selection charts for multi-criteria engineering material comparison.' }, tr: { label: 'Malzeme Keşfini Aç', desc: '**Malzeme Keşfi**\n\nÇok kriterli mühendislik malzemesi karşılaştırması için Ashby tarzı malzeme seçim grafikleri.' } },
  { keywords: ['material selector','malzeme seçici','ai material','malzeme öner','recommend material'], route: '/material-selector-ai/', en: { label: 'Open AI Material Selector', desc: '**AI Material Selector**\n\nIntelligent material recommendation engine based on loading conditions, environment, and cost constraints.' }, tr: { label: 'AI Malzeme Seçiciyi Aç', desc: '**AI Malzeme Seçici**\n\nYükleme koşulları, ortam ve maliyet kısıtlamalarına dayalı akıllı malzeme öneri motoru.' } },
  { keywords: ['motor','elektrik motor','electric motor','motor seç','select motor'], route: '/motor-selection/', en: { label: 'Open Motor Selection', desc: '**Motor Selection**\n\nIEC/NEMA standard motor sizing with torque-speed curves and efficiency class comparison.' }, tr: { label: 'Motor Seçimini Aç', desc: '**Motor Seçimi**\n\nIEC/NEMA standart motor boyutlandırma, tork-hız eğrileri ve verimlilik sınıfı karşılaştırması.' } },
  { keywords: ['gearbox','dişli kutusu','şanzıman','transmission','gear train','iletim'], route: '/gearbox-design/', en: { label: 'Open Gearbox Design', desc: '**Gearbox Design**\n\nMulti-stage gear train synthesis with ratio distribution, shaft layout, and housing envelope estimation.' }, tr: { label: 'Dişli Kutusu Tasarımını Aç', desc: '**Dişli Kutusu Tasarımı**\n\nÇok kademeli dişli takımı sentezi, oran dağılımı, mil yerleşimi ve gövde zarf tahmini.' } },
  { keywords: ['planetary','planet','gezegen dişli','güneş dişli','epicyclic','sun gear'], route: '/planetary-gearbox/', en: { label: 'Open Planetary Gearbox', desc: '**Planetary Gearbox**\n\nEpicyclic gear train analysis with animated sun-planet-ring visualization and ratio calculation.' }, tr: { label: 'Planet Dişli Kutusunu Aç', desc: '**Planet Dişli Kutusu**\n\nAnimasyonlu güneş-gezegen-halka görselleştirmesi ve oran hesabı ile episiklik dişli analizi.' } },
  { keywords: ['failure predict','arıza tahmin','reliability','güvenilirlik','predict failure'], route: '/failure-prediction/', en: { label: 'Open Failure Prediction', desc: '**Failure Prediction**\n\nReliability engineering tools for MTBF estimation and component failure probability modeling.' }, tr: { label: 'Arıza Tahminini Aç', desc: '**Arıza Tahmini**\n\nMTBF tahmini ve bileşen arıza olasılığı modelleme için güvenilirlik mühendisliği araçları.' } },
  { keywords: ['failure diagnos','arıza teşhis','root cause','kök neden','diagnose'], route: '/failure-diagnosis/', en: { label: 'Open Failure Diagnosis', desc: '**Failure Diagnosis**\n\nRoot cause analysis tools with fault tree analysis (FTA) and failure mode identification.' }, tr: { label: 'Arıza Teşhisini Aç', desc: '**Arıza Teşhisi**\n\nHata ağacı analizi (FTA) ve arıza modu tanımlama ile kök neden analiz araçları.' } },
  { keywords: ['concrete','beton','reinforcement','donatı','rebar','betonarme'], route: '/concrete-reinforcement/', en: { label: 'Open Concrete Module', desc: '**Concrete Reinforcement**\n\nReinforced concrete beam/column design with rebar layout per Eurocode 2 / ACI 318.' }, tr: { label: 'Betonarme Modülünü Aç', desc: '**Betonarme Hesabı**\n\nEurocode 2 / ACI 318 uyarınca betonarme kiriş/kolon tasarımı ve donatı yerleşimi.' } },
  { keywords: ['ohm','direnç','resistance','current','akım','elektrik','electrical'], route: '/ohms-law/', en: { label: 'Open Ohm\'s Law', desc: '**Ohm\'s Law Calculator**\n\nVoltage, current, resistance, and power calculations with series/parallel circuit analysis.' }, tr: { label: 'Ohm Kanunu Hesaplayıcıyı Aç', desc: '**Ohm Kanunu Hesaplayıcı**\n\nSeri/paralel devre analizi ile gerilim, akım, direnç ve güç hesaplamaları.' } },
  { keywords: ['voltage drop','gerilim düşümü','kablo','cable','wire','kesit'], route: '/voltage-drop/', en: { label: 'Open Voltage Drop', desc: '**Voltage Drop Calculator**\n\nCable sizing and voltage drop verification per IEC 60364 / NEC standards.' }, tr: { label: 'Gerilim Düşümünü Aç', desc: '**Gerilim Düşümü Hesaplayıcı**\n\nIEC 60364 / NEC standartlarına göre kablo boyutlandırma ve gerilim düşümü doğrulama.' } },
  { keywords: ['three phase','3 phase','üç faz','3 faz','three-phase'], route: '/three-phase-power/', en: { label: 'Open Three Phase Power', desc: '**Three Phase Power**\n\nStar/delta connection analysis, power factor correction, and 3-phase load balancing.' }, tr: { label: 'Üç Faz Gücünü Aç', desc: '**Üç Fazlı Güç**\n\nYıldız/üçgen bağlantı analizi, güç faktörü düzeltmesi ve 3 fazlı yük dengeleme.' } },
  { keywords: ['digital logic','dijital mantık','gate','boolean','logic gate','kapı'], route: '/digital-logic/', en: { label: 'Open Digital Logic', desc: '**Digital Logic Simulator**\n\nInteractive AND/OR/NOT/XOR gate circuit builder with truth table generation.' }, tr: { label: 'Dijital Mantık Simülatörünü Aç', desc: '**Dijital Mantık Simülatörü**\n\nDoğruluk tablosu oluşturma ile interaktif AND/OR/NOT/XOR kapı devre oluşturucu.' } },
  { keywords: ['filter','filtre','low pass','high pass','bandpass','frekans','frequency'], route: '/filter-design/', en: { label: 'Open Filter Design', desc: '**Filter Design**\n\nButterworth/Chebyshev active filter design with Bode plot visualization and component values.' }, tr: { label: 'Filtre Tasarımını Aç', desc: '**Filtre Tasarımı**\n\nBode grafiği görselleştirmesi ve bileşen değerleri ile Butterworth/Chebyshev aktif filtre tasarımı.' } },
  { keywords: ['periodic','periyodik','element','atom','atomic'], route: '/periodic-table/', en: { label: 'Open Periodic Table', desc: '**Interactive Periodic Table**\n\nFull periodic table with atomic properties, electron configurations, and element comparison.' }, tr: { label: 'Periyodik Tabloyu Aç', desc: '**İnteraktif Periyodik Tablo**\n\nAtomik özellikler, elektron konfigürasyonları ve element karşılaştırması ile tam periyodik tablo.' } },
  { keywords: ['chemistry','kimya','reaction','reaksiyon','denklem','equation','balance'], route: '/chemistry-reactions/', en: { label: 'Open Chemistry Module', desc: '**Chemistry Reactions**\n\nChemical equation balancing, stoichiometry calculations, and reaction type classification.' }, tr: { label: 'Kimya Modülünü Aç', desc: '**Kimyasal Reaksiyonlar**\n\nKimyasal denklem dengeleme, stokiyometri hesaplamaları ve reaksiyon tipi sınıflandırması.' } },
  { keywords: ['biology','biyoloji','genetics','genetik','dna','gen'], route: '/biology-genetics/', en: { label: 'Open Biology Module', desc: '**Biology & Genetics**\n\nPunnett square generator, DNA/RNA transcription tools, and genetic inheritance calculators.' }, tr: { label: 'Biyoloji Modülünü Aç', desc: '**Biyoloji & Genetik**\n\nPunnett karesi oluşturucu, DNA/RNA transkripsiyon araçları ve genetik kalıtım hesaplayıcıları.' } },
  { keywords: ['algorithm','algoritma','sorting','sıralama','data structure','bilgisayar'], route: '/cs-algorithms/', en: { label: 'Open CS Algorithms', desc: '**CS Algorithms**\n\nInteractive sorting/searching algorithm visualizer with complexity analysis and step-by-step execution.' }, tr: { label: 'Algoritma Modülünü Aç', desc: '**Bilgisayar Algoritmaları**\n\nKarmaşıklık analizi ve adım adım yürütme ile interaktif sıralama/arama algoritma görselleştirici.' } },
  { keywords: ['naval','gemi','hydrostatic','hidrostatik','ship','buoyancy','hull','tekne'], route: '/naval-hydrostatics/', en: { label: 'Open Naval Hydrostatics', desc: '**Naval Hydrostatics**\n\nHull displacement, buoyancy center, metacentric height, and stability curve calculations.' }, tr: { label: 'Gemi Hidrostatiğini Aç', desc: '**Gemi Hidrostatiği**\n\nTekne deplasmanı, kaldırma merkezi, metasentrik yükseklik ve stabilite eğrisi hesaplamaları.' } },
  { keywords: ['physics solver','fizik çöz','physics calc','fizik hesap','formül','formula'], route: '/physics-solver/', en: { label: 'Open Physics Solver', desc: '**Physics Solver**\n\nMulti-domain physics equation solver covering mechanics, thermodynamics, and electromagnetism.' }, tr: { label: 'Fizik Çözücüyü Aç', desc: '**Fizik Çözücü**\n\nMekanik, termodinamik ve elektromanyetizmayı kapsayan çok alanlı fizik denklem çözücü.' } },
  { keywords: ['lubrication','yağlama','lubricant','yağ','gres','grease','reducer lubric'], route: '/reducer-lubrication/', en: { label: 'Open Lubrication Module', desc: '**Reducer Lubrication**\n\nLubricant selection, oil volume calculation, and viscosity-temperature analysis for gearbox applications.' }, tr: { label: 'Yağlama Modülünü Aç', desc: '**Redüktör Yağlama**\n\nDişli kutusu uygulamaları için yağ seçimi, yağ hacmi hesabı ve viskozite-sıcaklık analizi.' } },
  { keywords: ['bolt torque','tork','sıkma torku','tightening','preload','ön yükleme','bulon'], route: '/bolt-torque/', en: { label: 'Open Bolt Torque', desc: '**Bolt Torque Calculator**\n\nPreload force, tightening torque, and bolt stress calculations per VDI 2230 methodology.' }, tr: { label: 'Cıvata Tork Hesabını Aç', desc: '**Cıvata Tork Hesaplayıcı**\n\nVDI 2230 metodolojisine göre ön yükleme kuvveti, sıkma torku ve cıvata gerilme hesaplamaları.' } },
  { keywords: ['machining','talaşlı','cnc','torna','turning','freze','milling','lathe'], route: '/machining-details/', en: { label: 'Open Machining Module', desc: '**Machining Details**\n\nCNC turning/milling parameter calculator: cutting speed, feed rate, and tool life estimation.' }, tr: { label: 'İşleme Modülünü Aç', desc: '**Talaşlı İmalat Detayları**\n\nCNC torna/freze parametre hesaplayıcı: kesme hızı, ilerleme ve takım ömrü tahmini.' } },
  { keywords: ['fatigue advanced','gelişmiş yorulma','miner','cumulative','hasar birikimi'], route: '/fatigue-advanced/', en: { label: 'Open Advanced Fatigue', desc: '**Advanced Fatigue Analysis**\n\nMiner\'s rule cumulative damage, variable amplitude loading, and rainflow cycle counting.' }, tr: { label: 'Gelişmiş Yorulma Analizini Aç', desc: '**Gelişmiş Yorulma Analizi**\n\nMiner kuralı kümülatif hasar, değişken genlikli yükleme ve rainflow çevrim sayımı.' } },
  { keywords: ['machine assembly','makine montaj','assembly','montaj'], route: '/machine-assembly/', en: { label: 'Open Machine Assembly', desc: '**Machine Assembly**\n\nAssembly sequence planning, interference checking, and tolerance stack-up analysis.' }, tr: { label: 'Makine Montajını Aç', desc: '**Makine Montajı**\n\nMontaj sıralama planlaması, girişim kontrolü ve tolerans yığılma analizi.' } },
  { keywords: ['manufacturing readiness','üretim hazırlık','mfg ready'], route: '/mfg-readiness/', en: { label: 'Open MFG Readiness', desc: '**Manufacturing Readiness**\n\nManufacturing readiness level (MRL) assessment and production feasibility evaluation.' }, tr: { label: 'Üretim Hazırlığını Aç', desc: '**Üretim Hazırlığı**\n\nÜretim hazırlık seviyesi (MRL) değerlendirmesi ve üretim fizibilite değerlendirmesi.' } },
  { keywords: ['manufacturing sandbox','üretim sandbox','mfg sandbox'], route: '/mfg-sandbox/', en: { label: 'Open MFG Sandbox', desc: '**Manufacturing Sandbox**\n\nExperimental manufacturing process simulation and parameter exploration environment.' }, tr: { label: 'Üretim Sandbox\'unu Aç', desc: '**Üretim Sandbox**\n\nDeneysel üretim süreci simülasyonu ve parametre keşif ortamı.' } },
  { keywords: ['engineering selection','mühendislik seçim','component select','komponent seç'], route: '/engineering-selection/', en: { label: 'Open Engineering Selection', desc: '**Engineering Selection System**\n\nMulti-criteria decision analysis (MCDA) for optimal engineering component selection.' }, tr: { label: 'Mühendislik Seçimini Aç', desc: '**Mühendislik Seçim Sistemi**\n\nOptimal mühendislik bileşeni seçimi için çok kriterli karar analizi (ÇKKA).' } },
  { keywords: ['calculator','hesap makinesi','basic calc','temel hesap'], route: '/calculator/', en: { label: 'Open Calculator', desc: '**Scientific Calculator**\n\nFull-featured scientific calculator with engineering notation and unit-aware computation.' }, tr: { label: 'Hesap Makinesini Aç', desc: '**Bilimsel Hesap Makinesi**\n\nMühendislik notasyonu ve birim farkındalıklı hesaplama ile tam özellikli bilimsel hesap makinesi.' } },
  { keywords: ['aluminum','alüminyum profil','profile weight','profil ağırlık'], route: '/aluminum/', en: { label: 'Open Aluminum Module', desc: '**Aluminum Profile Calculator**\n\nCross-section weight, moment of inertia, and section modulus for standard aluminum profiles.' }, tr: { label: 'Alüminyum Modülünü Aç', desc: '**Alüminyum Profil Hesaplayıcı**\n\nStandart alüminyum profiller için kesit ağırlığı, atalet momenti ve kesit modülü hesabı.' } },
];
