/** Auto-generated by scripts/generate-mobile-i18n.mjs — do not edit manually. */
import type { Language } from '@/store/i18nStore';

export type KernelDevStrings = {
  kernelButton: string;
  panelTitle: string;
  boot: string;
  modules: string;
  schemas: string;
  trace: string;
  legacy: string;
  mcp: string;
  activeLogicBridges: string;
  exposedTools: string;
  mcpNote: string;
  loadingKernel: string;
  noExecutionLogs: string;
  runCalculationHint: string;
  success: string;
  inputs: string;
  outputs: string;
  uncategorized: string;
  ready: string;
  connected: string;
  indexing: string;
  note: string;
  devModeRequired: string;
};

const EN: KernelDevStrings = {
    kernelButton: "Kernel",
    panelTitle: "Engineering Kernel OS",
    boot: "BOOT",
    modules: "MODULES",
    schemas: "Schemas",
    trace: "Trace",
    legacy: "Legacy",
    mcp: "MCP",
    activeLogicBridges: "Active Logic Bridges",
    exposedTools: "Exposed Tools",
    mcpNote: "These bridges allow AluCalc AI to access external engineering data and files autonomously.",
    loadingKernel: "Loading kernel state...",
    noExecutionLogs: "No execution logs yet.",
    runCalculationHint: "Run a calculation to see trace.",
    success: "SUCCESS",
    inputs: "INPUTS",
    outputs: "OUTPUTS",
    uncategorized: "Uncategorized",
    ready: "Ready",
    connected: "CONNECTED",
    indexing: "INDEXING",
    note: "NOTE",
    devModeRequired: "Developer mode required to view sandbox tools.",
};

const TR: KernelDevStrings = {
    kernelButton: "Çekirdek",
    panelTitle: "Mühendislik Çekirdek OS",
    boot: "ÖNYÜKLEME",
    modules: "MODÜLLER",
    schemas: "Şemalar",
    trace: "İz",
    legacy: "Eski",
    mcp: "MCP",
    activeLogicBridges: "Aktif Mantık Köprüleri",
    exposedTools: "Açık Araçlar",
    mcpNote: "Bu köprüler AluCalc AI'ın harici mühendislik verilerine otonom erişmesini sağlar.",
    loadingKernel: "Çekirdek durumu yükleniyor...",
    noExecutionLogs: "Henüz yürütme günlüğü yok.",
    runCalculationHint: "İzlemek için bir hesaplama çalıştırın.",
    success: "BAŞARILI",
    inputs: "GİRDİLER",
    outputs: "ÇIKTILAR",
    uncategorized: "Kategorisiz",
    ready: "Hazır",
    connected: "BAĞLI",
    indexing: "İNDEKSLENİYOR",
    note: "NOT",
    devModeRequired: "Sandbox araçlarını görmek için geliştirici modu gerekli.",
};

const DE_KD: KernelDevStrings = {
    kernelButton: "Kernel",
    panelTitle: "Engineering-Kernel-OS",
    boot: "BOOT",
    modules: "MODULE",
    schemas: "Schemas",
    trace: "Trace",
    legacy: "Legacy",
    mcp: "MCP",
    activeLogicBridges: "Aktive Logik-Brücken",
    exposedTools: "Freigegebene Tools",
    mcpNote: "Diese Brücken ermöglichen AluCalc AI den autonomen Zugriff auf externe Ingenieurdaten und Dateien.",
    loadingKernel: "Kernel-Status wird geladen...",
    noExecutionLogs: "Noch keine Ausführungsprotokolle.",
    runCalculationHint: "Führen Sie eine Berechnung aus, um die Trace anzuzeigen.",
    success: "ERFOLG",
    inputs: "EINGABEN",
    outputs: "AUSGABEN",
    uncategorized: "Unkategorisiert",
    ready: "Bereit",
    connected: "VERBUNDEN",
    indexing: "INDIZIERUNG",
    note: "HINWEIS",
    devModeRequired: "Entwicklermodus erforderlich für Sandbox-Tools.",
};

const ES_KD: KernelDevStrings = {
    kernelButton: "Kernel",
    panelTitle: "SO del núcleo de ingeniería",
    boot: "ARRANQUE",
    modules: "MÓDULOS",
    schemas: "Esquemas",
    trace: "Traza",
    legacy: "Legado",
    mcp: "MCP",
    activeLogicBridges: "Puentes lógicos activos",
    exposedTools: "Herramientas expuestas",
    mcpNote: "Estos puentes permiten que AluCalc AI acceda de forma autónoma a datos y archivos de ingeniería externos.",
    loadingKernel: "Cargando estado del kernel...",
    noExecutionLogs: "Aún no hay registros de ejecución.",
    runCalculationHint: "Ejecute un cálculo para ver la traza.",
    success: "ÉXITO",
    inputs: "ENTRADAS",
    outputs: "SALIDAS",
    uncategorized: "Sin categoría",
    ready: "Listo",
    connected: "CONECTADO",
    indexing: "INDEXANDO",
    note: "NOTA",
    devModeRequired: "Se requiere modo desarrollador para ver herramientas sandbox.",
};

const FR_KD: KernelDevStrings = {
    kernelButton: "Noyau",
    panelTitle: "OS Noyau Ingénierie",
    boot: "DÉMARRAGE",
    modules: "MODULES",
    schemas: "Schémas",
    trace: "Trace",
    legacy: "Héritage",
    mcp: "MCP",
    activeLogicBridges: "Ponts logiques actifs",
    exposedTools: "Outils exposés",
    mcpNote: "Ces ponts permettent à AluCalc AI d’accéder de manière autonome aux données et fichiers d’ingénierie externes.",
    loadingKernel: "Chargement de l’état du noyau...",
    noExecutionLogs: "Aucun journal d’exécution pour le moment.",
    runCalculationHint: "Exécutez un calcul pour afficher la trace.",
    success: "SUCCÈS",
    inputs: "ENTRÉES",
    outputs: "SORTIES",
    uncategorized: "Non classé",
    ready: "Prêt",
    connected: "CONNECTÉ",
    indexing: "INDEXATION",
    note: "NOTE",
    devModeRequired: "Mode développeur requis pour afficher les outils sandbox.",
};

const IT_KD: KernelDevStrings = {
    kernelButton: "Kernel",
    panelTitle: "OS Kernel Ingegneria",
    boot: "AVVIO",
    modules: "MODULI",
    schemas: "Schemi",
    trace: "Traccia",
    legacy: "Legacy",
    mcp: "MCP",
    activeLogicBridges: "Ponti logici attivi",
    exposedTools: "Strumenti esposti",
    mcpNote: "Questi ponti consentono ad AluCalc AI di accedere autonomamente a dati e file di ingegneria esterni.",
    loadingKernel: "Caricamento stato del kernel...",
    noExecutionLogs: "Nessun log di esecuzione ancora.",
    runCalculationHint: "Esegui un calcolo per visualizzare la traccia.",
    success: "SUCCESSO",
    inputs: "INGRESSI",
    outputs: "USCITE",
    uncategorized: "Non categorizzato",
    ready: "Pronto",
    connected: "CONNESSO",
    indexing: "INDICIZZAZIONE",
    note: "NOTA",
    devModeRequired: "Modalità sviluppatore richiesta per visualizzare gli strumenti sandbox.",
};

const PT_KD: KernelDevStrings = {
    kernelButton: "Kernel",
    panelTitle: "SO Kernel de Engenharia",
    boot: "INICIALIZAÇÃO",
    modules: "MÓDULOS",
    schemas: "Esquemas",
    trace: "Rastreio",
    legacy: "Legado",
    mcp: "MCP",
    activeLogicBridges: "Pontes lógicas ativas",
    exposedTools: "Ferramentas expostas",
    mcpNote: "Estas pontes permitem que o AluCalc AI aceda de forma autónoma a dados e ficheiros de engenharia externos.",
    loadingKernel: "A carregar estado do kernel...",
    noExecutionLogs: "Ainda não há registos de execução.",
    runCalculationHint: "Execute um cálculo para ver o rastreio.",
    success: "SUCESSO",
    inputs: "ENTRADAS",
    outputs: "SAÍDAS",
    uncategorized: "Sem categoria",
    ready: "Pronto",
    connected: "LIGADO",
    indexing: "INDEXAÇÃO",
    note: "NOTA",
    devModeRequired: "Modo de desenvolvedor necessário para ver ferramentas sandbox.",
};

const RU_KD: KernelDevStrings = {
    kernelButton: "Ядро",
    panelTitle: "Инженерная ОС ядра",
    boot: "ЗАГРУЗКА",
    modules: "МОДУЛИ",
    schemas: "Схемы",
    trace: "Трассировка",
    legacy: "Legacy",
    mcp: "MCP",
    activeLogicBridges: "Активные логические мосты",
    exposedTools: "Доступные инструменты",
    mcpNote: "Эти мосты позволяют AluCalc AI автономно получать доступ к внешним инженерным данным и файлам.",
    loadingKernel: "Загрузка состояния ядра...",
    noExecutionLogs: "Журналов выполнения пока нет.",
    runCalculationHint: "Запустите расчёт, чтобы увидеть трассировку.",
    success: "УСПЕХ",
    inputs: "ВХОДЫ",
    outputs: "ВЫХОДЫ",
    uncategorized: "Без категории",
    ready: "Готово",
    connected: "ПОДКЛЮЧЕНО",
    indexing: "ИНДЕКСАЦИЯ",
    note: "ПРИМЕЧАНИЕ",
    devModeRequired: "Для просмотра sandbox-инструментов требуется режим разработчика.",
};

const JA_KD: KernelDevStrings = {
    kernelButton: "カーネル",
    panelTitle: "エンジニアリングカーネルOS",
    boot: "ブート",
    modules: "モジュール",
    schemas: "スキーマ",
    trace: "トレース",
    legacy: "レガシー",
    mcp: "MCP",
    activeLogicBridges: "アクティブロジックブリッジ",
    exposedTools: "公開ツール",
    mcpNote: "これらのブリッジにより、AluCalc AIは外部のエンジニアリングデータとファイルに自律的にアクセスできます。",
    loadingKernel: "カーネル状態を読み込み中...",
    noExecutionLogs: "実行ログはまだありません。",
    runCalculationHint: "計算を実行してトレースを表示します。",
    success: "成功",
    inputs: "入力",
    outputs: "出力",
    uncategorized: "未分類",
    ready: "準備完了",
    connected: "接続済み",
    indexing: "インデックス作成中",
    note: "注記",
    devModeRequired: "サンドボックスツールの表示には開発者モードが必要です。",
};

const ZH_KD: KernelDevStrings = {
    kernelButton: "内核",
    panelTitle: "工程内核 OS",
    boot: "启动",
    modules: "模块",
    schemas: "模式",
    trace: "追踪",
    legacy: "旧版",
    mcp: "MCP",
    activeLogicBridges: "活动逻辑桥接",
    exposedTools: "公开工具",
    mcpNote: "这些桥接使 AluCalc AI 能够自主访问外部工程数据和文件。",
    loadingKernel: "正在加载内核状态...",
    noExecutionLogs: "尚无执行日志。",
    runCalculationHint: "运行计算以查看追踪。",
    success: "成功",
    inputs: "输入",
    outputs: "输出",
    uncategorized: "未分类",
    ready: "就绪",
    connected: "已连接",
    indexing: "索引中",
    note: "备注",
    devModeRequired: "查看沙盒工具需要开发者模式。",
};

const KO_KD: KernelDevStrings = {
    kernelButton: "커널",
    panelTitle: "엔지니어링 커널 OS",
    boot: "부트",
    modules: "모듈",
    schemas: "스키마",
    trace: "추적",
    legacy: "레거시",
    mcp: "MCP",
    activeLogicBridges: "활성 로직 브리지",
    exposedTools: "노출된 도구",
    mcpNote: "이 브리지를 통해 AluCalc AI가 외부 엔지니어링 데이터 및 파일에 자율적으로 접근할 수 있습니다.",
    loadingKernel: "커널 상태 로드 중...",
    noExecutionLogs: "아직 실행 로그가 없습니다.",
    runCalculationHint: "계산을 실행하여 추적을 확인하세요.",
    success: "성공",
    inputs: "입력",
    outputs: "출력",
    uncategorized: "미분류",
    ready: "준비됨",
    connected: "연결됨",
    indexing: "인덱싱",
    note: "참고",
    devModeRequired: "샌드박스 도구를 보려면 개발자 모드가 필요합니다.",
};

const AR_KD: KernelDevStrings = {
    kernelButton: "النواة",
    panelTitle: "نظام نواة الهندسة",
    boot: "إقلاع",
    modules: "الوحدات",
    schemas: "المخططات",
    trace: "التتبع",
    legacy: "قديم",
    mcp: "MCP",
    activeLogicBridges: "جسور المنطق النشطة",
    exposedTools: "الأدوات المعرّضة",
    mcpNote: "تتيح هذه الجسور لـ AluCalc AI الوصول الذاتي إلى بيانات وملفات الهندسة الخارجية.",
    loadingKernel: "جارٍ تحميل حالة النواة...",
    noExecutionLogs: "لا توجد سجلات تنفيذ بعد.",
    runCalculationHint: "نفّذ حساباً لعرض التتبع.",
    success: "نجاح",
    inputs: "المدخلات",
    outputs: "المخرجات",
    uncategorized: "غير مصنّف",
    ready: "جاهز",
    connected: "متصل",
    indexing: "فهرسة",
    note: "ملاحظة",
    devModeRequired: "يلزم وضع المطور لعرض أدوات sandbox.",
};

const BY_LOCALE: Record<Language, KernelDevStrings> = {
  en: EN,
  tr: TR,
  de: DE_KD,
  es: ES_KD,
  fr: FR_KD,
  it: IT_KD,
  pt: PT_KD,
  ru: RU_KD,
  ja: JA_KD,
  zh: ZH_KD,
  ko: KO_KD,
  ar: AR_KD,
};

export function getKernelDevStrings(locale: string): KernelDevStrings {
  return BY_LOCALE[locale as Language] ?? EN;
}
