'use client';

import { useState } from 'react';
import { FileDown, Camera } from 'lucide-react';
import { toPng } from 'html-to-image';

interface PDFGeneratorProps {
    filename: string;
    title: string;
    // Data sections
    inputs: Record<string, any>;
    results: Record<string, any>;
    // Visual capture target
    visualElementId?: string;
    // Additional notes
    notes?: string[];
}

export function PDFGenerator({ filename, title, inputs, results, visualElementId, notes }: PDFGeneratorProps) {
    const [generating, setGenerating] = useState(false);

    const handleGenerate = async () => {
        setGenerating(true);
        try {
            // dynamic imports
            const jsPDF = (await import('jspdf')).default;
            const autoTable = (await import('jspdf-autotable')).default;

            const doc = new jsPDF();

            // 1. Header
            doc.setFillColor(20, 20, 20);
            doc.rect(0, 0, 210, 30, 'F');
            doc.setFontSize(20);
            doc.setTextColor(255, 255, 255);
            doc.text(title.toUpperCase(), 14, 20);
            doc.setFontSize(10);
            doc.setTextColor(200, 200, 200);
            doc.text(`Generated by AluCalc OS • ${new Date().toLocaleString()}`, 14, 26);

            let currentY = 40;

            // 2. Visual Capture (2D/3D)
            if (visualElementId) {
                const element = document.getElementById(visualElementId);
                if (element) {
                    try {
                        // Use html-to-image which supports modern CSS (like oklab) better than html2canvas
                        const imgData = await toPng(element, {
                            backgroundColor: '#1e1e1e', // Force dark bg
                            cacheBust: true,
                            pixelRatio: 2, // High res for PDF
                        });

                        // Calculate aspect ratio to fit PDF width (max 180mm)
                        const imgProps = doc.getImageProperties(imgData);
                        const pdfWidth = 180;
                        const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

                        doc.addImage(imgData, 'PNG', 15, currentY, pdfWidth, pdfHeight);
                        currentY += pdfHeight + 10;
                    } catch (captureErr) {
                        console.error("Visual capture failed:", captureErr);
                        doc.setTextColor(255, 0, 0);
                        doc.text("[Visual Capture Failed - Check Console]", 15, currentY);
                        currentY += 10;
                    }
                }
            }

            // 3. Inputs Table
            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text("Design Parameters", 14, currentY);
            currentY += 5;

            const inputRows = Object.entries(inputs).map(([k, v]) => [k, v]);
            autoTable(doc, {
                startY: currentY,
                head: [['Parameter', 'Value']],
                body: inputRows,
                theme: 'grid',
                headStyles: { fillColor: [100, 100, 100] },
                styles: { fontSize: 10 }
            });
            currentY = (doc as any).lastAutoTable.finalY + 15;

            // 4. Results Table
            doc.setFontSize(14);
            doc.text("Analysis Results", 14, currentY);
            currentY += 5;

            const resultRows = Object.entries(results).map(([k, v]) => [k, v]);
            autoTable(doc, {
                startY: currentY,
                head: [['Result', 'Value']],
                body: resultRows,
                theme: 'grid',
                headStyles: { fillColor: [0, 100, 200] }, // Blue for results
                styles: { fontSize: 10, fontStyle: 'bold' }
            });
            currentY = (doc as any).lastAutoTable.finalY + 15;

            // 5. Notes / Production Info
            if (notes && notes.length > 0) {
                doc.setFontSize(14);
                doc.text("Production Notes", 14, currentY);
                currentY += 5;

                doc.setFontSize(10);
                doc.setTextColor(80, 80, 80);
                notes.forEach(note => {
                    doc.text(`• ${note}`, 14, currentY);
                    currentY += 6;
                });
            }

            // Footer
            const pageCount = (doc as any).internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150, 150, 150);
                doc.text('Authorized Engineering Document - Verify before manufacturing.', 14, 290);
            }

            doc.save(`${filename}.pdf`);

        } catch (e) {
            console.error(e);
            alert("Failed to generate PDF. See console.");
        } finally {
            setGenerating(false);
        }
    };

    return (
        <button
            onClick={handleGenerate}
            disabled={generating}
            className="w-full py-3 bg-slate-800 hover:bg-slate-700 text-white rounded border border-slate-700 flex items-center justify-center gap-2 transition-all active:scale-95 text-xs font-bold uppercase tracking-wider"
        >
            {generating ? (
                <span className="animate-pulse">Generating...</span>
            ) : (
                <>
                    <FileDown size={14} />
                    Export PDF Report
                </>
            )}
        </button>
    );
}
