module.exports=[796984,a=>{"use strict";function b(a,b){let c="";for(let a of(c+=`0\r
SECTION\r
2\r
HEADER\r
9\r
$ACADVER\r
1\r
AC1015\r
0\r
ENDSEC\r
0\r
SECTION\r
2\r
TABLES\r
0\r
TABLE\r
2\r
LAYER\r
`,b)){c+=`0\r
LAYER\r
2\r
${a.name}\r
70\r
0\r
`;let b=function(a){let b={"#ff0000":1,"#ffff00":2,"#00ff00":3,"#00ffff":4,"#0000ff":5,"#ff00ff":6,"#ffffff":7,"#000000":0},c=a.toLowerCase();return void 0!==b[c]?b[c]:7}(a.color);c+=`62\r
${b}\r
6\r
CONTINUOUS\r
0\r
`}for(let d of(c+=`0\r
ENDTAB\r
0\r
ENDSEC\r
0\r
SECTION\r
2\r
ENTITIES\r
`,a)){if(!d.isVisible)continue;let a=b.find(a=>a.id===d.layerId),e=a?a.name:"0";switch(d.geometry.type){case"LINE":c+=`0\r
LINE\r
8\r
${e}\r
10\r
${d.geometry.start.x}\r
20\r
${d.geometry.start.y}\r
30\r
0.0\r
11\r
${d.geometry.end.x}\r
21\r
${d.geometry.end.y}\r
31\r
0.0\r
`;break;case"CIRCLE":c+=`0\r
CIRCLE\r
8\r
${e}\r
10\r
${d.geometry.center.x}\r
20\r
${d.geometry.center.y}\r
30\r
0.0\r
40\r
${d.geometry.radius}\r
`;break;case"POLYLINE":for(let a of(c+=`0\r
LWPOLYLINE\r
8\r
${e}\r
100\r
AcDbEntity\r
100\r
AcDbPolyline\r
90\r
${d.geometry.vertices.length}\r
70\r
${+!!d.geometry.closed}\r
`,d.geometry.vertices))c+=`10\r
${a.x}\r
20\r
${a.y}\r
`;break;case"ARC":c+=`0\r
ARC\r
8\r
${e}\r
10\r
${d.geometry.center.x}\r
20\r
${d.geometry.center.y}\r
30\r
0.0\r
40\r
${d.geometry.radius}\r
50\r
${d.geometry.startAngle*(180/Math.PI)}\r
51\r
${d.geometry.endAngle*(180/Math.PI)}\r
`;break;case"POINT":c+=`0\r
POINT\r
8\r
${e}\r
10\r
${d.geometry.x}\r
20\r
${d.geometry.y}\r
30\r
0.0\r
`;break;case"DIMENSION":c+=`0\r
DIMENSION\r
8\r
${e}\r
2\r
*D${d.id}\r
10\r
${d.geometry.start.x}\r
20\r
${d.geometry.start.y}\r
30\r
0.0\r
11\r
${d.geometry.textPoint.x}\r
21\r
${d.geometry.textPoint.y}\r
31\r
0.0\r
70\r
32\r
1\r
${d.geometry.text}\r
`}}return c+`0\r
ENDSEC\r
0\r
EOF\r
`}a.s(["generateDXF",()=>b])}];

//# sourceMappingURL=_gemini_antigravity_scratch_alucalculator_src_cad_dxf_DxfGenerator_ts_e96bfca6._.js.map