import React from 'react';
import type { CalculatorSchemaV2 } from '@/types/calculator-schema-v2';
import { createValidatedValue } from '@/types/engineering';

export const motorEfficiencySchema: CalculatorSchemaV2 = {
    id: 'motor-efficiency',
    metadata: {
        title: 'Motor Efficiency & Load',
        description: 'Electrical input power, real-time operating efficiency, load factor, and annual energy/CO2 metrics for induction motors.',
        category: 'electrical',
        version: '1.0.0',
        author: 'AluCalc OS',
        lastUpdated: '2026-06-28',
        tags: ['induction motor', 'efficiency', 'load factor', 'electrical power', 'co2 savings', 'electrical engineering'],
        verifiedStandards: ['IEC 60034-30-1', 'IEEE Std 112']
    },
    documentation: {
        assumptions: [
            { id: 'a1', text: 'Three-phase balanced AC supply induction motor.', impact: 'high' },
            { id: 'a2', text: 'Constant power factor and voltage throughout operating range.', impact: 'medium' }
        ],
        standards: [
            { code: 'IEC 60034-30-1', title: 'Rotating electrical machines - Part 30-1: Efficiency classes of single-speed, three-phase, cage-induction motors' },
            { code: 'IEEE Std 112', title: 'Standard Test Procedure for Polyphase Induction Motors and Generators' }
        ],
        formulaLatex: 'P_{in} = \\frac{\\sqrt{3} \\cdot V \\cdot I \\cdot PF}{1000} \\quad , \\quad \\eta = \\frac{P_{out}}{P_{in}} \\cdot 100 \\quad , \\quad \\text{Load Factor} = \\frac{P_{out}}{P_{rated}}'
    },
    inputs: [
        { key: 'Prated', label: 'Nominal Rated Power', unit: 'kW', defaultValue: 15, description: 'Nameplate rated shaft output power', validation: { required: true, min: 0.1, max: 5000 } },
        { key: 'V', label: 'Line-to-Line Voltage (V)', unit: 'V', defaultValue: 400, description: 'Measured operating line voltage', validation: { required: true, min: 50, max: 15000 } },
        { key: 'I', label: 'Line Current (I)', unit: 'A', defaultValue: 28, description: 'Measured operating stator current', validation: { required: true, min: 0.1, max: 5000 } },
        { key: 'pf', label: 'Power Factor (cosφ)', unit: '-', defaultValue: 0.84, description: 'Operating power factor of the motor', validation: { required: true, min: 0.2, max: 1.0 } },
        { key: 'hrs', label: 'Annual Running Hours', unit: 'hours', defaultValue: 4000, description: 'Operating hours per year', validation: { required: true, min: 1, max: 8760 } },
        { key: 'elecCost', label: 'Electricity Cost', unit: '$/kWh' as any, defaultValue: 0.15, description: 'Electricity tariff per kilowatt-hour', validation: { required: true, min: 0.01, max: 2.0 } }
    ],
    outputs: [
        { key: 'Pin', label: 'Active Input Power (Pin)', unit: 'kW', description: 'Calculated electrical power drawn by the motor', precision: 2, formulaLatex: 'P_{in} = \\sqrt{3} \\cdot V \\cdot I \\cdot PF / 1000' },
        { key: 'eta', label: 'Motor Efficiency (η)', unit: '%', description: 'Estimated operating efficiency at this load point', precision: 1, formulaLatex: '\\eta = (P_{rated} / P_{in}) \\cdot 100' },
        { key: 'LF', label: 'Load Factor (LF)', unit: '-', description: 'Operating load ratio compared to nominal rating', precision: 2, formulaLatex: '\\text{LF} = P_{in} / P_{nominal\_in}' },
        { key: 'Eannual', label: 'Annual Consumption', unit: 'kWh', description: 'Yearly active electrical energy consumption', precision: 0, formulaLatex: 'E_{annual} = P_{in} \\cdot \\text{Hours}' },
        { key: 'CO2', label: 'CO2 Emissions', unit: 'tons' as any, description: 'Annual carbon footprint generated by power consumption', precision: 1, formulaLatex: '\\text{CO}_2 = E_{annual} \\cdot 0.0004' },
        { key: 'Cost', label: 'Annual Energy Cost', unit: '$' as any, description: 'Calculated annual cost of operating this motor', precision: 0, formulaLatex: '\\text{Cost}_{annual} = E_{annual} \\cdot \\text{Tariff}' }
    ],
    calculationEngine: (inputs: Record<string, any>) => {
        const Prated = Number(inputs.Prated.value);
        const V = Number(inputs.V.value);
        const I = Number(inputs.I.value);
        const pf = Number(inputs.pf.value);
        const hrs = Number(inputs.hrs.value);
        const elecCost = Number(inputs.elecCost.value);

        // 1. Input Active Power (Three-phase)
        const Pin = (Math.sqrt(3) * V * I * pf) / 1000;

        // Approximate nominal full-load input power assuming an average nominal efficiency of 91%
        const nominalEfficiency = 0.91;
        const PnominalIn = Prated / nominalEfficiency;

        // 2. Load Factor
        const LF = Pin / PnominalIn;

        // 3. Efficiency approximation based on load factor
        // Operating shaft power Pout = Prated * LF (simplified)
        const Pout = Prated * Math.min(LF, 1.1); // cap at 10% overload
        let eta = Pin > 0 ? (Pout / Pin) * 100 : 0;
        if (eta > 100) eta = 99.9;

        // 4. Annual metrics
        const Eannual = Pin * hrs;
        const CO2_tons = (Eannual * 0.4) / 1000; // 0.4 kg CO2 per kWh grid average
        const Cost = Eannual * elecCost;

        const warnings: { field: string; message: string; severity: "info" | "warning" | "critical" }[] = [];

        if (LF > 1.15) {
            warnings.push({
                field: 'I',
                message: `Motor overload alert! Operating load factor (${(LF * 100).toFixed(0)}%) exceeds 115% of rated capacity. Thermal protection trip likely.`,
                severity: 'critical'
            });
        }
        if (LF < 0.3) {
            warnings.push({
                field: 'I',
                message: `Underloaded motor operation (${(LF * 100).toFixed(0)}%). Efficiency and power factor drop significantly. Consider downsizing the motor.`,
                severity: 'warning'
            });
        }

        return {
            outputs: {
                Pin: createValidatedValue(Pin, 'kW', 'derived'),
                eta: createValidatedValue(eta, '%', 'derived'),
                LF: createValidatedValue(LF, '-', 'derived'),
                Eannual: createValidatedValue(Eannual, 'kWh', 'derived'),
                CO2: createValidatedValue(CO2_tons, 'tons' as any, 'derived'),
                Cost: createValidatedValue(Cost, '$' as any, 'derived')
            },
            verified: true,
            warnings,
            timestamp: Date.now()
        };
    },
    visualization: {
        type: 'svg-parametric',
        render: (result: any) => {
            const out = result.outputs || {};
            const LF = (out.LF?.value as number) || 0.75;
            
            // Scaled angle for load dial (0 to 180 degrees)
            const angle = Math.min(LF * 180, 220) - 90;

            return (
                <div className="w-full h-full flex flex-row items-center justify-center p-6 bg-[#05080b] gap-12">
                    {/* Dial SVG representing load factor */}
                    <div className="relative w-[180px] h-[180px]">
                        <svg viewBox="0 0 160 160" width="100%" height="100%" className="overflow-visible">
                            {/* Dial Arc */}
                            <path d="M 30 110 A 60 60 0 0 1 130 110" fill="none" stroke="#334155" strokeWidth="12" strokeLinecap="round" />
                            {/* Color Zones */}
                            <path d="M 30 110 A 60 60 0 0 1 70 58" fill="none" stroke="#38bdf8" strokeWidth="12" />
                            <path d="M 70 58 A 60 60 0 0 1 110 58" fill="none" stroke="#10b981" strokeWidth="12" />
                            <path d="M 110 58 A 60 60 0 0 1 130 110" fill="none" stroke="#ef4444" strokeWidth="12" />
                            
                            {/* Center Pin */}
                            <circle cx="80" cy="110" r="10" fill="#1e293b" stroke="#ffffff" strokeWidth="2" />
                            
                            {/* Needle */}
                            <line
                                x1="80"
                                y1="110"
                                x2="80"
                                y2="50"
                                stroke="#ffffff"
                                strokeWidth="3"
                                strokeLinecap="round"
                                transform={`rotate(${angle} 80 110)`}
                                className="transition-transform duration-500"
                            />
                        </svg>
                    </div>

                    {/* Stats */}
                    <div className="flex flex-col gap-5 w-36 border border-[#1a1f26] bg-[#0a0e14] p-4 rounded-xl">
                        <div>
                            <div className="text-[10px] text-gray-500 uppercase tracking-widest font-bold mb-1">Load Factor</div>
                            <div className="text-xl font-bold font-mono text-white">
                                {(LF * 100).toFixed(0)}%
                            </div>
                        </div>
                        <div className="w-full h-px bg-[#1a1f26]"></div>
                        <div>
                            <div className="text-[10px] text-gray-500 uppercase tracking-widest font-bold mb-1">Operating η</div>
                            <div className="text-xl font-bold font-mono text-emerald-400">
                                {((out.eta?.value as number) || 0).toFixed(1)}%
                            </div>
                        </div>
                        <div className="w-full h-px bg-[#1a1f26]"></div>
                        <div>
                            <div className="text-[10px] text-gray-500 uppercase tracking-widest font-bold mb-1">Annual Cost</div>
                            <div className="text-xl font-bold font-mono text-[#00e5ff]">
                                ${((out.Cost?.value as number) || 0).toFixed(0)}
                            </div>
                        </div>
                    </div>
                </div>
            );
        }
    },
    tier: 'free'
};

export default motorEfficiencySchema;
