import fs from 'fs';
import path from 'path';

// === MASTER TRANSLATION DATABASE ===
// This acts as the "Source of Truth" for the application.
// It maps logical keys to translations in 10 languages.

const LANGUAGES = ['en', 'tr', 'de', 'fr', 'es', 'it', 'pt', 'ru', 'ja', 'zh'];

const DATA = {
    nav: {
        home: { en: "Home", tr: "Ana Sayfa", de: "Startseite", fr: "Accueil", es: "Inicio", it: "Home", pt: "Início", ru: "Главная", ja: "ホーム", zh: "首页" },
        dashboard: { en: "Dashboard", tr: "Panel", de: "Dashboard", fr: "Tableau de bord", es: "Panel", it: "Cruscotto", pt: "Painel", ru: "Панель", ja: "ダッシュボード", zh: "仪表板" },
        modules: { en: "Modules", tr: "Modüller", de: "Module", fr: "Modules", es: "Módulos", it: "Moduli", pt: "Módulos", ru: "Модули", ja: "モジュール", zh: "模块" },
        settings: { en: "Settings", tr: "Ayarlar", de: "Einstellungen", fr: "Paramètres", es: "Ajustes", it: "Impostazioni", pt: "Configurações", ru: "Настройки", ja: "設定", zh: "设置" },
    },
    common: {
        calculate: { en: "Calculate", tr: "Hesapla", de: "Berechnen", fr: "Calculer", es: "Calcular", it: "Calcola", pt: "Calcular", ru: "Рассчитать", ja: "計算", zh: "计算" },
        reset: { en: "Reset", tr: "Sıfırla", de: "Zurücksetzen", fr: "Réinitialiser", es: "Restablecer", it: "Reimposta", pt: "Redefinir", ru: "Сброс", ja: "リセット", zh: "重置" },
        inputs: { en: "Inputs", tr: "Girdiler", de: "Eingaben", fr: "Entrées", es: "Entradas", it: "Input", pt: "Entradas", ru: "Ввод", ja: "入力", zh: "输入" },
        results: { en: "Results", tr: "Sonuçlar", de: "Ergebnisse", fr: "Résultats", es: "Resultados", it: "Risultati", pt: "Resultados", ru: "Результаты", ja: "結果", zh: "结果" },
        dimensions: { en: "Dimensions", tr: "Boyutlar", de: "Abmessungen", fr: "Dimensions", es: "Dimensiones", it: "Dimensioni", pt: "Dimensões", ru: "Размеры", ja: "寸法", zh: "尺寸" },
        material: { en: "Material", tr: "Malzeme", de: "Material", fr: "Matériau", es: "Material", it: "Materiale", pt: "Material", ru: "Материал", ja: "材料", zh: "材料" },
        weight: { en: "Weight", tr: "Ağırlık", de: "Gewicht", fr: "Poids", es: "Peso", it: "Peso", pt: "Peso", ru: "Вес", ja: "重量", zh: "重量" },
        cost: { en: "Cost", tr: "Maliyet", de: "Kosten", fr: "Coût", es: "Costo", it: "Costo", pt: "Custo", ru: "Стоимость", ja: "コスト", zh: "成本" },
        unitPrice: { en: "Unit Price", tr: "Birim Fiyat", de: "Stückpreis", fr: "Prix unitaire", es: "Precio unitario", it: "Prezzo unitario", pt: "Preço unitário", ru: "Цена за ед.", ja: "単価", zh: "单价" },
        quantity: { en: "Quantity", tr: "Adet", de: "Menge", fr: "Quantité", es: "Cantidad", it: "Quantità", pt: "Quantidade", ru: "Количество", ja: "数量", zh: "数量" },
        total: { en: "Total", tr: "Toplam", de: "Gesamt", fr: "Total", es: "Total", it: "Totale", pt: "Total", ru: "Итого", ja: "合計", zh: "总计" },
        save: { en: "Save", tr: "Kaydet", de: "Speichern", fr: "Enregistrer", es: "Guardar", it: "Salva", pt: "Salvar", ru: "Сохранить", ja: "保存", zh: "保存" },
        export: { en: "Export", tr: "Dışa Aktar", de: "Exportieren", fr: "Exporter", es: "Exportar", it: "Esporta", pt: "Exportar", ru: "Экспорт", ja: "エクスポート", zh: "导出" },
        generatedBy: { en: "Generated by AluCalc OS", tr: "AluCalc OS tarafından oluşturuldu", de: "Generiert von AluCalc OS", fr: "Généré par AluCalc OS", es: "Generado por AluCalc OS", it: "Generato da AluCalc OS", pt: "Gerado por AluCalc OS", ru: "Создано в AluCalc OS", ja: "AluCalc OSで生成", zh: "由AluCalc OS生成" },
        design: { en: "Design", tr: "Tasarım", de: "Entwurf", fr: "Conception", es: "Diseño", it: "Progetto", pt: "Design", ru: "Дизайн", ja: "デザイン", zh: "设计" },
        view2d: { en: "2D View", tr: "2D Görünüm", de: "2D-Ansicht", fr: "Vue 2D", es: "Vista 2D", it: "Vista 2D", pt: "Vista 2D", ru: "2D Вид", ja: "2D表示", zh: "2D视图" },
        view3d: { en: "3D View", tr: "3D Görünüm", de: "3D-Ansicht", fr: "Vue 3D", es: "Vista 3D", it: "Vista 3D", pt: "Vista 3D", ru: "3D Вид", ja: "3D表示", zh: "3D视图" },
        designParams: { en: "Design Parameters", tr: "Tasarım Parametreleri", de: "Entwurfsparameter", fr: "Paramètres de conception", es: "Parámetros de diseño", it: "Parametri di progettazione", pt: "Parâmetros de projeto", ru: "Параметры дизайна", ja: "設計パラメータ", zh: "设计参数" },
        analysisResults: { en: "Analysis Results", tr: "Analiz Sonuçları", de: "Analyseergebnisse", fr: "Résultats d'analyse", es: "Resultados del análisis", it: "Risultati analisi", pt: "Resultados da análise", ru: "Результаты анализа", ja: "分析結果", zh: "分析结果" },
        prodNotes: { en: "Production Notes", tr: "Üretim Notları", de: "Produktionsnotizen", fr: "Notes de production", es: "Notas de producción", it: "Note di produzione", pt: "Notas de produção", ru: "Производственные заметки", ja: "生産メモ", zh: "生产说明" },
        unitWeight: { en: "Unit Weight", tr: "Birim Ağırlık", de: "Einheitsgewicht", fr: "Poids unitaire", es: "Peso unitario", it: "Peso unitario", pt: "Peso unitário", ru: "Удельный вес", ja: "単位重量", zh: "单位重量" },
        totalWeight: { en: "Total Weight", tr: "Toplam Ağırlık", de: "Gesamtgewicht", fr: "Poids total", es: "Peso total", it: "Peso totale", pt: "Peso total", ru: "Общий вес", ja: "総重量", zh: "总重量" },
    },
    aluminum: {
        title: { en: "Profile Weight Calculator", tr: "Profil Ağırlık Hesaplayıcı", de: "Profilgewichtsrechner", fr: "Calculateur de poids de profil", es: "Calculadora de peso de perfil", it: "Calcolatore peso profilo", pt: "Calculadora de peso de perfil", ru: "Калькулятор веса профиля", ja: "プロファイル重量計算機", zh: "型材重量计算器" },
        shapes: {
            box: { en: "Box Profile", tr: "Kutu Profil", de: "Kastenprofil", fr: "Profilé caisson", es: "Perfil caja", it: "Profilo scatolato", pt: "Perfil caixa", ru: "Коробчатый профиль", ja: "ボックスプロファイル", zh: "箱型材" },
            sheet: { en: "Sheet / Plate", tr: "Levha / Sac", de: "Blech / Platte", fr: "Feuille / Plaque", es: "Chapa / Placa", it: "Lamiera / Piastra", pt: "Chapa / Placa", ru: "Лист / Плита", ja: "シート / プレート", zh: "板材" },
            pipe: { en: "Round Tube", tr: "Yuvarlak Boru", de: "Rundrohr", fr: "Tube rond", es: "Tubo redondo", it: "Tubo tondo", pt: "Tubo redondo", ru: "Круглая труба", ja: "丸パイプ", zh: "圆管" },
            bar: { en: "Solid Bar", tr: "Dolu Mil", de: "Vollstab", fr: "Barre pleine", es: "Barra maciza", it: "Barra piena", pt: "Barra sólida", ru: "Сплошной пруток", ja: "丸棒", zh: "实心棒" },
            angle: { en: "Angle (L)", tr: "Köşebent (L)", de: "Winkel (L)", fr: "Cornière (L)", es: "Ángulo (L)", it: "Angolare (L)", pt: "Cantoneira (L)", ru: "Уголок (L)", ja: "アングル (L)", zh: "角钢 (L)" },
            beam: { en: "Beam (I/H)", tr: "Kiriş (I/H)", de: "Träger (I/H)", fr: "Poutre (I/H)", es: "Viga (I/H)", it: "Trave (I/H)", pt: "Viga (I/H)", ru: "Балка (I/H)", ja: "ビーム (I/H)", zh: "工字钢 (I/H)" },
            channel: { en: "Channel (U)", tr: "Kanal (U)", de: "U-Profil", fr: "Profilé U", es: "Canal (U)", it: "Canale (U)", pt: "Perfil U", ru: "Швеллер (U)", ja: "チャンネル (U)", zh: "槽钢 (U)" },
            tee: { en: "T-Profile", tr: "T-Profil", de: "T-Profil", fr: "Profilé T", es: "Perfil T", it: "Profilo T", pt: "Perfil T", ru: "Тавр", ja: "T型鋼", zh: "T型钢" },
            hex: { en: "Hex Bar", tr: "Altıgen Çubuk", de: "Sechskantstab", fr: "Barre hexagonale", es: "Barra hexagonal", it: "Barra esagonale", pt: "Barra sextavada", ru: "Шестигранник", ja: "六角棒", zh: "六角棒" },
        },
        params: {
            width: { en: "Width (A)", tr: "Genişlik (A)", de: "Breite (A)", fr: "Largeur (A)", es: "Ancho (A)", it: "Larghezza (A)", pt: "Largura (A)", ru: "Ширина (A)", ja: "幅 (A)", zh: "宽度 (A)" },
            height: { en: "Height (B)", tr: "Yükseklik (B)", de: "Höhe (B)", fr: "Hauteur (B)", es: "Alto (B)", it: "Altezza (B)", pt: "Altura (B)", ru: "Высота (B)", ja: "高さ (B)", zh: "高度 (B)" },
            thickness: { en: "Thickness (t)", tr: "Kalınlık (t)", de: "Dicke (t)", fr: "Épaisseur (t)", es: "Espesor (t)", it: "Spessore (t)", pt: "Espessura (t)", ru: "Толщина (t)", ja: "厚さ (t)", zh: "厚度 (t)" },
            wall: { en: "Wall (t)", tr: "Et Kalınlığı (t)", de: "Wandstärke (t)", fr: "Paroi (t)", es: "Pared (t)", it: "Parete (t)", pt: "Parede (t)", ru: "Стенка (t)", ja: "肉厚 (t)", zh: "壁厚 (t)" },
            diameter: { en: "Diameter (D)", tr: "Çap (D)", de: "Durchmesser (D)", fr: "Diamètre (D)", es: "Diámetro (D)", it: "Diametro (D)", pt: "Diâmetro (D)", ru: "Диаметр (D)", ja: "直径 (D)", zh: "直径 (D)" },
            length: { en: "Length", tr: "Uzunluk", de: "Länge", fr: "Longueur", es: "Longitud", it: "Lunghezza", pt: "Comprimento", ru: "Длина", ja: "長さ", zh: "长度" },
            web: { en: "Web (tw)", tr: "Gövde (tw)", de: "Steg (tw)", fr: "Âme (tw)", es: "Alma (tw)", it: "Anima (tw)", pt: "Alma (tw)", ru: "Стенка (tw)", ja: "ウェブ (tw)", zh: "腹板 (tw)" },
            flange: { en: "Flange (tf)", tr: "Başlık (tf)", de: "Flansch (tf)", fr: "Semelle (tf)", es: "Ala (tf)", it: "Ala (tf)", pt: "Mesa (tf)", ru: "Полка (tf)", ja: "フランジ (tf)", zh: "翼缘 (tf)" },
        }
    },
    gears: {
        title: { en: "Gear Calculator", tr: "Dişli Hesaplayıcı", de: "Zahnradrechner", fr: "Calculateur d'engrenages", es: "Calculadora de engranajes", it: "Calcolatore ingranaggi", pt: "Calculadora de engrenagens", ru: "Калькулятор шестерен", ja: "歯車計算機", zh: "齿轮计算器" },
        module: { en: "Module (m)", tr: "Modül (m)", de: "Modul (m)", fr: "Module (m)", es: "Módulo (m)", it: "Modulo (m)", pt: "Módulo (m)", ru: "Модуль (m)", ja: "モジュール (m)", zh: "模数 (m)" },
        teeth: { en: "Teeth (z)", tr: "Diş Sayısı (z)", de: "Zähne (z)", fr: "Dents (z)", es: "Dientes (z)", it: "Denti (z)", pt: "Dentes (z)", ru: "Зубья (z)", ja: "歯数 (z)", zh: "齿数 (z)" },
        pressureAngle: { en: "Pressure Angle", tr: "Kavrama Açısı", de: "Eingriffswinkel", fr: "Angle de pression", es: "Ángulo de presión", it: "Angolo di pressione", pt: "Ângulo de pressão", ru: "Угол давления", ja: "圧力角", zh: "压力角" },
        helixAngle: { en: "Helix Angle", tr: "Helis Açısı", de: "Schrägungswinkel", fr: "Angle d'hélice", es: "Ángulo de hélice", it: "Angolo dell'elica", pt: "Ângulo de hélice", ru: "Угол наклона", ja: "ねじれ角", zh: "螺旋角" },
        faceWidth: { en: "Face Width", tr: "Diş Genişliği", de: "Zahnbreite", fr: "Largeur de face", es: "Ancho de cara", it: "Larghezza del dente", pt: "Largura da face", ru: "Ширина венца", ja: "歯幅", zh: "齿宽" },
        addendum: { en: "Addendum (ha)", tr: "Diş Başı (ha)", de: "Kopfhöhe (ha)", fr: "Saillie (ha)", es: "Adendo (ha)", it: "Addendum (ha)", pt: "Adendo (ha)", ru: "Высота головки (ha)", ja: "歯末のたけ (ha)", zh: "齿顶高 (ha)" },
        dedendum: { en: "Dedendum (hf)", tr: "Diş Dibi (hf)", de: "Fußhöhe (hf)", fr: "Creux (hf)", es: "Dedendo (hf)", it: "Dedendum (hf)", pt: "Dedendo (hf)", ru: "Высота ножки (hf)", ja: "歯元のたけ (hf)", zh: "齿根高 (hf)" },
        circularPitch: { en: "Circular Pitch (p)", tr: "Adım (p)", de: "Teilung (p)", fr: "Pas primitif (p)", es: "Paso circular (p)", it: "Passo circolare (p)", pt: "Passo circular (p)", ru: "Шаг (p)", ja: "円ピッチ (p)", zh: "周节 (p)" },
        recFaceWidth: { en: "Rec. Width (6m-10m)", tr: "Önerilen Gen. (6m-10m)", de: "Empf. Breite (6m-10m)", fr: "Larg. recomm. (6m-10m)", es: "Ancho rec. (6m-10m)", it: "Largh. racc. (6m-10m)", pt: "Larg. rec. (6m-10m)", ru: "Рек. ширина (6m-10m)", ja: "推奨歯幅 (6m-10m)", zh: "推荐齿宽 (6m-10m)" }
    },
    science: {
        title: { en: "Periodic Table", tr: "Periyodik Tablo", de: "Periodensystem", fr: "Tableau périodique", es: "Tabla periódica", it: "Tavola periodica", pt: "Tabela periódica", ru: "Периодическая таблица", ja: "周期表", zh: "元素周期表" },
        meltingPoint: { en: "Melting Point", tr: "Erime Noktası", de: "Schmelzpunkt", fr: "Point de fusion", es: "Punto de fusión", it: "Punto di fusione", pt: "Ponto de fusão", ru: "Точка плавления", ja: "融点", zh: "熔点" },
        boilingPoint: { en: "Boiling Point", tr: "Kaynama Noktası", de: "Siedepunkt", fr: "Point d'ébullition", es: "Punto de ebullición", it: "Punto di ebollizione", pt: "Ponto de ebulição", ru: "Точка кипения", ja: "沸点", zh: "沸点" },
        discoveredBy: { en: "Discovered By", tr: "Keşfeden", de: "Entdeckt von", fr: "Découvert par", es: "Descubierto por", it: "Scoperto da", pt: "Descoberto por", ru: "Открыт", ja: "発見者", zh: "发现者" },
        categories: {
            "alkali metal": { en: "Alkali Metal", tr: "Alkali Metal", de: "Alkalimetall", fr: "Métal alcalin", es: "Metal alcalino", it: "Metallo alcalino", pt: "Metal alcalino", ru: "Щелочной металл", ja: "アルカリ金属", zh: "碱金属" },
            "alkaline earth metal": { en: "Alkaline Earth", tr: "Toprak Alkali", de: "Erdalkalimetall", fr: "Alcalino-terreux", es: "Alcalinotérreo", it: "Alcalino terroso", pt: "Alcalino-terroso", ru: "Щёлочноземельный металл", ja: "アルカリ土類金属", zh: "碱土金属" },
            "transition metal": { en: "Transition Metal", tr: "Geçiş Metali", de: "Übergangsmetall", fr: "Métal de transition", es: "Metal de transición", it: "Metallo di transizione", pt: "Metal de transição", ru: "Переходный металл", ja: "遷移金属", zh: "过渡金属" },
            "noble gas": { en: "Noble Gas", tr: "Soy Gaz", de: "Edelgas", fr: "Gaz noble", es: "Gas noble", it: "Gas nobile", pt: "Gás nobre", ru: "Благородный газ", ja: "希ガス", zh: "稀有气体" },
            "halogen": { en: "Halogen", tr: "Halojen", de: "Halogen", fr: "Halogène", es: "Halógeno", it: "Alogeno", pt: "Halogênio", ru: "Галоген", ja: "ハロゲン", zh: "卤素" },
            "metalloid": { en: "Metalloid", tr: "Yarı Metal", de: "Halbmetall", fr: "Métalloïde", es: "Metaloide", it: "Metalloide", pt: "Metalóide", ru: "Металлоид", ja: "半金属", zh: "类金属" },
            "nonmetal": { en: "Nonmetal", tr: "Ametal", de: "Nichtmetall", fr: "Non-métal", es: "No metal", it: "Non metallo", pt: "Não-metal", ru: "Неметалл", ja: "非金属", zh: "非金属" },
            "lanthanide": { en: "Lanthanide", tr: "Lantanit", de: "Lanthanoid", fr: "Lanthanide", es: "Lantánido", it: "Lantanide", pt: "Lantanídeo", ru: "Лантаноид", ja: "ランタノイド", zh: "镧系元素" },
            "actinide": { en: "Actinide", tr: "Aktinit", de: "Actinoid", fr: "Actinide", es: "Actínido", it: "Attinide", pt: "Actinídeo", ru: "Актиноид", ja: "アクチノイド", zh: "锕系元素" }
        }
    },
    materials: {
        aluminum: { en: "Aluminum", tr: "Alüminyum", de: "Aluminium", fr: "Aluminium", es: "Aluminio", it: "Alluminio", pt: "Alumínio", ru: "Алюминий", ja: "アルミニウム", zh: "铝" },
        steel: { en: "Steel", tr: "Çelik", de: "Stahl", fr: "Acier", es: "Acero", it: "Acciaio", pt: "Aço", ru: "Сталь", ja: "鋼", zh: "钢" },
        stainless: { en: "Stainless Steel", tr: "Paslanmaz Çelik", de: "Edelstahl", fr: "Acier inoxydable", es: "Acero inoxidable", it: "Acciaio inossidabile", pt: "Aço inoxidável", ru: "Нержавеющая сталь", ja: "ステンレス鋼", zh: "不锈钢" },
        plastic: { en: "Plastic", tr: "Plastik", de: "Kunststoff", fr: "Plastique", es: "Plástico", it: "Plastica", pt: "Plástico", ru: "Пластик", ja: "プラスチック", zh: "塑料" },
        nonferrous: { en: "Non-Ferrous", tr: "Demir Dışı", de: "Nichteisen", fr: "Non ferreux", es: "No ferroso", it: "Non ferroso", pt: "Não ferroso", ru: "Цветные металлы", ja: "非鉄金属", zh: "有色金属" },
        superalloy: { en: "Superalloy", tr: "Süper Alaşım", de: "Superlegierung", fr: "Superalliage", es: "Superaleación", it: "Superlega", pt: "Superliga", ru: "Суперсплав", ja: "超合金", zh: "高温合金" }
    },
    civil: {
        title: { en: "Concrete Reinforcement", tr: "Beton Donatısı", de: "Betonbewehrung", fr: "Armature béton", es: "Refuerzo de hormigón", it: "Armatura cemento", pt: "Armadura de concreto", ru: "Арматура бетона", ja: "コンクリート補強", zh: "混凝土钢筋" },
        requiredAs: { en: "Required As", tr: "Gerekli As", de: "Erford. As", fr: "As requis", es: "As requerido", it: "As richiesto", pt: "As necessário", ru: "Требуемая As", ja: "必要 As", zh: "所需 As" },
        actualAs: { en: "Actual As", tr: "Mevcut As", de: "Vorh. As", fr: "As réel", es: "As real", it: "As effettivo", pt: "As real", ru: "Фактическая As", ja: "実 As", zh: "实际 As" },
        effectiveD: { en: "Effective d", tr: "Efektif d", de: "Effektives d", fr: "d effectif", es: "d efectiva", it: "d effettivo", pt: "d efetivo", ru: "Эффективная d", ja: "有効 d", zh: "有效 d" },
    },
    electrical: {
        title: { en: "Voltage Drop", tr: "Gerilim Düşümü", de: "Spannungsabfall", fr: "Chute de tension", es: "Caída de tensión", it: "Caduta di tensione", pt: "Queda de tensão", ru: "Падение напряжения", ja: "電圧降下", zh: "电压降" },
        powerFactor: { en: "Power Factor", tr: "Güç Faktörü", de: "Leistungsfaktor", fr: "Facteur de puissance", es: "Factor de potencia", it: "Fattore di potenza", pt: "Fator de potência", ru: "Коэффициент мощности", ja: "力率", zh: "功率因数" },
        cableRes: { en: "Cable Resistance", tr: "Kablo Direnci", de: "Kabelwiderstand", fr: "Résistance câble", es: "Resistencia cable", it: "Resistenza cavo", pt: "Resistência cabo", ru: "Сопротивление кабеля", ja: "ケーブル抵抗", zh: "电缆电阻" },
        powerLoss: { en: "Power Loss", tr: "Güç Kaybı", de: "Verlustleistung", fr: "Perte de puissance", es: "Pérdida de potencia", it: "Perdita di potenza", pt: "Perda de potência", ru: "Потеря мощности", ja: "電力損失", zh: "功率损耗" },
        recSize: { en: "Recommended Size", tr: "Önerilen Kesit", de: "Empf. Größe", fr: "Taille recomm.", es: "Tamaño recom.", it: "Dimensione racc.", pt: "Tamanho recom.", ru: "Рек. размер", ja: "推奨サイズ", zh: "推荐尺寸" },
    },
    sheetMetal: {
        bendAngle: { en: "Bend Angle", tr: "Büküm Açısı", de: "Biegewinkel", fr: "Angle de pliage", es: "Ángulo de plegado", it: "Angolo di piega", pt: "Ângulo de dobra", ru: "Угол гиба", ja: "曲げ角度", zh: "弯曲角度" },
        innerRadius: { en: "Inner Radius", tr: "İç Yarıçap", de: "Innenradius", fr: "Rayon intérieur", es: "Radio interior", it: "Raggio interno", pt: "Raio interno", ru: "Внутренний радиус", ja: "内半径", zh: "内半径" },
        bendLength: { en: "Bend Length", tr: "Büküm Boyu", de: "Biegelänge", fr: "Longueur de pli", es: "Longitud de plegado", it: "Lunghezza piega", pt: "Comprimento de dobra", ru: "Длина гиба", ja: "曲げ長さ", zh: "弯曲长度" },
        kFactor: { en: "K-Factor", tr: "K-Faktörü", de: "K-Faktor", fr: "Facteur K", es: "Factor K", it: "Fattore K", pt: "Fator K", ru: "K-фактор", ja: "Kファクター", zh: "K因子" },
    },
    reducer: {
        inputPower: { en: "Input Power", tr: "Giriş Gücü", de: "Eingangsleistung", fr: "Puissance d'entrée", es: "Potencia de entrada", it: "Potenza in ingresso", pt: "Potência de entrada", ru: "Входная мощность", ja: "入力電力", zh: "输入功率" },
        ambientTemp: { en: "Ambient Temp", tr: "Ortam Sıcaklığı", de: "Umgebungstemp.", fr: "Temp. ambiante", es: "Temp. ambiente", it: "Temp. ambiente", pt: "Temp. ambiente", ru: "Темп. окр. среды", ja: "周囲温度", zh: "环境温度" },
    },
    cutting: {
        stockLength: { en: "Stock Length", tr: "Stok Boyu", de: "Lagerlänge", fr: "Longueur stock", es: "Longitud stock", it: "Lunghezza stock", pt: "Comp. estoque", ru: "Длина заготовки", ja: "在庫長さ", zh: "库存长度" },
        bladeKerf: { en: "Blade Kerf", tr: "Testere Payı", de: "Schnittbreite", fr: "Trait de scie", es: "Espesor corte", it: "Spessore lama", pt: "Espessura corte", ru: "Ширина пропила", ja: "切り幅", zh: "锯缝宽度" },
        trimStart: { en: "Trim Start", tr: "Baş Kesimi", de: "Anschnitt", fr: "Coupe début", es: "Recorte inicio", it: "Taglio inizio", pt: "Corte inicial", ru: "Обрезка начала", ja: "端切り（始）", zh: "端头切除" },
        trimEnd: { en: "Trim End", tr: "Son Kesimi", de: "Abschnitt", fr: "Coupe fin", es: "Recorte final", it: "Taglio fine", pt: "Corte final", ru: "Обрезка конца", ja: "端切り（終）", zh: "端尾切除" },
    }
};

// Recursive function to extract data for a specific language
function extractLanguageData(obj: any, lang: string): any {
    const result: any = {};
    for (const key in obj) {
        if (typeof obj[key] === 'object' && obj[key] !== null) {
            // Check if this object IS the translation node (has the lang key directly)
            if (lang in obj[key] && typeof obj[key][lang] === 'string') {
                result[key] = obj[key][lang];
            } else {
                // Determine if it's a nested structure or a terminal node
                const hasLangKeys = LANGUAGES.some(l => l in obj[key]);
                if (hasLangKeys) {
                    // Fallback to English
                    result[key] = obj[key]['en'] || "";
                } else {
                    // Recurse deeper
                    const nested = extractLanguageData(obj[key], lang);
                    if (Object.keys(nested).length > 0) {
                        result[key] = nested;
                    }
                }
            }
        }
    }
    return result;
}

// Write function
async function generateFiles() {
    const outDir = path.join(process.cwd(), 'src', 'dictionaries');

    if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true });
    }

    // Process each language
    for (const lang of LANGUAGES) {
        console.log(`Generating ${lang}.json...`);
        const langData = extractLanguageData(DATA, lang);

        const filePath = path.join(outDir, `${lang}.json`);
        let finalData = langData;

        if (fs.existsSync(filePath)) {
            const existing = JSON.parse(fs.readFileSync(filePath, 'utf-8'));
            // Deep merge: Existing data wins if keys exist (to preserve custom edits not in script),
            // BUT our script should really be the master. 
            // However, the existing 'en.json' had some keys I didn't verify in DATA (e.g., 'handbook.desc').
            // So we merge: Existing + New. New overrides if collision (since I'm the authority now).
            finalData = deepMerge(existing, langData);
        }

        fs.writeFileSync(filePath, JSON.stringify(finalData, null, 2));
    }
    console.log("Translation generation complete.");
}

function deepMerge(target: any, source: any) {
    for (const key in source) {
        if (source[key] instanceof Object && key in target) {
            Object.assign(source[key], deepMerge(target[key], source[key]));
        }
    }
    Object.assign(target || {}, source);
    return target;
}

generateFiles();
