// UNITS 7 to 10 (Lessons 91 to 150)
module.exports = [
  // ─── UNIT 7: ELASTİK KARARSIZLIK & KOLON BURKULMASI (91-105) ───
  {
    num: 7, id: 'unit-7',
    titleTr: 'Ünite 7: Elastik Kararsızlık & Kolon Burkulması',
    titleEn: 'Unit 7: Elastic Instability & Column Buckling',
    descTr: 'Euler kritik yükü, narinlik oranı, Johnson-Tetmajer yaklaşımı ve yanal burulmalı burkulma.',
    descEn: 'Euler buckling load, slenderness ratio, inelastic column behavior, and lateral torsional buckling.',
    gradient: 'from-teal-600 to-emerald-600', difficulty: 'expert', accentColor: '#14b8a6',
    lessons: [
      { num: 91, slug: 'euler-buckling-4-cases-visual', std: 'Euler Burkulması', cat: 'Burkulma', diff: 'medium', pType: 'visual',
        tTr: '91. 4 Temel Euler Burkulma Mesnet Durumu & Efektif Boy (Le)', tEn: '91. 4 Fundamental Euler Buckling Cases & Effective Length',
        cTr: 'Euler burkulma yükü F_cr = (π² * E * I) / (Le²) formülüyle hesaplanır. Mesnet durumuna göre efektif boy: İki ucu mafsallı (Le = L, K=1), Bir ucu ankastre bir ucu serbest konsol (Le = 2L, K=2), İki ucu ankastre (Le = 0.5L, K=0.5).',
        cEn: 'Euler buckling load is F_cr = (π² * E * I) / (Le²). Effective length factor K: Pinned-Pinned (K=1.0), Fixed-Free Cantilever (K=2.0), Fixed-Fixed (K=0.5).',
        f: 'F_{cr} = \\frac{\\pi^2 \\cdot E \\cdot I}{L_e^2} = \\frac{\\pi^2 \\cdot E \\cdot I}{(K \\cdot L)^2}',
        visPTr: 'Aynı uzunluk (L) ve kesite sahip kolonlardan hangisi EN DÜŞÜK burkulma yüküyle (en zayıf) burkulur?',
        visPEn: 'Among identical columns of length L, which support condition buckles at the LOWEST critical load?',
        visCards: [
          { id: 'c1', titleTr: 'Bir Ucu Ankastre, Diğer Ucu Serbest Konsol (K = 2.0)', titleEn: 'Fixed-Free Cantilever Flagpole (K = 2.0)', descTr: 'Efektif boy Le = 2L olup kritik yük 4 kat daha düşüktür (Fcr = π²EI / 4L²)', descEn: 'Effective length Le = 2L yields lowest buckling load (1/4th of pinned case)', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'İki Ucu Ankastre Kolon (K = 0.5)', titleEn: 'Fixed-Fixed Column (K = 0.5)', descTr: 'En yüksek taşıma kapasitesi (Kritik yük 16 kat büyüktür)', descEn: 'Highest capacity (16x stronger than cantilever)', diagramSvgType: 'i_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Konsol bayrak direği durumu (K=2) efektif boyu iki katına çıkararak burkulma yükünü 1/4\'e düşürür.',
        expEn: 'Correct! Fixed-free column has Le = 2L, dropping critical load to 25% of standard pinned case.' },
      { num: 92, slug: 'euler-buckling-load-calculation', std: 'Euler Formülü', cat: 'Burkulma', diff: 'medium', pType: 'calculation',
        tTr: '92. Euler Kritik Burkulma Yükü (Fcr) Hesabı', tEn: '92. Euler Critical Buckling Load Calculation',
        cTr: 'E = 210,000 MPa, I = 10,000 mm⁴ ve efektif boy Le = 1000 mm olan iki ucu mafsallı çelik çubuğun kritik burkulma yükü Fcr = (π² * 210,000 * 10,000) / (1000²) ≈ 20,726 N (~20.7 kN) olur.',
        cEn: 'For E=210 GPa, I=10,000 mm⁴, and Le=1000 mm, Euler buckling load is Fcr = (π² * E * I) / Le² ≈ 20.7 kN.',
        f: 'F_{cr} = \\frac{\\pi^2 \\cdot E \\cdot I}{L_e^2}',
        calcPTr: 'π² ≈ 10, E = 200,000 MPa, I = 50,000 mm⁴ ve Le = 1000 mm için Fcr = (10 * 200,000 * 50,000) / (1,000,000) sonucunu (kN) hesaplayınız:',
        calcPEn: 'Calculate Fcr in kN using π²≈10, E=200,000 MPa, I=50,000 mm⁴, Le=1000 mm: (10 * 200,000 * 50,000) / 1,000,000 / 1000:',
        tVal: 100, tol: 1, u: 'kN', fHint: 'Fcr = 100,000 N = 100 kN',
        calcExpTr: 'Doğru! Fcr = 100,000 N = 100 kN.', calcExpEn: 'Correct! Fcr = 100 kN.' },
      { num: 93, slug: 'slenderness-ratio-lambda-calc', std: 'Mukavemet', cat: 'Burkulma', diff: 'medium', pType: 'calculation',
        tTr: '93. Narinlik Oranı (λ) ve Atalet Yarıçapı (i) Hesabı', tEn: '93. Slenderness Ratio (λ) & Radius of Gyration (i)',
        cTr: 'Kesitin atalet yarıçapı i = sqrt(I / A) formülüyle bulunur. Kolonun narinlik oranı λ = Le / i dir.',
        cEn: 'Radius of gyration is i = sqrt(I / A). Column slenderness ratio is λ = Le / i.',
        f: 'i = \\sqrt{\\frac{I}{A}}, \\quad \\lambda = \\frac{L_e}{i}',
        calcPTr: 'Efektif boy Le = 2000 mm ve atalet yarıçapı i = 20 mm olan bir kolonun narinlik oranını (λ) hesaplayınız:',
        calcPEn: 'Calculate slenderness ratio λ for effective length Le = 2000 mm and radius of gyration i = 20 mm:',
        tVal: 100, tol: 0.5, u: '', fHint: 'λ = 2000 / 20',
        calcExpTr: 'Doğru! λ = 2000 / 20 = 100.', calcExpEn: 'Correct! λ = 2000 / 20 = 100.' },
      { num: 94, slug: 'tetmajer-inelastic-buckling', std: 'Tetmajer / Johnson', cat: 'Burkulma', diff: 'hard', pType: 'quiz',
        tTr: '94. Tetmajer-Johnson Elastik Olmayan (İnelastik) Burkulma', tEn: '94. Inelastic Buckling: Tetmajer & Johnson Methods',
        cTr: 'Narinlik oranı sınır değerden küçük olduğunda (λ < λ_sınır ≈ 105 çelik için) gerilme orantı sınırını aşar. Bu bölgede Euler formülü geçersizdir; deneysel Tetmajer veya parabolik Johnson formülü uygulanır.',
        cEn: 'For intermediate slenderness (λ < 105 in structural steel), material yields before Euler elastic bifurcation. Inelastic Tetmajer/Johnson curves apply.',
        f: '\\sigma_{cr} = R_e - \\left( \\frac{R_e - R_p}{\\lambda_p} \\right) \\lambda \\quad (\\text{Tetmajer Doğrusu})',
        qTr: 'Narinliği λ = 45 olan kısa ve kalın bir çelik kolonda burkulma hesabı yaparken neden doğrudan Euler formülü KULLANILAMAZ?',
        qEn: 'Why is the classical Euler formula invalid for short stubby columns with low slenderness (λ = 45)?',
        oTr: ['Kolondaki gerilme malzemenin orantı sınırını (akmasını) aşarak elastik olmayan plastik bölgeye geçtiği için', 'Euler sadece ahşapta geçerli olduğu için', 'Yerçekimi kalktığı için', 'Sıcaklık düştüğü için'],
        oEn: ['Stress exceeds the proportional limit, entering the inelastic plastic yield regime', 'Euler is wood only', 'Zero gravity', 'Cold temperatures'],
        cIdx: 0, expTr: 'Doğru! Düşük narinlikte elastik sınır aşılır; Johnson/Tetmajer inelastik formülü zorunludur.',
        expEn: 'Correct! Inelastic yielding precedes bifurcation; Tetmajer/Johnson formulations must be used.' },
      { num: 95, slug: 'lateral-torsional-buckling-ltb-visual', std: 'EN 1993-1-1 / LTB', cat: 'Burkulma', diff: 'hard', pType: 'visual',
        tTr: '95. I-Kirişlerde Yanal Burulmalı Burkulma (LTB / Kip)', tEn: '95. Lateral Torsional Buckling (LTB)',
        cTr: 'Yüksek I-kirişler güçlü eksende (Ix) eğilmeye maruz kaldığında bası başlığı yana doğru kaçarak burulur (Kip / Lateral Torsional Buckling). Bunu önlemek için bası başlığı yana berkitmelerle bağlanır.',
        cEn: 'Deep I-beams under strong-axis bending buckle out-of-plane via simultaneous lateral deflection and cross-section twist (LTB).',
        f: 'M_{cr} = \\frac{\\pi^2 E I_y}{L^2} \\sqrt{\\frac{I_w}{I_y} + \\frac{L^2 G I_t}{\\pi^2 E I_y}}',
        visPTr: 'Düşey eğilme altındaki yüksek bir I-kirişin üst bası flanşının aniden yana doğru bükülüp kesiti döndürdüğü kararsızlık modu hangisidir?',
        visPEn: 'Which structural instability mode causes a deep I-beam under vertical bending to deflect sideways and twist catastrophically?',
        visCards: [
          { id: 'c1', titleTr: 'Yanal Burulmalı Burkulma (Kip / Lateral Torsional Buckling)', titleEn: 'Lateral Torsional Buckling (LTB)', descTr: 'Bası flanşının yana kaçması ve kirişin kendi ekseni etrafında burulması', descEn: 'Out-of-plane lateral displacement combined with torsional section rotation', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'Saf Düşey Sehim', titleEn: 'Pure In-Plane Vertical Deflection', descTr: 'Kararlı simetrik eğilme', descEn: 'Stable symmetrical deflection', diagramSvgType: 'i_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Kip (LTB) eğilme altındaki ince gövdeli I-kirişlerin en tehlikeli 3D kararsızlık modudur.',
        expEn: 'Correct! LTB is the dominant out-of-plane stability limit state for unrestrained slender girders.' },
      { num: 96, slug: 'eccentric-loading-secant-formula', std: 'Sekant Formülü', cat: 'Burkulma', diff: 'hard', pType: 'quiz',
        tTr: '96. Dışmerkez (Eksantrik) Yüklü Kolonlar & Sekant Formülü', tEn: '96. Eccentric Column Loading & Secant Formula',
        cTr: 'Yük eksenden e kadar kaçık uygulandığında ek eğilme momenti doğar ve maksimum gerilme sekant formülüyle σ_max = (P/A) * [1 + (e*c/i²) * sec(Le/(2i) * sqrt(P/EA))] hesaplanır.',
        cEn: 'Eccentricity e induces secondary bending. Peak stress is governed by the nonlinear Secant Formula.',
        f: '\\sigma_{\\max} = \\frac{P}{A} \\left[ 1 + \\frac{e \\cdot c}{i^2} \\sec\\left( \\frac{L_e}{2 i} \\sqrt{\\frac{P}{E A}} \\right) \\right]',
        qTr: 'Kolon yükleme noktasının merkezden dışarı kaçması (eksantriklik e) kritik taşıma kapasitesini nasıl etkiler?',
        qEn: 'How does unintentional load eccentricity (e > 0) influence column load capacity?',
        oTr: ['Ek eğilme momenti oluşturarak burkulma eşiğini ve taşıma kapasitesini ciddi oranda düşürür', 'Kapasiteyi artırır', 'Etkilemez', 'Sürtünmeyi artırır'],
        oEn: ['Generates secondary bending moments, significantly reducing load-carrying capacity', 'Increases capacity', 'No effect', 'Increases friction'],
        cIdx: 0, expTr: 'Doğru! Küçük bir eksantriklik bile kolonun erkenden yana eğilmesine ve kapasite kaybına yol açar.',
        expEn: 'Correct! Eccentricity triggers early lateral deflection, accelerating non-linear collapse.' },
      { num: 97, slug: 'southwell-plot-technique', std: 'Southwell Yöntemi', cat: 'Burkulma', diff: 'hard', pType: 'quiz',
        tTr: '97. Southwell Grafiği: Kolonu Kırmadan Fcr Tespiti', tEn: '97. Southwell Plot: Non-Destructive Buckling Testing',
        cTr: 'Southwell yöntemi deneysel testlerde kolonu kırmadan, düşük yüklerdeki sehim verilerini (δ / P\'ye karşı δ) grafiğe dökerek doğrunun eğiminden teorik Euler kritik yükünü (1/Fcr) tam bulur.',
        cEn: 'The Southwell plot fits low-load experimental lateral deflections (δ vs δ/P) to extrapolate critical buckling load non-destructively.',
        f: '\\frac{\\delta}{P} = \\frac{1}{F_{cr}} \\cdot \\delta + \\frac{\\delta_0}{F_{cr}} \\implies \\text{Eğim} = \\frac{1}{F_{cr}}',
        qTr: 'Southwell grafiği yönteminin deneysel mekanikteki en büyük pratik avantajı nedir?',
        qEn: 'What is the decisive experimental advantage of the Southwell plot in structural testing?',
        oTr: ['Kolonu aşırı yükleyip kalıcı hasara uğratmadan veya kırmadan kritik burkulma yükünü tam olarak ölçebilmesi', 'Malzemeyi sertleştirmesi', 'Test süresini uzatması', 'Sıcaklığı düşürmesi'],
        oEn: ['Accurately extracts theoretical critical buckling load without destroying or yielding the test specimen', 'Hardens material', 'Extends testing', 'Cools specimen'],
        cIdx: 0, expTr: 'Doğru! Southwell grafiği pahalı yapısal elemanları tahrip etmeden burkulma sınırını ölçer.',
        expEn: 'Correct! Southwell plotting extrapolates buckling bifurcation nondestructively from elastic test data.' },
      { num: 98, slug: 'plate-buckling-bryan-formula', std: 'Bryan / EN 1993-1-5', cat: 'Burkulma', diff: 'hard', pType: 'calculation',
        tTr: '98. İnce Levha Sac Burkulması (Plate Buckling) & Bryan Formülü', tEn: '98. Bryan Thin Plate Buckling Formula',
        cTr: 'b genişliğinde, t kalınlığında dört kenarından basit mesnetli levhanın bası altında burkulma kritik gerilmesi σ_cr = k_sigma * (π² * E) / (12*(1-ν²)) * (t/b)² formülüyle hesaplanır (k_sigma = 4.0).',
        cEn: 'Critical elastic plate buckling stress is σ_cr = k_σ * [π² E / (12(1-ν²))] * (t/b)² (k_σ = 4.0 for pure compression).',
        f: '\\sigma_{cr} = k_\\sigma \\cdot \\frac{\\pi^2 \\cdot E}{12 (1 - \\nu^2)} \\left( \\frac{t}{b} \\right)^2',
        calcPTr: 'k_sigma = 4.0, E_plaka_terimi = 200,000 MPa ve (t/b) = (2 mm / 200 mm) = 0.01 ((t/b)² = 0.0001) için kritik levha burkulma gerilmesini (σ_cr = 4 * 200000 * 0.0001) MPa cinsinden hesaplayınız:',
        calcPEn: 'Calculate plate buckling stress σ_cr in MPa for k=4.0, plate modulus factor=200,000 MPa and (t/b)²=0.0001:',
        tVal: 80, tol: 1, u: 'MPa', fHint: 'σ_cr = 4 * 200,000 * 0.0001 = 800,000 * 0.0001',
        calcExpTr: 'Doğru! σ_cr = 80 MPa.', calcExpEn: 'Correct! σ_cr = 80 MPa.' },
      { num: 99, slug: 'post-buckling-tension-field-draw', std: 'Wagner Çekme Alanı', cat: 'Burkulma', diff: 'hard', pType: 'drawing',
        tTr: '99. Burkulma Sonrası Taşıma Kapasitesi (Wagner Çekme Alanı)', tEn: '99. Post-Buckling Strength & Wagner Tension Field',
        cTr: 'Uçak gövde sacları ve derin I-kirişlerde sac buruşsa bile çapraz diyagonal çekme şeritleri (Wagner Tension Field) oluşturarak yük taşımaya devam eder.',
        cEn: 'Slender webs maintain substantial post-buckling capacity by developing diagonal tension field membrane bands.',
        f: '\\tau_{\\text{post-buckling}} = \\tau_{cr} + \\sigma_t \\cdot \\sin(\\phi) \\cos(\\phi)',
        dPromptTr: 'İnce bir sac panel kayma altında buruştuğunda panel içinde yükü taşımaya devam eden çekme diyagonalinin açısı ve yönü nasıldır?',
        dPromptEn: 'In a post-buckled web panel under shear, what direction do the membrane tension field stress ribbons align?',
        vOpts: [
          { id: 'w1', labelTr: 'Yaklaşık 45° diyagonal çekme doğrultusunda (+45° Gergi Şeridi)', labelEn: 'Along ~45° diagonal tension band', direction: 'up', isCorrect: true },
          { id: 'w2', labelTr: 'Düşey 90° dik açıda', labelEn: 'Vertical 90° line', direction: 'right', isCorrect: false },
        ],
        expTr: 'Doğru! Sac buruştuktan sonra yükü ~45° diyagonal membran çekme kuvvetiyle taşır.',
        expEn: 'Correct! Wagner tension fields form diagonal ~45° tensile trusses across the buckled web.' },
      { num: 100, slug: 'torsional-flexural-buckling-open-sections', std: 'EN 1993-1-1', cat: 'Burkulma', diff: 'hard', pType: 'quiz',
        tTr: '100. Açık İnce Profillerde Eğilmeli-Burulmalı Burkulma', tEn: '100. Torsional-Flexural Buckling in Thin-Walled Open Sections',
        cTr: 'Tek simetri eksenli açık profiller (örn. ince etli C veya Omega profiller) eksenel bası altında saf eğilerek değil, aynı anda eğilip burularak (Torsional-Flexural Buckling) kararsızlığa uğrar.',
        cEn: 'Singly symmetric thin-walled columns (stud channels) fail by coupled torsional-flexural buckling at lower loads than pure Euler bending.',
        f: '(F - F_{cr,x})(F - F_{cr,y})(F - F_{cr,z}) - F^2 (y_0^2 + x_0^2) = 0',
        qTr: 'Hafif çelik yapı profillerinde (C ve U aşıklar) eğilmeli-burulmalı burkulmayı engellemek için ne yapılır?',
        qEn: 'How is torsional-flexural buckling mitigated in cold-formed lightweight C-purlins?',
        oTr: ['Açıklık boyunca yanal ara gergiler (sag rod / bridging) ve dudak kıvrımları (stiffening lips) eklenir', 'Profil boyu uzatılır', 'Profiller boyanır', 'Sıcaklık artırılır'],
        oEn: ['Add bridging/sag rods and stiffener edge lips along the span', 'Lengthen the purlin', 'Paint profiles', 'Increase temperature'],
        cIdx: 0, expTr: 'Doğru! Kenar kıvrımları ve ara gergiler burulma modunu engelleyerek taşıma gücünü artırır.',
        expEn: 'Correct! Stiffener lips and bridging braces restrain cross-section rotation, suppressing torsional collapse.' },
      { num: 101, slug: 'effective-width-von-karman', std: 'von Kármán Formülü', cat: 'Burkulma', diff: 'hard', pType: 'calculation',
        tTr: '101. von Kármán Efektif Genişlik Yöntemi (beff)', tEn: '101. von Kármán Effective Width Method (beff)',
        cTr: 'Buruşan sac levhalarda merkez yük taşıyamaz hale gelir; yük kenarlardaki beff genişliğine yığılır: beff = t * sqrt((π² * E) / (12*(1-ν²) * fy)).',
        cEn: 'Post-buckled plates carry load primarily along supported edges. von Kármán effective width models this edge concentration.',
        f: 'b_{\\text{eff}} = C \\cdot t \\cdot \\sqrt{\\frac{E}{f_y}}',
        calcPTr: 'C * sqrt(E/fy) çarpanı 50 olan bir sacda et kalınlığı t = 2.0 mm ise efektif taşıyıcı genişliği (beff = 2.0 * 50) mm cinsinden hesaplayınız:',
        calcPEn: 'Calculate effective load-bearing width beff in mm for thickness t = 2.0 mm and factor = 50:',
        tVal: 100, tol: 0.5, u: 'mm', fHint: 'beff = 2.0 * 50',
        calcExpTr: 'Doğru! beff = 100 mm (levhanın sadece kenarlarındaki 100 mm\'lik şerit akma sınırında yük taşır).',
        calcExpEn: 'Correct! beff = 100 mm.' },
      { num: 102, slug: 'snapping-through-arch-instability-visual', std: 'Snap-Through', cat: 'Burkulma', diff: 'hard', pType: 'visual',
        tTr: '102. Basık Kemerlerde Ani Çökme (Snap-Through Kararsızlığı)', tEn: '102. Snap-Through Buckling in Shallow Arches & Shells',
        cTr: 'Basık küre kabuklar veya kavisli yaylar tepe yükü kritik bir eşiği aştığında doğrusal olmayan dinamik bir sıçramayla aniden içe doğru çöker (Snap-Through / Durchschlag).',
        cEn: 'Shallow spherical shells and arched diaphragms exhibit limit-point snap-through instability, jumping dynamically into an inverted geometry.',
        f: '\\frac{dP}{dw} = 0 \\implies \\text{Tepe Noktasında Dinamik İçe Çökme Sıçraması}',
        visPTr: 'Basıldığında "klik" sesiyle aniden ters dönen membran tuşlarındaki veya basık kubbe çatılardaki ani içe çökme kararsızlığı hangisidir?',
        visPEn: 'Which non-linear geometric instability describes the sudden violent inversion of loaded shallow domes or tactile dome switches?',
        visCards: [
          { id: 'c1', titleTr: 'Snap-Through İçe Çökme Kararsızlığı', titleEn: 'Snap-Through Arch Inversion', descTr: 'Kritik tepe yükünde sistemin dengesizleşip anında ters basık forma sıçraması', descEn: 'Dynamic jump from convex to concave inverted geometry at limit point', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'Doğrusal Sürekli Esneme', titleEn: 'Linear Proportional Spring Action', descTr: 'Kademeli kararlı deformasyon', descEn: 'Stable linear deformation without jumps', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Snap-through limit noktası kararsızlığı dinamik ani ters dönme fenomenidir.',
        expEn: 'Correct! Snap-through represents a geometric limit-point bifurcation where geometry inverts violently.' },
      { num: 103, slug: 'creep-buckling-high-temperature', std: 'Sünme Burkulması', cat: 'Burkulma', diff: 'hard', pType: 'quiz',
        tTr: '103. Yüksek Sıcaklıkta Sünme Burkulması (Creep Buckling)', tEn: '103. High-Temperature Creep Buckling',
        cTr: 'Yüksek sıcaklıkta (T > 0.4*T_erime) çalışan kolonlar Euler kritik yükünün çok altındaki statik bası yüklerinde dahi zamanla sünme deformasyonu biriktirerek saatler veya yıllar sonra aniden burkulur.',
        cEn: 'At elevated temperatures (T > 0.4 Tm), columns undergo time-dependent creep strain, leading to delayed creep buckling under sub-critical loads.',
        f: '\\dot{\\varepsilon}_{\\text{creep}} = A \\cdot \\sigma^n \\cdot e^{-\\frac{Q}{R T}} \\implies t_{\\text{rupture}} = f(\\sigma, T)',
        qTr: 'Nükleer reaktör yakıt çubuklarında veya gaz türbini kanatlarında sünme burkulmasını (creep buckling) önlemek için ne yapılır?',
        qEn: 'In nuclear fuel cladding and gas turbine components, what design practice prevents time-dependent creep buckling?',
        oTr: ['Yüksek sünme dirençli nikel süperalaşımlar (Inconel) seçilir ve çalışma sıcaklık-zaman ömür matrisi sınırlandırılır', 'Çelik suyla soğutulur', 'Parçalar inceltilir', 'Yük iki katına çıkarılır'],
        oEn: ['Select high creep-strength nickel superalloys (Inconel) and enforce finite creep-life operating limits', 'Water quench in operation', 'Thinner sections', 'Double the load'],
        cIdx: 0, expTr: 'Doğru! Sünme burkulması zamana bağlıdır; yüksek sıcaklık süperalaşımları ve ömür denetimi şarttır.',
        expEn: 'Correct! Creep buckling is time-temperature dependent, requiring creep-resistant superalloys and strict design lives.' },
      { num: 104, slug: 'column-base-fixity-vectors', std: 'EN 1993-1-8', cat: 'Burkulma', diff: 'medium', pType: 'drawing',
        tTr: '104. Kolon Taban Mesnet Ankastrelik Moment Vektörü', tEn: '104. Column Base Fixity Restraining Moment',
        cTr: 'Kolonun taban plakası ve ankraj cıvataları yana devrilmeyi önleyen reaksiyon momenti (M_base) üreterek efektif burkulma boyunu K=2.0\'dan K=1.0 veya K=0.7\'ye düşürür.',
        cEn: 'Column baseplate anchorages supply rotational restraint M_base, slashing effective length factor from K=2.0 down toward K=0.7.',
        f: 'M_{\\text{base}} = F_{\\text{anchor}} \\cdot d_{\\text{lever}} \\ge M_{\\text{overturning}}',
        dPromptTr: 'Bir kolon tepe noktasından sağa doğru devrilmeye zorlandığında, ankastre taban mesnetinin kolonu dik tutmak için ürettiği reaksiyon momenti yönü nedir?',
        dPromptEn: 'When a column top is pushed rightward (+X), what direction does the fixed base reaction moment exert to resist tipping?',
        vOpts: [
          { id: 'bm1', labelTr: 'Saat yönünün tersi (CCW / ↺) [Devrilmeyi Önleyici]', labelEn: 'Counter-Clockwise (CCW / ↺) [Restoring Moment]', direction: 'ccw', isCorrect: true },
          { id: 'bm2', labelTr: 'Saat yönü (CW / ↻)', labelEn: 'Clockwise (CW / ↻)', direction: 'cw', isCorrect: false },
        ],
        expTr: 'Doğru! Taban ankastre momenti devrilme yönüne zıt yönde (CCW) etki ederek kolonu stabilize eder.',
        expEn: 'Correct! Base restoring moment opposes tipping rotation to maintain structural stability.' },
      { num: 105, slug: 'boss-telescopic-crane-boom-buckling', std: 'EN 13001-2 / DIN 18800', cat: 'Burkulma', diff: 'hard', pType: 'boss', isBoss: true,
        tTr: '105. 👑 BOSS SINAVI: 100 Tonluk Mobil Vinç Teleskobik Bom Burkulma Doğrulaması', tEn: '105. 👑 BOSS TEST: 100-Ton Mobile Crane Telescopic Boom Buckling Verification',
        cTr: '50 metre açılmış yüksek mukavemetli S960QL çeliğinden imal U-şekilli oval teleskobik vinç bomunda: 1) Euler global elastik burkulma güvenliği S_Euler ≥ 2.5, 2) Levha sac lokal buruşma güvenliği S_plate ≥ 1.5, 3) İkinci mertebe P-Delta momenti ve 4) Yanal burulma kararlılığı aynı anda kanıtlanmalıdır.',
        cEn: 'Advanced 100-ton crane boom stability certification using non-linear P-Delta geometric stiffness analysis, S960QL yield limits, and EN 13001-2 safety margins.',
        f: 'S_{\\text{total}} = \\frac{1}{\\frac{P}{P_{cr}} + \\frac{P \\cdot e_0 \\cdot \\sec\\left(\\frac{\\pi}{2}\\sqrt{\\frac{P}{P_{cr}}}\\right)}{M_{pl}}} \\ge 2.0',
        qTr: 'Mobil vinç teleskobik bom kesitlerinin klasik dikdörtgen kutu yerine sekizgen veya yuvarlatılmış oval tabanlı (U-form / Cikloidal) üretilmesinin ana burkulma avantajı nedir?',
        qEn: 'Why do modern mobile crane telescopic booms utilize rounded cycloidal / octagonal base cross-sections instead of flat rectangular boxes?',
        oTr: ['Geniş düz sac alanlarını ortadan kaldırarak lokal sac buruşmasını (plate buckling) engeller ve ağırlık başına burkulma dayanımını maksimize eder', 'Boyanması daha kolaydır', 'Kaynak dikişini uzatır', 'Rüzgarı tutmaz'],
        oEn: ['Eliminates wide flat plates prone to premature local buckling, maximizing buckling strength per unit weight', 'Easier painting', 'Longer welds', 'Wind resistance'],
        cIdx: 0, expTr: 'Tebrikler Başmühendis! Yuvarlatılmış oval taban levha buruşmasını önleyerek bomun 100 ton yük altında kararlı kalmasını sağlar!',
        expEn: 'Congratulations Master Engineer! Rounded bottom geometry suppresses local plate buckling, delivering world-class structural efficiency!' }
    ]
  },

  // ─── UNIT 8: SAC METAL, BÜKÜM & İMALAT TEKNOLOJİSİ (106-120) ───
  {
    num: 8, id: 'unit-8',
    titleTr: 'Ünite 8: Sac Metal, Büküm & İmalat Teknolojisi',
    titleEn: 'Unit 8: Sheet Metal, Bending & Manufacturing',
    descTr: 'DIN 6935 büküm açınımı, K-faktörü, geri esneme (springback) ve talaş kaldırma mekaniği.',
    descEn: 'DIN 6935 bend allowance, neutral axis shift, springback compensation, and chip formation mechanics.',
    gradient: 'from-amber-500 to-orange-600', difficulty: 'expert', accentColor: '#f59e0b',
    lessons: [
      { num: 106, slug: 'din6935-bend-allowance-k-factor', std: 'DIN 6935', cat: 'Sac Metal', diff: 'medium', pType: 'quiz',
        tTr: '106. DIN 6935 Sac Büküm Açınımı & K-Faktörü', tEn: '106. DIN 6935 Sheet Metal Bend Allowance & K-Factor',
        cTr: 'Bükümde dış lifler uzarken iç lifler basılır. Tarafsız eksen iç kavis yönüne kayar. K-faktörü K = t_iç / T olup sac açınım boyu L = L1 + L2 + BA formülüyle hesaplanır.',
        cEn: 'During bending, the neutral axis shifts inward. K-factor K = t_inner / T defines neutral layer position for flat pattern development.',
        f: 'B A = \\frac{\\pi \\cdot \\alpha}{180^\\circ} \\cdot (r + K \\cdot T)',
        qTr: 'Standart hava bükümünde (air bending) iç kavis yarıçapı et kalınlığına eşitken (r ≈ T) K-faktörü tipik olarak yaklaşık kaç alınır?',
        qEn: 'For standard air bending where internal bend radius roughly equals sheet thickness (r ≈ T), what is the typical K-factor value?',
        oTr: ['0.33 - 0.40 (Tarafsız eksen içe kaymıştır)', '1.0 (Dış yüzey)', '0.0', '2.5'],
        oEn: ['0.33 - 0.40 (Inward shifted neutral layer)', '1.0 (Outer surface)', '0.0', '2.5'],
        cIdx: 0, expTr: 'Doğru! Plastik bası bölgesinin genişlemesi sebebiyle tarafsız eksen içe kayarak K ≈ 0.35-0.40 olur.',
        expEn: 'Correct! Plastic deformation shifts the neutral axis inward to K ≈ 0.33-0.40.' },
      { num: 107, slug: 'bend-deduction-calculation', std: 'DIN 6935', cat: 'Sac Metal', diff: 'medium', pType: 'calculation',
        tTr: '107. Sac Açınım Boyu (Flat Pattern) Sayısal Hesabı', tEn: '107. Flat Pattern Blank Length Calculation',
        cTr: '90° bükümde flanş dış boyları A = 50 mm, B = 50 mm ve büküm kesintisi BD = 3.5 mm ise açınım boyu L = A + B - BD = 50 + 50 - 3.5 = 96.5 mm olur.',
        cEn: 'For a 90° bend with outer flanges A = 50 mm, B = 50 mm, and bend deduction BD = 3.5 mm, blank length is L = A + B - BD = 96.5 mm.',
        f: 'L = A + B - B D',
        calcPTr: 'A = 80 mm, B = 40 mm ve büküm kesintisi BD = 4.2 mm olan 90° sac parçanın açınım kesim boyunu (L) mm cinsinden hesaplayınız:',
        calcPEn: 'Calculate flat pattern length L in mm for A = 80 mm, B = 40 mm, and BD = 4.2 mm:',
        tVal: 115.8, tol: 0.1, u: 'mm', fHint: 'L = 80 + 40 - 4.2 = 120 - 4.2',
        calcExpTr: 'Doğru! L = 120 - 4.2 = 115.8 mm.', calcExpEn: 'Correct! L = 115.8 mm.' },
      { num: 108, slug: 'springback-compensation-visual', std: 'Sac İmalatı', cat: 'Sac Metal', diff: 'medium', pType: 'visual',
        tTr: '108. Sac Bükümünde Geri Esneme (Springback) & Kompanzasyon', tEn: '108. Sheet Metal Bending Springback & Compensation',
        cTr: 'Abkant pres bükümünden sonra elastik lifler gevşeyerek açıyı açar (Δθ_springback). İstenen 90° köşeyi elde etmek için sac 88°\'ye fazla bükülür (overbending).',
        cEn: 'Elastic recovery causes springback angle Δθ upon tool release. Overbending compensates for springback to hit exact 90° parts.',
        f: 'K_s = \\frac{R_i / T + 1}{R_f / T + 1} = \\frac{\\theta_f}{\\theta_i} < 1.0',
        visPTr: 'Yüksek akma dayanımlı çelik sac büküldükten sonra zımba geri çekildiğinde sacın elastik olarak açılma davranışını gösteren durum hangisidir?',
        visPEn: 'Which visual representation shows elastic springback upon punch release in sheet metal forming?',
        visCards: [
          { id: 'c1', titleTr: 'Geri Esneme ile Açının Büyümesi (Springback)', titleEn: 'Springback Angle Opening', descTr: 'Zımba kalkınca 90° hedeflenen parça elastik geri dönmeyle 92°\'ye açılır', descEn: 'Part angle opens from 90° to 92° due to elastic core recovery', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'Sıfır Elastikiyet Tam Plastik Kalma', titleEn: 'Zero Springback Rigid Plastic', descTr: 'Hiç esnememe (İmkansız ideal durum)', descEn: 'Zero springback assumption (Unrealistic)', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Tüm metallerde elastik lifler yük kalktığında geri esneme (springback) yapar.',
        expEn: 'Correct! Elastic core recovery opens the bend angle upon unloading.' },
      { num: 109, slug: 'minimum-bend-radius-cracking', std: 'ISO 7438 / DIN 6935', cat: 'Sac Metal', diff: 'medium', pType: 'quiz',
        tTr: '109. Minimum Büküm Yarıçapı (R_min) & Dış Yüzey Yırtılması', tEn: '109. Minimum Bend Radius & Outer Fiber Cracking',
        cTr: 'Büküm yarıçapı minimum sınırın altına düşürülürse (r < R_min) dış lifteki çekme gerinimi kopma uzamasını aşar ve büküm köşesinde çatlak/yırtık oluşur.',
        cEn: 'Bending below minimum radius (r < R_min) exceeds outer fiber tensile fracture strain, causing surface cracking.',
        f: '\\varepsilon_{\\text{outer}} = \\frac{1}{1 + 2 \\frac{R_i}{T}} \\le A_5 \\quad (\\text{Kopma Uzaması Sınırı})',
        qTr: 'Sert temperli Alüminyum 7075-T6 veya Paslanmaz sac bükülürken dış köşede çatlama olmaması için ne yapılmalıdır?',
        qEn: 'To prevent outer edge cracking when bending high-strength 7075-T6 Aluminum or Stainless sheet, what parameter must be enlarged?',
        oTr: ['Zımba büküm yarıçapı (R_punch) büyütülmeli ve sac hadde yönüne 90° dik bükülmelidir', 'Sac inceltilmelidir', 'Pres hızı 10 katına çıkarılmalıdır', 'Büküm açısı 180° yapılmalıdır'],
        oEn: ['Enlarge punch radius (R_punch) and bend transverse (90°) to grain rolling direction', 'Thin the sheet', '10x press speed', '180° sharp bend'],
        cIdx: 0, expTr: 'Doğru! Geniş büküm radyusu ve hadde çizgisine dik büküm çatlak oluşumunu tamamen engeller.',
        expEn: 'Correct! Generous tooling radii and bending perpendicular to grain direction prevent fracture.' },
      { num: 110, slug: 'air-bending-tonnage-calculation', std: 'Abkant Büküm', cat: 'Sac Metal', diff: 'hard', pType: 'calculation',
        tTr: '110. Abkant Pres Büküm Tonajı (F_bend) Hesabı', tEn: '110. Press Brake Bending Tonnage Calculation',
        cTr: 'Hava bükümünde gereken pres kuvveti F = (1.42 * Rm * b * T²) / V formülüyle hesaplanır (V = alt kalıp V-kanal genişliği ≈ 8*T).',
        cEn: 'Air bending tonnage is calculated via F = (1.42 * Rm * b * T²) / V where V is die opening width.',
        f: 'F = \\frac{1.42 \\cdot R_m \\cdot b \\cdot T^2}{V}',
        calcPTr: 'Rm = 400 MPa, b = 1000 mm (1 m), T = 2 mm (T² = 4) ve V = 16 mm için büküm kuvvetini (F = 1.42 * 400 * 1000 * 4 / 16) Newton cinsinden hesaplayınız:',
        calcPEn: 'Calculate bending force in Newtons for Rm = 400 MPa, b = 1000 mm, T = 2 mm, V = 16 mm: (1.42 * 400 * 1000 * 4 / 16):',
        tVal: 142000, tol: 500, u: 'N', fHint: 'F = 1.42 * 400 * 4000 / 16 = 142,000 N (~14.2 ton)',
        calcExpTr: 'Doğru! F = 142,000 N (~14.2 ton/metre).', calcExpEn: 'Correct! F = 142,000 N (~14.2 tons/meter).' },
      { num: 111, slug: 'blanking-shear-force-and-clearance', std: 'DIN 9870', cat: 'Sac Metal', diff: 'medium', pType: 'calculation',
        tTr: '111. Sac Kesme & Zımba Boşluğu (Die Clearance)', tEn: '111. Punch Blanking Force & Die Clearance (u)',
        cTr: 'Zımba kesme kuvveti F_cut = L_kesim * T * 0.8 * Rm dir. Çapaksız temiz kesit için zımba-matris boşluğu sac kalınlığının %5-10\'u (u ≈ 0.08*T) olmalıdır.',
        cEn: 'Blanking shear force is F_cut = Perimeter * T * 0.8 * Rm. Optimal clearance u ≈ 0.08*T ensures burr-free rollover-burnish-fracture zones.',
        f: 'F_{\\text{cut}} = P_{\\text{cut}} \\cdot T \\cdot \\tau_B \\approx 0.8 \\cdot P_{\\text{cut}} \\cdot T \\cdot R_m',
        calcPTr: 'Çevresi P = 200 mm, sac kalınlığı T = 2 mm ve kesme dayanımı τ = 300 MPa olan bir sac pulun zımba kesme kuvvetini (kN) hesaplayınız:',
        calcPEn: 'Calculate blanking punch force in kN for perimeter P = 200 mm, T = 2 mm, τ = 300 MPa (200 * 2 * 300 / 1000):',
        tVal: 120, tol: 1, u: 'kN', fHint: 'F = 200 * 2 * 300 = 120,000 N = 120 kN',
        calcExpTr: 'Doğru! F = 120 kN (~12.2 ton).', calcExpEn: 'Correct! F = 120 kN.' },
      { num: 112, slug: 'deep-drawing-limiting-ratio-ldrs', std: 'DIN 8584 / LDR', cat: 'Sac Metal', diff: 'hard', pType: 'visual',
        tTr: '112. Derin Çekme (Deep Drawing) & Limit Çekme Oranı (LDR)', tEn: '112. Deep Drawing & Limiting Draw Ratio (LDR)',
        cTr: 'Limit Çekme Oranı LDR = D_pul / d_zımba olup sacın tek pasoda yırtılmadan çekilebileceği maksimum orandır (tipik çelik için LDR ≈ 2.0 - 2.2). Fazla oranda bardak tabanı yırtılır.',
        cEn: 'Limiting Draw Ratio LDR = D_blank / d_punch ≈ 2.0-2.2 defines the maximum blank diameter drawable without cup base tearing.',
        f: '\\beta_{\\max} = \\text{LDR} = \\frac{D_{\\text{blank},\\max}}{d_{\\text{punch}}} \\approx 2.0 - 2.2',
        visPTr: 'Derin çekme işleminde sac tutucu (blank holder) baskısı yetersiz olduğunda flanş bölgesinde meydana gelen kırışma dalgalanması hasarı hangisidir?',
        visPEn: 'Which defect manifests as circumferential wrinkling waves in deep drawing when blank-holder clamp force is insufficient?',
        visCards: [
          { id: 'c1', titleTr: 'Flanş Kırışması (Flange Wrinkling)', titleEn: 'Flange Wrinkling Defect', descTr: 'Çevresel bası gerilmelerinden doğan dalgalı kıvrımlar ve potlaşma', descEn: 'Circumferential compressive buckling forming wavy ripples in the outer flange', diagramSvgType: 'pitting_crack', isCorrect: true },
          { id: 'c2', titleTr: 'Pürüzsüz Çekilmiş Silindirik Kap', titleEn: 'Smooth Drawn Cup', descTr: 'Kusursuz çekilmiş parça', descEn: 'Ideal defect-free drawn component', diagramSvgType: 'i_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Yetersiz pot çemberi basıncı çevresel bası sebebiyle flanşta kırışma (wrinkling) yaratır.',
        expEn: 'Correct! Low blank-holder force allows circumferential compressive buckling (flange wrinkling).' },
      { num: 113, slug: 'forming-limit-diagram-fld', std: 'ISO 12004', cat: 'Sac Metal', diff: 'hard', pType: 'quiz',
        tTr: '113. Şekillendirme Sınır Diyagramı (FLD / FLC)', tEn: '113. Forming Limit Diagram (FLD / FLC)',
        cTr: 'FLD grafiği asal gerinim düzleminde (ε1 ve ε2) sacın yırtılmadan deforme olabileceği emniyetli bölgeyi tanımlar. En kritik ve en düşük gerinim noktası düzlemsel gerinim (plane strain: ε2 = 0) durumudur (FLC0).',
        cEn: 'The Forming Limit Curve (FLC) plots major strain ε1 vs minor strain ε2. The lowest point occurs at plane strain (ε2 = 0, FLC0).',
        f: '\\text{Safety Margin} = \\varepsilon_{1,\\text{FLC}} - \\varepsilon_{1,\\text{actual}} > 0',
        qTr: 'Şekillendirme Sınır Diyagramında (FLD) sac malzemenin yırtılmaya EN HASSAS olduğu (en düşük majör gerinim FLC0 noktası) deformasyon modu hangisidir?',
        qEn: 'On a Forming Limit Diagram (FLD), which strain state represents the lowest limit strain (FLC0) most susceptible to localized necking?',
        oTr: ['Düzlemsel Gerinim Durumu (Plane Strain: ε2 = 0)', 'Çift Eksenli Çekme (Equi-biaxial)', 'Saf Kayma', 'Bası Gerinimi'],
        oEn: ['Plane Strain State (ε2 = 0)', 'Equi-biaxial tension', 'Pure shear', 'Compression'],
        cIdx: 0, expTr: 'Doğru! FLC0 düzlemsel gerinim noktası sacın incelip yırtılmaya en yatkın olduğu dip noktadır.',
        expEn: 'Correct! Plane strain (ε2 = 0) eliminates lateral strain alleviation, producing the lowest FLC0 necking threshold.' },
      { num: 114, slug: 'taylor-tool-life-equation', std: 'ISO 3685 / Taylor', cat: 'İmalat', diff: 'medium', pType: 'calculation',
        tTr: '114. Talaşlı İmalatta Taylor Takım Ömrü Formülü', tEn: '114. Taylor Tool Life Equation (v * T^n = C)',
        cTr: 'Kesme hızı v ve takım ömrü T arasındaki bağıntı v * T^n = C (Taylor denklemi) ile hesaplanır. Kesme hızının artırılması takım ömrünü üstel olarak hızla tüketir.',
        cEn: 'Taylor\'s tool life equation is v * T^n = C. Cutting speed elevation exponentially accelerates abrasive/crater tool wear.',
        f: 'v \\cdot T^n = C \\implies T = \\left( \\frac{C}{v} \\right)^{1/n}',
        calcPTr: 'n = 0.5 (1/n = 2) ve C = 400 olan bir karbür kesici uç için kesme hızı v = 200 m/dak seçilirse takım ömrünü (T = (400/200)²) dakika cinsinden hesaplayınız:',
        calcPEn: 'Calculate carbide tool life T in minutes for n = 0.5, C = 400 and cutting speed v = 200 m/min: T = (400/200)²:',
        tVal: 4, tol: 0.1, u: 'dakika', fHint: 'T = (2)² = 4',
        calcExpTr: 'Doğru! T = 2² = 4 dakika.', calcExpEn: 'Correct! T = 4 minutes.' },
      { num: 115, slug: 'merchant-circle-cutting-forces-draw', std: 'Merchant Kesme Çemberi', cat: 'İmalat', diff: 'hard', pType: 'drawing',
        tTr: '115. Merchant Kesme Çemberi & Talaş Açısı (γ)', tEn: '115. Merchant\'s Cutting Circle & Rake Angle',
        cTr: 'Merchant analizinde kesici takım talaş yüzeyindeki sürtünme kuvveti F ve dik normal kuvvet N bileşkesi kesme düzlemi kayma kuvvetini (Fs) dengeler.',
        cEn: 'Merchant\'s circle resolves resultant cutting force into shear plane components (Fs, Fn) and rake face friction components (F, N).',
        f: '\\phi = 45^\\circ + \\frac{\\gamma}{2} - \\frac{\\beta}{2} \\quad (\\text{Ernst-Merchant Kayma Düzlemi Açısı})',
        dPromptTr: 'Torna takımının ana kesme kuvveti (Fc - Tangential Cutting Force) iş parçasına hangi doğrultuda etki eder?',
        dPromptEn: 'In cylindrical turning, in which direction does the primary tangential cutting force Fc act on the workpiece?',
        vOpts: [
          { id: 'fc1', labelTr: 'Dönme teğeti yönünde aşağı doğru (-Y / Kesme Doğrultusu)', labelEn: 'Downward tangent to rotational velocity (-Y / Cutting Direction)', direction: 'down', isCorrect: true },
          { id: 'fc2', labelTr: 'Tornadan yukarı fırlatacak yönde (+Y)', labelEn: 'Upward (+Y)', direction: 'up', isCorrect: false },
        ],
        expTr: 'Doğru! Ana kesme kuvveti iş parçasının dönme teğetine karşı aşağı yönlü etki eder.',
        expEn: 'Correct! Primary cutting force Fc opposes workpiece rotation downwards.' },
      { num: 116, slug: 'cnc-milling-climb-vs-conventional', std: 'DIN 6580', cat: 'İmalat', diff: 'medium', pType: 'quiz',
        tTr: '116. CNC Frezelemede Eş Yönlü (Climb) vs Zıt Yönlü (Conventional) Kesme', tEn: '116. Climb vs Conventional CNC Milling',
        cTr: 'Eş yönlü frezelemede (Climb Milling) kesici talaşa maksimum kalınlıkta girip sıfır kalınlıkta çıkar. Bu durum üstün yüzey kalitesi, düşük takım aşınması ve iş parçasını tablaya basma kuvveti sağlar (Modern CNC\'lerin standardıdır).',
        cEn: 'In climb (down) milling, chips start at maximum thickness and exit at zero. This yields superior finish, extended tool life, and downward clamping force.',
        f: 'h(\\theta) = f_z \\cdot \\sin(\\theta) \\implies h_{\\text{entry}} = h_{\\max}',
        qTr: 'Modern CNC frezeleme tezgahlarında neden zıt yönlü yerine eş yönlü (climb / down milling) kesme kesinlikle tercih edilir?',
        qEn: 'Why is climb milling (down milling) universally preferred on rigid modern CNC machining centers?',
        oTr: ['Takım talaşa kalın girip ince çıktığı için sürtünme/ovalamayı önler, mükemmel yüzey pürüzlülüğü ve 2-3 kat uzun takım ömrü sunar', 'Daha çok ses çıkardığı için', 'Daha fazla talaş biriktirdiği için', 'Devri düşürdüğü için'],
        oEn: ['Chips thin to zero at exit, eliminating rubbing/burnishing, maximizing tool life and surface finish', 'Louder sound', 'More chip accumulation', 'Slows speed'],
        cIdx: 0, expTr: 'Doğru! Eş yönlü kesme takımın yüzeyi kazımasını engelleyerek kusursuz ayna yüzey verir.',
        expEn: 'Correct! Climb milling eliminates entry rubbing, minimizing work hardening and heat build-up.' },
      { num: 117, slug: 'laser-cutting-assist-gases-o2-vs-n2', std: 'ISO 9013', cat: 'Sac Metal', diff: 'medium', pType: 'visual',
        tTr: '117. Fiber Lazer Kesiminde Yardımcı Gazlar: Oksijen (O2) vs Azot (N2)', tEn: '117. Fiber Laser Assist Gases: O2 vs N2',
        cTr: 'Oksijen (O2) ekzotermik yanma ile kalın sacları düşük basınçta keser fakat kenarda sert oksit tabakası bırakır. Yüksek basınçlı Azot (N2) ise inert gaz olarak eriyiği üfler, pürüzsüz oksitsiz parlak kaynak/boyaya hazır kenar sağlar.',
        cEn: 'O2 assist gas burns exothermically leaving an oxide scale. High-pressure N2 blows melt cleanly, yielding shiny oxide-free weldable edges.',
        f: 'p_{N2} \\approx 15 - 25 \\text{ bar} \\quad (\\text{Oksitsiz Parlak Kesim Kenarı})',
        visPTr: 'Paslanmaz çelik veya alüminyum sacların fiber lazerde yüksek basınçlı Azot (N2) gazıyla kesilmesinden sonra elde edilen kenar yapısı hangisidir?',
        visPEn: 'Which edge morphology characterizes high-pressure Nitrogen (N2) laser cutting on stainless steel?',
        visCards: [
          { id: 'c1', titleTr: 'Oksitsiz Parlak Metalik Kesim Yüzeyi (N2 Azot Kesimi)', titleEn: 'Clean Oxide-Free Metallic Edge (N2)', descTr: 'Kimyasal yanma yok, doğrudan kaynak ve elektrostatik toz boyaya hazır parlak yüzey', descEn: 'Zero oxide scaling; directly ready for welding and powder coat painting', diagramSvgType: 'i_beam_stress', isCorrect: true },
          { id: 'c2', titleTr: 'Siyah Cüruflu Oksitlenmiş Yüzey', titleEn: 'Black Oxidized Slag Edge', descTr: 'Boyayı tutmayan kalın oksit tabakası', descEn: 'Thick brittle iron-oxide scale', diagramSvgType: 'stress_notch', isCorrect: false },
        ],
        expTr: 'Doğru! Azot gazı kimyasal reaksiyona girmeyerek temiz, oksitsiz ve parlak kesim kenarı üretir.',
        expEn: 'Correct! High-pressure inert N2 expels melt mechanically without oxidation.' },
      { num: 118, slug: 'aluminum-welding-thermal-haz-loss', std: 'EN 1999-1-1 / Eurocode 9', cat: 'İmalat', diff: 'hard', pType: 'quiz',
        tTr: '118. Alüminyum Kaynağında Isı Tesiri Altındaki Bölge (ITAB / HAZ)', tEn: '118. Aluminum Welding Heat-Affected Zone (HAZ) Softening',
        cTr: 'Isıl işlemli alüminyum alaşımları (6000 ve 7000 serisi) kaynaklandığında kaynak dikişi çevresindeki ITAB (HAZ) bölgesinde çökelme sertleşmesi yok olur ve mekanik dayanım %40-50 düşer (ρ_haz ≈ 0.55).',
        cEn: 'Welding precipitation-hardened aluminum (6000/7000 series) dissolves strengthening precipitates, suffering a 40-50% yield strength drop in the HAZ.',
        f: 'f_{u,\\text{haz}} = \\rho_{\\text{haz}} \\cdot f_u \\approx 0.50 - 0.65 \\cdot f_u',
        qTr: '6082-T6 alüminyum profili kaynak yaptıktan sonra kaynak dikişinin hemen yanındaki bölgede neden kopma meydana gelir?',
        qEn: 'Why do welded 6082-T6 aluminum structures frequently fracture in the zone immediately adjacent to the weld bead?',
        oTr: ['Kaynak ısısı T6 yapay yaşlandırma fazlarını çözüp bölgeyi tavlayarak mukavemeti yarı yarıya düşürdüğü (HAZ yumuşaması) için', 'Alüminyum yandığı için', 'Gaz kaçağı olduğu için', 'Cıvata gevşediği için'],
        oEn: ['Welding heat dissolves T6 precipitates, annealing the HAZ and halving base metal strength', 'Aluminum combusts', 'Gas leaks', 'Bolts loosen'],
        cIdx: 0, expTr: 'Doğru! HAZ bölgesinde T6 çökelme fazları çözünür ve mukavemet taban metale göre %50 düşer.',
        expEn: 'Correct! High heat over-ages and dissolves strengthening Mg2Si precipitates in the HAZ.' },
      { num: 119, slug: 'milling-surface-roughness-ra-calc', std: 'ISO 4287 / ISO 1302', cat: 'İmalat', diff: 'medium', pType: 'calculation',
        tTr: '119. Yüzey Pürüzlülüğü (Rz / Ra) ve İlerleme (fz) Hesabı', tEn: '119. Theoretical Surface Roughness (Rz) vs Feed (fz)',
        cTr: 'Torna veya frezelemede teorik tepe-vadi pürüzlülüğü Rz = f² / (8 * r_uç) formülüyle hesaplanır. İlerleme f iki katına çıkarsa pürüzlülük 4 KATINA çıkar!',
        cEn: 'Theoretical kinematic peak-to-valley roughness is Rz = f² / (8 * r_ε). Doubling feed per revolution quadruples surface roughness!',
        f: 'R_z \\approx \\frac{f^2}{8 \\cdot r_\\varepsilon} \\cdot 1000 \\quad [\\mu\\text{m}]',
        calcPTr: 'Uç yarıçapı r_ε = 0.8 mm olan torna kateriyle f = 0.08 mm/devir ilerlemede (f² = 0.0064, 8*r = 6.4) teorik Rz pürüzlülüğünü (Rz = 0.0064 / 6.4 * 1000) mikrometre (μm) cinsinden hesaplayınız:',
        calcPEn: 'Calculate theoretical surface roughness Rz in μm for tool nose radius r_ε = 0.8 mm and feed f = 0.08 mm/rev:',
        tVal: 1.0, tol: 0.05, u: 'μm', fHint: 'Rz = (0.0064 / 6.4) * 1000 = 0.001 * 1000',
        calcExpTr: 'Doğru! Rz = 1.0 μm (Ra ≈ 0.25 μm taşlama kalitesinde süper finiş yüzey).',
        calcExpEn: 'Correct! Rz = 1.0 μm (Ra ≈ 0.25 μm grinding-grade surface finish).' },
      { num: 120, slug: 'boss-sheet-metal-chassis-production', std: 'Komple İmalat Sertifikasyonu', cat: 'Sac Metal', diff: 'hard', pType: 'boss', isBoss: true,
        tTr: '120. 👑 BOSS SINAVI: 3000 Parçalık CNC Lazer & Abkant Sac Kasa İmalat Doğrulaması', tEn: '120. 👑 BOSS TEST: Precision Sheet Metal Chassis Manufacturing Certification',
        cTr: '2.5 mm paslanmaz çelik (1.4301) endüstriyel sunucu kasasında: 1) DIN 6935 açınım toleransı (±0.2 mm), 2) 90° hava bükümü geri esneme açısı (Δθ = 1.8° kompanzasyonu), 3) Lazer azot kesim kenarı pürüzlülüğü (Ra ≤ 3.2 μm) ve 4) Perçin/cıvata delik deformasyon payları aynı anda doğrulanmalıdır.',
        cEn: 'Complete industrial sheet metal fabrication certification validating DIN 6935 blank unfolding tolerances, springback overbend angle compensation, and laser assist gas parameters.',
        f: 'L_{\\text{blank}} = \\sum A_i + \\sum B_i - \\sum B D_i, \\quad \\Delta \\theta_{\\text{overbend}} = \\theta_{\\text{springback}}, \\quad R_a \\le 3.2 \\, \\mu\\text{m}',
        qTr: 'Sac metal bükümünde deliklerin büküm çizgisine çok yakın delinmesi durumunda bükme anında deliğin ovalleşip deforme olmasını önlemek için minimum delik-kenar mesafesi ne olmalıdır?',
        qEn: 'To prevent circular holes near a bend line from tearing or warping into ovals during bending, what minimum spacing d_min from the bend tangent must be respected?',
        oTr: ['d_min ≥ 2 * T + R_büküm (Minimum güvenli deformasyon sınırı)', 'd_min = 0 (Büküm çizgisi üstü)', 'd_min = 0.1 mm', 'Fark etmez'],
        oEn: ['d_min ≥ 2 * T + R_bend (Minimum safe clearance outside deformation zone)', 'd_min = 0 (On bend line)', 'd_min = 0.1 mm', 'Irrelevant'],
        cIdx: 0, expTr: 'Tebrikler Başmühendis! Minimum delik mesafesi kuralı sacın akarken delikleri deforme etmesini engeller!',
        expEn: 'Congratulations Master Engineer! Proper clearance isolates mounting holes from plastic strain distortion zones!' }
    ]
  },

  // ─── UNIT 9: TERMODİNAMİK, AKIŞKANLAR & ISI TRANSFERİ (121-135) ───
  {
    num: 9, id: 'unit-9',
    titleTr: 'Ünite 9: Termodinamik, Akışkanlar & Isı Transferi',
    titleEn: 'Unit 9: Thermodynamics, Fluids & Heat Transfer',
    descTr: 'Navier-Stokes, Darcy-Weisbach boru sürtünmesi, Fourier iletimi ve su koçu darbesi.',
    descEn: 'Navier-Stokes foundations, Darcy-Weisbach pipe losses, Fourier conduction, and water hammer shock.',
    gradient: 'from-orange-600 to-red-600', difficulty: 'expert', accentColor: '#ea580c',
    lessons: [
      { num: 121, slug: 'bernoulli-equation-head-loss', std: 'Bernoulli İlkesi', cat: 'Akışkanlar', diff: 'medium', pType: 'quiz',
        tTr: '121. Bernoulli Enerji Korunumu & Basınç Düşüşü', tEn: '121. Bernoulli Energy Equation & Pressure Drop',
        cTr: 'Sürtünmesiz sıkıştırılamaz akışta statik basınç, dinamik basınç ve hidrostatik yük toplamı sabittir: p + 1/2 * ρ * v² + ρ * g * z = sabit. Kesit daraldığında akış hızı (v) artar, statik basınç (p) DÜŞER (Venturi etkisi).',
        cEn: 'Bernoulli\'s principle balances static, dynamic, and elevation pressure: p + 1/2 ρ v² + ρ g z = constant. Flow restriction accelerates velocity v, dropping static pressure p (Venturi effect).',
        f: 'p_1 + \\frac{1}{2} \\rho v_1^2 + \\rho g z_1 = p_2 + \\frac{1}{2} \\rho v_2^2 + \\rho g z_2',
        qTr: 'Boru çapı daralan bir Venturi borusundan su geçerken daralan boğaz kesitinde akış hızı ve statik basınç nasıl değişir?',
        qEn: 'As water flows through a constricted Venturi throat, how do flow velocity and static wall pressure change?',
        oTr: ['Akış hızı ARTAR, statik basınç DÜŞER', 'Akış hızı düşer, basınç artar', 'İkisi de artar', 'İkisi de sıfırlanır'],
        oEn: ['Flow velocity INCREASES, static pressure DROPS', 'Velocity drops, pressure rises', 'Both increase', 'Both zero'],
        cIdx: 0, expTr: 'Doğru! Süreklilik denklemi hızı artırırken Bernoulli yasası statik basıncı düşürür.',
        expEn: 'Correct! Continuity accelerates the fluid, converting static pressure into dynamic velocity head.' },
      { num: 122, slug: 'reynolds-number-calculation', std: 'ISO 80000-4', cat: 'Akışkanlar', diff: 'medium', pType: 'calculation',
        tTr: '122. Reynolds Sayısı (Re) & Laminer-Türbülanslı Geçiş Hesabı', tEn: '122. Reynolds Number (Re) & Laminar-Turbulent Transition',
        cTr: 'Boru içi akışta Re = (v * D) / ν formülüyle hesaplanır. Re < 2300 laminer akış, Re > 4000 tam türbülanslı akıştır.',
        cEn: 'Reynolds number in pipe flow is Re = (v * D) / ν. Re < 2300 is laminar; Re > 4000 is fully turbulent.',
        f: 'Re = \\frac{v \\cdot D}{\\nu} = \\frac{\\rho \\cdot v \\cdot D}{\\mu}',
        calcPTr: 'v = 2.0 m/s hızda akan, iç çapı D = 0.05 m olan boruda kinematik viskozite ν = 10⁻⁶ m²/s (su) için Reynolds sayısını (Re = 2.0 * 0.05 / 1e-6) hesaplayınız:',
        calcPEn: 'Calculate Reynolds number Re for v = 2.0 m/s, D = 0.05 m, and ν = 10⁻⁶ m²/s: (2.0 * 0.05 / 10^-6):',
        tVal: 100000, tol: 1000, u: '', fHint: 'Re = 0.10 / 10^-6 = 100,000',
        calcExpTr: 'Doğru! Re = 100,000 (Re >> 4000 olduğundan akış tam türbülanslıdır).',
        calcExpEn: 'Correct! Re = 100,000 (Fully turbulent regime).' },
      { num: 123, slug: 'darcy-weisbach-pressure-drop', std: 'Darcy-Weisbach', cat: 'Akışkanlar', diff: 'hard', pType: 'calculation',
        tTr: '123. Darcy-Weisbach Boru Basınç Kaybı (Δp) Hesabı', tEn: '123. Darcy-Weisbach Pipe Pressure Loss (Δp)',
        cTr: 'Boru boyunca sürtünmeden kaynaklanan basınç düşüşü Δp = f * (L/D) * (1/2 * ρ * v²) formülüyle hesaplanır.',
        cEn: 'Frictional pipe pressure loss is calculated via the Darcy-Weisbach equation: Δp = f * (L/D) * (1/2 ρ v²).',
        f: '\\Delta p = f_D \\cdot \\frac{L}{D} \\cdot \\frac{\\rho \\cdot v^2}{2}',
        calcPTr: 'Sürtünme faktörü f = 0.02, boru boyu L = 100 m, çap D = 0.1 m (L/D = 1000) ve dinamik basınç 1/2*ρ*v² = 2000 Pa için basınç kaybını (Δp = 0.02 * 1000 * 2000) Pascal cinsinden hesaplayınız:',
        calcPEn: 'Calculate Darcy pressure drop Δp in Pa for f = 0.02, L/D = 1000, and dynamic pressure = 2000 Pa:',
        tVal: 40000, tol: 200, u: 'Pa', fHint: 'Δp = 0.02 * 1000 * 2000 = 20 * 2000',
        calcExpTr: 'Doğru! Δp = 40,000 Pa (0.4 bar).', calcExpEn: 'Correct! Δp = 40,000 Pa (0.4 bar).' },
      { num: 124, slug: 'moody-diagram-relative-roughness-visual', std: 'Moody Diyagramı', cat: 'Akışkanlar', diff: 'hard', pType: 'visual',
        tTr: '124. Moody Diyagramı & Bağıl Pürüzlülük (ε/D)', tEn: '124. Moody Chart & Relative Roughness',
        cTr: 'Moody diyagramı Darcy sürtünme faktörünü (f) Reynolds sayısı ve bağıl pürüzlülük (ε/D) fonksiyonu olarak verir. Yüksek türbülans bölgesinde f sadece pürüzlülüğe bağlı sabit bir değere oturur.',
        cEn: 'The Moody chart plots Darcy friction factor f against Re and relative roughness ε/D, showing the complete laminar-turbulent transition.',
        f: '\\frac{1}{\\sqrt{f}} = -2 \\log_{10}\\left( \\frac{\\varepsilon / D}{3.7} + \\frac{2.51}{\\text{Re} \\sqrt{f}} \\right) \\quad (\\text{Colebrook-White})',
        visPTr: 'Moody diyagramında Reynolds sayısının Re < 2300 olduğu ve sürtünme faktörünün pürüzlülükten bağımsız olarak f = 64/Re doğrusunu takip ettiği sol bölge hangisidir?',
        visPEn: 'Which region on the Moody chart represents laminar flow where friction factor follows f = 64/Re independently of wall roughness?',
        visCards: [
          { id: 'c1', titleTr: 'Laminer Akış Bölgesi (Re < 2300, Düz Eğimli Çizgi)', titleEn: 'Laminar Flow Zone (f = 64/Re)', descTr: 'Sürtünme faktörü yüzey pürüzlülüğünden tamamen bağımsızdır, sadece viskoziteye bağlıdır', descEn: 'Friction factor depends strictly on fluid viscosity, immune to pipe roughness', diagramSvgType: 'rect_beam_stress', isCorrect: true },
          { id: 'c2', titleTr: 'Tam Türbülanslı Pürüzlü Bölge', titleEn: 'Fully Rough Turbulent Zone', descTr: 'Sürtünme faktörü yatay sabit çizgiye döner', descEn: 'Friction factor levels off to horizontal plateau', diagramSvgType: 'stress_notch', isCorrect: false },
        ],
        expTr: 'Doğru! Laminer akışta sürtünme sadece f = 64/Re ile belirlenir; boru pürüzlülüğünün hiçbir etkisi yoktur.',
        expEn: 'Correct! Laminar friction factor is strictly f = 64/Re, unaffected by boundary surface roughness.' },
      { num: 125, slug: 'fourier-heat-conduction-calc', std: 'Fourier Yasası', cat: 'Isı Transferi', diff: 'medium', pType: 'calculation',
        tTr: '125. Fourier Isı İletimi (Kondüksiyon) Hesabı', tEn: '125. Fourier\'s Law of Thermal Conduction',
        cTr: 'Düzlem duvardan geçen ısı akısı Q = (k * A * (T1 - T2)) / L formülüyle hesaplanır (k = ısıl iletkenlik W/mK).',
        cEn: 'Conductive heat transfer rate is Q = (k * A * ΔT) / L where k is thermal conductivity in W/mK.',
        f: '\\dot{Q} = k \\cdot A \\cdot \\frac{T_1 - T_2}{L}',
        calcPTr: 'Isıl iletkenliği k = 200 W/mK olan alüminyum plakanın alanı A = 0.5 m², kalınlığı L = 0.01 m (10 mm) ve sıcaklık farkı ΔT = 20 K ise iletilen ısı gücünü (Q) Watt cinsinden hesaplayınız:',
        calcPEn: 'Calculate conductive heat power Q in Watts for k = 200 W/mK, A = 0.5 m², L = 0.01 m, and ΔT = 20 K: (200 * 0.5 * 20 / 0.01):',
        tVal: 200000, tol: 1000, u: 'W', fHint: 'Q = 100 * 20 / 0.01 = 2000 / 0.01 = 200,000 W (200 kW)',
        calcExpTr: 'Doğru! Q = 200,000 W (200 kW).', calcExpEn: 'Correct! Q = 200,000 W (200 kW).' },
      { num: 126, slug: 'newton-cooling-convection-heat', std: 'Newton Soğuma Yasası', cat: 'Isı Transferi', diff: 'medium', pType: 'calculation',
        tTr: '126. Taşınım (Konveksiyon) ile Isı Transferi & h Katsayısı', tEn: '126. Convective Heat Transfer & Newton\'s Law',
        cTr: 'Yüzeyden akışkana geçen ısı gücü Q = h * A * (T_yüzey - T_akışkan) formülüyle hesaplanır (h = konveksiyon katsayısı W/m²K).',
        cEn: 'Convective heat transfer rate is Q = h * A * (T_surface - T_fluid) where h is film coefficient in W/m²K.',
        f: '\\dot{Q} = h \\cdot A \\cdot (T_s - T_\\infty)',
        calcPTr: 'h = 50 W/m²K (zorlanmış hava), yüzey alanı A = 2.0 m² ve sıcaklık farkı (Ts - T∞) = 30°C olan bir radyatörün attığı ısı gücünü (Q) Watt cinsinden hesaplayınız:',
        calcPEn: 'Calculate heat dissipation Q in Watts for h = 50 W/m²K, A = 2.0 m², and ΔT = 30 K (50 * 2.0 * 30):',
        tVal: 3000, tol: 20, u: 'W', fHint: 'Q = 50 * 2.0 * 30 = 3000 W (3 kW)',
        calcExpTr: 'Doğru! Q = 3000 W (3 kW).', calcExpEn: 'Correct! Q = 3000 W (3 kW).' },
      { num: 127, slug: 'stefan-boltzmann-radiation-heat', std: 'Stefan-Boltzmann', cat: 'Isı Transferi', diff: 'hard', pType: 'quiz',
        tTr: '127. Stefan-Boltzmann Işınım (Radyasyon) Isı Transferi (T⁴)', tEn: '127. Stefan-Boltzmann Thermal Radiation (T⁴)',
        cTr: 'Termal radyasyon sıcaklığın DÖRDÜNCÜ KUVVETİYLE (T⁴, Kelvin cinsinden) orantılıdır: Q = ε * σ * A * (T1⁴ - T2⁴). Yüksek sıcaklıklarda (fırınlar, uzay uygulamaları) radyasyon ana transfer modu haline gelir.',
        cEn: 'Radiative heat transfer scales with absolute temperature to the fourth power: Q = ε σ A (T1⁴ - T2⁴).',
        f: '\\dot{Q}_{\\text{rad}} = \\varepsilon \\cdot \\sigma \\cdot A \\cdot (T_1^4 - T_2^4), \\quad \\sigma = 5.67 \\times 10^{-8} \\, \\frac{\\text{W}}{\\text{m}^2 \\text{K}^4}',
        qTr: 'Bir yüzeyin mutlak sıcaklığı (Kelvin) 300 K\'den 600 K\'e (2 katına) çıkarılırsa yaydığı termal radyasyon enerjisi kaç katına çıkar?',
        qEn: 'If the absolute temperature of a blackbody is doubled from 300 K to 600 K, by what factor does its emitted thermal radiation increase?',
        oTr: ['16 katına (2⁴ = 16)', '2 katına', '4 katına', '8 katına'],
        oEn: ['16 times (2⁴ = 16)', '2 times', '4 times', '8 times'],
        cIdx: 0, expTr: 'Doğru! Stefan-Boltzmann yasasına göre ışıma sıcaklığın 4. kuvvetiyle (2⁴ = 16) artar.',
        expEn: 'Correct! Radiation scales with T⁴, multiplying emissions by 2⁴ = 16x.' },
      { num: 128, slug: 'thermal-stress-expansion-restraint', std: 'Termo-Mekanik', cat: 'Mukavemet', diff: 'hard', pType: 'calculation',
        tTr: '128. İki Ucu Sabit Çubukta Termal Gerilme (σ_th) Hesabı', tEn: '128. Constrained Thermal Expansion Stress (σ_th)',
        cTr: 'İki ucu rijit sabitlenmiş bir çubuk ΔT kadar ısıtıldığında serbest uzayamadığı için içinde σ = E * α * ΔT bası gerilmesi doğar.',
        cEn: 'Constrained thermal expansion induces axial compressive stress σ_th = E * α * ΔT.',
        f: '\\sigma_{\\text{thermal}} = E \\cdot \\alpha \\cdot \\Delta T',
        calcPTr: 'E = 200,000 MPa, termal genleşme katsayısı α = 12e-6 1/K ve sıcaklık artışı ΔT = 50 K olan çelik çubuktaki termal gerilmeyi (σ = 200000 * 12e-6 * 50) MPa cinsinden hesaplayınız:',
        calcPEn: 'Calculate constrained thermal stress σ_th in MPa for E = 200,000 MPa, α = 12e-6 1/K, and ΔT = 50 K:',
        tVal: 120, tol: 1, u: 'MPa', fHint: 'σ = 200,000 * 0.000012 * 50 = 2.4 * 50',
        calcExpTr: 'Doğru! σ = 120 MPa bası gerilmesi oluşur.', calcExpEn: 'Correct! σ = 120 MPa compressive stress.' },
      { num: 129, slug: 'joukowsky-water-hammer-shock-calc', std: 'Joukowsky Teoremi', cat: 'Akışkanlar', diff: 'hard', pType: 'calculation',
        tTr: '129. Joukowsky Su Koçu Darbesi (Water Hammer) Hesabı', tEn: '129. Joukowsky Water Hammer Shock Wave Pressure',
        cTr: 'Akış halindeki boruda vana aniden kapatıldığında akışkan momentumu şok dalgasına dönüşür ve ani basınç artışı Δp = ρ * c * Δv formülüyle hesaplanır (c = akışkandaki ses hızı ≈ 1000-1400 m/s).',
        cEn: 'Rapid valve closure converts kinetic momentum into shock wave pressure rise Δp = ρ * c * Δv.',
        f: '\\Delta p_{\\text{hammer}} = \\rho \\cdot c \\cdot \\Delta v',
        calcPTr: 'Su yoğunluğu ρ = 1000 kg/m³, ses dalga hızı c = 1200 m/s ve ani durdurulan hız Δv = 2.0 m/s için su koçu basınç darbesini (Δp = 1000 * 1200 * 2.0) Pascal cinsinden hesaplayınız:',
        calcPEn: 'Calculate water hammer pressure shock Δp in Pa for ρ = 1000 kg/m³, c = 1200 m/s, Δv = 2.0 m/s:',
        tVal: 2400000, tol: 10000, u: 'Pa', fHint: 'Δp = 2,400,000 Pa = 24 bar',
        calcExpTr: 'Doğru! Δp = 2,400,000 Pa = 24 bar ek şok basıncı boruları patlatabilir.',
        calcExpEn: 'Correct! Δp = 2.4 MPa (24 bar) shock pressure.' },
      { num: 130, slug: 'npsh-cavitation-pumps-visual', std: 'ISO 9906 / NPSH', cat: 'Akışkanlar', diff: 'hard', pType: 'visual',
        tTr: '130. Pompalarda Kavitasyon & Net Pozitif Emme Yüksekliği (NPSH)', tEn: '130. Pump Cavitation & Net Positive Suction Head (NPSH)',
        cTr: 'Pompa emişindeki statik basınç sıvının buharlaşma basıncının (p_sat) altına düşerse mikro buhar kabarcıkları oluşur ve yüksek basınç bölgesine geçince mikrosaniyelik mikrojet darbeleriyle patlayarak çarkı oyar (kavitasyon). NPSH_available > NPSH_required + 0.5 m olmalıdır.',
        cEn: 'Cavitation occurs when suction pressure drops below liquid vapor pressure, forming micro-bubbles that implode violently against impellers. NPSHa > NPSHr is mandatory.',
        f: '\\text{NPSH}_A = \\frac{p_{\\text{suction}} - p_{\\text{vapor}}}{\\rho g} + \\frac{v^2}{2 g} > \\text{NPSH}_R',
        visPTr: 'Santrifüj pompa çark kanatlarında kavitasyon mikrojet patlamalarının metal yüzeyinde açtığı karakteristik süngerimsi oyuk hasarı hangisidir?',
        visPEn: 'Which visual depicts cavitation pitting erosion damage on centrifugal pump impeller blades?',
        visCards: [
          { id: 'c1', titleTr: 'Kavitasyon Oyuklaşması (Cavitation Pitting & Sponge Erosion)', titleEn: 'Cavitation Impeller Pitting Erosion', descTr: 'Milyonlarca buhar kabarcığının patlamasıyla metal yüzeyinin sünger gibi oyulması ve aşırı ses/titreşim', descEn: 'Severe pitted spongelike material loss from imploding micro-bubble shock jets', diagramSvgType: 'pitting_crack', isCorrect: true },
          { id: 'c2', titleTr: 'Pürüzsüz Parlak Çark Kanadı', titleEn: 'Smooth Pristine Impeller Vane', descTr: 'Kavitasyonsuz sağlıklı çalışma', descEn: 'Undamaged hydraulic surface', diagramSvgType: 'i_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Kavitasyon buhar kabarcıklarının 1000 bar yerel mikrojet şoklarıyla metali sünger gibi oymasıdır.',
        expEn: 'Correct! Cavitation bubble implosions generate localized microjets exceeding 1000 bar, eroding blade metal.' },
      { num: 131, slug: 'heat-exchanger-lmtd-calc', std: 'Isı Değiştiricileri', cat: 'Isı Transferi', diff: 'hard', pType: 'quiz',
        tTr: '131. Isı Değiştiricilerinde Logaritmik Ortalama Sıcaklık Farkı (LMTD)', tEn: '131. Logarithmic Mean Temperature Difference (LMTD)',
        cTr: 'Karşıt akışlı (counter-flow) ısı değiştiricilerinde sıcak ve soğuk akışkanlar zıt yönlerde aktığı için paralel akışa göre çok daha yüksek LMTD ve %20-30 daha yüksek termal verim elde edilir.',
        cEn: 'Counter-flow heat exchangers maintain a more uniform temperature gradient, yielding higher LMTD and thermal effectiveness than parallel-flow.',
        f: '\\Delta T_{\\text{LMTD}} = \\frac{\\Delta T_1 - \\Delta T_2}{\\ln\\left(\\frac{\\Delta T_1}{\\Delta T_2}\\right)}, \\quad \\dot{Q} = U \\cdot A \\cdot \\Delta T_{\\text{LMTD}}',
        qTr: 'Aynı yüzey alanına ve debilere sahip bir ısı değiştiricisinde neden paralel akış yerine daima karşıt akış (counter-flow) tercih edilir?',
        qEn: 'Why is counter-flow configuration preferred over parallel-flow in shell-and-tube and plate heat exchangers?',
        oTr: ['Daha yüksek Logaritmik Ortalama Sıcaklık Farkı (LMTD) sağlayarak aynı alandan maksimum ısı transferi yaptığı için', 'Daha ucuz olduğu için', 'Daha az yer kapladığı için', 'Basıncı sıfırladığı için'],
        oEn: ['Maintains higher LMTD throughout the unit, maximizing total heat exchange per unit area', 'Cheaper material', 'Takes less space', 'Zeros pressure'],
        cIdx: 0, expTr: 'Doğru! Karşıt akışta sıcaklık gradyanı korunarak maksimum LMTD verimi elde edilir.',
        expEn: 'Correct! Counter-flow maximizes the mean driving temperature difference across the heat transfer area.' },
      { num: 132, slug: 'fin-efficiency-extended-surfaces', std: 'Kanatçıklı Yüzeyler', cat: 'Isı Transferi', diff: 'medium', pType: 'quiz',
        tTr: '132. Isı Alıcı Kanatçık Verimi (Fin Efficiency η_fin)', tEn: '132. Extended Surface Fin Efficiency (η_fin)',
        cTr: 'Elektronik soğutucularda alüminyum kanatçıklar yüzey alanını katlar. Kanatçık uzadıkça uçtaki sıcaklık düşer; kanatçık verimi η_fin = tanh(m*L) / (m*L) ile hesaplanır.',
        cEn: 'Heat sink fins multiply convective area. Fin efficiency η = tanh(mL)/(mL) accounts for conductive temperature drop along the fin length.',
        f: 'm = \\sqrt{\\frac{h \\cdot P}{k \\cdot A_c}}, \\quad \\eta_{\\text{fin}} = \\frac{\\tanh(m L)}{m L}',
        qTr: 'CPU soğutucu alüminyum kanatçıklarının aşırı uzun (L -> ∞) yapılmasının termal verim açısından dezavantajı nedir?',
        qEn: 'What is the diminishing thermal return of designing excessively long heat sink fins (L -> ∞)?',
        oTr: ['Kanatçık ucuna doğru sıcaklık ortam sıcaklığına yaklaşır, uç kısımlar ısı transferi yapmazken sadece ağırlık ve hava akış direnci yaratır', 'Kanatçık erir', 'Isı transferi sıfırlanır', 'İşlemci donar'],
        oEn: ['Fin tip temperature approaches ambient, contributing zero additional heat transfer while adding mass and airflow resistance', 'Fins melt', 'Heat transfer stops', 'CPU freezes'],
        cIdx: 0, expTr: 'Doğru! Termal iletim direnci nedeniyle aşırı uzun kanatların uçları ısı yayamaz.',
        expEn: 'Correct! Conduction resistance drops the tip temperature to ambient, rendering excess fin length ineffective.' },
      { num: 133, slug: 'navier-stokes-momentum-balance-draw', std: 'Navier-Stokes', cat: 'Akışkanlar', diff: 'hard', pType: 'drawing',
        tTr: '133. Navier-Stokes Sınır Tabaka Hız Profili Vektörleri', tEn: '133. Navier-Stokes Boundary Layer Velocity Profile',
        cTr: 'Katı cidar üzerindeki viskoz akışta cidar yüzeyinde kaymama koşulu (no-slip condition: v = 0) geçerlidir. Hız duvardan uzaklaştıkça artarak serbest akış hızına (U∞) ulaşır.',
        cEn: 'Viscous boundary layers obey the no-slip condition (v = 0 at wall), developing parabolic/logarithmic velocity profiles transitioning to freestream velocity U∞.',
        f: '\\rho \\left( \\frac{\\partial \\vec{v}}{\\partial t} + \\vec{v} \\cdot \\nabla \\vec{v} \\right) = -\\nabla p + \\mu \\nabla^2 \\vec{v} + \\rho \\vec{g}',
        dPromptTr: 'Boru iç çeperinde sıfır olan akışkan hız vektörü, borunun tam merkez eksenine doğru gidildikçe nasıl değişir?',
        dPromptEn: 'How does laminar fluid flow velocity change from the pipe wall toward the centerline axis?',
        vOpts: [
          { id: 'ns1', labelTr: 'Duvarda 0, merkez hattında parabolik maksimum hız (2 * v_ortalama)', labelEn: 'Zero at wall, increasing parabolically to peak velocity at centerline (2 * v_avg)', direction: 'right', isCorrect: true },
          { id: 'ns2', labelTr: 'Duvarda maksimum, merkezde 0', labelEn: 'Max at wall, zero at centerline', direction: 'left', isCorrect: false },
        ],
        expTr: 'Doğru! Poiseuille laminer profilinde hız cidarında sıfırdan merkezde 2*Vort tepe değerine çıkar.',
        expEn: 'Correct! Parabolic Poiseuille flow satisfies no-slip at wall and peaks at the pipe centerline.' },
      { num: 134, slug: 'carnot-efficiency-limit', std: 'Termodinamik 2. Yasa', cat: 'Termodinamik', diff: 'medium', pType: 'calculation',
        tTr: '134. Carnot Çevrimi & Maksimum Teorik Termal Verim', tEn: '134. Carnot Cycle & Maximum Theoretical Thermal Efficiency',
        cTr: 'Hiçbir ısı makinesi aynı iki sıcaklık deposu arasında çalışan Carnot makinesinden daha verimli olamaz: η_Carnot = 1 - (T_soğuk / T_sıcak) (Sıcaklıklar mutlak Kelvin olmalıdır!).',
        cEn: 'Carnot efficiency defines the absolute thermodynamic limit: η_Carnot = 1 - (T_cold / T_hot) in Kelvin.',
        f: '\\eta_{\\text{Carnot}} = 1 - \\frac{T_L}{T_H} \\quad (\\text{Kelvin Cinsinden})',
        calcPTr: 'T_sıcak = 600 K ve T_soğuk = 300 K arasında çalışan ideal bir Carnot motorunun teorik maksimum verimini (η = 1 - 300/600) yüzde (%) olarak hesaplayınız:',
        calcPEn: 'Calculate theoretical Carnot efficiency in percent (%) for T_hot = 600 K and T_cold = 300 K: (1 - 300/600) * 100:',
        tVal: 50, tol: 0.1, u: '%', fHint: 'η = 1 - 0.5 = 0.50 => %50',
        calcExpTr: 'Doğru! η_Carnot = %50.', calcExpEn: 'Correct! η_Carnot = 50%.' },
      { num: 135, slug: 'boss-steam-power-piping-validation', std: 'ASME B31.1 / EN 13480', cat: 'Termodinamik & Akışkanlar', diff: 'hard', pType: 'boss', isBoss: true,
        tTr: '135. 👑 BOSS SINAVI: 100 Bar / 540°C Kızgın Buhar Boru Hattı Hidro-Termal Doğrulaması', tEn: '135. 👑 BOSS TEST: 100 Bar / 540°C Superheated Steam Piping Hydro-Thermal Proof',
        cTr: 'Termik santral 100 bar, 540°C kızgın buhar hattında (P91 çeliği): 1) Darcy-Weisbach basınç düşümü (Δp ≤ %3), 2) Joukowsky ani buhar türbini trip kapanma koçu şoku, 3) 540°C termal genleşme kompansatör gerilmesi ve 4) Yalıtım ısı kaybı aynı anda kanıtlanmalıdır.',
        cEn: 'Comprehensive ASME B31.1 power piping validation proving hoop stress under 100 bar, steam hammer trip transient mitigation, and thermal expansion loops.',
        f: '\\sigma_{\\text{hoop}} = \\frac{p \\cdot (D_o - 2 t \\cdot Y)}{2 t} \\le S_{\\text{allow}}(540^\\circ\\text{C}), \\quad \\Delta p_{\\text{friction}} \\le 0.03 \\cdot p_{\\text{inlet}}',
        qTr: '540°C sıcaklığındaki 100 metre uzunluğundaki buhar boru hattının ısıyla 600 mm uzamasını boru mesnetlerini kırmadan absorbe etmek için boru hattına ne eklenir?',
        qEn: 'To absorb 600 mm of thermal expansion along a 100-meter 540°C high-pressure steam line without overstressing anchors, what piping feature is installed?',
        oTr: ['U-Büküm Termal Genleşme Döngüleri (Expansion Loops) veya Körük Kompansatörler', 'Boru kelepçelerini kaynaklamak', 'Boru çapını daraltmak', 'Yalıtımı sökmek'],
        oEn: ['U-shaped Thermal Expansion Loops or Bellows Expansion Joints', 'Rigid anchor clamps', 'Narrower pipe', 'Strip insulation'],
        cIdx: 0, expTr: 'Tebrikler Başmühendis! Termal genleşme döngüleri (U-Loop) devasa termal genleşmeyi elastik esnemeyle emerek tesis güvenliğini garanti eder!',
        expEn: 'Congratulations Master Engineer! Expansion loops flex elastically, safely absorbing severe thermal growth without overstressing pipe anchors!' }
    ]
  },

  // ─── UNIT 10: 💀 İLERİ FEA, ÇOK EKSENLİ YORULMA & EKSTREM MÜHENDİSLİK (136-150) ───
  {
    num: 10, id: 'unit-10',
    titleTr: 'Ünite 10: 💀 İleri FEA, Çok Eksenli Yorulma & Ekstrem Mühendislik',
    titleEn: 'Unit 10: 💀 Advanced FEA, Multi-Axial Fatigue & Extreme Engineering',
    descTr: 'Cauchy gerilme tensörü, J2 akma teorisi, 3D Mohr küresi, SIMP topoloji optimizasyonu ve kırılma mekaniği.',
    descEn: 'Cauchy stress tensors, J2 plasticity invariants, 3D Mohr sphere, SIMP topology optimization, and LEFM fracture.',
    gradient: 'from-purple-950 via-rose-950 to-amber-950', difficulty: 'extreme', accentColor: '#f59e0b',
    lessons: [
      { num: 136, slug: 'cauchy-stress-tensor-invariants', std: 'Sürekli Ortamlar Mekaniği', cat: 'İleri FEA', diff: 'extreme', pType: 'quiz',
        tTr: '136. Cauchy Gerilme Tensörü & Değişmezleri (I1, I2, I3)', tEn: '136. Cauchy Stress Tensor & Invariants (I1, I2, I3)',
        cTr: '3D uzayda gerilme durumu 3x3 simetrik Cauchy gerilme tensörü [σ] ile tanımlanır. Tensörün birinci değişmezi I1 = σxx + σyy + σzz (hidrostatik gerilmenin 3 katı) olup koordinat sisteminin dönmesinden bağımsızdır.',
        cEn: '3D stress states are represented by the 3x3 symmetric Cauchy tensor. The first invariant I1 = tr(σ) = σxx + σyy + σzz represents 3x hydrostatic pressure.',
        f: '[\\sigma] = \\begin{bmatrix} \\sigma_{xx} & \\tau_{xy} & \\tau_{xz} \\\\ \\tau_{yx} & \\sigma_{yy} & \\tau_{yz} \\\\ \\tau_{zx} & \\tau_{zy} & \\sigma_{zz} \\end{bmatrix}, \\quad I_1 = \\text{tr}([\\sigma]) = \\sigma_1 + \\sigma_2 + \\sigma_3',
        qTr: 'Koordinat sistemi uzayda istenen açıda döndürülsün, Cauchy gerilme tensörünün birinci değişmezi (I1 = σ1 + σ2 + σ3) değeri nasıl değişir?',
        qEn: 'Regardless of coordinate system rotation in 3D space, how does the first stress invariant I1 change?',
        oTr: ['Değişmez (İnvarianttır / Sabit Kalır)', 'Açıyla birlikte sıfırlanır', 'İki katına çıkar', 'Sadece eksenel boyutta artar'],
        oEn: ['Remains strictly invariant (Constant scalar)', 'Rotates to zero', 'Doubles', 'Increases along X'],
        cIdx: 0, expTr: 'Doğru! Tensör değişmezleri koordinat dönüşümlerinden etkilenmeyen skaler fiziksel büyüklüklerdir.',
        expEn: 'Correct! Tensor invariants are frame-indifferent physical quantities.' },
      { num: 137, slug: 'j2-deviatoric-stress-invariant-calc', std: 'von Mises / J2 Plastisite', cat: 'İleri Mukavemet', diff: 'extreme', pType: 'calculation',
        tTr: '137. Deviatorik Gerilme Tensörü & J2 İkinci Değişmezi Hesabı', tEn: '137. Deviatoric Stress Tensor & J2 Invariant Calculation',
        cTr: 'Plastik deformasyonu ve metallerde akmayı sadece şekil değiştirici deviatorik gerilme [s] yönetir. İkinci değişmez J2 = 1/2 * (s_ij * s_ij) olup von Mises eşdeğer gerilmesi σv = sqrt(3 * J2) ile doğrudan bağıntılıdır.',
        cEn: 'Plastic yielding in ductile metals is governed strictly by the deviatoric stress tensor [s]. The second invariant J2 relates to von Mises stress via σv = sqrt(3 * J2).',
        f: 's_{ij} = \\sigma_{ij} - \\frac{1}{3} I_1 \\delta_{ij}, \\quad J_2 = \\frac{1}{6}\\left[ (\\sigma_1 - \\sigma_2)^2 + (\\sigma_2 - \\sigma_3)^2 + (\\sigma_3 - \\sigma_1)^2 \\right]',
        calcPTr: 'J2 = 1200 MPa² olarak hesaplanan çok eksenli bir gerilme durumunda von Mises eşdeğer gerilmesini (σv = sqrt(3 * 1200) = sqrt(3600)) MPa cinsinden hesaplayınız:',
        calcPEn: 'Calculate von Mises equivalent stress σv in MPa for deviatoric invariant J2 = 1200 MPa²: σv = sqrt(3 * 1200):',
        tVal: 60, tol: 0.5, u: 'MPa', fHint: 'σv = sqrt(3600) = 60',
        calcExpTr: 'Doğru! σv = sqrt(3 * 1200) = sqrt(3600) = 60 MPa.', calcExpEn: 'Correct! σv = sqrt(3600) = 60 MPa.' },
      { num: 138, slug: '3d-mohr-circles-visual', std: 'Mohr Dairesi', cat: 'İleri Mukavemet', diff: 'extreme', pType: 'visual',
        tTr: '138. 3 Boyutlu Mohr Gerilme Çemberleri & Maksimum Kayma', tEn: '138. 3D Mohr Stress Circles & Absolute Maximum Shear (τ_abs_max)',
        cTr: '3D gerilme durumunda asal gerilmeler σ1 ≥ σ2 ≥ σ3 olup uzaydaki tüm olası düzlemlerin gerilme durumları 3 Mohr çemberinin arasındaki taralı bölgede yer alır. Mutlak maksimum kayma gerilmesi τ_max = (σ1 - σ3) / 2 dir.',
        cEn: 'All admissible 3D stress states lie within the region bounded by three Mohr circles. Absolute peak shear stress is τ_abs_max = (σ1 - σ3) / 2.',
        f: '\\tau_{\\text{abs},\\max} = \\frac{\\sigma_1 - \\sigma_3}{2} \\quad (\\text{Tresca Akma Kriteri})',
        visPTr: '3D Mohr çemberlerinde asal gerilmeler σ1 = 100 MPa, σ2 = 50 MPa ve σ3 = -60 MPa olduğunda mutlak maksimum kayma gerilmesini (τ_max) belirleyen en büyük dış çember hangi iki asal gerilme arasındadır?',
        visPEn: 'In a 3D stress state with principal stresses σ1 = 100 MPa, σ2 = 50 MPa, σ3 = -60 MPa, which pair defines the outermost major Mohr circle?',
        visCards: [
          { id: 'c1', titleTr: 'σ1 ve σ3 Arasındaki Ana Çember (Çap = σ1 - σ3 = 160 MPa)', titleEn: 'Major Circle between σ1 and σ3 (τ_max = 80 MPa)', descTr: 'Mutlak tepe kayma gerilmesini τ_max = (100 - (-60))/2 = 80 MPa olarak belirler', descEn: 'Governs absolute maximum shear stress τ_abs_max = 80 MPa across 45° planes', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'σ1 ve σ2 Arasındaki İç Çember', titleEn: 'Minor Circle between σ1 and σ2', descTr: 'Küçük yerel kayma', descEn: 'Sub-dominant local shear', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! En büyük dış Mohr çemberi daima en büyük asal gerilme (σ1) ile en küçük asal gerilme (σ3) arasındadır.',
        expEn: 'Correct! The outer major circle spanning σ1 to σ3 governs peak shear sliding.' },
      { num: 139, slug: 'findley-multiaxial-fatigue-model', std: 'Findley Kritik Düzlem', cat: 'Çok Eksenli Yorulma', diff: 'extreme', pType: 'quiz',
        tTr: '139. Findley & Brown-Miller Kritik Düzlem Çok Eksenli Yorulma Modelleri', tEn: '139. Findley & Brown-Miller Critical Plane Multiaxial Fatigue',
        cTr: 'Faz farkı olan (non-proportional) çok eksenli dinamik yüklerde von Mises teorisi %40 hatalı sonuç verir! Findley ve Brown-Miller yöntemleri uzaydaki tüm açılarda dönen düzlemleri tarayarak kayma genliği ve normal gerilmenin tepe yaptığı KRİTİK DÜZLEMİ (Critical Plane) bulur.',
        cEn: 'Under out-of-phase multiaxial cyclic loading, scalar von Mises fails. Critical plane criteria (Findley, Brown-Miller) search all 3D orientations for peak shear-normal damage planes.',
        f: '\\max_{\\theta, \\phi} \\left[ \\frac{\\Delta \\tau}{2} + k \\cdot \\sigma_{n,\\max} \\right] \\le f_w',
        qTr: 'Dönen bir milde eğilme ve burulma momentleri arasında 90° faz farkı (biri maksimumdayken diğeri sıfır) olduğunda neden standart skaler von Mises analizi kullanılamaz?',
        qEn: 'When rotating bending and cyclic torsion operate with a 90° phase lag, why does static scalar von Mises yield erroneous non-conservative predictions?',
        oTr: ['Asal gerilme doğrultuları malzeme içinde sürekli fırıl fırıl dönerek (rotating principal axes) çatlakları birden çok düzlemde büyüttüğü için', 'Malzeme eridiği için', 'Frekans sıfırlandığı için', 'Sıcaklık düştüğü için'],
        oEn: ['Principal stress axes continuously rotate in 3D space, driving cyclic shear damage across shifting orientations', 'Material melts', 'Zero frequency', 'Temperature drops'],
        cIdx: 0, expTr: 'Doğru! Dönen asal gerilme eksenleri kayma hasarını yayar; kritik düzlem analizi zorunludur.',
        expEn: 'Correct! Out-of-phase loading rotates principal directions, requiring critical-plane shear search algorithms.' },
      { num: 140, slug: 'lefm-stress-intensity-factor-k1', std: 'ASTM E399 / LEFM', cat: 'Kırılma Mekaniği', diff: 'extreme', pType: 'calculation',
        tTr: '140. Doğrusal Elastik Kırılma Mekaniği (LEFM) & Gerilme Şiddet Faktörü (K_I)', tEn: '140. LEFM Mode-I Stress Intensity Factor (K_I) Calculation',
        cTr: '2a uzunluğunda çatlak içeren bir plakada çatlak ucu gerilme şiddet faktörü K_I = Y * σ * sqrt(π * a) formülüyle hesaplanır. K_I ≥ K_IC (Kırılma Tokluğu) olduğunda parça ANİDE VE FELAKET ŞEKLİNDE KOPAR.',
        cEn: 'Mode-I stress intensity factor is K_I = Y * σ * sqrt(π * a). Unstable fast brittle fracture occurs instantaneously when K_I ≥ K_IC.',
        f: 'K_I = Y \\cdot \\sigma \\cdot \\sqrt{\\pi \\cdot a} \\le K_{IC} \\quad [\\text{MPa}\\sqrt{\\text{m}}]',
        calcPTr: 'Geometrik faktör Y = 1.0, nominal çekme gerilmesi σ = 200 MPa ve çatlak yarı boyu a = 0.01 m (π * a = 3.1416 * 0.01 = 0.031416, sqrt(0.031416) ≈ 0.17725 m^(1/2)) için K_I = 200 * 0.17725 değerini (MPa*m^(1/2)) hesaplayınız:',
        calcPEn: 'Calculate Mode-I stress intensity factor K_I in MPa*m^(1/2) for Y = 1.0, σ = 200 MPa, and sqrt(π * a) = 0.17725:',
        tVal: 35.45, tol: 0.5, u: 'MPa√m', fHint: 'K_I = 200 * 0.17725 ≈ 35.45',
        calcExpTr: 'Doğru! K_I ≈ 35.45 MPa√m (Eğer malzemenin K_IC tokluğu 30 MPa√m ise parça anında ikiye ayrılır!).',
        calcExpEn: 'Correct! K_I = 35.45 MPa√m.' },
      { num: 141, slug: 'paris-erdogan-crack-growth-law', std: 'ASTM E647 / Paris Yasası', cat: 'Kırılma Mekaniği', diff: 'extreme', pType: 'calculation',
        tTr: '141. Paris-Erdogan Yorulma Çatlağı İlerleme Yasası (da/dN)', tEn: '141. Paris-Erdogan Fatigue Crack Growth Law (da/dN)',
        cTr: 'Döngü başına çatlak büyüme hızı da/dN = C * (ΔK)^m formülüyle hesaplanır. Çatlak her çevrimde mikron mikron büyüyerek kritik boya (a_crit) ulaşır.',
        cEn: 'Fatigue crack propagation rate is governed by Paris\' Law: da/dN = C * (ΔK)^m.',
        f: '\\frac{da}{dN} = C \\cdot (\\Delta K)^m \\implies N_{\\text{cycles}} = \\int_{a_0}^{a_{crit}} \\frac{da}{C \\cdot (\\Delta K)^m}',
        calcPTr: 'C = 10⁻¹¹ mm/(çevrim*(MPa√m)³), m = 3 ve ΔK = 20 MPa√m ((ΔK)³ = 8000) için döngü başına çatlak ilerleme hızını (da/dN = 10^-11 * 8000 = 8 * 10^-8 mm/çevrim) 10⁻⁸ mm cinsinden hesaplayınız:',
        calcPEn: 'Calculate crack growth rate in units of 10⁻⁸ mm/cycle for C = 10⁻¹¹, m = 3, and ΔK = 20: da/dN = 10^-11 * 8000 = X * 10^-8:',
        tVal: 8.0, tol: 0.1, u: 'x10⁻⁸ mm/çevrim', fHint: '8000 * 10^-11 = 8 * 10^-8 => 8.0',
        calcExpTr: 'Doğru! da/dN = 8.0 x 10⁻⁸ mm/çevrim.', calcExpEn: 'Correct! da/dN = 8.0 x 10^-8 mm/cycle.' },
      { num: 142, slug: 'simp-topology-optimization-visual', std: 'SIMP Metodu', cat: 'İleri FEA', diff: 'extreme', pType: 'visual',
        tTr: '142. SIMP Topoloji Optimizasyonu & Yapay Yoğunluk (Solid Isotropic Material with Penalization)', tEn: '142. SIMP Topology Optimization Density Field',
        cTr: 'SIMP yönteminde her FEA elemanına 0 ile 1 arasında yapay yoğunluk (ρ_e) atanır ve elastisite modülü E(ρ) = ρ^p * E0 ceza üssüyle (p=3) ölçeklenerek gerilme taşımayan bölgelerdeki malzeme boşaltılır.',
        cEn: 'SIMP penalizes intermediate densities via E(ρe) = ρe^p * E0 (typically p=3), driving the domain toward discrete 0 (void) or 1 (solid) organic load trusses.',
        f: 'E_e(\\rho_e) = \\rho_e^p \\cdot E_0, \\quad \\min_{\\vec{\\rho}} C(\\vec{\\rho}) = \\vec{U}^T \\mathbf{K} \\vec{U} \\quad \\text{subject to } V \\le V_{\\text{target}}',
        visPTr: 'Ağırlığı %50 azaltılmış bir konsol taşıyıcı kolun SIMP topoloji optimizasyonu sonrasında aldığı organik kemiksi kafes strüktür görüntüsü hangisidir?',
        visPEn: 'Which visual depicts an optimized organic bone-like load-path structure resulting from SIMP FEA topology optimization?',
        visCards: [
          { id: 'c1', titleTr: 'SIMP Organik Yük Yolu Kafesi (Organik Boşaltılmış Tasarım)', titleEn: 'SIMP Optimized Organic Truss Structure', descTr: 'Kuvvet akış çizgilerini takip eden kemiksi dallanmalar ve gerilmesiz bölgelerin tamamen boşaltıldığı hafif tasarım', descEn: 'Bionic organic load-aligned branching ribs with non-structural voids evacuated', diagramSvgType: 'i_beam_stress', isCorrect: true },
          { id: 'c2', titleTr: 'Ağır İçi Dolu Masif Blok', titleEn: 'Solid Homogeneous Block', descTr: 'Optimizasyon yapılmamış gereksiz ağır kütle', descEn: 'Unoptimized heavy block with dead weight zones', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! SIMP optimizasyonu doğadaki kemik yapısı gibi sadece kuvvet ileten lifleri koruyarak hafifletir.',
        expEn: 'Correct! SIMP topology optimization produces biomimetic lightweight structures along principal stress vectors.' },
      { num: 143, slug: 'johnson-cook-high-strain-rate-plasticity', std: 'Johnson-Cook Modeli', cat: 'İleri FEA', diff: 'extreme', pType: 'quiz',
        tTr: '143. Johnson-Cook Yüksek Şekil Değiştirme Hızı & Çarpışma (Crash) Plastisitesi', tEn: '143. Johnson-Cook High Strain-Rate Dynamic Plasticity',
        cTr: 'Otomotiv çarpışma (crash) ve balistik penetrasyon analizlerinde metaller plastik deformasyon hızına (dε/dt) ve termal yumuşamaya (T/Tm) göre modellenir: σ = [A + B*ε^n] * [1 + C*ln(ε_dot*)] * [1 - (T*)^m].',
        cEn: 'The Johnson-Cook constitutive law couples strain hardening, strain rate sensitivity, and thermal softening for high-velocity crash and impact dynamics.',
        f: '\\sigma = \\left[ A + B \\varepsilon_p^n \\right] \\left[ 1 + C \\ln\\left( \\frac{\\dot{\\varepsilon}_p}{\\dot{\\varepsilon}_0} \\right) \\right] \\left[ 1 - \\left( \\frac{T - T_{\\text{room}}}{T_{\\text{melt}} - T_{\\text{room}}} \\right)^m \\right]',
        qTr: 'Yüksek hızlı balistik bir çarpışmada çeliğin şekil değiştirme hızı aniden 10,000 1/s mertebesine çıktığında akma gerilmesi ve deformasyon davranışı nasıl değişir?',
        qEn: 'During high-velocity ballistic projectile impact (strain rates > 10,000 s⁻¹), how does material yield behavior change according to Johnson-Cook?',
        oTr: ['Dinamik gerinim hızı sertleşmesi (strain-rate hardening) nedeniyle malzemenin anlık akma dayanımı statik değerinin 2-3 katına fırlar', 'Malzeme sıvılaşır', 'Akma sıfırlanır', 'Sertlik düşer'],
        oEn: ['Dynamic strain-rate hardening multiplies instantaneous yield strength 2 to 3x over static values', 'Material liquefies', 'Yield drops to zero', 'Hardness decreases'],
        cIdx: 0, expTr: 'Doğru! Yüksek hızda dislokasyon hareketi zorlaşır ve dinamik akma mukavemeti devasa oranda artar.',
        expEn: 'Correct! Viscoplastic drag locks dislocation glide at extreme strain rates, spiking dynamic yield stress.' },
      { num: 144, slug: 'hourglassing-zero-energy-modes-fea', std: 'FEA Nümerik Analiz', cat: 'İleri FEA', diff: 'extreme', pType: 'visual',
        tTr: '144. İndirgenmiş İntegrasyon ve Kum Saati (Hourglassing) Sıfır Enerji Modları', tEn: '144. Reduced Integration & Hourglass Zero-Energy Modes',
        cTr: '1. derece 4 düğümlü kabuk veya 8 düğümlü heksahedral elemanlarda tek nokta Gauss integrasyonu (reduced integration) kullanıldığında hiçbir gerilme üretmeyen sahte dalgalı deformasyon (Hourglassing) oluşur. Hourglass kontrol rijitliği eklenmelidir.',
        cEn: 'Under-integrated solid/shell elements exhibit spurious zero-energy deformation modes (Hourglassing) producing zero stress at Gauss points. Artificial stiffness/viscous controls are required.',
        f: '\\int_V \\mathbf{B}^T \\mathbf{D} \\mathbf{B} \\, dV \\implies \\mathbf{K} \\vec{u}_{\\text{hourglass}} = \\vec{0}',
        visPTr: 'FEA ağında tek noktalı indirgenmiş integrasyonlu elemanların gerilme üretmeksizin zikzak şeklinde deforme olduğu sahte kum saati deseni hangisidir?',
        visPEn: 'Which mesh deformation pattern shows spurious non-physical Hourglassing zero-energy modes in under-integrated FEA elements?',
        visCards: [
          { id: 'c1', titleTr: 'Kum Saati Deformasyonu (Hourglassing Spurious Mode)', titleEn: 'Hourglassing Zero-Energy Mesh Distortion', descTr: 'İntegrasyon noktasında gerilme hissetmeyen sahte zikzak dalgalanma hatası', descEn: 'Non-physical alternating zig-zag grid distortion with zero strain energy at Gauss points', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'Düzgün Homojen Deplasman Ağı', titleEn: 'Smooth Regular Deformed Mesh', descTr: 'Hatasız fiziksel deformasyon', descEn: 'Properly integrated physical strain field', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Kum saati modu indirgenmiş elemanların entegrasyon noktasındaki türev körlüğünden kaynaklanan sahte deformasyondur.',
        expEn: 'Correct! Hourglassing stems from under-integrated Gauss points remaining blind to rank-deficient bending modes.' },
      { num: 145, slug: 'cohesive-zone-delamination-fem', std: 'CZM / Abaqus / Ansys', cat: 'İleri FEA', diff: 'extreme', pType: 'quiz',
        tTr: '145. Kohezif Bölge Modeli (CZM) ile Kompozit Tabaka Ayrılması (Delaminasyon)', tEn: '145. Cohesive Zone Modeling (CZM) & Composite Delamination',
        cTr: 'Karbon fiber kompozitlerde (CFRP) tabakalar arası ayrılma (delaminasyon) çekme ayrılması ve kayma enerjisini (G_I, G_II, G_IC) eşleştiren Kohezif Bölge Modeli (Traction-Separation Law) ile simüle edilir.',
        cEn: 'Composite interlaminar delamination is captured via Traction-Separation Cohesive Zone Models (CZM) governed by critical fracture energies GIc and GIIc.',
        f: 'G_I = \\int_0^{\\delta_n^f} \\sigma_n(\\delta) \\, d\\delta = G_{IC}',
        qTr: 'Kohezif elemanlarda (CZM) hasar başlangıcı (damage initiation) oluştuktan sonra eleman tam kopana kadar geçen aşamada ne gerçekleşir?',
        qEn: 'In a traction-separation Cohesive Zone Model, what physical process occurs between damage initiation and complete separation?',
        oTr: ['Kohezif çekme gerilmesi elastik tepe noktasından sıfıra doğru doğrusal/üstel olarak söner (Softening / Enerji Yutumu)', 'Gerilme sonsuz olur', 'Eleman sertleşir', 'Sıcaklık sıfırlanır'],
        oEn: ['Traction softens linearly/exponentially toward zero, dissipating critical fracture energy Gc', 'Stress becomes infinite', 'Element stiffens', 'Temperature zeros'],
        cIdx: 0, expTr: 'Doğru! Hasar başladığında gerilme düşer (softening) ve kırılma enerjisi yutularak delaminasyon tamamlanır.',
        expEn: 'Correct! Softening traction dissipates fracture energy Gc until complete interface debonding occurs.' },
      { num: 146, slug: 'neuber-rule-elastoplastic-notches', std: 'Neuber Kuralı', cat: 'İleri Mukavemet', diff: 'extreme', pType: 'calculation',
        tTr: '146. Neuber Kuralı: Çentik Dibinde Elastoplastik Gerilme-Gerinim', tEn: '146. Neuber\'s Rule for Local Notch Elasto-Plasticity',
        cTr: 'Çentik dibinde lokal akma meydana geldiğinde elastik gerilme konsantrasyonu Kt ile gerçek gerilme (σ) ve gerinim (ε) arasında Neuber kuralı geçerlidir: Kt² = K_sigma * K_epsilon => σ * ε = (Kt * S)² / E.',
        cEn: 'Neuber\'s rule relates linear elastic peak notch stress to actual elastic-plastic local stress and strain: σ * ε = (Kt * S)² / E.',
        f: 'K_t^2 = K_\\sigma \\cdot K_\\varepsilon \\implies \\sigma \\cdot \\varepsilon = \\frac{(K_t \\cdot S)^2}{E}',
        calcPTr: 'Kt * S = 600 MPa, E = 200,000 MPa ((Kt*S)² / E = 360,000 / 200,000 = 1.8 MPa) ve lokal akma gerilmesi σ = 300 MPa ise çentik dibindeki gerçek gerinimi (ε = 1.8 / 300) hesaplayınız:',
        calcPEn: 'Calculate actual notch strain ε using Neuber\'s rule for (Kt*S)²/E = 1.8 MPa and local stress σ = 300 MPa: ε = 1.8 / 300:',
        tVal: 0.006, tol: 0.0001, u: '', fHint: 'ε = 1.8 / 300 = 0.006 (%0.6 gerinim)',
        calcExpTr: 'Doğru! ε = 0.006 (%0.6 lokal gerinim).', calcExpEn: 'Correct! ε = 0.006 (0.6% local notch strain).' },
      { num: 147, slug: 'random-vibration-psd-fatigue', std: 'Steinberg / Dirlik / PSD', cat: 'Dinamik FEA', diff: 'extreme', pType: 'quiz',
        tTr: '147. Rastgele Titreşim (Random Vibration) & PSD Dirlik Yorulma Analizi', tEn: '147. Random Vibration PSD & Dirlik Fatigue Life',
        cTr: 'Roket fırlatması ve otomotiv yol testlerinde rastgele titreşim Güç Spektral Yoğunluğu (PSD: g²/Hz) ile tanımlanır. Dirlik frekans-alanı yöntemi PSD sinyalinin momentlerinden (m0, m1, m2, m4) gerilme olasılık yoğunluk fonksiyonunu çıkararak yorulma ömrünü tahmin eder.',
        cEn: 'Random vibration is defined via Power Spectral Density (PSD: g²/Hz). Dirlik\'s spectral method extracts cycle count probability density from spectral moments to predict fatigue life.',
        f: 'p(\\sigma) = \\frac{1}{2 \\sqrt{m_0}} \\left[ \\frac{D_1}{Q} e^{-\\frac{Z}{Q}} + \\frac{D_2 Z}{R^2} e^{-\\frac{Z^2}{2 R^2}} + D_3 Z e^{-\\frac{Z^2}{2}} \\right]',
        qTr: 'Havacılık ve roket aviyonik kutularının titreşim testinde neden tekil sinüs titreşimi yerine PSD Rastgele Titreşim (Random Vibration) testi zorunludur?',
        qEn: 'Why do aerospace and rocket avionics standards mandate Random PSD Vibration over single-frequency sine sweeps?',
        oTr: ['Gerçek roket fırlatmasında tüm rezonans frekansları aynı anda rastgele uyarılarak çok modlu yorulma hasarı oluşturduğu için', 'Test daha kısa sürdüğü için', 'Sensör gerektirmediği için', 'Maliyeti sıfırladığı için'],
        oEn: ['Rocket launches excite all structural resonances simultaneously across a wide frequency band', 'Shorter test time', 'No sensors required', 'Zero cost'],
        cIdx: 0, expTr: 'Doğru! Rastgele titreşim sistemin tüm serbestlik derecelerini aynı anda uyararak gerçek çalışma koşulunu modeller.',
        expEn: 'Correct! Broadband PSD excitation simulates real multi-modal rocket vibration environments accurately.' },
      { num: 148, slug: 'danso-3d-principal-stress-vectors', std: 'Asal Gerilmeler', cat: 'İleri Mukavemet', diff: 'extreme', pType: 'drawing',
        tTr: '148. 3D Asal Gerilme Yönü ve Özvektör Yönelimi', tEn: '148. 3D Principal Stress Eigenvector Alignment',
        cTr: 'Asal gerilme düzlemlerinde kayma gerilmeleri tamamen sıfırdır (τ = 0). Bu düzlemlerin normal vektörleri Cauchy gerilme tensörünün özvektörleridir ([σ]*n = σ*n).',
        cEn: 'On principal stress planes, shear stresses are identically zero (τ = 0). Normal vectors align with tensor eigenvectors ([σ] n = σ n).',
        f: '([\\sigma] - \\sigma_i \\mathbf{I}) \\vec{n}_i = \\vec{0} \\implies \\tau_{\\text{shear}} = 0',
        dPromptTr: 'Asal çekme gerilmesi σ1\'in etki ettiği asal düzlem üzerinde kayma gerilmesinin (τ) büyüklüğü ve yönü nedir?',
        dPromptEn: 'On the principal stress plane corresponding to maximum normal stress σ1, what is the magnitude of the shear stress vector?',
        vOpts: [
          { id: 'pr1', labelTr: 'Sıfırdır (Kayma gerilmesi tamamen yok olur)', labelEn: 'Identically Zero (Pure normal stress state)', direction: 'up', isCorrect: true },
          { id: 'pr2', labelTr: 'Maksimum tepe değerindedir', labelEn: 'At maximum peak', direction: 'right', isCorrect: false },
        ],
        expTr: 'Doğru! Asal düzlemlerin tanımı gereği bu düzlemlerde tüm kayma gerilmeleri tam olarak sıfırdır.',
        expEn: 'Correct! By definition, shear stresses vanish completely on principal planes.' },
      { num: 149, slug: 'co-rotational-geometric-nonlinearity', std: 'Non-Linear FEA', cat: 'İleri FEA', diff: 'extreme', pType: 'quiz',
        tTr: '149. Geometrik Doğrusal Olmayan Analiz (Büyük Deplasman / Co-Rotational FEA)', tEn: '149. Large Displacement & Geometric Non-Linear FEA',
        cTr: 'Yapıda büyük dönmeler ve yerdeğiştirmeler oluştuğunda (örn. ince çubuğun U-şeklinde bükülmesi) küçük deformasyon teorisi çöker. Co-rotational formülasyon rijit cisim hareketini elastik gerinimden ayırarak teğetsel rijitlik matrisini [KT] sürekli günceller.',
        cEn: 'Large rotations invalidate linear kinematics. Co-rotational FEA decouples rigid-body translation/rotation from pure elastic strain, updating tangent stiffness [KT] via Newton-Raphson iterations.',
        f: '\\mathbf{K}_T = \\mathbf{K}_{\\text{material}} + \\mathbf{K}_{\\text{geometric}}(\\vec{\\sigma}) + \\mathbf{K}_{\\text{displacement}}',
        qTr: 'İnce bir yay çeliği cetveli 180° kıvırarak U şekline getirdiğimizde doğrusal elastik lineer FEA analizi neden saçma ve devasa hatalı gerilmeler hesaplar?',
        qEn: 'When bending a thin flexible ruler 180° into a U-shape, why does linear small-displacement FEA yield absurd catastrophic errors?',
        oTr: ['Rijit cisim dönmesini yapay sahte gerinim (fictitious strain) olarak algılayıp geometri değişimini ihmal ettiği için', 'Çelik eridiği için', 'Poisson oranı sıfırlandığı için', 'Eleman sayısı az olduğu için'],
        oEn: ['Linear formulation interprets rigid-body rotation as fictitious engineering strain without updating geometric equilibrium', 'Steel melts', 'Poisson ratio vanishes', 'Low element count'],
        cIdx: 0, expTr: 'Doğru! Büyük dönmelerde doğrusal formülasyon rijit dönmeyi gerinime çevirir; non-linear büyük deplasman formülasyonu şarttır.',
        expEn: 'Correct! Linear kinematics fails under large rotations; non-linear geometric co-rotational solvers are mandatory.' },
      { num: 150, slug: 'boss-grandmaster-spacecraft-extreme-proof', std: 'NASA / ESA / ECSS-E-ST-32C', cat: 'Ekstrem Mühendislik', diff: 'extreme', pType: 'boss', isBoss: true,
        tTr: '150. 👑 GRANDMASTER BOSS: Artemis Ay Görevi Roket Kapsülü Tam Çoklu-Fizik Sertifikasyonu', tEn: '150. 👑 GRANDMASTER BOSS: Artemis Lunar Mission Crew Capsule Multi-Physics Certification',
        cTr: 'Kapsülün Dünya atmosferine 11 km/s hızla girişi ve Ay inişinde: 1) 3000°C aerotermal plazma akışında ablatif ısı kalkanı termal iletimi, 2) 15g darbe şokunda Johnson-Cook titanyum kafes plastik çökme güvenliği (S ≥ 2.0), 3) 50g²/Hz rastgele roket akustik titreşiminde Dirlik çok eksenli yorulma ömrü (> 10⁷ çevrim), 4) Kırılma mekaniği LEFM çatlak ilerleme toleransı (K_I < 0.5*K_IC) ve 5) Basınçlı kabin von Kármán kabuk burkulması tek bir simülasyon sisteminde tam kanıtlanmalıdır.',
        cEn: 'Ultimate Grandmaster multi-physics aerospace certification proving combined aerothermal ablation, 15g high-rate impact dynamics, Dirlik random acoustic fatigue, and NASA-STD-5001 fracture mechanics compliance.',
        f: '\\text{Margin of Safety (MoS)} = \\frac{\\text{Allowable Design Limit}}{\\text{Calculated Extreme Multi-Physics Response} \\times \\text{Factor of Safety}} - 1.0 \\ge +0.20',
        qTr: 'Tüm bu ekstrem uzay çoklu-fizik analizinde havacılık-uzay standardı (NASA / ECSS) gereğince nihai tasarımın onaylanması için Güvenlik Marjı (Margin of Safety - MoS) hangi şartı sağlamalıdır?',
        qEn: 'Under NASA and ECSS spaceflight standards, what mathematical condition must the Margin of Safety (MoS) satisfy for flight readiness clearance?',
        oTr: ['MoS = (Limit / (Hesaplanan x Emniyet Katsayısı)) - 1.0 ≥ 0 (Pozitif Güvenlik Marjı)', 'MoS < -1.0', 'MoS = 0 olması felakettir', 'MoS sonsuz olmalıdır'],
        oEn: ['Margin of Safety (MoS) ≥ 0.0 (Positive Margin of Safety under worst-case combined extremes)', 'MoS < -1.0', 'MoS must be negative', 'MoS infinite only'],
        cIdx: 0, expTr: 'TEBRİKLER BÜYÜK BAŞMÜHENDİS! 150 BÖLÜMLÜK TÜM MÜHENDİSLİK MÜFREDATINI EN YÜKSEK DÜZEYDE TAMAMLADINIZ! 👑🚀 ALÜMİNYUM VE MEKANİK AKADEMİSİNİN EFSANEVİ BAŞMİMARISINIZ!',
        expEn: 'CONGRATULATIONS GRANDMASTER CHIEF ENGINEER! You have conquered all 150 sections of the advanced engineering curriculum! 👑🚀 You are the legendary Master Architect of Alucalculator Academy!' }
    ]
  }
];

console.log('Units 7-10 dataset ready.');
