// UNITS 4 to 6 (Lessons 46 to 90)
module.exports = [
  // ─── UNIT 4: DİŞLİ MEKANİZMALARI & ISO 6336 (46-60) ───
  {
    num: 4, id: 'unit-4',
    titleTr: 'Ünite 4: Dişli Mekanizmaları & ISO 6336',
    titleEn: 'Unit 4: Gear Mechanisms & ISO 6336',
    descTr: 'Modül, taksimat dairesi, diş dibi eğilmesi (sigma_F), Hertz temas basıncı (sigma_H) ve Willis formülü.',
    descEn: 'Module, pitch diameter, root bending fatigue, Hertzian contact pressure, and planetary Willis equations.',
    gradient: 'from-purple-600 via-pink-600 to-rose-600', difficulty: 'hard', accentColor: '#ec4899',
    lessons: [
      { num: 46, slug: 'gear-geometry-module-pitch', std: 'DIN 867 / ISO 53', cat: 'Dişliler', diff: 'easy', pType: 'quiz',
        tTr: '46. Düz Dişli Geometrisi: Modül (m) ve Taksimat Çapı (d)', tEn: '46. Spur Gear Geometry: Module (m) & Pitch Diameter (d)',
        cTr: 'Standart evolvent dişlilerde taksimat dairesi çapı d = m * z formülüyle hesaplanır. Standart kavrama açısı α = 20° dir.',
        cEn: 'In standard involute gears, pitch diameter is d = m * z. Standard pressure angle is α = 20°.',
        f: 'd = m \\cdot z, \\quad p = \\pi \\cdot m',
        qTr: 'Modülü m = 4 mm ve diş sayısı z = 25 olan bir düz dişlinin taksimat dairesi çapı (d) kaç mm\'dir?',
        qEn: 'What is the pitch diameter (d) of a spur gear with module m = 4 mm and tooth count z = 25?',
        oTr: ['100 mm (4 x 25)', '50 mm', '200 mm', '29 mm'], oEn: ['100 mm (4 x 25)', '50 mm', '200 mm', '29 mm'],
        cIdx: 0, expTr: 'Doğru! d = m * z = 4 * 25 = 100 mm.', expEn: 'Correct! d = m * z = 4 * 25 = 100 mm.' },
      { num: 47, slug: 'gear-ratio-speed-calculation', std: 'Mekanizma Tekniği', cat: 'Dişliler', diff: 'easy', pType: 'calculation',
        tTr: '47. Dişli Çevrim Oranı (i) ve Çıkış Devri Hesabı', tEn: '47. Gear Ratio (i) & Output Speed Calculation',
        cTr: 'Çevrim oranı i = z2 / z1 = n1 / n2 formülüyle hesaplanır. Çıkış devri n2 = n1 / i olur.',
        cEn: 'Transmission ratio is i = z2 / z1 = n1 / n2. Output rotational speed is n2 = n1 / i.',
        f: 'i = \\frac{z_2}{z_1} = \\frac{n_1}{n_2}',
        calcPTr: 'Giriş dişlisi z1 = 20, çıkış dişlisi z2 = 80 olan bir kademede n1 = 1400 d/dak motor bağlıysa çıkış mili devrini (d/dak) hesaplayınız:',
        calcPEn: 'For z1 = 20, z2 = 80 and motor speed n1 = 1400 RPM, calculate output shaft RPM:',
        tVal: 350, tol: 2, u: 'd/dak', fHint: 'i = 80 / 20 = 4; n2 = 1400 / 4',
        calcExpTr: 'Doğru! i = 4 ve n2 = 1400 / 4 = 350 d/dak.', calcExpEn: 'Correct! i = 4 and n2 = 1400 / 4 = 350 RPM.' },
      { num: 48, slug: 'tangential-force-calculation', std: 'ISO 6336-1', cat: 'Dişliler', diff: 'medium', pType: 'calculation',
        tTr: '48. Dişli Teğetsel Kuvveti (Ft) Hesabı', tEn: '48. Gear Tangential Force (Ft) Calculation',
        cTr: 'Tork T (Nm) ve taksimat yarıçapı r = d / 2 (mm) bilindiğinde teğetsel kuvvet Ft = 2000 * T / d (Newton) olarak hesaplanır.',
        cEn: 'Tangential force at the pitch cylinder is Ft = 2000 * T / d (in Newtons) where T is in Nm and d is in mm.',
        f: 'F_t = \\frac{2000 \\cdot T}{d}',
        calcPTr: 'T = 300 Nm tork aktaran d = 150 mm çapındaki bir pinyon dişlideki teğetsel kuvveti (Ft) Newton cinsinden hesaplayınız:',
        calcPEn: 'Calculate tangential force Ft in Newtons for torque T = 300 Nm and diameter d = 150 mm:',
        tVal: 4000, tol: 20, u: 'N', fHint: 'Ft = 2000 * 300 / 150 = 600,000 / 150',
        calcExpTr: 'Doğru! Ft = 600,000 / 150 = 4000 N (4 kN).', calcExpEn: 'Correct! Ft = 2000 * 300 / 150 = 4000 N.' },
      { num: 49, slug: 'radial-and-axial-gear-forces-draw', std: 'ISO 6336', cat: 'Dişliler', diff: 'medium', pType: 'drawing',
        tTr: '49. Kavrama Açısı & Radyal Kuvvet (Fr) Yönü', tEn: '49. Pressure Angle & Radial Force Direction',
        cTr: 'Kavrama açısı α=20° nedeniyle diş temasında pinyonu eksenden dışarı iten radyal kuvvet Fr = Ft * tan(α) doğar.',
        cEn: 'Pressure angle α=20° generates radial separating force Fr = Ft * tan(α) pushing gears apart.',
        f: 'F_r = F_t \\cdot \\tan(\\alpha)',
        dPromptTr: 'Döndüren pinyon dişli çarkın temas noktasında oluşan radyal kuvvet (Fr) pinyon milini hangi yöne doğru zorlar?',
        dPromptEn: 'In external spur gearing, what direction does the radial separating force Fr push the pinion center?',
        vOpts: [
          { id: 'g1', labelTr: 'Dişli merkezini diğer dişliden uzağa (Dışa / İtme yönü)', labelEn: 'Away from mating gear (Separating force)', direction: 'up', isCorrect: true },
          { id: 'g2', labelTr: 'Dişlileri birbirinin içine doğru çeker', labelEn: 'Pulls gears into each other', direction: 'down', isCorrect: false },
        ],
        expTr: 'Doğru! Dış dişlilerde evolvent kavrama dişli millerini birbirinden uzağa iten radyal kuvvet üretir.',
        expEn: 'Correct! Involute contact generates a radial separating force pushing centers apart.' },
      { num: 50, slug: 'tooth-root-bending-stress-iso6336', std: 'ISO 6336-3', cat: 'Dişliler', diff: 'hard', pType: 'visual',
        tTr: '50. ISO 6336-3 Diş Dibi Eğilme Gerilmesi (σF)', tEn: '50. ISO 6336-3 Tooth Root Bending Stress (σF)',
        cTr: 'Diş dibi kırılması ani ve felaket getiren bir yorulma hasarıdır. Diş dibi gerilmesi Lewis form faktörü YF ve gerilme düzeltme faktörü YS ile hesaplanır.',
        cEn: 'Root fillet stress σF is calculated via ISO 6336-3 incorporating form factor YF and notch stress correction YS.',
        f: '\\sigma_F = \\frac{F_t}{b \\cdot m} \\cdot Y_F \\cdot Y_S \\cdot Y_\\beta \\cdot K_A \\cdot K_v \\cdot K_{F\\beta} \\le \\sigma_{FP}',
        visPTr: 'ISO 6336-3 analizinde diş dibi eğilme kırılmasını başlatan kritik çentik gerilmesi nerede oluşur?',
        visPEn: 'In ISO 6336-3 root stress analysis, where is peak tensile bending notch stress located?',
        visCards: [
          { id: 'c1', titleTr: 'Diş Dibi Geçiş Radyusu (Fillet Radius Çentik Bölgesi)', titleEn: 'Tooth Root Fillet Transition', descTr: '30° teğet noktasında maksimum çekme gerilmesi yığılması ve yorulma çatlağı başlangıcı', descEn: '30° tangent root fillet where cyclic tensile stresses initiate fatigue cracks', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'Dişin Tam Tepe Düzlüğü', titleEn: 'Tooth Top Land', descTr: 'Eğilme momenti sıfırdır', descEn: 'Zero bending moment region', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Diş dibi kavisi en yüksek çekme çentik gerilmesinin ve yorulma kırılmasının başladığı yerdir.',
        expEn: 'Correct! Root fillet notch concentrates cyclic tension, triggering fatigue fractures.' },
      { num: 51, slug: 'hertz-contact-stress-iso6336', std: 'ISO 6336-2', cat: 'Dişliler', diff: 'hard', pType: 'calculation',
        tTr: '51. ISO 6336-2 Hertz Temas Basıncı (σH) & Pitting', tEn: '51. ISO 6336-2 Hertzian Contact Stress (σH)',
        cTr: 'Diş yüzeyi çukurlaşması (pitting) temas basıncına bağlıdır: σH = ZH * ZE * Zε * sqrt(Ft / (d1*b) * (u+1)/u) <= σHP.',
        cEn: 'Flank pitting resistance is verified against Hertz contact pressure σH ≤ σHP per ISO 6336-2.',
        f: '\\sigma_H = Z_H \\cdot Z_E \\cdot Z_\\varepsilon \\cdot \\sqrt{\\frac{F_t}{d_1 \\cdot b} \\cdot \\frac{u + 1}{u}}',
        calcPTr: 'ZH*ZE*Zε faktörler çarpımı 500 MPa^(1/2) ve karekök içi terim 4 N/mm² ise temas gerilmesini (σH) MPa cinsinden hesaplayınız:',
        calcPEn: 'Calculate Hertz stress σH in MPa for factor product 500 and sqrt term = 2 (sqrt(4)=2):',
        tVal: 1000, tol: 20, u: 'MPa', fHint: 'σH = 500 * sqrt(4) = 500 * 2',
        calcExpTr: 'Doğru! σH = 500 * 2 = 1000 MPa.', calcExpEn: 'Correct! σH = 500 * 2 = 1000 MPa.' },
      { num: 52, slug: 'helical-gear-axial-thrust', std: 'DIN 3960', cat: 'Dişliler', diff: 'medium', pType: 'quiz',
        tTr: '52. Helis Dişlilerde Eksenel İtme Kuvveti (Fa) ve β Açısı', tEn: '52. Helical Gear Axial Thrust (Fa) & Helix Angle (β)',
        cTr: 'Helis dişlilerde helis açısı β (genellikle 10°-25°) sayesinde kavrama oranı artar ve sessiz çalışma sağlanır ancak mile eksenel itme kuvveti Fa = Ft * tan(β) yüklenir.',
        cEn: 'Helical gears provide smooth multi-tooth overlap but induce axial thrust Fa = Ft * tan(β) requiring thrust bearings.',
        f: 'F_a = F_t \\cdot \\tan(\\beta), \\quad F_n = \\frac{F_t}{\\cos(\\alpha_n) \\cos(\\beta)}',
        qTr: 'Helis dişlilerde ortaya çıkan eksenel itme kuvvetini sıfırlamak ve rulmanları rahatlatmak için hangi dişli tipi kullanılır?',
        qEn: 'Which gear type eliminates axial thrust while retaining helical smoothness?',
        oTr: ['Çavuş Dişli (Çift Helis / Herringbone / Double Helical)', 'Düz Dişli', 'Sonsuz Vida', 'Zincir Dişli'],
        oEn: ['Herringbone / Double Helical Gear', 'Spur Gear', 'Worm Gear', 'Sprocket'],
        cIdx: 0, expTr: 'Doğru! Çavuş dişliler zıt yönlü iki helisi birleştirerek eksenel kuvvetleri gövde içinde sıfırlar.',
        expEn: 'Correct! Double helical/herringbone gears cancel opposing axial thrust forces internally.' },
      { num: 53, slug: 'bevel-gear-cone-pitch-angle', std: 'ISO 23509', cat: 'Dişliler', diff: 'medium', pType: 'calculation',
        tTr: '53. Koni Dişliler (Bevel Gears) & Eksen Açısı', tEn: '53. Bevel Gear Pitch Cone Angle (δ)',
        cTr: '90° dik eksenli koni dişlilerde pinyon taksimat konisi açısı tan(δ1) = z1 / z2 = 1 / i ile hesaplanır.',
        cEn: 'For 90° shaft angle bevel gears, pinion pitch cone angle is tan(δ1) = z1 / z2 = 1 / i.',
        f: '\\tan(\\delta_1) = \\frac{z_1}{z_2} = \\frac{1}{i}, \\quad \\delta_1 + \\delta_2 = 90^\\circ',
        calcPTr: 'z1 = 20 ve z2 = 20 olan 1:1 koni dişli çiftinde pinyon koni açısını (δ1) derece cinsinden bulunuz:',
        calcPEn: 'Find pinion pitch cone angle δ1 in degrees for 1:1 ratio bevel gears (z1=20, z2=20):',
        tVal: 45, tol: 0.1, u: 'derece', fHint: 'tan(δ1) = 20 / 20 = 1 => δ1 = 45°',
        calcExpTr: 'Doğru! tan(δ1) = 1 olduğundan δ1 = 45° dir.', calcExpEn: 'Correct! tan(δ1) = 1 gives δ1 = 45°.' },
      { num: 54, slug: 'worm-gear-self-locking-condition', std: 'DIN 3975 / DIN 3996', cat: 'Dişliler', diff: 'hard', pType: 'quiz',
        tTr: '54. Sonsuz Vida Mekanizması & Otokontrol (Self-Locking)', tEn: '54. Worm Gear Drives & Self-Locking Condition',
        cTr: 'Sonsuz vida adım açısı γ sürtünme açısından küçük olduğunda (γ < ρ\' = arctan(μ\')) mekanizma çıkış milinden geriye döndürülemez (otokontrol / kendiliğinden frenleme).',
        cEn: 'A worm drive is self-locking when lead angle γ is less than effective friction angle ρ\' (γ < arctan(μ\')).',
        f: '\\gamma < \\rho\' = \\arctan\\left(\\frac{\\mu}{\\cos(\\alpha_n)}\\right) \\implies \\eta_{\\text{back}} \\le 0',
        qTr: 'Asansör ve vinç redüktörlerinde güvenlik amacıyla sonsuz vida mekanizmasının otokontrollü (self-locking) olması ne sağlar?',
        qEn: 'In cranes and hoists, what safety advantage does a self-locking worm gear provide?',
        oTr: ['Motor kapansa bile yükün kendi ağırlığıyla geriye doğru düşmesini engeller', 'Verimi %100 yapar', 'Yağ gereksinimini kaldırır', 'Sesi artırır'],
        oEn: ['Prevents suspended load from backdriving and falling upon motor power loss', '100% efficiency', 'No oil needed', 'Increases noise'],
        cIdx: 0, expTr: 'Doğru! Otokontrol statik sürtünmeyle mekanizmayı kilitleyerek yükün düşmesini engeller.',
        expEn: 'Correct! Friction locks back-driving, preventing suspended loads from dropping.' },
      { num: 55, slug: 'planetary-willis-equation', std: 'Planetary Gearing', cat: 'Dişliler', diff: 'hard', pType: 'calculation',
        tTr: '55. Planet Dişli Mekanizmaları & Willis Formülü', tEn: '55. Epicyclic Planetary Gearing & Willis Equation',
        cTr: 'Güneş (sun / s), planet (planet / p), çember (ring / r) ve taşıyıcı koldan (carrier / c) oluşan sistemde çember sabitken çevrim oranı i = 1 + (zr / zs) olur.',
        cEn: 'For a planetary gearset with fixed ring gear, transmission ratio is i_sc = 1 + (zr / zs).',
        f: 'i = 1 + \\frac{z_{\\text{ring}}}{z_{\\text{sun}}}',
        calcPTr: 'Güneş dişli zs = 20, sabit çember dişli zr = 80 olan bir planet mekanizmada güneşten kola çevrim oranını (i) hesaplayınız:',
        calcPEn: 'Calculate gear ratio i from sun to carrier for zs = 20 and fixed ring zr = 80:',
        tVal: 5.0, tol: 0.05, u: '', fHint: 'i = 1 + (80 / 20) = 1 + 4',
        calcExpTr: 'Doğru! i = 1 + (80 / 20) = 5.0.', calcExpEn: 'Correct! i = 1 + (80 / 20) = 5.0.' },
      { num: 56, slug: 'gear-scuffing-flash-temperature', std: 'ISO 6336-20 / Blok', cat: 'Dişliler', diff: 'hard', pType: 'visual',
        tTr: '56. Dişli Sıvanması (Scuffing / Galling) & Blok Flaş Sıcaklığı', tEn: '56. Gear Scuffing & Blok Flash Temperature',
        cTr: 'Yüksek hız ve temas basıncında yağ filmi ani flaş sıcaklığı (θ_flash > 180-250°C) ile yanarak buharlaşır ve diş yüzeyleri birbirine anlık kaynak olup sıvanır.',
        cEn: 'Scuffing occurs when local contact flash temperature θ_flash exceeds lubricant limit, welding asperities.',
        f: '\\theta_B = \\theta_M + \\Delta \\theta_{\\text{flash}} \\le \\theta_{S,\\text{crit}}',
        visPTr: 'Aşırı temas basıncı ve kayma hızında yağ filminin yırtılmasıyla diş yüzeylerinde meydana gelen yapışma ve sıyrılma hasarı hangisidir?',
        visPEn: 'Which catastrophic adhesive wear pattern results from hydrodynamic oil film breakdown under high sliding speeds?',
        visCards: [
          { id: 'c1', titleTr: 'Sıvanma Hasarı (Scuffing / Scoring / Galling)', titleEn: 'Gear Scuffing / Scoring', descTr: 'Evolvent kayma yönünde metalik erime, yapışma ve derin yırtılma çizgileri', descEn: 'Severe adhesive micro-welding and torn radial score marks along sliding paths', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'Hafif Parlama (Polishing)', titleEn: 'Mild Flank Polishing', descTr: 'Kontrollü düzgün alıştırma aşınması', descEn: 'Uniform smooth run-in surface', diagramSvgType: 'i_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Sıvanma (scuffing) yağ filminin termal çöküşüyle metalik kaynaşmasıdır.',
        expEn: 'Correct! Scuffing is adhesive welding triggered by flash-temperature lubricant collapse.' },
      { num: 57, slug: 'profile-shift-undercutting-limit', std: 'DIN 3960 / ISO 21771', cat: 'Dişliler', diff: 'hard', pType: 'quiz',
        tTr: '57. Profil Kaydırma (x) ve Alttan Kesilme (Undercut) Sınırı', tEn: '57. Profile Shift Coefficient (x) & Undercut Limit',
        cTr: 'Standart α=20° dişlilerde diş sayısı z < 17 olduğunda azdırma çakısı diş dibini oyarak (undercut) zayıflatır. Bunu önlemek için pozitif profil kaydırma (x > 0) verilir.',
        cEn: 'For tooth counts z < 17, hobbing tools undercut root fillets. Positive profile shift (x > 0) prevents undercutting.',
        f: 'z_{\\min} = \\frac{2}{\\sin^2(20^\\circ)} \\approx 17.1 \\implies x_{\\min} = \\frac{17 - z}{17}',
        qTr: 'z = 12 dişli bir pinyonda diş dibinin oyulup (undercut) zayıflamasını engellemek için ne yapılmalıdır?',
        qEn: 'To prevent tooth root undercutting on a small z = 12 pinion, what design modification is required?',
        oTr: ['Pozitif profil kaydırma (x > 0) uygulanmalıdır', 'Modül sıfırlanmalıdır', 'Diş sayısı 6\'ya düşürülmelidir', 'Kavrama açısı 5° yapılmalıdır'],
        oEn: ['Apply positive profile shift (x > 0)', 'Zero the module', 'Reduce tooth count to 6', 'Set pressure angle to 5°'],
        cIdx: 0, expTr: 'Doğru! Pozitif profil kaydırma x=(17-12)/17 ≈ +0.29 verilerek diş dibi kalınlaştırılır.',
        expEn: 'Correct! Positive profile shift thickens root fillet and eliminates tool interference.' },
      { num: 58, slug: 'gear-efficiency-mesh-loss-calc', std: 'Niemann / ISO 14179', cat: 'Dişliler', diff: 'medium', pType: 'calculation',
        tTr: '58. Dişli Kavrama Sürtünme Kaybı (Pvz) & Verim Hesabı', tEn: '58. Mesh Power Loss (Pvz) & Stage Efficiency',
        cTr: 'Bir helis dişli kademesinde kavrama verimi η ≈ 1 - μm * Hv formülüyle hesaplanır (yaklaşık η = %98.5 - %99.0).',
        cEn: 'Gear mesh efficiency is η ≈ 1 - μm * Hv (typically 98.5% to 99.0% per precision stage).',
        f: 'P_{\\text{loss}} = P_{\\text{in}} \\cdot (1 - \\eta)',
        calcPTr: 'P_in = 50 kW giriş gücü ve kademe verimi η = 0.98 (%98) olan bir redüktörde ısıya dönüşen sürtünme kaybı gücünü (kW) hesaplayınız:',
        calcPEn: 'Calculate mesh heat loss in kW for input power Pin = 50 kW and efficiency η = 0.98:',
        tVal: 1.0, tol: 0.05, u: 'kW', fHint: 'P_loss = 50 * (1 - 0.98) = 50 * 0.02',
        calcExpTr: 'Doğru! 50 kW * 0.02 = 1.0 kW ısı enerjisine dönüşür.', calcExpEn: 'Correct! 50 * 0.02 = 1.0 kW dissipated as heat.' },
      { num: 59, slug: 'gear-contact-ratio-vectors', std: 'ISO 6336', cat: 'Dişliler', diff: 'hard', pType: 'drawing',
        tTr: '59. Kavrama Çizgisi ve Kavrama Oranı (εα)', tEn: '59. Line of Action & Transverse Contact Ratio (εα)',
        cTr: 'Evolvent dişlilerde kuvvet iletimi daima ortak kavrama çizgisi (line of action) boyunca gerçekleşir. εα ≥ 1.2 şartı kesintisiz yük aktarımı sağlar.',
        cEn: 'Involute force transmission acts along the line of action inclined at angle α. Contact ratio εα ≥ 1.2 ensures continuous tooth sharing.',
        f: '\\varepsilon_\\alpha = \\frac{g_\\alpha}{p_b} \\ge 1.2',
        dPromptTr: 'Evolvent dişli temasında diş yüzeyine uygulanan toplam normal kuvvet (Fn) vektörü hangi çizgi üzerinde uzanır?',
        dPromptEn: 'Along which geometric path does the resultant normal tooth contact force vector Fn act?',
        vOpts: [
          { id: 'n1', labelTr: '20° kavrama açılı temas çizgisi (Line of Action) boyunca', labelEn: 'Along the 20° line of action tangent to base circles', direction: 'right', isCorrect: true },
          { id: 'n2', labelTr: 'Mil eksenine tam 90° dik eksende', labelEn: 'Perpendicular to shaft axis', direction: 'up', isCorrect: false },
        ],
        expTr: 'Doğru! Evolvent mekanizmalarında normal kuvvet daima temel dairelere teğet kavrama çizgisi üzerindedir.',
        expEn: 'Correct! Involute normal force travels strictly along the line of action tangent to base circles.' },
      { num: 60, slug: 'boss-iso6336-heavy-gearbox-validation', std: 'ISO 6336 Tam Sertifikasyon', cat: 'Dişliler', diff: 'hard', pType: 'boss', isBoss: true,
        tTr: '60. 👑 BOSS SINAVI: 500 kW Ağır Sanayi Redüktörü ISO 6336 Doğrulaması', tEn: '60. 👑 BOSS TEST: 500 kW Heavy Industrial Gearbox Certification',
        cTr: '500 kW çimento değirmeni redüktöründe 18CrNiMo7-6 semente çeliği helis dişliler için: 1) Diş dibi emniyeti SF ≥ 1.4, 2) Yüzey ezilme/pitting emniyeti SH ≥ 1.3 ve 3) Sıvanma güvenliği SS ≥ 2.0 aynı anda kanıtlanmalıdır.',
        cEn: 'Comprehensive ISO 6336 certification verifying tooth root safety SF ≥ 1.4, pitting safety SH ≥ 1.3, and scuffing safety SS ≥ 2.0.',
        f: 'S_F = \\frac{\\sigma_{FE} \\cdot Y_{ST}}{\\sigma_F} \\ge 1.4, \\quad S_H = \\frac{\\sigma_{H,\\lim} \\cdot Z_N}{\\sigma_H} \\ge 1.3, \\quad S_S \\ge 2.0',
        qTr: 'ISO 6336 analizinde diş genişliği boyunca yükün bir uca yığılmasını (K_Hβ yük dağılım faktörünü) azaltıp güvenliği artırmak için dişliye ne tür bir modifikasyon yapılır?',
        qEn: 'To mitigate face load maldistribution (factor KHβ) and uniformize contact stress across the tooth width, what micro-geometry correction is applied?',
        oTr: ['Diş boyuna bombe (crowning / lead crowning) ve uç rahatlatması (tip relief)', 'Dişleri tamamen düzeltmek', 'Sertliği düşürmek', 'Modülü küçültmek'],
        oEn: ['Lead crowning / longitudinal barrel modification and tip relief', 'Flat teeth', 'Lower hardness', 'Reduce module'],
        cIdx: 0, expTr: 'Tebrikler Başmühendis! Bombeli diş modifikasyonu mil esnemelerini kompanse ederek diş boyunca kusursuz yük dağılımı sağlar!',
        expEn: 'Congratulations Master Engineer! Lead crowning compensates for shaft deflections, ensuring even contact load distribution!' }
    ]
  },

  // ─── UNIT 5: MİLLER, KAMALAR & DIN 743 (61-75) ───
  {
    num: 5, id: 'unit-5',
    titleTr: 'Ünite 5: Miller, Kamalar & DIN 743',
    titleEn: 'Unit 5: Shafts, Keys & DIN 743',
    descTr: 'Burulma ve eğilme gerilmeleri, DIN 6885 paralel kamalar, kritik dönme hızı ve DIN 743 yorulma güvenliği.',
    descEn: 'Torsion-bending combined stress, DIN 6885 keys, whirling resonance, and DIN 743 fatigue proof.',
    gradient: 'from-rose-600 via-red-600 to-amber-600', difficulty: 'hard', accentColor: '#f43f5e',
    lessons: [
      { num: 61, slug: 'torsional-shear-stress-calc', std: 'Mukavemet', cat: 'Miller', diff: 'easy', pType: 'quiz',
        tTr: '61. Mil Burulma Kayma Gerilmesi (τt) ve Wp Hesabı', tEn: '61. Torsional Shear Stress (τt) & Polar Modulus (Wp)',
        cTr: 'Dolu dairesel kesitli milin kutupsal mukavemet momenti Wp = (π * d³) / 16 dır. Burulma gerilmesi τt = T / Wp formülüyle hesaplanır.',
        cEn: 'For solid round shafts, polar section modulus is Wp = (π * d³) / 16. Shear stress is τt = T / Wp.',
        f: 'W_p = \\frac{\\pi \\cdot d^3}{16} \\approx 0.2 \\cdot d^3, \\quad \\tau_t = \\frac{T}{W_p}',
        qTr: 'Mil çapı 2 katına çıkarılırsa burulma dayanım momenti (Wp) kaç katına çıkar?',
        qEn: 'If shaft diameter is doubled, by what factor does its torsional section modulus (Wp) increase?',
        oTr: ['8 katına (2³ = 8)', '2 katına', '4 katına', '16 katına'],
        oEn: ['8 times (2³ = 8)', '2 times', '4 times', '16 times'],
        cIdx: 0, expTr: 'Doğru! Wp çapın küpüyle (d³) orantılı olduğundan 2³ = 8 katına çıkar.',
        expEn: 'Correct! Polar modulus scales with d³, so 2³ = 8x.' },
      { num: 62, slug: 'shaft-diameter-torsion-calculation', std: 'DIN 743', cat: 'Miller', diff: 'medium', pType: 'calculation',
        tTr: '62. Saf Burulmada Minimum Mil Çapı Hesabı', tEn: '62. Minimum Shaft Sizing in Pure Torsion',
        cTr: 'Emniyetli kayma gerilmesi τ_allow = 50 MPa olan bir milde T = 100,000 Nmm (100 Nm) burulma momenti için Wp = T / τ = 2000 mm³ gerekir.',
        cEn: 'Required polar modulus is Wp = T / τ_allow. Diameter is derived via d = (16 * T / (π * τ_allow))^(1/3).',
        f: 'd = \\sqrt[3]{\\frac{16 \\cdot T}{\\pi \\cdot \\tau_{\\text{allow}}}}',
        calcPTr: 'Wp = 0.2 * d³ formülünde gereken Wp = 2000 mm³ ise mil çapının küpünü (d³ = 2000 / 0.2) hesaplayınız:',
        calcPEn: 'If required Wp = 2000 mm³ and Wp = 0.2 * d³, calculate d³ in mm³:',
        tVal: 10000, tol: 50, u: 'mm³', fHint: 'd³ = 2000 / 0.2 = 10,000',
        calcExpTr: 'Doğru! d³ = 10,000 mm³ (buradan d ≈ 21.5 mm => standart 25 mm mil seçilir).',
        calcExpEn: 'Correct! d³ = 10,000 mm³.' },
      { num: 63, slug: 'din6885-parallel-key-sizing', std: 'DIN 6885-1', cat: 'Kamalar', diff: 'medium', pType: 'calculation',
        tTr: '63. DIN 6885-1 Paralel Düz Kama Boyu (l) Hesabı', tEn: '63. DIN 6885-1 Feather Key Length Sizing',
        cTr: 'Kama yüzey ezilme basıncı p = 2000 * T / (d * k * l_eff) <= p_allow formülüyle kontrol edilir (k = göbek temas yüksekliği ≈ h/2).',
        cEn: 'Key flank contact pressure is p = 2000 * T / (d * k * l_eff) ≤ p_allow per DIN 6885.',
        f: 'p = \\frac{2000 \\cdot T}{d \\cdot (h - t_1) \\cdot l_{\\text{eff}}} \\le p_{\\text{allow}}',
        calcPTr: 'T = 200 Nm, mil d = 40 mm, temas yüksekliği k = 4 mm ve p_allow = 100 MPa için gereken minimum efektif kama boyunu (l_eff) mm cinsinden hesaplayınız:',
        calcPEn: 'Calculate minimum effective key length l_eff in mm for T=200 Nm, d=40 mm, k=4 mm, p_allow=100 MPa:',
        tVal: 25, tol: 0.5, u: 'mm', fHint: 'l_eff = 2000 * 200 / (40 * 4 * 100) = 400,000 / 16,000',
        calcExpTr: 'Doğru! l_eff = 400,000 / 16,000 = 25 mm.', calcExpEn: 'Correct! l_eff = 400,000 / 16,000 = 25 mm.' },
      { num: 64, slug: 'din6885-key-failure-visual', std: 'DIN 6885', cat: 'Kamalar', diff: 'medium', pType: 'visual',
        tTr: '64. Kama Hasar Modları: Yüzey Ezilmesi vs Kesilme', tEn: '64. Key Failure Modes: Surface Crushing vs Shear',
        cTr: 'Kamalarda en yaygın hasar dinamik tork darbeleri altında kama yan yüzeylerinin ve göbek kama kanalının ezilmesidir (p > p_allow).',
        cEn: 'Most frequent feather key failure is plastic flank brinelling and socket wall deformation under cyclic torque reversals.',
        f: 'p_{\\text{flank}} \\le p_{\\text{allow}} \\approx 100 - 150 \\text{ MPa (Çelik Göbek)}',
        visPTr: 'Aşırı tork altında kamanın yan yüzeyinde meydana gelen kalıcı plastik ezilme hasarı hangisidir?',
        visPEn: 'Which failure mode depicts flank surface brinelling crushing along keyway contact walls?',
        visCards: [
          { id: 'c1', titleTr: 'Kama Yan Yüzey Ezilmesi (Flank Crushing)', titleEn: 'Keyway Flank Plastic Indentation', descTr: 'Kama ve kanal yan temas yüzeyinde kalıcı plastik çökme ve boşluk oluşması', descEn: 'Permanent localized plastic indentation widening the keyway slot', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'Temiz Hatasız Kama', titleEn: 'Pristine Fitted Key', descTr: 'Hasarsız montaj', descEn: 'Undamaged keyway fit', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Yüzey ezilmesi kamanın boşluk yapmasına ve dinamik darbelerle kırılmasına yol açar.',
        expEn: 'Correct! Flank crushing introduces backlash, leading to catastrophic impact shearing.' },
      { num: 65, slug: 'von-mises-equivalent-shaft-stress', std: 'DIN 743-2', cat: 'Miller', diff: 'hard', pType: 'calculation',
        tTr: '65. Von Mises Eşdeğer Mil Gerilmesi (σv) Hesabı', tEn: '65. Von Mises Equivalent Shaft Stress (σv)',
        cTr: 'Eğilme gerilmesi σb ve burulma gerilmesi τt aynı anda etkidiğinde von Mises eşdeğer gerilmesi σv = sqrt(σb² + 3 * τt²) formülüyle hesaplanır.',
        cEn: 'Under combined bending and torsion, von Mises equivalent stress is σv = sqrt(σb² + 3*τt²).',
        f: '\\sigma_v = \\sqrt{\\sigma_b^2 + 3 \\cdot \\tau_t^2}',
        calcPTr: 'σb = 80 MPa eğilme ve τt = 34.64 MPa burulma (3 * τt² = 3 * 1200 = 3600) altındaki milin von Mises gerilmesini (σv) MPa cinsinden hesaplayınız:',
        calcPEn: 'Calculate von Mises stress σv in MPa for σb = 80 MPa and 3*τt² = 3600 (σb² = 6400):',
        tVal: 100, tol: 1, u: 'MPa', fHint: 'σv = sqrt(6400 + 3600) = sqrt(10000)',
        calcExpTr: 'Doğru! σv = sqrt(6400 + 3600) = sqrt(10,000) = 100 MPa.', calcExpEn: 'Correct! σv = sqrt(10000) = 100 MPa.' },
      { num: 66, slug: 'shaft-shoulder-fillet-notch-factor', std: 'DIN 743-2', cat: 'Miller', diff: 'hard', pType: 'visual',
        tTr: '66. Mil Faturalarında Kavis Radyusu (r) ve Çentik Faktörü (αk)', tEn: '66. Shaft Shoulder Fillet Radius & Notch Factor (αk)',
        cTr: 'Mil kademe geçişlerinde (fatura) keskin köşe (r ≈ 0) bırakılması gerilmeyi 3-5 katına fırlatır. Kavis radyusu r büyütüldükçe çentik faktörü hızla düşer.',
        cEn: 'Sharp shoulder steps cause severe notch stress concentrations (αk > 3.0). Generous fillet radii drastically reduce fatigue risk.',
        f: '\\alpha_k = f\\left( \\frac{D}{d}, \\frac{r}{d} \\right) \\implies r \\ge 0.1 \\cdot d',
        visPTr: 'Millerde yorulma kırılmalarının en sık başladığı kademe geometrisi hangisidir?',
        visPEn: 'Where do the majority of rotational shaft fatigue fractures initiate?',
        visCards: [
          { id: 'c1', titleTr: 'Fatura Kökündeki Keskin Köşe (Fillet Transition)', titleEn: 'Sharp Step Shoulder Notch', descTr: 'Çentik faktörünün tepe yaptığı ve dönel eğilme çatlağının başladığı köşe', descEn: 'Point of peak geometrical stress concentration initiating rotating-bending fatigue cracks', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'Düz Pürüzsüz Mil Gövdesi', titleEn: 'Smooth Mid-Shaft Section', descTr: 'Düşük homojen gerilme alanı', descEn: 'Uniform stress field without notches', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Mil kademe faturaları yorulma çatlaklarının bir numaralı başlangıç merkezidir.',
        expEn: 'Correct! Shaft shoulder fillets are the most common initiation site for rotational fatigue failure.' },
      { num: 67, slug: 'critical-whirling-speed-shaft', std: 'Dunkerley / Rayleigh', cat: 'Miller', diff: 'hard', pType: 'calculation',
        tTr: '67. Millerin Kritik Dönme Hızı (n_crit) & Rezonans', tEn: '67. Critical Whirling Speed & Shaft Resonance',
        cTr: 'Mil statik sehimi f (mm) cinsinden bilindiğinde birinci kritik rezonans dönme hızı n_crit ≈ 946 / sqrt(f) (d/dak) formülüyle kestirilir.',
        cEn: 'First critical whirling speed is approximated from static deflection f (in mm) via n_crit ≈ 946 / sqrt(f) RPM.',
        f: 'n_{\\text{crit}} \\approx \\frac{946}{\\sqrt{f}} \\quad [\\text{RPM}]',
        calcPTr: 'Ağır rotor ağırlığı altında statik sehimi f = 0.04 mm olan bir milin kritik dönme hızını (n_crit) d/dak cinsinden hesaplayınız:',
        calcPEn: 'Calculate critical whirling speed n_crit in RPM for static deflection f = 0.04 mm (sqrt(0.04) = 0.2):',
        tVal: 4730, tol: 50, u: 'd/dak', fHint: 'n_crit = 946 / 0.2',
        calcExpTr: 'Doğru! n_crit = 946 / 0.2 = 4730 d/dak. Çalışma devri bunun %20 uzağında tutulmalıdır.',
        calcExpEn: 'Correct! n_crit = 946 / 0.2 = 4730 RPM.' },
      { num: 68, slug: 'interference-shrink-fit-shaft-hub', std: 'DIN 7190', cat: 'Miller', diff: 'hard', pType: 'quiz',
        tTr: '68. DIN 7190 Sıkı Pres & Sıcak Geçme (Shrink Fit)', tEn: '68. DIN 7190 Interference & Shrink Fits',
        cTr: 'Kamasız mil-göbek bağlantılarında göbek ısıtılıp mile geçirilir. Soğuduğunda oluşan temas basıncı pF sürtünmeyle tork aktarır ve kama kanalının yarattığı çentik etkisini ortadan kaldırır.',
        cEn: 'Shrink fits eliminate keyway stress concentrations by transmitting pure frictional torque via radial contact pressure pF.',
        f: 'T_{\\text{friction}} = p_F \\cdot \\pi \\cdot d \\cdot B \\cdot \\mu \\cdot \\frac{d}{2}',
        qTr: 'Kama kanalı yerine DIN 7190 sıkı geçme (pres/sıcak geçme) kullanılmasının yorulma dayanımı açısından en büyük faydası nedir?',
        qEn: 'What is the primary fatigue advantage of DIN 7190 shrink fits over traditional keyways?',
        oTr: ['Kama kanalının yarattığı yüksek gerilme yığılmasını ve çentik etkisini tamamen ortadan kaldırır', 'Mil ağırlığını yarıya indirir', 'Sıcaklığı sıfırlar', 'Milin eğrilmesini sağlar'],
        oEn: ['Eliminates high keyway stress concentration notches completely', 'Halves shaft weight', 'Zeros temperature', 'Allows shaft bowing'],
        cIdx: 0, expTr: 'Doğru! Kama kanalları mil yorulma dayanımını %40 düşürür; sıkı geçme bu zayıflığı yok eder.',
        expEn: 'Correct! Keyways impose severe notch factors (βk ≈ 2.0); interference fits retain full cross-section integrity.' },
      { num: 69, slug: 'torsion-shear-stress-distribution-draw', std: 'Mukavemet', cat: 'Miller', diff: 'medium', pType: 'drawing',
        tTr: '69. Dairesel Milde Kayma Gerilmesi Dağılımı Çizimi', tEn: '69. Circular Shaft Torsional Shear Stress Profile',
        cTr: 'Burulmaya çalışan dairesel bir milin merkezinde kayma gerilmesi sıfırdır (τ=0), en dış yüzey liflerinde ise maksimuma (τ_max) ulaşır.',
        cEn: 'Torsional shear stress varies linearly from zero at the center axis to maximum τ_max at the outer surface radius.',
        f: '\\tau(r) = \\frac{T \\cdot r}{I_p} \\implies \\tau(0) = 0, \\quad \\tau(R) = \\tau_{\\max}',
        dPromptTr: 'Burulan dolu bir mil kesitinde gerilmenin merkezden dış yüzeye doğru dağılım vektör doğrultusu nasıldır?',
        dPromptEn: 'How does torsional shear stress magnitude distribute from shaft center to outer perimeter?',
        vOpts: [
          { id: 'sh1', labelTr: 'Merkezde 0, dış yüzeyde maksimum (Doğrusal Artan)', labelEn: 'Zero at core, linearly increasing to maximum at surface', direction: 'up', isCorrect: true },
          { id: 'sh2', labelTr: 'Merkezde maksimum, dış yüzeyde sıfır', labelEn: 'Maximum at core, zero at surface', direction: 'down', isCorrect: false },
        ],
        expTr: 'Doğru! Kayma gerilmesi yarıçapla doğru orantılı olarak merkezde sıfır, dış kabukta maksimumdur.',
        expEn: 'Correct! Torsional shear scales linearly with radius, peaking at outer fibers.' },
      { num: 70, slug: 'hollow-shaft-weight-efficiency', std: 'Mukavemet', cat: 'Miller', diff: 'medium', pType: 'quiz',
        tTr: '70. İçi Boş Boru Millerin Ağırlık Verimliliği', tEn: '70. Hollow Shaft Weight Optimization',
        cTr: 'İçi boş millerde merkezdeki verimsiz malzeme çıkarıldığı için aynı burulma torkunu dolu mile göre yaklaşık %50-60 daha az ağırlıkla taşıyabilir.',
        cEn: 'Hollow shafts remove low-stressed core material, transmitting equal torque at 50-60% weight savings.',
        f: 'W_{p,\\text{hollow}} = \\frac{\\pi (D^4 - d^4)}{16 D}',
        qTr: 'Havacılık ve yarış araçlarının tahrik şaftlarında neden dolu çelik yerine içi boş tüp miller tercih edilir?',
        qEn: 'Why do aerospace and racing driveshafts utilize hollow tubes rather than solid bars?',
        oTr: ['Yüksek kutupsal atalet momentini minimum kütle ile sağlayarak devasa ağırlık tasarrufu sunduğu için', 'Üretimi daha ucuz olduğu için', 'Rulman istemediği için', 'Esnek olduğu için'],
        oEn: ['Maximizes polar section modulus per unit mass, drastically cutting rotational inertia and weight', 'Cheaper manufacturing', 'No bearings needed', 'Extreme flexibility'],
        cIdx: 0, expTr: 'Doğru! Dış çapa yerleştirilen malzeme hafiflikle birlikte maksimum rijitlik sağlar.',
        expEn: 'Correct! Placing mass far from neutral axis maximizes specific torsional stiffness.' },
      { num: 71, slug: 'spline-shaft-din5480-iso4156', std: 'DIN 5480 / ISO 4156', cat: 'Miller', diff: 'medium', pType: 'visual',
        tTr: '71. DIN 5480 Evolvent Frezeli Mil (Spline) Bağlantıları', tEn: '71. DIN 5480 Involute Splined Shafts',
        cTr: 'Tek kamaya göre frezeli miller torku 10-30 adet evolvent diş üzerinden eşit paylaşarak çok daha yüksek dinamik tork taşır ve merkezleme hassasiyeti sunar.',
        cEn: 'Involute splines (DIN 5480) distribute torque over numerous gear-like teeth, offering superior capacity and self-centering.',
        f: 'p_{\\text{spline}} = \\frac{2000 \\cdot T}{d_m \\cdot h \\cdot l \\cdot z \\cdot k_{\\phi}} \\le p_{\\text{allow}}',
        visPTr: 'Ağır vasıta diferansiyel ve şanzıman çıkışlarında kullanılan çok dişli evolvent mil profili hangisidir?',
        visPEn: 'Which heavy-duty shaft-hub connection utilizes multi-tooth involute profiles for maximum cyclic torque capacity?',
        visCards: [
          { id: 'v1', titleTr: 'DIN 5480 Evolvent Frezeli Mil (Involute Spline)', titleEn: 'Involute Splined Shaft', descTr: 'Çok sayıda evolvent diş ile homojen tork paylaşımı ve kendiliğinden merkezleme', descEn: 'Multi-tooth involute profile ensuring uniform load sharing and dynamic balance', diagramSvgType: 'i_beam_stress', isCorrect: true },
          { id: 'v2', titleTr: 'Tek Düz Kamalı Mil', titleEn: 'Single Keyed Shaft', descTr: 'Tek noktadan yük aktarır, asimetrik gerilme üretir', descEn: 'Single-point asymmetric load transfer', diagramSvgType: 'stress_notch', isCorrect: false },
        ],
        expTr: 'Doğru! DIN 5480 frezeli miller ağır sanayi ve otomotivde tork aktarımının altın standardıdır.',
        expEn: 'Correct! Involute splines deliver maximum torque density and structural balance.' },
      { num: 72, slug: 'polygonal-shaft-p3g-p4c', std: 'DIN 32711 / DIN 32712', cat: 'Miller', diff: 'medium', pType: 'quiz',
        tTr: '72. DIN 32711 Poligon Mil Bağlantıları (P3G / P4C)', tEn: '72. DIN 32711 Polygon Shaft Connections (P3G)',
        cTr: 'P3G üçgenimsi poligon miller hiçbir çentik ve köşe içermeyen sürekli kavisli profiliyle çentik faktörünü αk ≈ 1.0\'a indirerek kırılmaları önler.',
        cEn: 'Polygon profiles (P3G) eliminate notch corners entirely (αk ≈ 1.0), maximizing dynamic endurance.',
        f: '\\alpha_k(\\text{P3G}) \\approx 1.0 - 1.2 \\quad (\\text{Çentiksiz Kusursuz Geometri})',
        qTr: 'P3G poligon mil profilinin klasik kamalı millere göre en üstün mekanik avantajı nedir?',
        qEn: 'What is the decisive mechanical superiority of P3G polygon profiles over keyed connections?',
        oTr: ['Köşe ve çentik barındırmadığı için gerilme yığılmasını sıfırlayıp dinamik yorulma ömrünü maksimize eder', 'Kaynamayı önler', 'İç boşluk bırakmaz', 'Soğutma sağlar'],
        oEn: ['Smooth continuous curvature eliminates stress-concentrating notches, maximizing dynamic fatigue life', 'Prevents galling', 'Zero backlash', 'Provides cooling'],
        cIdx: 0, expTr: 'Doğru! Poligon profiller çentiksiz pürüzsüz kavisleriyle sonsuz yorulma ömrüne olanak tanır.',
        expEn: 'Correct! Notchless smooth geometry suppresses fatigue initiation sites.' },
      { num: 73, slug: 'bending-moment-shaft-equilibrium', std: 'Statik & Mukavemet', cat: 'Miller', diff: 'hard', pType: 'calculation',
        tTr: '73. İki Mesnetli Milde Eğilme Momenti (Mb) Hesabı', tEn: '73. Simply Supported Shaft Bending Moment (Mb)',
        cTr: 'L = 500 mm açıklıklı iki rulman mesneti ortasındaki kasnaktan F = 4000 N radyal kayış yükü geliyorsa ortadaki maksimum eğilme momenti Mb = F * L / 4 olur.',
        cEn: 'For centered transverse load F on span L, maximum bending moment is Mb = F * L / 4.',
        f: 'M_b = \\frac{F \\cdot L}{4}',
        calcPTr: 'F = 4000 N ve L = 500 mm (0.5 m) için maksimum eğilme momentini (Mb) Nm cinsinden hesaplayınız:',
        calcPEn: 'Calculate peak bending moment Mb in Nm for F = 4000 N and span L = 0.5 m:',
        tVal: 500, tol: 5, u: 'Nm', fHint: 'Mb = 4000 * 0.5 / 4',
        calcExpTr: 'Doğru! Mb = 4000 * 0.5 / 4 = 500 Nm (500,000 Nmm).', calcExpEn: 'Correct! Mb = 4000 * 0.5 / 4 = 500 Nm.' },
      { num: 74, slug: 'rotating-bending-fatigue-mechanism', std: 'Wöhler / DIN 50100', cat: 'Miller', diff: 'hard', pType: 'drawing',
        tTr: '74. Dönel Eğilmede Lif Gerilme Değişimi (Bası-Çekme)', tEn: '74. Rotating-Bending Cyclic Stress Reversal',
        cTr: 'Dönen bir milde üst yüzeydeki lif bası altındayken, 180° döndüğünde alt yüzeye inerek tam çekme gerilmesine maruz kalır (R = -1 tam değişken çevrim).',
        cEn: 'Rotating shafts subject material fibers to continuous alternating tension-compression cycles (stress ratio R = -1).',
        f: '\\sigma(t) = \\sigma_b \\cdot \\sin(\\omega t) \\implies R = \\frac{\\sigma_{\\min}}{\\sigma_{\\max}} = -1',
        dPromptTr: 'Dönen bir milin tepe noktasında oluşan bası gerilmesi lifi 180° dönüp en alt konuma ulaştığında hangi gerilme durumuna geçer?',
        dPromptEn: 'When a shaft rotates 180°, what stress state does a fiber at the top compressive position transition into?',
        vOpts: [
          { id: 'cy1', labelTr: 'Maksimum Çekme Gerilmesi (+σb)', labelEn: 'Peak Tensile Stress (+σb)', direction: 'up', isCorrect: true },
          { id: 'cy2', labelTr: 'Sıfır Gerilme', labelEn: 'Zero Stress', direction: 'left', isCorrect: false },
        ],
        expTr: 'Doğru! Her tam devirde her malzeme lifi +σb çekme ile -σb bası arasında yorulur.',
        expEn: 'Correct! Each revolution subjects fibers to fully reversed cyclic tension-compression.' },
      { num: 75, slug: 'boss-din743-stepped-shaft-proof', std: 'DIN 743 Tam Denetim', cat: 'Miller', diff: 'hard', pType: 'boss', isBoss: true,
        tTr: '75. 👑 BOSS SINAVI: DIN 743 Kademeli Transmisyon Mili Yorulma Doğrulaması', tEn: '75. 👑 BOSS TEST: DIN 743 Stepped Shaft Fatigue Safety Proof',
        cTr: 'Kombine dinamik dönel eğilme (Mb = 1200 Nm) ve statik burulma (Tt = 2500 Nm) altındaki 42CrMo4 kademeli mil için DIN 743 Blatt 1-4 standardına göre: 1) Statik güvenlik S_stat ≥ 1.5 ve 2) Dinamik sürekli yorulma güvenliği S_dyn ≥ 1.5 kanıtlanmalıdır.',
        cEn: 'Rigorous DIN 743 proof calculating notch sensitivity βk, size factor K3, surface roughness factor KF, and combined fatigue safety S_dyn ≥ 1.5.',
        f: 'S_{\\text{dyn}} = \\frac{1}{\\sqrt{\\left(\\frac{\\sigma_{ba}}{\\sigma_{bWK}}\\right)^2 + \\left(\\frac{\\tau_{ta}}{\\tau_{tWK}}\\right)^2}} \\ge 1.5',
        qTr: 'DIN 743 analizinde mil fatura kavis yarıçapı r büyütüldüğünde ve yüzey taşlanarak pürüzlülük Rz düşürüldüğünde dinamik yorulma güvenliği (S_dyn) nasıl değişir?',
        qEn: 'Under DIN 743, increasing the shoulder fillet radius r and improving surface finish (lower Rz) has what effect on fatigue safety S_dyn?',
        oTr: ['Çentik faktörü düşer, yüzey faktörü yükselir ve dinamik emniyet katsayısı (S_dyn) belirgin şekilde ARTAR', 'Emniyet katsayısı düşer', 'Mil esnemesi durur', 'Tork sıfırlanır'],
        oEn: ['Notch factor drops, surface factor improves, and fatigue safety S_dyn INCREASES significantly', 'Safety drops', 'Shaft stops flexing', 'Torque zeros'],
        cIdx: 0, expTr: 'Tebrikler Başmühendis! Geniş fatura kavisleri ve kaliteli taşlama DIN 743 yorulma güvenliğinin temel anahtarıdır!',
        expEn: 'Congratulations Master Engineer! Generous fillet radii and precision grinding unlock maximum DIN 743 fatigue safety!' }
    ]
  },

  // ─── UNIT 6: KİRİŞLER, SEHİM & İLERİ MUKAVEMET (76-90) ───
  {
    num: 6, id: 'unit-6',
    titleTr: 'Ünite 6: Kirişler, Sehim & İleri Mukavemet',
    titleEn: 'Unit 6: Beams, Deflection & Advanced Strength',
    descTr: 'Kesme-moment diyagramları, Jourawski kayması, Timoshenko kalın kirişler ve eğrilikli elemanlar.',
    descEn: 'Shear-moment diagrams, Jourawski shear flow, Timoshenko thick beams, and curved members.',
    gradient: 'from-emerald-500 to-teal-600', difficulty: 'hard', accentColor: '#10b981',
    lessons: [
      { num: 76, slug: 'shear-force-bending-moment-diagrams', std: 'Euler-Bernoulli', cat: 'Mukavemet', diff: 'medium', pType: 'quiz',
        tTr: '76. Kesme Kuvveti (V) ve Eğilme Momenti (M) Bağıntısı', tEn: '76. Shear Force (V) & Bending Moment (M) Relations',
        cTr: 'Diferansiyel kiriş dengesinde kesme kuvveti eğilme momentinin türevidir: V(x) = dM/dx. Kesme kuvvetinin sıfır olduğu (V=0) kesitte eğilme momenti MAKSİMUM veya MİNİMUM tepe değerine ulaşır.',
        cEn: 'Shear is the derivative of bending moment: V(x) = dM/dx. Peak bending moments occur strictly where shear force crosses zero (V=0).',
        f: 'V(x) = \\frac{dM(x)}{dx}, \\quad q(x) = -\\frac{dV(x)}{dx}',
        qTr: 'Bir kiriş boyunca kesme kuvvetinin sıfır (V = 0) olduğu noktada eğilme momenti ne durumdadır?',
        qEn: 'At the exact location along a beam where shear force crosses zero (V = 0), what is true of the bending moment?',
        oTr: ['Maksimum veya ekstremum tepe değerine ulaşır (dM/dx = 0)', 'Sıfırdır', 'Eksidir', 'Sonsuzdur'],
        oEn: ['Reaches a local maximum or extremum peak (dM/dx = 0)', 'Zero', 'Negative', 'Infinite'],
        cIdx: 0, expTr: 'Doğru! V = dM/dx = 0 türev kuralı gereği momentin tepe noktasını verir.',
        expEn: 'Correct! Calculus mandates that dM/dx = 0 identifies local extremum moments.' },
      { num: 77, slug: 'cantilever-beam-deflection-calculation', std: 'Mukavemet', cat: 'Mukavemet', diff: 'medium', pType: 'calculation',
        tTr: '77. Konsol Kiriş Uç Sehimi (w_max) Sayısal Hesabı', tEn: '77. Cantilever Beam Tip Deflection Calculation',
        cTr: 'L uzunluğundaki konsol kirişin ucuna uygulanan F noktasal yükü altında maksimum uç sehimi w = (F * L³) / (3 * E * I) formülüyle hesaplanır.',
        cEn: 'Tip deflection for an end-loaded cantilever is w_max = (F * L³) / (3 * E * I).',
        f: 'w_{\\max} = \\frac{F \\cdot L^3}{3 \\cdot E \\cdot I}',
        calcPTr: 'F = 3000 N, L = 1000 mm, E*I = 10¹² Nmm² olan konsol kirişin uç sehimini (w_max) mm cinsinden hesaplayınız:',
        calcPEn: 'Calculate tip deflection w_max in mm for F = 3000 N, L = 1000 mm, and E*I = 10¹² Nmm²:',
        tVal: 1.0, tol: 0.05, u: 'mm', fHint: 'w = 3000 * (1000)³ / (3 * 10^12) = 3 * 10^12 / 3 * 10^12',
        calcExpTr: 'Doğru! w = 3e12 / 3e12 = 1.0 mm.', calcExpEn: 'Correct! w = 1.0 mm.' },
      { num: 78, slug: 'simply-supported-udl-deflection', std: 'Mukavemet', cat: 'Mukavemet', diff: 'medium', pType: 'calculation',
        tTr: '78. Düzgün Yayılı Yüklü Kiriş Orta Sehimi Hesabı', tEn: '78. Simply Supported Beam Center Deflection (UDL)',
        cTr: 'q düzgün yayılı yük taşıyan basit mesnetli kirişte maksimum orta sehim w_max = (5 * q * L⁴) / (384 * E * I) formülüyle bulunur.',
        cEn: 'Midspan deflection for simply supported beam under uniform load q is w_max = (5 * q * L⁴) / (384 * E * I).',
        f: 'w_{\\max} = \\frac{5 \\cdot q \\cdot L^4}{384 \\cdot E \\cdot I}',
        calcPTr: 'Toplam yük Q = q*L = 3840 N, L = 1000 mm ve E*I = 10¹¹ Nmm² için w_max pay terimi (5 * 3840 * 10^9) / (384 * 10^11) sonucunu (mm) hesaplayınız:',
        calcPEn: 'Calculate center deflection w_max in mm: (5 * 3840 * 10^9) / (384 * 10^11):',
        tVal: 0.5, tol: 0.02, u: 'mm', fHint: '19,200 * 10^9 / 38,400 * 10^9 = 0.5',
        calcExpTr: 'Doğru! w_max = 0.5 mm.', calcExpEn: 'Correct! w_max = 0.5 mm.' },
      { num: 79, slug: 'jourawski-shear-stress-profile-visual', std: 'Jourawski Formülü', cat: 'Mukavemet', diff: 'hard', pType: 'visual',
        tTr: '79. Jourawski Enine Kayma Gerilmesi Dağılımı', tEn: '79. Jourawski Shear Stress Distribution',
        cTr: 'Kiriş kesitinde enine kayma gerilmesi τ(y) = (V * Q(y)) / (I * b(y)) dir. Dikdörtgen kesitte tarafsız eksende maksimuma (τ_max = 1.5 * V/A) ulaşır; üst ve alt dış yüzeylerde ise SIFIRDIR.',
        cEn: 'Jourawski shear stress peaks at the neutral axis (τ_max = 1.5 * V/A for rectangles) and drops to zero at top and bottom free surfaces.',
        f: '\\tau(y) = \\frac{V \\cdot Q(y)}{I \\cdot b(y)} \\implies \\tau_{\\max} = \\frac{3}{2} \\frac{V}{A} \\quad (\\text{Tarafsız Eksende})',
        visPTr: 'Eğilmeye maruz dikdörtgen bir kiriş kesitinde enine kayma gerilmesinin (τ) tepe noktası nerededir?',
        visPEn: 'In a rectangular cross-section under transverse shear, where does maximum shear stress occur?',
        visCards: [
          { id: 'c1', titleTr: 'Tarafsız Eksen (Merkez Hattı - Parabolik Tepe)', titleEn: 'Neutral Axis (Centroidal Line)', descTr: 'Kayma gerilmesi merkezde maksimum 1.5 * V/A değerine ulaşır, en dış liflerde sıfırdır', descEn: 'Parabolic shear stress distribution peaks at the neutral axis and drops to zero at surfaces', diagramSvgType: 'rect_beam_stress', isCorrect: true },
          { id: 'c2', titleTr: 'En Dış Üst Yüzey Lifleri', titleEn: 'Top Outer Surface', descTr: 'Kayma gerilmesi sıfırdır', descEn: 'Zero shear stress region', diagramSvgType: 'i_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Normal eğilme gerilmesi dış lifte maksimumken, kayma gerilmesi tam merkez tarafsız eksende maksimumdur.',
        expEn: 'Correct! Bending stress peaks at outer fibers, whereas shear stress peaks at the neutral axis.' },
      { num: 80, slug: 'timoshenko-thick-beam-theory', std: 'Timoshenko Beam', cat: 'Mukavemet', diff: 'hard', pType: 'quiz',
        tTr: '80. Timoshenko Kalın Kiriş Teorisi vs Euler-Bernoulli', tEn: '80. Timoshenko Thick Beam Theory',
        cTr: 'Euler-Bernoulli teorisi kayma deformasyonunu ihmal eder (L/h > 10 ince kirişler için geçerlidir). Kısa ve kalın kirişlerde (L/h < 5) kayma sehiminin de hesaba katıldığı Timoshenko teorisi zorunludur.',
        cEn: 'Euler-Bernoulli ignores shear deformation (valid for L/h > 10). Short thick beams (L/h < 5) require Timoshenko beam theory.',
        f: 'w_{\\text{total}} = w_{\\text{bending}} + w_{\\text{shear}} = \\frac{F L^3}{3 E I} + \\frac{F L}{\\kappa G A}',
        qTr: 'Açıklık/yükseklik oranı L/h = 3 olan çok kalın bir kirişin sehimi incelenirken Euler-Bernoulli yerine neden Timoshenko teorisi kullanılmalıdır?',
        qEn: 'Why must Timoshenko theory replace Euler-Bernoulli for stubby beams with L/h = 3?',
        oTr: ['Kalın kirişlerde kesme deformasyonunun (shear deformation) sehimdeki payı %20-30\'lara ulaşarak ihmal edilemez hale geldiği için', 'Timoshenko daha hafiftir', 'Formülü daha basittir', 'Sadece ahşapta kullanılır'],
        oEn: ['Transverse shear deformation accounts for 20-30% of total deflection and cannot be neglected', 'Timoshenko is lighter', 'Simpler formula', 'Wood only'],
        cIdx: 0, expTr: 'Doğru! Kalın kirişlerde enine kayma deformasyonu toplam sehimi ciddi oranda artırır.',
        expEn: 'Correct! Thick beam shear flexibility contributes significantly to overall deflection.' },
      { num: 81, slug: 'curved-beam-winkler-bach', std: 'Winkler-Bach Teorisi', cat: 'Mukavemet', diff: 'hard', pType: 'visual',
        tTr: '81. Winkler-Bach Eğrilikli Kiriş Teorisi & Vinç Kancaları', tEn: '81. Winkler-Bach Curved Beam Theory & Crane Hooks',
        cTr: 'Eğri eksenli kirişlerde (vinç kancaları, C-pres gövdeleri) tarafsız eksen eğrilik merkezine doğru kayar ve iç liflerdeki gerilme doğrusal değil hiperbolik olarak çok yüksek seviyeye fırlar.',
        cEn: 'In sharply curved beams (crane hooks), neutral axis shifts toward the center of curvature, concentrating hyperbolic tensile stress at the inner fiber.',
        f: '\\sigma_{\\text{inner}} = \\frac{M}{A \\cdot e} \\left( \\frac{y_i}{r_i} \\right), \\quad e = R - r_n',
        visPTr: 'Vinç kancasında eğrilik nedeniyle maksimum çekme gerilmesinin oluştuğu kritik bölge neresidir?',
        visPEn: 'Where does peak tensile stress concentrate in a loaded crane hook cross-section?',
        visCards: [
          { id: 'c1', titleTr: 'İç Kavis Lifleri (Inner Radius Flank)', titleEn: 'Inner Curvature Surface', descTr: 'Tarafsız eksen içe kaydığı için iç lifte hiperbolik aşırı gerilme yığılması oluşur', descEn: 'Hyperbolic stress spike due to neutral axis inward shift', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'c2', titleTr: 'Dış Sırt Kavis Lifleri', titleEn: 'Outer Back Surface', descTr: 'Bası gerilmesi daha düşüktür', descEn: 'Lower compressive stress region', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Winkler-Bach teorisine göre eğrilikli kancaların iç yüzeyi en yüksek çekme gerilmesini taşır.',
        expEn: 'Correct! Inward neutral axis shift amplifies tensile stresses on the inner radius.' },
      { num: 82, slug: 'castigliano-theorem-energy-deflection', std: 'Castigliano Teoremi', cat: 'Mukavemet', diff: 'hard', pType: 'calculation',
        tTr: '82. Castigliano Enerji Yöntemi ile Deplasman Hesabı', tEn: '82. Castigliano\'s Energy Theorem Displacement',
        cTr: 'Kirişin toplam elastik şekil değiştirme enerjisinin U uygulanan kuvvete F göre kısmi türevi, o kuvvetin doğrultusundaki yerdeğiştirmeyi verir: δ = ∂U / ∂F.',
        cEn: 'Deflection is the partial derivative of total strain energy U with respect to applied force F: δ = ∂U / ∂F.',
        f: '\\delta_i = \\frac{\\partial U}{\\partial F_i} = \\int_0^L \\frac{M(x)}{E I} \\frac{\\partial M(x)}{\\partial F_i} dx',
        calcPTr: 'U = (F² * L³) / (6 * E * I) enerji ifadesinde F = 1000 N, L³/(3*E*I) = 0.002 mm/N için δ = (F*L³)/(3*E*I) deplasmanını (mm) hesaplayınız:',
        calcPEn: 'Calculate deflection δ in mm for F = 1000 N and compliance term = 0.002 mm/N:',
        tVal: 2.0, tol: 0.05, u: 'mm', fHint: 'δ = 1000 * 0.002',
        calcExpTr: 'Doğru! δ = 1000 * 0.002 = 2.0 mm.', calcExpEn: 'Correct! δ = 2.0 mm.' },
      { num: 83, slug: 'shear-center-open-thin-walled-profiles', std: 'Kayma Merkezi', cat: 'Mukavemet', diff: 'hard', pType: 'drawing',
        tTr: '83. İnce Cidarlı Açık Profillerde Kayma Merkezi (Shear Center)', tEn: '83. Shear Center in Open Thin-Walled Sections',
        cTr: 'U-profil (UNP) veya C-profillerde düşey yük profilin ağırlık merkezinden uygulanırsa kiriş burulur! Burulmasız saf eğilme için yük kesitin dışındaki KAYMA MERKEZİNDEN (Shear Center) geçmelidir.',
        cEn: 'Applying loads through the centroid of C-channels causes twisting. Loads must pass through the external Shear Center to prevent torsion.',
        f: 'e = \\frac{b^2 \\cdot h^2 \\cdot t}{4 \\cdot I_x} \\quad (\\text{Gövdeden Dışarıdaki Kayma Merkezi Uzaklığı})',
        dPromptTr: 'U-profil (kanal kesit) bir kirişe burulma momenti oluşturmadan saf eğilme yaptırmak için yük hangi noktadan uygulanmalıdır?',
        dPromptEn: 'Where must transverse loads act on a channel section to cause pure bending without inducing torsion?',
        vOpts: [
          { id: 'sc1', labelTr: 'Profil gövdesinin dışındaki Kayma Merkezinden (Shear Center)', labelEn: 'Through the external Shear Center behind the web', direction: 'left', isCorrect: true },
          { id: 'sc2', labelTr: 'Ağırlık merkezinden (Centroid)', labelEn: 'Through centroid (causes severe twist)', direction: 'right', isCorrect: false },
        ],
        expTr: 'Doğru! U-profillerde kayma merkezi gövdenin arkasında kesit dışındadır.',
        expEn: 'Correct! Channel shear center lies outside the web; off-center loading prevents twisting.' },
      { num: 84, slug: 'composite-beam-transformed-section', std: 'Kompozit Kiriş', cat: 'Mukavemet', diff: 'medium', pType: 'quiz',
        tTr: '84. Kompozit Kirişler & Dönüştürülmüş Kesit Yöntemi (n = E1/E2)', tEn: '84. Transformed-Section Method (n = E1/E2)',
        cTr: 'Çelik ve alüminyumun birlikte çalıştığı kompozit kirişlerde elastisite modülü oranı n = E_çelik / E_alüminyum ≈ 210/70 = 3 alınarak çeliğin genişliği 3 katına dönüştürülüp tek homojen kesit gibi çözülür.',
        cEn: 'Transformed-section method scales component widths by modular ratio n = E1/E2 to model heterogeneous beams homogeneously.',
        f: 'n = \\frac{E_1}{E_2} \\approx 3.0, \\quad b_{\\text{transformed}} = n \\cdot b',
        qTr: 'E_çelik = 210 GPa ve E_alüminyum = 70 GPa olan kompozit bir kirişte çelik parça eşdeğer alüminyum kesite dönüştürülürken genişliği kaçla çarpılır?',
        qEn: 'In a steel-aluminum composite beam (Esteel = 210 GPa, Eal = 70 GPa), what modular factor n scales the steel width?',
        oTr: ['3 (210 / 70 = 3)', '1', '10', '0.33'],
        oEn: ['3 (210 / 70 = 3)', '1', '10', '0.33'],
        cIdx: 0, expTr: 'Doğru! n = 210 / 70 = 3 olduğundan çelik kesit 3 kat genişlikte alüminyum gibi modellenir.',
        expEn: 'Correct! Modular ratio n = 210/70 = 3 scales the stiffer material equivalent area.' },
      { num: 85, slug: 'unsymmetrical-bending-principal-axes', std: 'Asimetrik Eğilme', cat: 'Mukavemet', diff: 'hard', pType: 'quiz',
        tTr: '85. Asimetrik Eğilme & Asal Atalet Eksenleri', tEn: '85. Unsymmetrical Bending & Principal Axes',
        cTr: 'Eğer eğilme momenti asal atalet eksenlerinden birine paralel değilse (örn. L-köşebent profil), sehim yükün uygulandığı düzlemde değil iki eksenli bileşke doğrultusunda gerçekleşir.',
        cEn: 'If applied bending moment does not align with principal inertia axes (e.g. angle iron), deflection deviates out-of-plane.',
        f: '\\sigma(x,y) = \\frac{M_u \\cdot v}{I_u} + \\frac{M_v \\cdot u}{I_v}',
        qTr: 'L-köşebent (eşit kollu olmayan L profil) kiriş düşey yüklendiğinde neden aynı zamanda yatay olarak da yana doğru sehim yapar?',
        qEn: 'Why does an unsymmetrical angle beam deflect laterally when loaded purely in the vertical plane?',
        oTr: ['Geometrik eksenleri asal atalet eksenleriyle çakışmadığı ve çarpım atalet momenti (Ixy ≠ 0) sıfır olmadığı için', 'Yerçekimi yana kaydığı için', 'Plastik aktığı için', 'Sürtünme olmadığı için'],
        oEn: ['Geometric axes do not coincide with principal axes (product of inertia Ixy ≠ 0)', 'Gravity shifts', 'Plastic flow', 'Zero friction'],
        cIdx: 0, expTr: 'Doğru! Asal eksenlere göre çözülmeyen asimetrik profiller iki eksenli yana eğilme üretir.',
        expEn: 'Correct! Non-zero product moment of inertia Ixy couples vertical load into lateral deflection.' },
      { num: 86, slug: 'betti-maxwell-reciprocal-theorem', std: 'Maxwell Teoremi', cat: 'Mukavemet', diff: 'hard', pType: 'quiz',
        tTr: '86. Maxwell-Betti Karşılıklılık Teoremi (Reciprocal Theorem)', tEn: '86. Maxwell-Betti Reciprocal Deflection Theorem',
        cTr: 'Lineer elastik bir yapıda 1 noktasındaki F1 kuvvetinin 2 noktasında yaptığı sehim (δ21), 2 noktasına uygulanan aynı F2 kuvvetinin 1 noktasında yaptığı sehime (δ12) eşittir.',
        cEn: 'In linear elastic structures, deflection at point 1 caused by unit load at point 2 equals deflection at point 2 caused by unit load at point 1 (δ12 = δ21).',
        f: '\\delta_{12} = \\delta_{21}, \\quad \\sum F_i \\cdot \\delta_i\' = \\sum F_j\' \\cdot \\delta_j',
        qTr: 'Maxwell karşılıklılık teoreminin yapısal analiz ve sonlu elemanlar (FEA) rijitlik matrislerindeki en önemli sonucu nedir?',
        qEn: 'What fundamental FEA stiffness matrix property arises directly from the Maxwell-Betti reciprocal theorem?',
        oTr: ['Global rijitlik matrisinin simetrik olması ([K] = [K]^T)', 'Rijitlik matrisinin sıfır olması', 'Tüm yer değiştirmelerin eşit olması', 'Kuvvetlerin yok olması'],
        oEn: ['Global stiffness matrix symmetry ([K] = [K]^T)', 'Zero stiffness matrix', 'Equal displacements', 'Forces cancel'],
        cIdx: 0, expTr: 'Doğru! Karşılıklılık teoremi FEA rijitlik matrisinin simetrik [K]=[K]^T olmasını sağlar.',
        expEn: 'Correct! Reciprocal work guarantees symmetric stiffness matrices [K] = [K]^T in structural mechanics.' },
      { num: 87, slug: 'plastic-hinge-collapse-load-calc', std: 'Plastik Limit Analizi', cat: 'İleri Mukavemet', diff: 'hard', pType: 'calculation',
        tTr: '87. Plastik Mafsal (Plastic Hinge) ve Şekil Faktörü (Z/W)', tEn: '87. Plastic Hinge Moment (Mp) & Shape Factor',
        cTr: 'Dikdörtgen kesitte plastik mukavemet momenti Z = (b*h²)/4 olup elastik W = (b*h²)/6 ya oranı şekil faktörünü verir: k = Z/W = 1.50.',
        cEn: 'Plastic section modulus for rectangles is Z = (b*h²)/4. Shape factor is k = Z/W = 1.50.',
        f: 'k = \\frac{Z}{W} = 1.50 \\quad (\\text{Dikdörtgen}), \\quad k \\approx 1.15 \\quad (\\text{I-Kiriş})',
        calcPTr: 'Akma momenti My = 100 kNm olan dikdörtgen kesitli çelik kirişin tam plastik mafsal oluşturacağı taşıma kapasitesi momentini (Mp = 1.5 * My) kNm cinsinden hesaplayınız:',
        calcPEn: 'Calculate fully plastic collapse moment Mp in kNm for yield moment My = 100 kNm (Mp = 1.5 * My):',
        tVal: 150, tol: 1, u: 'kNm', fHint: 'Mp = 1.5 * 100',
        calcExpTr: 'Doğru! Mp = 1.5 * 100 = 150 kNm.', calcExpEn: 'Correct! Mp = 1.5 * 100 = 150 kNm.' },
      { num: 88, slug: 'prandtl-membrane-analogy-torsion', std: 'Prandtl Membran Analojisi', cat: 'Mukavemet', diff: 'medium', pType: 'visual',
        tTr: '88. Prandtl Sabun Köpüğü Membran Analojisi (Burulma)', tEn: '88. Prandtl Soap-Film Membrane Analogy for Torsion',
        cTr: 'Prandtl sabun zarı analojisinde şişirilen membranın eğimi kesitteki kayma gerilmesini, zarı altındaki hacim ise aktarılan torku temsil eder. İnce açık kesitlerin neden burulmaya dayanıksız olduğunu açıklar.',
        cEn: 'Prandtl membrane slope models torsional shear stress, while inflated volume represents transmitted torque.',
        f: '\\tau = 2 G \\theta \\cdot \\frac{\\partial z}{\\partial n}, \\quad T = 2 \\iint z \\, dx \\, dy',
        visPTr: 'Prandtl membran analojisine göre eşit et kalınlığına sahip profillerden hangisi burulmaya karşı EN YÜKSEK rijitliğe sahiptir?',
        visPEn: 'According to Prandtl membrane analogy, which profile provides dramatically superior torsional rigidity?',
        visCards: [
          { id: 'c1', titleTr: 'Kapalı Kutu Profil (Bredt Kapalı Tüp)', titleEn: 'Closed Box Tubular Section', descTr: 'Şişirilen membran devasa bir hacim tutar (Yüksek burulma rijitliği)', descEn: 'Inflated membrane captures enormous enclosed volume (High torsional rigidity)', diagramSvgType: 'i_beam_stress', isCorrect: true },
          { id: 'c2', titleTr: 'Açık Yarıklı İnce C-Profili', titleEn: 'Open Slit C-Channel', descTr: 'Zar hacim tutamaz, burulma rijitliği neredeyse sıfırdır', descEn: 'Membrane cannot hold volume; negligible torsional stiffness', diagramSvgType: 'stress_notch', isCorrect: false },
        ],
        expTr: 'Doğru! Kapalı tüpler (Bredt formülü) açık profillere göre 100-500 kat daha yüksek burulma rijitliğine sahiptir.',
        expEn: 'Correct! Closed tubular sections enclose massive membrane volume, multiplying torsional stiffness hundreds of times.' },
      { num: 89, slug: 'bredt-thin-walled-closed-tubes', std: 'Bredt Formülleri', cat: 'Mukavemet', diff: 'hard', pType: 'quiz',
        tTr: '89. İnce Cidarlı Kapalı Tüpler & 1. Bredt Formülü', tEn: '89. Thin-Walled Closed Tubes & Bredt\'s First Formula',
        cTr: 'Kapalı ince cidarlı kesitlerde kayma akısı q = τ * t = sabit olup burulma momenti T = 2 * Am * q (Am = profil orta çizgisiyle çevrelenen alan) formülüyle taşınır.',
        cEn: 'For closed thin-walled tubes, constant shear flow is q = τ * t. Torque capacity is T = 2 * Am * q.',
        f: 'q = \\tau \\cdot t = \\text{sabit}, \\quad T = 2 \\cdot A_m \\cdot q = 2 \\cdot A_m \\cdot t \\cdot \\tau',
        qTr: 'Bredt 1. formülünde Am neyi temsil eder?',
        qEn: 'In Bredt\'s first torsion formula (T = 2 * Am * t * τ), what does the geometric parameter Am represent?',
        oTr: ['Profil et kalınlığının orta eksen çizgisi (orta hat) ile çevrelenen kapalı alan', 'Toplam metal kesit alanı', 'Dış yüzey alanı', 'Profil uzunluğu'],
        oEn: ['Enclosed area bounded by the mean perimeter centerline of the wall', 'Total solid metal area', 'Outer surface area', 'Profile length'],
        cIdx: 0, expTr: 'Doğru! Am cidar orta hattının çevrelediği iç kapalı alandır.',
        expEn: 'Correct! Am is the enclosed geometric area bounded by the median line of the wall thickness.' },
      { num: 90, slug: 'boss-gantry-crane-box-girder-proof', std: 'EN 1993-1-1 / EN 13001', cat: 'İleri Mukavemet', diff: 'hard', pType: 'boss', isBoss: true,
        tTr: '90. 👑 BOSS SINAVI: 50 Tonluk Portal Vinç Kutu Kirişi Tam Mukavemet Denetimi', tEn: '90. 👑 BOSS TEST: 50-Ton Gantry Crane Box Girder Certification',
        cTr: '30 metre açıklıklı 50 tonluk çift kutu kirişli portal vinçte: 1) Maksimum sehim sınırı w ≤ L/800 = 37.5 mm, 2) Birleşik von Mises gerilmesi σv ≤ 0.85*fy, 3) Jourawski gövde sacı kayma gerilmesi τ ≤ 0.58*fy ve 4) Bredt burulma rijitliği aynı anda kanıtlanmalıdır.',
        cEn: 'Complete gantry girder certification according to EN 13001 proving deflection w ≤ L/800, equivalent stress σv ≤ 0.85*fy, and Jourawski web shear compliance.',
        f: 'w_{\\max} \\le \\frac{L}{800}, \\quad \\sigma_v = \\sqrt{\\sigma_b^2 + 3 (\\tau_{\\text{shear}} + \\tau_{\\text{torsion}})^2} \\le \\frac{f_y}{\\gamma_{M0}}',
        qTr: 'Kutu kiriş gövde saclarının ince olması nedeniyle düşey yük altında gövde sacının lokal buruşmasını (web plate buckling) önlemek için kiriş içine ne kaynatılır?',
        qEn: 'To prevent thin web plate shear buckling under heavy concentrated wheel bogie loads, what internal structural elements are welded inside the box girder?',
        oTr: ['Düşey ve boyuna gövde berkitme levhaları (Stiffener / Diyafram plakaları)', 'Plastik dolgu', 'Kurşun ağırlıklar', 'Delikler'],
        oEn: ['Vertical and longitudinal web plate stiffeners and diaphragm plates', 'Plastic foam', 'Lead weights', 'Perforations'],
        cIdx: 0, expTr: 'Tebrikler Başmühendis! Berkitme diyaframları gövde sacının buruşmasını önleyerek kutu kirişin tam mukavemete ulaşmasını sağlar!',
        expEn: 'Congratulations Master Engineer! Web stiffeners and diaphragms prevent plate shear buckling, securing full load-carrying capacity!' }
    ]
  }
];

console.log('Units 4-6 dataset ready.');
