// UNITS 1 to 3 (Lessons 1 to 45)
module.exports = [
  // ─── UNIT 1: Statik & Atalet (1-15) ───
  {
    num: 1, id: 'unit-1',
    titleTr: 'Ünite 1: Temel Mekanik, Statik & Atalet',
    titleEn: 'Unit 1: Fundamentals of Statics & Inertia',
    descTr: 'Birim dönüşümleri, serbest cisim diyagramı (FBD), mesnet tepkileri ve alan atalet momentleri.',
    descEn: 'Unit conversions, free body diagrams (FBD), support reactions, and area moments of inertia.',
    gradient: 'from-blue-600 via-cyan-500 to-teal-500', difficulty: 'easy', accentColor: '#00e5ff',
    lessons: [
      { num: 1, slug: 'si-units-and-conversions', std: 'ISO 80000-1', cat: 'Statik', diff: 'easy', pType: 'quiz',
        tTr: '1. SI Birim Sistemi & Gerilme Dönüşümleri', tEn: '1. SI Units & Stress Conversions',
        cTr: 'Mühendislikte 1 MPa = 1 N/mm² = 10⁶ Pa = 10 bar. Kuvvet Newton (N), uzunluk milimetre (mm), gerilme Megapascal (MPa) cinsinden alınır.',
        cEn: 'In engineering 1 MPa = 1 N/mm² = 10⁶ Pa = 10 bar. Force in Newtons, length in mm, stress in MPa.',
        f: '1 \\text{ MPa} = 1 \\frac{\\text{N}}{\\text{mm}^2} = 10^6 \\text{ Pa}',
        qTr: '150 MPa gerilme kaç N/mm²\'ye eşittir?', qEn: '150 MPa stress equals how many N/mm²?',
        oTr: ['150 N/mm²', '1.5 N/mm²', '1500 N/mm²', '0.15 N/mm²'], oEn: ['150 N/mm²', '1.5 N/mm²', '1500 N/mm²', '0.15 N/mm²'],
        cIdx: 0, expTr: 'Doğru! 1 MPa tam olarak 1 N/mm²\'dir.', expEn: 'Correct! 1 MPa is exactly 1 N/mm².' },
      { num: 2, slug: 'free-body-diagram-interactive', std: 'Newton Statik', cat: 'Statik', diff: 'easy', pType: 'drawing',
        tTr: '2. Serbest Cisim Diyagramı (FBD) Vektör Çizimi', tEn: '2. Free Body Diagram Vector Placement',
        cTr: 'Serbest Cisim Diyagramında (FBD) cisim çevresinden izole edilir ve temas noktalarındaki tüm kuvvetler ve mesnet tepkileri yönlü vektörlerle gösterilir.',
        cEn: 'In a Free Body Diagram (FBD), the body is isolated with all active external forces and reaction vectors.',
        f: '\\sum \\vec{F} = 0, \\quad \\sum \\vec{M} = 0',
        dPromptTr: 'Aşağıdan yukarıya 1000 N yerçekimi yükü binen bir askı kancasında tavan mesnet tepkisinin yönü ne olmalıdır?',
        dPromptEn: 'For a hanger hook carrying a downward 1000 N weight, what is the required ceiling reaction vector direction?',
        vOpts: [
          { id: 'v1', labelTr: 'Yukarı Doğru (+Y) [Dengeleyici Tepki]', labelEn: 'Upward (+Y) [Balancing Reaction]', direction: 'up', isCorrect: true },
          { id: 'v2', labelTr: 'Aşağı Doğru (-Y)', labelEn: 'Downward (-Y)', direction: 'down', isCorrect: false },
          { id: 'v3', labelTr: 'Sağa Doğru (+X)', labelEn: 'Rightward (+X)', direction: 'right', isCorrect: false },
          { id: 'v4', labelTr: 'Sola Doğru (-X)', labelEn: 'Leftward (-X)', direction: 'left', isCorrect: false },
        ],
        expTr: 'Harika! Aşağı çeken yüke karşı denge için tavan tepkisi yukarı yönlü (+Y) olmalıdır.', expEn: 'Great! Upward ceiling reaction balances the downward gravity load.' },
      { num: 3, slug: 'support-reactions-calculation', std: 'Newton Statik', cat: 'Statik', diff: 'easy', pType: 'calculation',
        tTr: '3. Mesnet Tepkileri Sayısal Hesabı', tEn: '3. Numerical Support Reaction Calculation',
        cTr: 'L = 4 metre açıklıklı basit mesnetli bir kirişin tam ortasına (x = 2 m) F = 8000 N noktasal yük uygulanmıştır. Simetriden dolayı mesnet tepkileri R_A = R_B = F / 2 olur.',
        cEn: 'For a simply supported beam of span L=4m with centered load F=8000 N, symmetry yields RA = RB = F/2.',
        f: 'R_A = R_B = \\frac{F}{2} = \\frac{8000}{2} = 4000 \\text{ N}',
        calcPTr: 'L = 6 m boyunda, sol mesnetten 2 m uzaklıkta 6000 N yük taşıyan kirişte sol mesnet tepkisini (R_A) Newton cinsinden hesaplayınız:',
        calcPEn: 'For a 6m beam with 6000 N load applied 2m from left support, calculate left reaction RA (in Newtons):',
        tVal: 4000, tol: 50, u: 'N', fHint: 'R_A = F * (L - a) / L = 6000 * 4 / 6',
        calcExpTr: 'Doğru! R_A = 6000 x 4 / 6 = 4000 N.', calcExpEn: 'Correct! RA = 6000 * 4 / 6 = 4000 N.' },
      { num: 4, slug: 'centroid-calculation', std: 'Geometri & Statik', cat: 'Statik', diff: 'easy', pType: 'calculation',
        tTr: '4. Kesit Ağırlık Merkezi (Centroid) Hesabı', tEn: '4. Section Centroid Calculation',
        cTr: 'Parçalı kesitlerin ağırlık merkezi y_c = (Σ A_i y_i) / (Σ A_i) formülüyle hesaplanır.',
        cEn: 'Centroid of composite sections is calculated via yc = (Σ Ai*yi) / (Σ Ai).',
        f: 'y_c = \\frac{\\sum A_i \\cdot y_i}{\\sum A_i}',
        calcPTr: 'Tabanı b=100 mm, yüksekliği h=60 mm olan dikdörtgen kesitin tabanından ağırlık merkezi yüksekliğini (mm) hesaplayınız:',
        calcPEn: 'Calculate the height of centroid from base (in mm) for a rectangle b=100mm, h=60mm:',
        tVal: 30, tol: 0.1, u: 'mm', fHint: 'y_c = h / 2 = 60 / 2',
        calcExpTr: 'Doğru! Homojen dikdörtgende ağırlık merkezi tam ortada (h/2 = 30 mm) yer alır.', calcExpEn: 'Correct! Homogeneous rectangle centroid is at h/2 = 30 mm.' },
      { num: 5, slug: 'area-moment-of-inertia-visual', std: 'Mukavemet', cat: 'Statik', diff: 'medium', pType: 'visual',
        tTr: '5. Alan Atalet Momenti & Eğilme Rijitliği', tEn: '5. Area Moment of Inertia & Rigidity',
        cTr: 'Eğilme rijitliği kesitin tarafsız eksenden ne kadar uzakta malzeme topladığına bağlıdır (Ix = ∫ y² dA). I-kirişler dikdörtgene göre çok daha yüksek atalet momentine sahiptir.',
        cEn: 'Bending stiffness depends on material distribution away from neutral axis (Ix = ∫ y² dA). I-beams provide superior inertia per unit mass.',
        f: 'I_{\\text{rect}} = \\frac{b \\cdot h^3}{12}',
        visPTr: 'Eşit kesit alanına ve ağırlığa sahip profillerden hangisi düşey eğilmeye karşı EN YÜKSEK atalet momentine (Ix) sahiptir?',
        visPEn: 'Among profiles with equal area and weight, which exhibits the HIGHEST moment of inertia (Ix) for vertical bending?',
        visCards: [
          { id: 'c1', titleTr: 'Yüksek I-Profili (HEB / IPE)', titleEn: 'Tall I-Beam Profile', descTr: 'Malzemenin büyük kısmı flanşlarda en dış liflerde toplanmıştır (Maksimum Ix)', descEn: 'Material concentrated in outer flanges (Max Ix)', diagramSvgType: 'i_beam_stress', isCorrect: true },
          { id: 'c2', titleTr: 'Yassı Lama Profil', titleEn: 'Flat Bar Profile', descTr: 'Yüksekliği dar, atalet momenti çok düşüktür', descEn: 'Low height, low inertia', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! I-kirişler başlıkları (flanşları) dış liflerde toplayarak Ix değerini maksimize eder.', expEn: 'Correct! I-beams concentrate area far from the neutral axis, maximizing Ix.' },
      { num: 6, slug: 'steiner-parallel-axis-theorem', std: 'Steiner Teoremi', cat: 'Mukavemet', diff: 'medium', pType: 'calculation',
        tTr: '6. Steiner Paralel Eksen Teoremi Hesabı', tEn: '6. Steiner Parallel Axis Theorem Calc',
        cTr: 'Kendi eksenindeki atalet momenti I_0 olan A alanındaki parça, d mesafesindeki yeni bir eksene taşındığında I = I_0 + A * d² olur.',
        cEn: 'Parallel axis theorem shifts inertia by A*d²: I = I0 + A*d².',
        f: 'I_{new} = I_{centroid} + A \\cdot d^2',
        calcPTr: 'Alanı A = 2000 mm² olan bir plakanın kendi ağırlık merkezinden geçen eksene mesafesi d = 10 mm ise eklenen Steiner terimini (A * d²) mm⁴ cinsinden hesaplayınız:',
        calcPEn: 'For area A = 2000 mm² at distance d = 10 mm, calculate the Steiner term (A * d²) in mm⁴:',
        tVal: 200000, tol: 1000, u: 'mm⁴', fHint: 'A * d² = 2000 * (10)² = 2000 * 100',
        calcExpTr: 'Doğru! 2000 * 100 = 200,000 mm⁴.', calcExpEn: 'Correct! 2000 * 100 = 200,000 mm⁴.' },
      { num: 7, slug: 'section-modulus-wx', std: 'Mukavemet', cat: 'Statik', diff: 'medium', pType: 'quiz',
        tTr: '7. Mukavemet Momenti (Wx) & Maksimum Gerilme', tEn: '7. Section Modulus (Wx) & Peak Stress',
        cTr: 'Eğilme dayanım momenti Wx = Ix / y_max\'tır. Maksimum eğilme gerilmesi σ_max = M / Wx ile hesaplanır.',
        cEn: 'Elastic section modulus Wx = Ix / y_max. Maximum bending stress is σ_max = M / Wx.',
        f: 'W_x = \\frac{I_x}{y_{\\max}}, \\quad \\sigma_{\\max} = \\frac{M}{W_x} \\le \\sigma_{allow}',
        qTr: 'M = 2000 Nm eğilme momenti altındaki bir kesitte Wx = 20 cm³ (20,000 mm³) ise maksimum gerilme kaç MPa\'dır?',
        qEn: 'For M = 2000 Nm (2,000,000 Nmm) and Wx = 20,000 mm³, what is maximum bending stress in MPa?',
        oTr: ['100 MPa', '20 MPa', '200 MPa', '50 MPa'], oEn: ['100 MPa', '20 MPa', '200 MPa', '50 MPa'],
        cIdx: 0, expTr: 'Doğru! σ = 2,000,000 Nmm / 20,000 mm³ = 100 MPa.', expEn: 'Correct! σ = 2,000,000 / 20,000 = 100 MPa.' },
      { num: 8, slug: 'iso286-fits-and-tolerances', std: 'ISO 286-1', cat: 'İmalat', diff: 'medium', pType: 'quiz',
        tTr: '8. ISO 286 Tolerans ve Geçme Sistemleri', tEn: '8. ISO 286 Tolerances & Fits',
        cTr: 'ISO 286 sisteminde büyük harfler delik (örn. H7), küçük harfler mil (örn. g6, h6, k6, p6) toleranslarını belirtir. H7/g6 boşluklu, H7/p6 sıkı geçmedir.',
        cEn: 'ISO 286 uses capital letters for bores (H7) and lowercase for shafts (h6, p6). H7/g6 is clearance, H7/p6 is interference.',
        f: 'T = D_{\\max} - D_{\\min} = IT \\text{ grade}',
        qTr: 'H7/p6 geçmesi mekanik montajda ne tür bir geçme sınıfıdır?',
        qEn: 'What type of fit is H7/p6 in mechanical engineering assembly?',
        oTr: ['Sıkı Geçme (Pres Geçme / Interference Fit)', 'Boşluklu Geçme (Clearance)', 'Kaygan Geçme', 'Belirsiz'],
        oEn: ['Interference Fit (Press Fit)', 'Clearance Fit', 'Sliding Fit', 'Loose Fit'],
        cIdx: 0, expTr: 'Doğru! p6 mil çapı H7 delikten büyük olduğundan her zaman sıkı pres geçme oluşur.',
        expEn: 'Correct! Shaft p6 is larger than bore H7, ensuring guaranteed interference.' },
      { num: 9, slug: 'stress-strain-tensile-curve', std: 'ISO 6892-1', cat: 'Malzeme', diff: 'medium', pType: 'visual',
        tTr: '9. Çekme Testi & Akma Dayanımı Rp0.2', tEn: '9. Tensile Test & Yield Strength Rp0.2',
        cTr: 'Belirgin akma göstermeyen alüminyum gibi metallerde %0.2 kalıcı plastik uzamaya karşılık gelen gerilme akma sınırı (Rp0.2) olarak tanımlanır.',
        cEn: 'For alloys without sharp yield point, Rp0.2 is the offset stress corresponding to 0.2% permanent plastic strain.',
        f: 'R_{p0.2} = \\sigma_{(\\varepsilon_{plastic} = 0.2\\%)}',
        visPTr: 'Gerilme-gerinim grafiğinde Hooke kanununun (elastik bölge doğrusal eğimi E modülü) geçerli olduğu bölge hangisidir?',
        visPEn: 'In a stress-strain tensile curve, which region represents linear elasticity (Hooke\'s Law slope = E)?',
        visCards: [
          { id: 'v1', titleTr: 'Doğrusal Elastik Bölge (0 - Rp0.2)', titleEn: 'Linear Elastic Region', descTr: 'Kuvvet kalktığında parça eski haline tam döner (σ = E * ε)', descEn: 'Full springback to original dimensions upon unloading', diagramSvgType: 'rect_beam_stress', isCorrect: true },
          { id: 'v2', titleTr: 'Plastik Boyun Verme (Necking)', titleEn: 'Plastic Necking Region', descTr: 'Kalıcı deformasyon ve kesit daralması', descEn: 'Irreversible plastic flow and section necking', diagramSvgType: 'pitting_crack', isCorrect: false },
        ],
        expTr: 'Doğru! Elastik bölgede gerilme ile gerinim arasında σ = E * ε doğrusal bağıntısı vardır.',
        expEn: 'Correct! The initial linear slope defines Young\'s modulus E.' },
      { num: 10, slug: 'moment-equilibrium-direction', std: 'Statik', cat: 'Statik', diff: 'medium', pType: 'drawing',
        tTr: '10. Moment Dengesi ve Dönme Yönü Seçimi', tEn: '10. Moment Equilibrium & Vector Direction',
        cTr: 'Saat yönünün tersi (CCW) pozitif moment yönü kabul edilir: Σ M_A = 0.',
        cEn: 'Counter-clockwise (CCW) is conventionally taken as positive moment: Σ MA = 0.',
        f: '\\sum M_z = 0 \\implies M_{\\text{applied}} - M_{\\text{reaction}} = 0',
        dPromptTr: 'A noktasından sabitlenmiş bir anahtara saat yönünde (CW) 50 Nm tork uygulanırsa mesnetin reaksiyon momenti hangi yönde olmalıdır?',
        dPromptEn: 'If a clockwise (CW) torque of 50 Nm is applied to a fixed wrench at A, what is the direction of the reaction moment?',
        vOpts: [
          { id: 'm1', labelTr: 'Saat Yönünün Tersi (CCW / ↺) [Dengeleyici]', labelEn: 'Counter-Clockwise (CCW / ↺) [Balancing]', direction: 'ccw', isCorrect: true },
          { id: 'm2', labelTr: 'Saat Yönü (CW / ↻)', labelEn: 'Clockwise (CW / ↻)', direction: 'cw', isCorrect: false },
        ],
        expTr: 'Doğru! Statik denge için reaksiyon torku dış torka zıt yönde (CCW) etki etmelidir.',
        expEn: 'Correct! Reaction moment must oppose applied torque to satisfy Σ M = 0.' },
      { num: 11, slug: 'distributed-load-equivalent', std: 'Statik', cat: 'Statik', diff: 'medium', pType: 'calculation',
        tTr: '11. Düzgün Yayılı Yük Eşdeğeri Hesabı', tEn: '11. Distributed Load Resultant Calculation',
        cTr: 'q (N/m) yayılı yükün toplam bileşke kuvveti F_eq = q * L olup yayılı yükün tam orta noktasından (L/2) etki eder.',
        cEn: 'Uniformly distributed load q has resultant force Feq = q*L acting at midspan (L/2).',
        f: 'F_{eq} = q \\cdot L, \\quad x_{eq} = \\frac{L}{2}',
        calcPTr: 'q = 500 N/m yayılı yük taşıyan L = 4 metre boyundaki kirişin toplam eşdeğer yükünü (N) hesaplayınız:',
        calcPEn: 'Calculate total equivalent resultant load (in N) for q = 500 N/m over length L = 4m:',
        tVal: 2000, tol: 10, u: 'N', fHint: 'F_eq = q * L = 500 * 4',
        calcExpTr: 'Doğru! F_eq = 500 N/m * 4 m = 2000 N.', calcExpEn: 'Correct! F_eq = 500 * 4 = 2000 N.' },
      { num: 12, slug: '3d-vector-components', std: 'Vektör Mekaniği', cat: 'Statik', diff: 'medium', pType: 'quiz',
        tTr: '12. 3 Boyutlu Kuvvet Bileşenleri', tEn: '12. 3D Force Components',
        cTr: '3D uzayda kuvvet vektörü bileşenleri F = sqrt(Fx² + Fy² + Fz²) formülüyle toplanır.',
        cEn: '3D force vector magnitude is |F| = sqrt(Fx² + Fy² + Fz²).',
        f: '|\\vec{F}| = \\sqrt{F_x^2 + F_y^2 + F_z^2}',
        qTr: 'Fx = 300 N, Fy = 400 N ve Fz = 0 N olan bir kuvvetin toplam büyüklüğü nedir?',
        qEn: 'For Fx = 300 N, Fy = 400 N, and Fz = 0 N, what is the magnitude of the resultant force?',
        oTr: ['500 N', '700 N', '100 N', '350 N'], oEn: ['500 N', '700 N', '100 N', '350 N'],
        cIdx: 0, expTr: 'Doğru! sqrt(300² + 400²) = sqrt(90000 + 160000) = 500 N.', expEn: 'Correct! sqrt(300² + 400²) = 500 N.' },
      { num: 13, slug: 'coulomb-friction-calculation', std: 'Triboloji & Statik', cat: 'Statik', diff: 'medium', pType: 'calculation',
        tTr: '13. Coulomb Sürtünme Kuvveti Hesabı', tEn: '13. Coulomb Friction Calculation',
        cTr: 'Statik sürtünme kuvveti F_s = μ_s * N formülüyle hesaplanır.',
        cEn: 'Static friction limit is Fs = μs * N, scaling linearly with normal clamp force N.',
        f: 'F_{s,\\max} = \\mu_s \\cdot N',
        calcPTr: 'μs = 0.30 sürtünme katsayısına sahip çelik yüzeyde N = 2000 N dik basma kuvveti altında kaymayı başlatacak kritik kuvveti (N) hesaplayınız:',
        calcPEn: 'Calculate the maximum static friction force (in N) for μs = 0.30 and normal force N = 2000 N:',
        tVal: 600, tol: 5, u: 'N', fHint: 'F_s = 0.30 * 2000',
        calcExpTr: 'Doğru! F_s = 0.30 * 2000 = 600 N.', calcExpEn: 'Correct! F_s = 0.30 * 2000 = 600 N.' },
      { num: 14, slug: 'truss-node-equilibrium', std: 'Kafes Sistemler', cat: 'Statik', diff: 'medium', pType: 'drawing',
        tTr: '14. Kafes Sistemlerde Düğüm Noktası Kuvvet Yönü', tEn: '14. Truss Method of Joints Force Direction',
        cTr: 'Kafes kirişlerde çubuklar sadece eksenel çekme veya bası taşır. Düğümden dışa çeken çubuk ÇEKME elemanıdır.',
        cEn: 'Truss members carry pure axial tension or compression. Vectors pointing away from joints denote tension.',
        f: '\\sum F_x = 0, \\quad \\sum F_y = 0',
        dPromptTr: 'Bir düğüm noktasına etki eden çubuğun düğümü kendine doğru çektiği (düğümden dışarı doğru) durum hangi gerilme tipidir?',
        dPromptEn: 'When a member vector pulls away from the joint, what stress state does the member experience?',
        vOpts: [
          { id: 't1', labelTr: 'Çekme (Tension)', labelEn: 'Tension', direction: 'right', isCorrect: true },
          { id: 't2', labelTr: 'Bası (Compression)', labelEn: 'Compression', direction: 'left', isCorrect: false },
        ],
        expTr: 'Doğru! Düğümden dışa doğru çekilen çubuk çekme (tension) altındadır.',
        expEn: 'Correct! Pulling away from the joint indicates tension.' },
      { num: 15, slug: 'boss-crane-arm-statics', std: 'Komple Statik Analiz', cat: 'Statik', diff: 'hard', pType: 'boss', isBoss: true,
        tTr: '15. 👑 BOSS SINAVI: Konsol Vinç Kolu Statik Denge Analizi', tEn: '15. 👑 BOSS TEST: Cantilever Crane Arm Equilibrium',
        cTr: 'Konsol bir vinç kolunda uç yükü F, vinç kolu öz ağırlığı q*L ve diyagonal gergi çubuğu çekme kuvveti T aynı anda çözülerek mafsal reaksiyon kuvvetleri ve emniyet katsayısı (S ≥ 2.0) doğrulanır.',
        cEn: 'Crane boom statics requires simultaneously solving payload F, self-weight q*L, and tie-rod tension T with S ≥ 2.0.',
        f: '\\sum M_{\\text{pin}} = 0, \\quad T = \\frac{F \\cdot L + q L \\cdot \\frac{L}{2}}{L \\sin(\\theta)}',
        qTr: 'L = 5 m vinç kolu ucunda 20 kN yük varken, gergi çubuğu kolla 30° açı yapıyorsa gergi çubuğu çekme kuvveti (T) yaklaşık kaç kN olur? (Öz ağırlık ihmal)',
        qEn: 'For L=5m boom with 20 kN tip load and tie-rod at θ=30°, what is tie-rod tension T? (Neglect boom weight)',
        oTr: ['40 kN (20 / sin(30°))', '20 kN', '10 kN', '80 kN'],
        oEn: ['40 kN (20 / sin(30°))', '20 kN', '10 kN', '80 kN'],
        cIdx: 0, expTr: 'Tebrikler! Moment dengesinden T * L * sin(30°) = 20 * L => T = 20 / 0.5 = 40 kN!',
        expEn: 'Congratulations! By moment equilibrium T * sin(30°) = 20 => T = 40 kN!' }
    ]
  },

  // ─── UNIT 2: CIVATALI BAĞLANTILAR & VDI 2230 (16-30) ───
  {
    num: 2, id: 'unit-2',
    titleTr: 'Ünite 2: Cıvatalı Bağlantılar & VDI 2230',
    titleEn: 'Unit 2: Bolted Joints & VDI 2230',
    descTr: 'Cıvata mukavemet sınıfları (8.8, 10.9), ön yük hesabı, sıkma torku ve Rötscher birleşme konisi.',
    descEn: 'Bolt strength classes (8.8, 10.9), preload sizing, tightening torque, and joint compliance.',
    gradient: 'from-cyan-600 via-blue-600 to-indigo-600', difficulty: 'medium', accentColor: '#3b82f6',
    lessons: [
      { num: 16, slug: 'bolt-strength-grades-iso898', std: 'ISO 898-1', cat: 'Cıvatalar', diff: 'easy', pType: 'quiz',
        tTr: '16. ISO 898-1 Cıvata Mukavemet Sınıfları (8.8, 10.9, 12.9)', tEn: '16. ISO 898-1 Bolt Strength Grades',
        cTr: 'Mukavemet sınıfı (örn. 8.8): İlk rakam çekme dayanımının 1/100\'ü (800 MPa), ikinci rakam akmanın çekmeye oranıdır (0.8 x 800 = 640 MPa akma).',
        cEn: 'Grade 8.8: First digit x 100 = 800 MPa tensile strength. Second digit x 0.1 x 800 = 640 MPa yield strength.',
        f: 'R_m = 100 \\times 8 = 800 \\text{ MPa}, \\quad R_{p0.2} = 800 \\times 0.8 = 640 \\text{ MPa}',
        qTr: '10.9 kalite bir cıvatanın akma dayanımı (Rp0.2) kaç MPa\'dır?', qEn: 'What is the yield strength (Rp0.2) of a 10.9 grade bolt in MPa?',
        oTr: ['900 MPa (1000 x 0.9)', '1000 MPa', '800 MPa', '640 MPa'], oEn: ['900 MPa (1000 x 0.9)', '1000 MPa', '800 MPa', '640 MPa'],
        cIdx: 0, expTr: 'Doğru! Rm = 1000 MPa, Rp0.2 = 1000 x 0.9 = 900 MPa.', expEn: 'Correct! Rm = 1000 MPa, Rp0.2 = 1000 * 0.9 = 900 MPa.' },
      { num: 17, slug: 'bolt-stress-area-calculation', std: 'DIN 13 / ISO 965', cat: 'Cıvatalar', diff: 'medium', pType: 'calculation',
        tTr: '17. Metrik Cıvata Gerilme Alanı (As) Hesabı', tEn: '17. Metric Bolt Tensile Stress Area (As)',
        cTr: 'Cıvata gerilme alanı diş dibi ve böğür çaplarının ortalamasından As = π/4 * ((d2 + d3)/2)² formülüyle hesaplanır. M10 standart adım (P=1.5) için As ≈ 58 mm²\'dir.',
        cEn: 'Tensile stress area As = π/4 * ((d2+d3)/2)². For M10 standard coarse thread (P=1.5mm), As ≈ 58.0 mm².',
        f: 'A_s = \\frac{\\pi}{4} \\left( \\frac{d_2 + d_3}{2} \\right)^2',
        calcPTr: 'M12 standart cıvatanın (As = 84.3 mm²) 8.8 kalitede akma kuvvetini (F_yield = 640 MPa * As) Newton cinsinden hesaplayınız:',
        calcPEn: 'Calculate the yield force in Newtons for M12 8.8 bolt (As = 84.3 mm², Rp0.2 = 640 MPa):',
        tVal: 53952, tol: 200, u: 'N', fHint: 'F_yield = 640 * 84.3',
        calcExpTr: 'Doğru! 640 MPa * 84.3 mm² = 53,952 N (~54 kN).', calcExpEn: 'Correct! 640 * 84.3 = 53,952 N.' },
      { num: 18, slug: 'vdi2230-preload-and-torque', std: 'VDI 2230 Blatt 1', cat: 'Cıvatalar', diff: 'medium', pType: 'calculation',
        tTr: '18. VDI 2230 Ön Yük & Sıkma Torku (MA) Hesabı', tEn: '18. VDI 2230 Preload & Tightening Torque',
        cTr: 'Kellermann-Klein formülü ile sıkma torku diş sürtünmesi ve baş altı sürtünmesinden oluşur: MA = FM * (0.16 * P + 0.58 * d2 * μth + r_b * μb).',
        cEn: 'Kellermann-Klein torque formula balances thread helix, thread friction and under-head friction.',
        f: 'M_A = F_M \\left[ 0.16 P + 0.58 d_2 \\mu_{th} + r_b \\mu_b \\right]',
        calcPTr: 'Pratik tork formülü MA = k * d * FM bağıntısında k = 0.20, d = 0.010 m (M10) ve FM = 25,000 N ön yük için gereken torku (Nm) hesaplayınız:',
        calcPEn: 'Using MA = k * d * FM with k=0.20, d=0.010m (M10) and FM=25,000 N, calculate tightening torque (in Nm):',
        tVal: 50, tol: 1, u: 'Nm', fHint: 'M_A = 0.20 * 0.010 * 25000',
        calcExpTr: 'Doğru! MA = 0.20 * 0.010 * 25000 = 50 Nm.', calcExpEn: 'Correct! MA = 0.20 * 0.010 * 25000 = 50 Nm.' },
      { num: 19, slug: 'roetscher-clamping-cone-visual', std: 'VDI 2230', cat: 'Cıvatalar', diff: 'medium', pType: 'visual',
        tTr: '19. Rötscher Birleşme Konisi & Parça Esnekliği', tEn: '19. Rötscher Clamping Cone & Compliance',
        cTr: 'Cıvata sıkıldığında sıkıştırılan plakalar içinde tan(phi)=0.5 açısıyla çift konili bir basınç hacmi (Rötscher birleşme konisi) oluşur.',
        cEn: 'Clamped plates form a double-frustum compressive zone defined by Rötscher\'s envelope angle tan(phi)=0.5.',
        f: '\\tan(\\varphi) = 0.5 \\quad (\\text{Rötscher Basınç Konisi Açısı})',
        visPTr: 'VDI 2230 birleşme konisinde cıvata ön yükü sıkılan parçalara nasıl dağılır?',
        visPEn: 'How does bolt clamping pressure disperse through the joined flange plates in VDI 2230?',
        visCards: [
          { id: 'c1', titleTr: 'Rötscher Çift Koni Basınç Dağılımı', titleEn: 'Rötscher Double Frustum Zone', descTr: 'Baş altından ayrım yüzeyine doğru genişleyen konik basınç alanı', descEn: 'Conical stress envelope expanding toward interface', diagramSvgType: 'roetscher_cone', isCorrect: true },
          { id: 'c2', titleTr: 'Tek Noktasal İnce Çizgi', titleEn: 'Single Line Model', descTr: 'Basınç sadece delik kenarında kalır (Hatalı model)', descEn: 'Incorrect narrow cylinder assumption', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Rötscher konisi yükün genişleyerek yayılmasını ve plaka rijitliğini açıklar.', expEn: 'Correct! Rötscher cone accurately models flange compliance.' },
      { num: 20, slug: 'friction-coefficient-classes', std: 'VDI 2230 Tablo 5', cat: 'Cıvatalar', diff: 'medium', pType: 'quiz',
        tTr: '20. Diş ve Baş Altı Sürtünme Katsayıları (μ)', tEn: '20. Thread & Bearing Friction Classes',
        cTr: 'Kuru çelik cıvatalarda μ = 0.14 - 0.18, yağlı cıvatalarda μ = 0.10 - 0.14, MoS2 kaplı cıvatalarda μ = 0.08 - 0.10 mertebesindedir. Düşük sürtünmede aynı tork çok daha yüksek ön yük üretir!',
        cEn: 'Dry steel μ = 0.14-0.18, oiled μ = 0.10-0.14, MoS2 coated μ = 0.08-0.10. Lower friction produces higher preload for identical torque!',
        f: '\\mu_{\\text{oiled}} \\approx 0.12, \\quad \\mu_{\\text{dry}} \\approx 0.16',
        qTr: 'Yağlı bir cıvatayı kuru tork tablosundaki yüksek torkla sıkarsak ne tehlikesi doğar?',
        qEn: 'If an oiled bolt is tightened with dry torque specifications, what severe failure occurs?',
        oTr: ['Cıvata aşırı gerilerek akar veya kopar (Over-tightening yield/fracture)', 'Cıvata gevşer', 'Tork sıfırlanır', 'Sıcaklık düşer'],
        oEn: ['Bolt yields or fractures due to excessive axial preload', 'Bolt loosens', 'Torque zeros', 'Temp drops'],
        cIdx: 0, expTr: 'Doğru! Yağ sürtünmeyi düşürdüğü için torkun büyük kısmı eksenel kuvvete dönüşerek cıvatayı koparabilir.',
        expEn: 'Correct! Reduced friction channels torque into excessive axial force, risking bolt rupture.' },
      { num: 21, slug: 'stainless-steel-galling-a2-a4', std: 'ISO 3506-1', cat: 'Cıvatalar', diff: 'medium', pType: 'quiz',
        tTr: '21. Paslanmaz Cıvatalar (A2-70, A4-80) & Soğuk Kaynama', tEn: '21. Stainless Bolts (A2, A4) & Thread Galling',
        cTr: 'Östenitik paslanmaz çelikler (A2 / A4) sıkılırken yüzeydeki krom oksit tabakası sürtünmeyle yırtılır ve soğuk kaynama (galling) meydana gelerek cıvata kilitlenir. Montajda anti-seize pasta kullanılmalıdır.',
        cEn: 'Austenitic stainless bolts suffer from thread galling. Protective anti-seize paste is mandatory.',
        f: 'A4\\text{-}80: R_m = 800 \\text{ MPa}, \\quad R_{p0.2} = 600 \\text{ MPa}',
        qTr: 'Paslanmaz çelik cıvatalarda dişlerin birbirine yapışıp kilitlenmesini (galling) önlemek için ne sürülür?',
        qEn: 'What lubricant must be applied to stainless steel threads to prevent galling seizure?',
        oTr: ['Anti-seize montaj pastası / seramik gres', 'Su', 'Tiner', 'Zımpara tozu'],
        oEn: ['Anti-seize assembly paste / ceramic grease', 'Water', 'Thinner', 'Abrasive powder'],
        cIdx: 0, expTr: 'Doğru! Anti-seize pastalar metal-metal temasını keserek soğuk kaynamayı önler.',
        expEn: 'Correct! Anti-seize compounds prevent metal-to-metal cold welding.' },
      { num: 22, slug: 'junker-transverse-vibration-test', std: 'DIN 65151 / ISO 16130', cat: 'Cıvatalar', diff: 'medium', pType: 'visual',
        tTr: '22. Junker Enine Titreşim Testi & Kendiliğinden Gevşeme', tEn: '22. Junker Transverse Vibration Loosening',
        cTr: 'Junker testinde eksenel değil enine dinamik titreşim uygulandığında standart yaylı rondelalar işe yaramazken Nord-Lock kamalı kilit rondelaları ön yükü korur.',
        cEn: 'Junker vibration tests prove spring washers fail under transverse cyclic shear. Nord-Lock wedge-locking washers preserve clamp force.',
        f: '\\alpha_{\\text{cam}} > \\beta_{\\text{thread}} \\quad (\\text{Kama Açısı Diş Adım Açısından Büyük})',
        visPTr: 'Junker enine titreşim testinde cıvatanın gevşemesini kesin olarak engelleyen rondela geometrisi hangisidir?',
        visPEn: 'Which locking washer geometry positively prevents bolt self-loosening under Junker vibration?',
        visCards: [
          { id: 'v1', titleTr: 'Nord-Lock Çift Kamalı Kilit Rondelası', titleEn: 'Nord-Lock Wedge Locking Pair', descTr: 'Kama açısı diş adım açısından büyüktür, gevşeme yönünde cıvatayı daha da sıkar', descEn: 'Cam angle exceeds thread pitch, increasing clamp force upon loosening attempt', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'v2', titleTr: 'Düz Standart Pul', titleEn: 'Standard Flat Washer', descTr: 'Titreşim altında hızla dönerek gevşer', descEn: 'Loosens rapidly under dynamic transverse slip', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Nord-Lock kamalı rondelalar gevşemeyi fiziksel kama geometrisiyle imkansız kılar.',
        expEn: 'Correct! Nord-Lock uses wedge action where cam lift exceeds thread lead.' },
      { num: 23, slug: 'thread-stripping-strength-calculation', std: 'VDI 2230', cat: 'Cıvatalar', diff: 'hard', pType: 'calculation',
        tTr: '23. Diş Sıyırma Dayanımı & Minimum Vidalama Boyu', tEn: '23. Thread Stripping & Minimum Engagement',
        cTr: 'Yumuşak malzemelerde (örn. Alüminyum gövdeye çelik cıvata) gövde dişlerinin sıyrılmaması için minimum vidalama boyu m_eff ≥ 1.5 - 2.0 * d olmalıdır.',
        cEn: 'For soft base materials (aluminum casting with steel bolt), minimum thread engagement must be meff ≥ 1.5 - 2.0 * d.',
        f: 'm_{\\text{eff}} \\ge 1.5 \\times d \\quad (\\text{Alüminyum Gövde})',
        calcPTr: 'd = 10 mm (M10) cıvatanın Alüminyum 6061 gövdeye vidalanmasında güvenli minimum vidalama boyunu (mm) hesaplayınız (m = 1.6 * d):',
        calcPEn: 'Calculate minimum safe thread engagement length (in mm) for M10 bolt into 6061 Aluminum (m = 1.6 * d):',
        tVal: 16, tol: 0.5, u: 'mm', fHint: 'm = 1.6 * 10',
        calcExpTr: 'Doğru! m = 1.6 * 10 = 16 mm.', calcExpEn: 'Correct! m = 1.6 * 10 = 16 mm.' },
      { num: 24, slug: 'torque-angle-tightening-method', std: 'VDI 2230 Blatt 1', cat: 'Cıvatalar', diff: 'medium', pType: 'visual',
        tTr: '24. Tork-Açı Kontrollü Sıkma Yöntemi', tEn: '24. Torque-Angle Tightening Method',
        cTr: 'Sadece torkla sıkmada sürtünme belirsizliği ön yükte ±%30 sapma yaratır. Tork-açı yönteminde önce eşik torkuna gelinir, sonra hassas derece döndürülerek doğrudan akma bölgesinde dar toleranslı ön yük elde edilir.',
        cEn: 'Torque-angle tightening overcomes friction scatter (±30% in torque-only) by rotating an exact angle beyond snug torque.',
        f: 'F_M = \\frac{P \\cdot \\theta}{360 \\cdot (\\delta_S + \\delta_P)}',
        visPTr: 'Kritik motor biyel kolu ve silindir kapağı cıvatalarında neden tork-açı yöntemi tercih edilir?',
        visPEn: 'Why is torque-angle tightening favored in critical engine connecting rods and cylinder heads?',
        visCards: [
          { id: 'c1', titleTr: 'Hassas Dar Ön Yük Dağılımı (±%10)', titleEn: 'Precise Preload Band (±10%)', descTr: 'Sürtünme değişkenliğinden etkilenmeksizin akma sınırına yakın maksimum sıkma sağlar', descEn: 'Eliminates friction variation, locking consistent clamp force', diagramSvgType: 'i_beam_stress', isCorrect: true },
          { id: 'c2', titleTr: 'Rastgele Gevşek Bağlantı', titleEn: 'Uncontrolled Tightening', descTr: 'Ön yük kontrolsüz kalır', descEn: 'Uncontrolled clamp force', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Tork-açı yöntemi sürtünme belirsizliğini ortadan kaldırarak maksimum ön yük kararlılığı sağlar.',
        expEn: 'Correct! Torque-angle control bypasses friction variance, achieving uniform preloads.' },
      { num: 25, slug: 'bolt-diagram-force-vectors', std: 'VDI 2230', cat: 'Cıvatalar', diff: 'hard', pType: 'drawing',
        tTr: '25. Cıvata Birleşim Şeması Kuvvet Akışı', tEn: '25. Joint Diagram Force Vectors',
        cTr: 'Dış çalışma yükü FA uygulandığında bu yükün cıvataya aktarılan kısmı yük faktörü Φ ile hesaplanır: ΔFSA = Φ * FA (Φ ≈ 0.15 - 0.25).',
        cEn: 'External force FA adds only a fraction to bolt load: ΔFSA = Φ * FA (Φ ≈ 0.15-0.25), while reducing clamp force on plates.',
        f: '\\Phi = \\frac{\\delta_P}{\\delta_S + \\delta_P} \\approx 0.20',
        dPromptTr: 'Dış çekme kuvveti FA uygulandığında plakalar arasındaki sıkıştırma kuvvetinin (FK) yönü ve değişimi nedir?',
        dPromptEn: 'When external tensile load FA is applied, what happens to the residual clamping force FK on the flange plates?',
        vOpts: [
          { id: 'f1', labelTr: 'Sıkıştırma kuvveti azalır (-ΔFPA)', labelEn: 'Clamping force decreases (-ΔFPA)', direction: 'down', isCorrect: true },
          { id: 'f2', labelTr: 'Sıkıştırma kuvveti iki katına çıkar', labelEn: 'Clamping force doubles', direction: 'up', isCorrect: false },
        ],
        expTr: 'Doğru! Dış çekme yükü plakaların baskısını gevşetir (ayrılma sınırına yaklaştırır).',
        expEn: 'Correct! External tension relieves compressive clamp force between plates.' },
      { num: 26, slug: 'thermal-expansion-preload-loss', std: 'VDI 2230', cat: 'Cıvatalar', diff: 'hard', pType: 'calculation',
        tTr: '26. Sıcaklık Değişiminde Cıvata Ön Yük Değişimi', tEn: '26. Thermal Expansion Preload Shift',
        cTr: 'Alüminyum gövde (α = 23e-6) içine çelik cıvata (α = 12e-6) sıkıldığında sıcaklık artışı alüminyumu daha çok uzatarak cıvata ön yükünü artırır; soğuma ise gevşetir.',
        cEn: 'Thermal coefficient mismatch (Al 23e-6 vs Steel 12e-6) alters preload with temperature changes.',
        f: '\\Delta F_{th} = \\frac{(\\alpha_P - \\alpha_S) \\cdot \\Delta T \\cdot L_K}{\\delta_S + \\delta_P}',
        calcPTr: 'L_K = 50 mm sıkma boyunda, sıcaklık farkı ΔT = 100°C ve termal genleşme farkı ΔL = 0.055 mm ise k = 500 kN/mm sistem rijitliğiyle oluşan ek kuvveti (kN) hesaplayınız:',
        calcPEn: 'For ΔL = 0.055 mm and stiffness k = 500 kN/mm, calculate thermal force increase in kN:',
        tVal: 27.5, tol: 0.5, u: 'kN', fHint: 'F = 0.055 * 500',
        calcExpTr: 'Doğru! F = 0.055 mm * 500 kN/mm = 27.5 kN.', calcExpEn: 'Correct! F = 0.055 * 500 = 27.5 kN.' },
      { num: 27, slug: 'flange-joint-leakage-safety', std: 'EN 1591 / VDI 2230', cat: 'Cıvatalar', diff: 'medium', pType: 'quiz',
        tTr: '27. Basınçlı Flanş Bağlantılarında Sızdırmazlık Emniyeti', tEn: '27. Flange Joint Gasket Sealing Safety',
        cTr: 'İç basınç altındaki flanşlarda conta yüzey basıncı minimum conta sızdırmazlık basıncının altına düşmemelidir (FK_min > p_internal * A_gasket_factor).',
        cEn: 'Residual gasket stress under operating internal pressure must exceed minimum seating stress to prevent fluid leakage.',
        f: 'F_{K,\\min} \\ge F_{K,req} > 0 \\implies S_K = \\frac{F_{K,\\min}}{F_{K,req}} \\ge 1.2',
        qTr: 'İç basınç yükseldiğinde flanş cıvataları uzar ve contadaki bası gerilmesi sıfıra inerse ne gerçekleşir?',
        qEn: 'If internal pressure stretches flange bolts causing gasket compression to drop to zero, what failure occurs?',
        oTr: ['Flanş ayrılması ve basınçlı akışkan sızıntısı (Leakage / Joint Separation)', 'Cıvata kalınlaşır', 'Tork artar', 'Basınç sıfırlanır'],
        oEn: ['Joint separation and fluid leakage', 'Bolt thickens', 'Torque increases', 'Pressure zeros'],
        cIdx: 0, expTr: 'Doğru! Conta basıncı sıfırlandığında sızdırmazlık çöker ve akışkan dışarı sızar.',
        expEn: 'Correct! Loss of residual gasket clamp force causes immediate fluid leakage.' },
      { num: 28, slug: 'countersunk-vs-cap-screw-notches', std: 'ISO 10642 vs ISO 4762', cat: 'Cıvatalar', diff: 'medium', pType: 'visual',
        tTr: '28. Gömme Başlı vs Silindirik Cıvata Gerilme Yığılması', tEn: '28. Countersunk vs Socket Head Stress Notch',
        cTr: 'Gömme başlı (havşalı) cıvatalarda konik baş altı 90° köşesi yüksek gerilme yığılması oluşturur ve yorulma dayanımı silindirik başlı (ISO 4762) cıvatalara göre %30-40 daha düşüktür.',
        cEn: 'Countersunk screws have high notch sensitivity under head. Socket head cap screws offer superior dynamic fatigue life.',
        f: '\\alpha_k(\\text{Countersunk}) > \\alpha_k(\\text{Cap Screw})',
        visPTr: 'Dinamik yorulma yükü taşıyan yüksek emniyetli makine parçalarında hangi cıvata başı geometrisi tercih edilmelidir?',
        visPEn: 'Which bolt head style is strongly preferred for high dynamic fatigue reliability?',
        visCards: [
          { id: 'c1', titleTr: 'Silindirik Başlı İmbus Cıvata (ISO 4762)', titleEn: 'Socket Head Cap Screw', descTr: 'Geniş baş altı geçiş radyusu ve düz oturma yüzeyi ile minimum çentik etkisi', descEn: 'Generous fillet radius, minimal stress concentration', diagramSvgType: 'i_beam_stress', isCorrect: true },
          { id: 'c2', titleTr: '90° Havşalı Gömme Başlı Cıvata', titleEn: 'Countersunk Screw', descTr: 'Konik geçişte yüksek gerilme yığılması ve çatlak riski', descEn: 'High stress concentration at conical transition', diagramSvgType: 'stress_notch', isCorrect: false },
        ],
        expTr: 'Doğru! Silindirik başlı cıvatalar geniş kavisli baş altı radyusu ile üstün yorulma ömrü sunar.',
        expEn: 'Correct! Socket head screws have generous transition fillets that suppress notch stress.' },
      { num: 29, slug: 'bolt-fatigue-notch-factor', std: 'VDI 2230 / DIN 969', cat: 'Cıvatalar', diff: 'hard', pType: 'quiz',
        tTr: '29. Cıvata Dinamik Yorulma Dayanımı & Çentik Faktörü', tEn: '29. Bolt Dynamic Fatigue Endurance & Notches',
        cTr: 'Cıvataların yorulma kırılmalarının %65\'i somuna veya gövdeye giren İLK DİŞ dibinde gerçekleşir. Ovalanmış (rolled) dişler kesilmiş dişlere göre 2 kat yüksek yorulma ömrü sağlar.',
        cEn: '65% of bolt fatigue failures initiate at the first engaged thread root. Rolled threads dramatically outperform cut threads.',
        f: '\\sigma_{a,allow} \\approx 0.85 \\cdot \\sigma_{ASG} \\quad (\\text{İlk Diş Çentik Faktörü } \\beta_k \\approx 2.5 - 3.5)',
        qTr: 'Cıvata dişlerinin talaş kaldırma yerine soğuk ovalama (thread rolling) ile üretilmesinin en büyük avantajı nedir?',
        qEn: 'What is the primary fatigue advantage of cold thread rolling over machining/cutting?',
        oTr: ['Sürekli lif yapısı ve diş dibinde bası kalıntı gerilmesi oluşturarak yorulma ömrünü katlar', 'Cıvatayı yumuşatır', 'Paslanmayı hızlandırır', 'Ağırlığı sıfırlar'],
        oEn: ['Preserves continuous grain flow and induces compressive residual stresses at roots', 'Softens steel', 'Accelerates corrosion', 'Zeros weight'],
        cIdx: 0, expTr: 'Doğru! Soğuk ovalama kesintisiz metal lifleri ve bası kalıntı gerilmeleri yaratarak çatlak oluşumunu durdurur.',
        expEn: 'Correct! Thread rolling produces unbroken grain flow and compressive residual surface stress.' },
      { num: 30, slug: 'boss-vdi2230-cylinder-head-bolting', std: 'VDI 2230 Tam Denetim', cat: 'Cıvatalar', diff: 'hard', pType: 'boss', isBoss: true,
        tTr: '30. 👑 BOSS SINAVI: Yüksek Basınçlı Silindir Kapağı Cıvata Doğrulaması', tEn: '30. 👑 BOSS TEST: High-Pressure Cylinder Head Bolted Joint',
        cTr: '200 bar patlama basıncı altında 10.9 M16 cıvatalar için: 1) Montaj akma güvenliği SF ≥ 1.2, 2) Ayrılma emniyeti SK ≥ 1.5, 3) Dinamik yorulma güvenliği SD ≥ 1.5 ve 4) Yüzey ezilme basıncı Sp ≥ 1.1 aynı anda sağlanmalıdır.',
        cEn: 'Complete VDI 2230 verification requires proving yield safety SF ≥ 1.2, joint opening safety SK ≥ 1.5, dynamic fatigue safety SD ≥ 1.5, and interface contact pressure Sp ≥ 1.1.',
        f: 'S_F = \\frac{R_{p0.2}}{\\sigma_{red,M}} \\ge 1.2, \\quad S_K = \\frac{F_{K,\\min}}{F_{K,req}} \\ge 1.5, \\quad S_D = \\frac{\\sigma_{A,allow}}{\\sigma_a} \\ge 1.5',
        qTr: 'VDI 2230 analizinde cıvata ön yükü FM arttırıldığında flanşın ayrılma güvenliği (SK) ve cıvatanın maruz kaldığı dinamik genlik gerilmesi (σa) nasıl değişir?',
        qEn: 'Under VDI 2230, as bolt preload FM increases, how do separation safety (SK) and dynamic alternating stress amplitude (σa) change?',
        oTr: ['Ayrılma güvenliği ARTAR, cıvatadaki dinamik gerilme genliği DEĞİŞMEZ veya AZALIR (Mükemmel durum)', 'Ayrılma güvenliği düşer', 'Cıvata gevşer', 'Patlama basıncı artar'],
        oEn: ['Separation safety INCREASES, dynamic stress amplitude remains constant or decreases (Optimal)', 'Separation drops', 'Bolt loosens', 'Pressure spikes'],
        cIdx: 0, expTr: 'Tebrikler Başmühendis! Yüksek ön yük plakaları sıkı tutarak dinamik yükün cıvataya geçmesini engeller ve yorulma ömrünü korur!',
        expEn: 'Congratulations Master Engineer! High preload clamps the joint, isolating the bolt from cyclic fatigue amplitudes!' }
    ]
  },

  // ─── UNIT 3: RULMANLAR, TRİBOLOJİ & ISO 281 (31-45) ───
  {
    num: 3, id: 'unit-3',
    titleTr: 'Ünite 3: Rulmanlar, Triboloji & ISO 281',
    titleEn: 'Unit 3: Bearings, Tribology & ISO 281',
    descTr: 'Dinamik yük sayısı C, L10 ve L10h yorulma ömrü, Stribeck eğrisi ve yağ viskozite oranı kappa.',
    descEn: 'Dynamic load rating C, L10/L10h fatigue life, Stribeck lubrication curve, and viscosity ratio kappa.',
    gradient: 'from-indigo-600 via-violet-600 to-purple-600', difficulty: 'medium', accentColor: '#8b5cf6',
    lessons: [
      { num: 31, slug: 'bearing-types-and-applications', std: 'ISO 15 / DIN 616', cat: 'Rulmanlar', diff: 'easy', pType: 'quiz',
        tTr: '31. Rulman Çeşitleri & Yük Karakteristikleri', tEn: '31. Rolling Bearing Types & Loads',
        cTr: 'Sabit bilyalı rulmanlar (6000 serisi) radyal ve orta eksenel yük taşır. Silindirik makaralı rulmanlar (NU/N) çok yüksek radyal yük taşırken eksenel yük taşıyamaz. Konik makaralı rulmanlar ise yüksek kombine yük taşır.',
        cEn: 'Deep groove ball bearings take radial + moderate thrust. Cylindrical roller bearings take high radial only. Tapered roller bearings support high combined loads.',
        f: 'P = X \\cdot F_r + Y \\cdot F_a',
        qTr: 'Sadece yüksek radyal yük taşıyan ve eksenel yer değiştirmeye izin veren rulman tipi hangisidir?',
        qEn: 'Which bearing type supports heavy radial loads while accommodating axial thermal floating?',
        oTr: ['Silindirik Makaralı Rulman (NU/N Tipi)', 'Eksenel Bilyalı Rulman', 'Eğik Temaslı Bilyalı Rulman', 'Konik Makaralı Rulman'],
        oEn: ['Cylindrical Roller Bearing (NU/N)', 'Thrust Ball Bearing', 'Angular Contact Bearing', 'Tapered Roller Bearing'],
        cIdx: 0, expTr: 'Doğru! Silindirik makaralar yüksek radyal temas hattına sahiptir ve eksenel kaymaya izin verir.',
        expEn: 'Correct! Cylindrical rollers offer line contact for pure radial duty with free axial float.' },
      { num: 32, slug: 'equivalent-dynamic-bearing-load', std: 'ISO 281', cat: 'Rulmanlar', diff: 'medium', pType: 'calculation',
        tTr: '32. Eşdeğer Dinamik Yük (P) Sayısal Hesabı', tEn: '32. Equivalent Dynamic Load (P) Calculation',
        cTr: 'Radyal ve eksenel yük altındaki bir rulmanda eşdeğer dinamik yük P = X*Fr + Y*Fa formülüyle hesaplanır.',
        cEn: 'Equivalent dynamic load is calculated via P = X*Fr + Y*Fa depending on Fa/Fr ratio relative to e.',
        f: 'P = X \\cdot F_r + Y \\cdot F_a',
        calcPTr: 'Fr = 5000 N, Fa = 2000 N, radyal faktör X = 0.56 ve eksenel faktör Y = 1.60 için eşdeğer yükü (P) Newton cinsinden hesaplayınız:',
        calcPEn: 'Calculate equivalent load P in Newtons for Fr=5000N, Fa=2000N, X=0.56, Y=1.60:',
        tVal: 6000, tol: 50, u: 'N', fHint: 'P = 0.56 * 5000 + 1.60 * 2000 = 2800 + 3200',
        calcExpTr: 'Doğru! P = 2800 + 3200 = 6000 N (6 kN).', calcExpEn: 'Correct! P = 2800 + 3200 = 6000 N.' },
      { num: 33, slug: 'iso281-l10-life-calculation', std: 'ISO 281', cat: 'Rulmanlar', diff: 'medium', pType: 'calculation',
        tTr: '33. ISO 281 L10 Yorulma Ömrü Hesabı (Milyon Devir)', tEn: '33. ISO 281 L10 Fatigue Life (Million Revs)',
        cTr: 'L10 ömrü bilyalı rulmanlar için p=3, makaralı rulmanlar için p=10/3 üssüyle L10 = (C / P)^p milyon devir olarak hesaplanır.',
        cEn: 'L10 rating life is L10 = (C/P)^p in million revolutions (p=3 for ball, p=10/3 for roller).',
        f: 'L_{10} = \\left( \\frac{C}{P} \\right)^p \\quad [10^6 \\text{ revs}]',
        calcPTr: 'Dinamik yük sayısı C = 40 kN olan bir bilyalı rulman (p=3), P = 20 kN eşdeğer yük altında kaç milyon devir (L10) ömre sahiptir?',
        calcPEn: 'Calculate L10 rating life in million revolutions for ball bearing (p=3) with C = 40 kN and P = 20 kN:',
        tVal: 8, tol: 0.1, u: '10⁶ devir', fHint: 'L10 = (40 / 20)³ = 2³',
        calcExpTr: 'Doğru! L10 = (2)³ = 8 milyon devir.', calcExpEn: 'Correct! L10 = (40/20)³ = 8 million revolutions.' },
      { num: 34, slug: 'l10h-operating-hours-calculation', std: 'ISO 281', cat: 'Rulmanlar', diff: 'medium', pType: 'calculation',
        tTr: '34. Çalışma Saati (L10h) Cinsinden Rulman Ömrü', tEn: '34. Bearing Life in Operating Hours (L10h)',
        cTr: 'L10h = (10⁶ * L10) / (60 * n) formülüyle devir cinsinden ömür doğrudan çalışma saatine dönüştürülür.',
        cEn: 'Operating hours life is L10h = (10⁶ * L10) / (60 * n) where n is shaft RPM.',
        f: 'L_{10h} = \\frac{10^6 \\cdot L_{10}}{60 \\cdot n}',
        calcPTr: 'L10 = 30 milyon devir ömre sahip bir rulman n = 1000 d/dak hızda kaç saat (L10h) çalışabilir?',
        calcPEn: 'For L10 = 30 million revs and shaft speed n = 1000 RPM, calculate operating hours L10h:',
        tVal: 500, tol: 5, u: 'saat', fHint: 'L10h = (30 * 10^6) / (60 * 1000) = 30,000,000 / 60,000',
        calcExpTr: 'Doğru! 30,000,000 / 60,000 = 500 saat.', calcExpEn: 'Correct! 30,000,000 / 60,000 = 500 hours.' },
      { num: 35, slug: 'stribeck-lubrication-curve-visual', std: 'Triboloji', cat: 'Triboloji', diff: 'medium', pType: 'visual',
        tTr: '35. Stribeck Yağlama Rejimleri Eğrisi', tEn: '35. Stribeck Friction & Lubrication Regimes',
        cTr: 'Stribeck eğrisi sürtünme katsayısını (μ) hız*viskozite/yük (Hersey sayısı) fonksiyonu olarak gösterir: Sınır Yağlama -> Karma Yağlama -> Hidrodinamik / EHL Yağlama.',
        cEn: 'The Stribeck curve characterizes lubrication regimes: Boundary -> Mixed -> Full Fluid / EHL film.',
        f: '\\kappa = \\frac{\\nu}{\\nu_1} \\quad (\\text{Viskozite Oranı})',
        visPTr: 'Millerin tam dur-kalk yaptığı veya aşırı düşük hızda yüksek yük altında çalıştığı, yüzey pürüzlerinin doğrudan birbirine sürttüğü bölge hangisidir?',
        visPEn: 'Which lubrication regime occurs at stop-start conditions where surface asperities make direct metallic contact?',
        visCards: [
          { id: 'v1', titleTr: 'Sınır Yağlama (Boundary Lubrication)', titleEn: 'Boundary Lubrication Regime', descTr: 'Yağ filmi oluşmaz, pürüzler doğrudan temas eder, sürtünme ve aşınma en yüksek seviyededir', descEn: 'Zero fluid film lift, direct asperity contact, maximum wear rate', diagramSvgType: 'pitting_crack', isCorrect: true },
          { id: 'v2', titleTr: 'Tam Hidrodinamik Film', titleEn: 'Full Hydrodynamic Film', descTr: 'Metal yüzeyler tam ayrılmıştır', descEn: 'Complete separation of metal surfaces', diagramSvgType: 'i_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Sınır yağlamada sıvı film taşıyıcılığı oluşmaz ve aşınma katı-katı temasından doğar.',
        expEn: 'Correct! Boundary regime lacks fluid wedge pressure, causing metallic friction.' },
      { num: 36, slug: 'viscosity-ratio-kappa-rule', std: 'ISO 281 Ek 1', cat: 'Triboloji', diff: 'medium', pType: 'quiz',
        tTr: '36. Yağ Viskozite Oranı (κ) & Yağlama Kalitesi', tEn: '36. Viscosity Ratio (κ) & Lubrication Quality',
        cTr: 'κ = ν / ν1 oranı çalışma sıcaklığındaki viskozitenin gereken minimum viskoziteye oranıdır. κ ≥ 1.0 tam elastohidrodinamik (EHL) film oluştururken κ < 0.4 şiddetli aşınma yaratır.',
        cEn: 'Viscosity ratio κ = ν / ν1. Values κ ≥ 1.0 indicate full EHL separation; κ < 0.4 leads to high asperity wear.',
        f: '\\kappa = \\frac{\\nu}{\\nu_1} \\ge 1.0 - 4.0 \\quad (\\text{Optimal EHL Rejimi})',
        qTr: 'Bir redüktörde κ = 0.35 ölçülmüşse yağlama durumu ve alınması gereken önlem nedir?',
        qEn: 'If a gearbox operates at κ = 0.35, what is the tribological state and required corrective action?',
        oTr: ['Yetersiz yağ filmi ve aşınma riski vardır; daha yüksek viskoziteli (ISO VG) yağ seçilmeli veya soğutma artırılmalıdır', 'Yağ mükemmeldir', 'Rulman sökülmelidir', 'Devir artırılmalıdır'],
        oEn: ['Deficient oil film risking rapid wear; upgrade to higher ISO VG oil or improve cooling', 'Ideal lubrication', 'Remove bearing', 'Increase speed'],
        cIdx: 0, expTr: 'Doğru! κ < 0.4 durumunda yağ filmi çöker; daha kalın baz yağlı viskoziteye geçilmelidir.',
        expEn: 'Correct! κ < 0.4 indicates film collapse requiring higher viscosity grade.' },
      { num: 37, slug: 'c0-static-load-safety-calculation', std: 'ISO 76', cat: 'Rulmanlar', diff: 'medium', pType: 'calculation',
        tTr: '37. Statik Güvenlik Faktörü (s0) & C0 Hesabı', tEn: '37. Static Safety Factor (s0) & C0 Rating',
        cTr: 'Darbe veya dururken ağır yük altındaki rulmanlarda kalıcı ezilmeyi önlemek için statik güvenlik katsayısı s0 = C0 / P0 ≥ 1.5 - 2.0 olmalıdır.',
        cEn: 'Static safety s0 = C0 / P0 prevents permanent raceway indentations under shock loads (s0 ≥ 1.5-2.0).',
        f: 's_0 = \\frac{C_0}{P_0} \\ge 1.5',
        calcPTr: 'Statik yük sayısı C0 = 60 kN olan bir rulmanda maksimum şok yükü P0 = 30 kN ise statik güvenlik faktörünü (s0) hesaplayınız:',
        calcPEn: 'Calculate static safety factor s0 for static rating C0 = 60 kN and shock load P0 = 30 kN:',
        tVal: 2.0, tol: 0.05, u: '', fHint: 's0 = 60 / 30',
        calcExpTr: 'Doğru! s0 = 60 / 30 = 2.0.', calcExpEn: 'Correct! s0 = 60 / 30 = 2.0.' },
      { num: 38, slug: 'bearing-clearance-classes-c3-c4', std: 'ISO 5753-1', cat: 'Rulmanlar', diff: 'medium', pType: 'quiz',
        tTr: '38. Radyal Boşluk Sınıfları (CN, C3, C4)', tEn: '38. Internal Radial Clearance (CN, C3, C4)',
        cTr: 'Rulman sıkı geçme yapıldığında iç bilezik genleşir, mil ısındığında ise iç bilezik dıştan daha sıcak olur ve boşluk daralır. Bu durumlarda C3 (artırılmış iç boşluk) seçilmelidir.',
        cEn: 'Press fits and hot shaft running expand inner rings, consuming internal clearance. C3 clearance prevents hot bearing seizure.',
        f: '\\Delta r_{\\text{operating}} = \\Delta r_0 - \\Delta d_i - \\alpha \\cdot \\Delta T \\cdot d',
        qTr: 'Elektrik motorlarında yüksek devir ve mil ısınması nedeniyle neden genellikle standart (CN) yerine C3 boşluklu rulman kullanılır?',
        qEn: 'Why do high-speed electric motors commonly require C3 internal clearance bearings over standard (CN)?',
        oTr: ['Milin termal genleşmesi ve sıkı geçme payı çalışma anında iç boşluğu sıfırlayıp rulmanın sıkışmasını önlemek için', 'Rulmanın daha sesli çalışması için', 'Radyal yükü sıfırlamak için', 'Fiyatı ucuz olduğu için'],
        oEn: ['Thermal expansion and press fits reduce clearance; C3 prevents thermal preloading and seizure', 'To make it louder', 'To zero radial load', 'Cost reasons'],
        cIdx: 0, expTr: 'Doğru! Mil sıcaklığı iç bileziği şişirir; C3 boşluk çalışma sıcaklığında ideal boşluğu sağlar.',
        expEn: 'Correct! Shaft heating expands inner ring; C3 ensures optimal operating clearance without thermal binding.' },
      { num: 39, slug: 'bearing-failure-modes-visual', std: 'ISO 15243', cat: 'Triboloji', diff: 'hard', pType: 'visual',
        tTr: '39. ISO 15243 Rulman Hasar Modları & Pitting', tEn: '39. ISO 15243 Bearing Failure Modes & Pitting',
        cTr: 'Yüzey altı yorulması (sub-surface fatigue) mikroskobik çatlakların yüzeye ulaşıp malzeme koparmasıyla çukurlaşma (pitting / spalling) şeklinde nihai rulman ömrünü sonlandırır.',
        cEn: 'Sub-surface shear stress initiates microcracks that propagate to the contact surface, leading to flaking/spalling (pitting).',
        f: '\\tau_{\\max} \\approx 0.31 \\cdot p_0 \\quad (z \\approx 0.78 b \\text{ Derinlikte Maksimum Kayma})',
        visPTr: 'Dönme teması altındaki yuvarlanma yollarında periyodik Hertz basıncından doğan malzeme dökülme hasarı hangisidir?',
        visPEn: 'Which cyclic rolling contact fatigue failure manifests as metal flaking and crater craters on bearing raceways?',
        visCards: [
          { id: 'c1', titleTr: 'Yorulma Çukurlaşması (Flaking / Pitting)', titleEn: 'Fatigue Spalling / Pitting', descTr: 'Maksimum yüzey altı kayma gerilmesinden doğan pul pul dökülme ve kraterler', descEn: 'Progressive raceway spalling and subsurface crater flaking', diagramSvgType: 'pitting_crack', isCorrect: true },
          { id: 'c2', titleTr: 'Düzgün Parlak Yüzey', titleEn: 'Smooth Polished Raceway', descTr: 'Hasarsız sağlıklı yuvarlanma yolu', descEn: 'Undamaged operating raceway', diagramSvgType: 'i_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Pitting yuvarlanma temasında yorulma ömrünün doğal ve kaçınılmaz fiziksel sonucudur.',
        expEn: 'Correct! Spalling/pitting is the primary rolling-contact fatigue end-of-life mechanism.' },
      { num: 40, slug: 'angular-contact-bearing-arrangement', std: 'ISO 15', cat: 'Rulmanlar', diff: 'hard', pType: 'drawing',
        tTr: '40. Çift Eğik Temaslı Bilyalı Rulman Dizilişleri (O vs X)', tEn: '40. Angular Contact Arrangements (Back-to-Back O vs Face-to-Face X)',
        cTr: 'Sırta Sırta (DB / "O" Düzeni) temas çizgileri dışa doğru açıldığı için yüksek eğilme momenti rijitliği sağlar (CNC iş mili için ideal). Yüze Yüze (DF / "X" Düzeni) ise eksen kaçıklıklarını tolere eder.',
        cEn: 'Back-to-back (DB / "O") creates a wide effective spread, maximizing tilting moment stiffness for CNC machine spindles.',
        f: 'H_{\\text{effective}} = L + 2 \\cdot a \\quad (\\text{O Düzeninde Efektif Taban Mesafesi Genişler})',
        dPromptTr: 'CNC freze iş milinde kesici uçtan gelen yüksek devirme momentini en rijit şekilde karşılamak için hangi çift rulman yerleşim düzeni seçilmelidir?',
        dPromptEn: 'Which duplex arrangement provides maximum angular tilting rigidity for a machine tool spindle?',
        vOpts: [
          { id: 'a1', labelTr: 'Sırta Sırta (O Düzeni / DB) [Maksimum Moment Dayanımı]', labelEn: 'Back-to-Back (O-Arrangement / DB) [Max Moment Stiffness]', direction: 'right', isCorrect: true },
          { id: 'a2', labelTr: 'Yüze Yüze (X Düzeni / DF)', labelEn: 'Face-to-Face (X-Arrangement / DF)', direction: 'left', isCorrect: false },
        ],
        expTr: 'Doğru! "O" düzeninde yük temas çizgileri dışa açılarak efektif mesnet aralığını ve moment rijitliğini büyütür.',
        expEn: 'Correct! DB arrangement broadens the effective reaction baseline, resisting bending moments.' },
      { num: 41, slug: 'grease-life-relubrication-calc', std: 'DIN 51825', cat: 'Triboloji', diff: 'medium', pType: 'calculation',
        tTr: '41. Gres Yağlama Ömrü & Yeniden Yağlama Aralığı', tEn: '41. Grease Relubrication Interval (tf)',
        cTr: 'Gres ömrü sıcaklık her 15°C arttığında yaklaşık yarı yarıya düşer (Arrhenius kuralı). 70°C\'de 4000 saat dayanan bir gres 85°C\'de yaklaşık 2000 saat dayanır.',
        cEn: 'Grease relubrication intervals halve for every 15°C operating temperature rise above 70°C.',
        f: 't_f(T + 15^\\circ\\text{C}) \\approx 0.5 \\times t_f(T)',
        calcPTr: '70°C standart sıcaklıkta 6000 saat ömrü olan bir gresin 85°C çalışma sıcaklığındaki ömrünü (saat) hesaplayınız:',
        calcPEn: 'If grease life is 6000 hours at 70°C, calculate service life in hours at 85°C (+15°C shift):',
        tVal: 3000, tol: 100, u: 'saat', fHint: 't_f = 6000 / 2',
        calcExpTr: 'Doğru! Sıcaklık 15°C yükseldiğinde gres baz yağı oksidasyonu iki katına çıkarak ömrü 3000 saate indirir.',
        expEn: 'Correct! 15°C thermal elevation halves grease life to 3000 hours.' },
      { num: 42, slug: 'false-brinelling-vs-fretting', std: 'ISO 15243', cat: 'Triboloji', diff: 'medium', pType: 'quiz',
        tTr: '42. Sahte Brinell Hasarı (False Brinelling) & Taşıma Titreşimi', tEn: '42. False Brinelling & Standstill Vibration',
        cTr: 'Duran veya sadece mikro salınım yapan makinelerde (örn. trenle taşınan araç rulmanları) bilyalar koruyucu yağ filmini ezerek yuvarlanma yolunda çöküntüler ve oksit korozyonu oluşturur.',
        cEn: 'False brinelling occurs when stationary bearings subject to external transport vibrations squeeze out oil film, causing localized fretting marks.',
        f: '\\text{Mikro titreşim genliği } < \\text{ Elastik temas elipsi genişliği}',
        qTr: 'Çalışmayan durağan makinelerde harici titreşim sebebiyle bilyaların yuvarlanma yolunu ezmesi hasarına ne ad verilir?',
        qEn: 'What is the failure mode where stationary bearings develop micro-wear depression marks from ambient transport vibration?',
        oTr: ['Sahte Brinell Hasarı (False Brinelling / Fretting Corrosion)', 'Aşırı Hız Kırılması', 'Elektrik Erozyonu', 'Kavitasyon'],
        oEn: ['False Brinelling / Fretting Corrosion', 'Over-speed Rupture', 'Electrical Fluting', 'Cavitation'],
        cIdx: 0, expTr: 'Doğru! Mikro titreşim yağ filmini parçalayarak metal teması ve oksidasyon çukurları üretir.',
        expEn: 'Correct! Micro-oscillation expels lubricant, creating fretting depressions matching rolling element spacing.' },
      { num: 43, slug: 'bearing-electrical-fluting-visual', std: 'IEC 60034-25', cat: 'Triboloji', diff: 'hard', pType: 'visual',
        tTr: '43. VFD Motor Rulmanlarında Akım Geçişi (Fluting)', tEn: '43. VFD Motor Bearing Current Fluting',
        cTr: 'Frekans invertörlü (VFD) motorlarda yüksek frekanslı şaft gerilimi yağ filmini delip mikro elektrik arkları üretir ve oluklu dalga izleri (fluting) oluşturur. Seramik hibrit rulman veya yalıtımlı bilezik kullanılmalıdır.',
        cEn: 'PWM inverter voltage spikes break down grease dielectric strength, discharging EDM arcs that carve washboard fluting ripples across raceways.',
        f: 'V_{\\text{shaft}} > V_{\\text{dielectric,oil}} \\implies I_{\\text{discharge}} \\approx \\text{EDM Mikro Kaynak}',
        visPTr: 'VFD invertörlü elektrik motoru rulmanında mikro elektrik arklarının yuvarlanma yolunda açtığı paralel oluklu çamaşır tahtası deseni hangisidir?',
        visPEn: 'Which raceway pattern indicates electrical EDM fluting damage from VFD high-frequency shaft currents?',
        visCards: [
          { id: 'v1', titleTr: 'Elektrik Akım İzi (Fluting - Oluklu Dalgalar)', titleEn: 'Electrical EDM Fluting Corrugations', descTr: 'Yuvarlanma yolunda mikro ark erimeleriyle oluşan karakteristik paralel dalga desenleri', descEn: 'Regular washboard transverse fluting grooves from EDM micro-melting', diagramSvgType: 'stress_notch', isCorrect: true },
          { id: 'v2', titleTr: 'Pürüzsüz Temiz Yüzey', titleEn: 'Smooth Clean Raceway', descTr: 'Akım geçişi olmayan sağlıklı yüzey', descEn: 'Healthy raceway without electrical discharge', diagramSvgType: 'rect_beam_stress', isCorrect: false },
        ],
        expTr: 'Doğru! Elektrik arkları mikroskobik erimelerle yuvarlanma yolunda oluklu çamaşır tahtası çizgileri oluşturur.',
        expEn: 'Correct! EDM micro-arcing melts discrete crater lines, creating the signature washboard fluting pattern.' },
      { num: 44, slug: 'combined-bearing-load-vector', std: 'ISO 281', cat: 'Rulmanlar', diff: 'hard', pType: 'drawing',
        tTr: '44. Radyal ve Eksenel Rulman Kuvvet Vektörleri', tEn: '44. Radial and Thrust Force Vectors',
        cTr: 'Eğik temaslı bir rulmanda temas açısı α boyunca etki eden bileşke kuvvet hem radyal hem eksenel bileşen üretir.',
        cEn: 'The contact angle α resolves the internal contact line load into paired radial and axial reaction forces.',
        f: 'F_a = F_r \\cdot \\tan(\\alpha)',
        dPromptTr: 'Bir mil ekseni boyunca sağa doğru 5000 N itme kuvveti geliyorsa, mili tutan sabit yatak mesnetinin uygulayacağı eksenel reaksiyon yönü ne olmalıdır?',
        dPromptEn: 'If a shaft experiences a rightward (+X) axial thrust load of 5000 N, what is the required locating bearing reaction direction?',
        vOpts: [
          { id: 'ax1', labelTr: 'Sola Doğru (-X) [Dengeleyici Eksenel Tepki]', labelEn: 'Leftward (-X) [Balancing Thrust Reaction]', direction: 'left', isCorrect: true },
          { id: 'ax2', labelTr: 'Sağa Doğru (+X)', labelEn: 'Rightward (+X)', direction: 'right', isCorrect: false },
        ],
        expTr: 'Doğru! Sağa iten eksenel kuvvete karşı sabit rulman sola doğru (-X) tepki vermelidir.',
        expEn: 'Correct! Locating bearing counteracts rightward thrust with an equal leftward reaction.' },
      { num: 45, slug: 'boss-wind-turbine-bearing-sizing', std: 'ISO 281 & DIN 743', cat: 'Rulmanlar', diff: 'hard', pType: 'boss', isBoss: true,
        tTr: '45. 👑 BOSS SINAVI: 3 MW Rüzgar Türbini Ana Mil Rulmanı Tasarımı', tEn: '45. 👑 BOSS TEST: 3 MW Wind Turbine Main Bearing Sizing',
        cTr: '20 yıllık kesintisiz tasarım ömrü (L10h ≥ 175,000 saat) için ISO 281 genişletilmiş ömür faktörü aISO (yağ temizliği eC ve viskozite oranı κ hesabı) ile 1200 mm çaplı çift sıra oynak makaralı rulman (Spherical Roller Bearing) doğrulaması.',
        cEn: 'Comprehensive 20-year wind turbine bearing verification proving L10mh ≥ 175,000 hrs using ISO 281 life modification factor aISO.',
        f: 'L_{nm} = a_1 \\cdot a_{\\text{ISO}} \\cdot L_{10}, \\quad a_{\\text{ISO}} = f\\left( \\frac{e_C \\cdot C_u}{P}, \\kappa \\right)',
        qTr: 'Rüzgar türbini ana rulmanında yüksek viskozite oranı (κ = 2.5) ve yüksek yağ filtreleme temizliği (eC = 0.8) sağlandığında ISO 281 aISO ömür katsayısı ve rulman ömrü nasıl değişir?',
        qEn: 'When high viscosity ratio (κ = 2.5) and exceptional oil cleanliness (eC = 0.8) are achieved, how does the aISO factor impact bearing life?',
        oTr: ['aISO katsayısı 3 ila 5 katına çıkarak rulman yorulma ömrünü devasa oranda uzatır', 'Ömür yarıya düşer', 'Sürtünme sıfırlanır', 'Türbin hızı 10 katına çıkar'],
        oEn: ['aISO factor reaches 3 to 5x, dramatically multiplying calculated fatigue life', 'Life is halved', 'Friction drops to zero', 'Speed increases 10x'],
        cIdx: 0, expTr: 'Tebrikler Başmühendis! Temiz yağ ve ideal EHL filmi rulmanın teorik sonsuz ömre yaklaşmasını sağlar!',
        expEn: 'Congratulations Master Engineer! Clean lubricant and thick EHL film unlock multi-fold fatigue life extensions!' }
    ]
  }
];

console.log('Units 1-3 dataset ready.');
