/**
 * Full academy i18n sync: reads locale-data/{lang}.json packs and writes
 * intro-map, desc-map, seo-title-map, bodies/{lang}/*.json, langs/{lang}-academy-extras.mjs
 *
 * Run: node scripts/academy-i18n-data/full-sync.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..', '..');
const ARTICLES = path.join(ROOT, 'src/data/academy-articles');
const LOCALE_DATA = path.join(__dirname, 'locale-data');
const BODIES_DIR = path.join(__dirname, 'bodies');
const LANGS_DIR = path.join(__dirname, 'langs');

const LANGS = ['de', 'es', 'fr', 'it', 'pt', 'ru', 'zh', 'ja', 'ko', 'ar'];

function loadJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function loadArticleSlugs() {
  return fs
    .readdirSync(ARTICLES)
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace('.json', ''));
}

function deepMergeLesson(base, override) {
  if (!override) return base;
  return {
    ...base,
    ...override,
    meta: override.meta ? { ...base.meta, ...override.meta } : base.meta,
    hero: override.hero ? { ...base.hero, ...override.hero } : base.hero,
    formula: override.formula
      ? { ...base.formula, variables: { ...base.formula?.variables, ...override.formula?.variables } }
      : base.formula,
    example: override.example ? { ...base.example, ...override.example } : base.example,
    calculatorCta: override.calculatorCta
      ? { ...base.calculatorCta, ...override.calculatorCta }
      : base.calculatorCta,
  };
}

function loadLocalePack(lang) {
  const file = path.join(LOCALE_DATA, `${lang}.json`);
  if (!fs.existsSync(file)) {
    console.warn(`Missing locale pack: ${file}`);
    return null;
  }
  return loadJson(file);
}

function writeExtrasMjs(lang, pack) {
  const out = path.join(LANGS_DIR, `${lang}-academy-extras.mjs`);
  const content = `/** Auto-generated by full-sync.mjs — do not edit manually. */
export const walkthroughs = ${JSON.stringify(pack.walkthroughs ?? {}, null, 2)};

export const quizzes = ${JSON.stringify(pack.quizzes ?? {}, null, 2)};

export const practice = ${JSON.stringify(pack.practice ?? {}, null, 2)};
`;
  fs.writeFileSync(out, content, 'utf8');
}

function patchLangMjs(lang) {
  const file = path.join(LANGS_DIR, `${lang}.mjs`);
  if (!fs.existsSync(file)) return;
  let src = fs.readFileSync(file, 'utf8');
  const extrasImport = `export { walkthroughs, quizzes, practice } from './${lang}-academy-extras.mjs';\n`;
  if (src.includes('-academy-extras.mjs')) return;
  // Remove empty walkthroughs/quizzes exports
  src = src.replace(/\nimport \{ buildWalkthroughTitles \}[^;]+;\n\nexport const walkthroughs = buildWalkthroughTitles\([^)]+\);\n\nexport const quizzes = \{\};\n/, '\n');
  src = src.replace(/\nexport const walkthroughs = \{\};\n\nexport const quizzes = \{\};\n/, '\n');
  src = src.replace(/\nexport const seoGuides = \{\};\n$/, `\n${extrasImport}\nexport const seoGuides = {};\n`);
  if (!src.includes('-academy-extras.mjs')) {
    src = src.replace(/export const seoGuides = \{\};\s*$/, `${extrasImport}\nexport const seoGuides = {};\n`);
  }
  fs.writeFileSync(file, src, 'utf8');
}

function main() {
  const slugs = loadArticleSlugs();
  const titleMap = loadJson(path.join(__dirname, 'title-map.json'));
  const descMap = loadJson(path.join(__dirname, 'desc-map.json'));
  const introMap = loadJson(path.join(__dirname, 'intro-map.json'));
  const seoTitleMap = loadJson(path.join(__dirname, 'seo-title-map.json'));
  const seoIntroMap = loadJson(path.join(__dirname, 'seo-intro-map.json'));

  for (const lang of LANGS) {
    const pack = loadLocalePack(lang);
    if (!pack) continue;

    for (const slug of slugs) {
      const lesson = pack.lessons?.[slug];
      if (!lesson) continue;

      if (lesson.meta?.description) {
        descMap[lang] = descMap[lang] ?? {};
        descMap[lang][slug] = lesson.meta.description;
      }
      if (lesson.hero?.intro) {
        introMap[lang] = introMap[lang] ?? {};
        introMap[lang][slug] = lesson.hero.intro;
      }

      const bodyDir = path.join(BODIES_DIR, lang);
      fs.mkdirSync(bodyDir, { recursive: true });
      const bodyFields = { ...lesson };
      delete bodyFields.meta;
      delete bodyFields.hero;
      if (Object.keys(bodyFields).length > 0) {
        fs.writeFileSync(path.join(bodyDir, `${slug}.json`), JSON.stringify(bodyFields, null, 2), 'utf8');
      }
    }

    if (pack.seoTitles) {
      seoTitleMap[lang] = { ...seoTitleMap[lang], ...pack.seoTitles };
      for (const [slug, title] of Object.entries(pack.seoTitles)) {
        const intro = seoIntroMap[lang]?.[slug];
        if (intro) continue;
        const fromPack = pack.seoGuides?.[slug]?.hero?.intro;
        if (fromPack) {
          seoIntroMap[lang] = seoIntroMap[lang] ?? {};
          seoIntroMap[lang][slug] = fromPack;
        }
      }
    }

    writeExtrasMjs(lang, pack);
    patchLangMjs(lang);
    console.log(`Synced ${lang}: ${Object.keys(pack.lessons ?? {}).length} lessons`);
  }

  fs.writeFileSync(path.join(__dirname, 'desc-map.json'), JSON.stringify(descMap, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, 'intro-map.json'), JSON.stringify(introMap, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, 'seo-title-map.json'), JSON.stringify(seoTitleMap, null, 2), 'utf8');
  fs.writeFileSync(path.join(__dirname, 'seo-intro-map.json'), JSON.stringify(seoIntroMap, null, 2), 'utf8');
  console.log('Maps updated. Run: npx tsx scripts/academy-i18n-data/build-all.ts');
}

main();
