name: Hostinger'a Dağıt
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Build ve Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek (Checkout)
        uses: actions/checkout@v3

      - name: Node.js Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Bağımlılıkları Yükle (Install)
        run: npm install --legacy-peer-deps

      - name: Projeyi Derle (Build)
        env:
          CI: true
        run: npm run build

      - name: FTP ile Yükle (Hostinger)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: srv2070.hstgr.io
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          local-dir: ./out/
          server-dir: ./public_html/
          timeout: 600000
